# Generated by Django 6.0.4 on 2026-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lote', models.CharField(max_length=80, unique=True)),
                ('empresa_aserradero', models.CharField(max_length=160)),
                ('fecha', models.DateField()),
                ('especie', models.CharField(max_length=120)),
                ('volumen_m3', models.DecimalField(decimal_places=3, max_digits=12)),
                ('origen', models.CharField(max_length=180)),
                ('destino', models.CharField(max_length=180)),
                ('emisiones_kg_co2e', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
