# Generated by Django 6.0.1 on 2026-06-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructora",
            name="preset",
            field=models.CharField(
                choices=[
                    ("construccion", "Construcción"),
                    ("aserradero", "Aserradero / Forestal"),
                    ("transporte", "Transporte"),
                    ("industrial", "Industrial"),
                ],
                db_index=True,
                default="construccion",
                max_length=40,
            ),
        ),
    ]
