# Generated by Django 6.0.4 on 2026-04-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='emisiones_kg_co2e',
        ),
        migrations.CreateModel(
            name='EmisionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=120)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidad', models.CharField(max_length=40)),
                ('factor_emision', models.DecimalField(decimal_places=6, max_digits=12)),
                ('emisiones_kg_co2e', models.DecimalField(decimal_places=3, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='analytics.lote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
