# Generated by Django 6.0.1 on 2026-06-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_constructora_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="factoremision",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="factoremision",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="factoremision",
            name="module",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="factoremision",
            name="preset",
            field=models.CharField(
                choices=[
                    ("construccion", "Construcción"),
                    ("aserradero", "Aserradero / Forestal"),
                    ("transporte", "Transporte"),
                    ("industrial", "Industrial"),
                ],
                db_index=True,
                default="construccion",
                max_length=40,
            ),
        ),
    ]
