# Generated by Django 6.0.4 on 2026-04-28 18:43

from django.db import migrations, models


def seed_especies_madera(apps, schema_editor):
    especie_madera = apps.get_model("analytics", "EspecieMadera")
    especies = [
        ("Pino radiata", "500.000", "0.5000"),
        ("Eucalipto", "700.000", "0.5000"),
        ("Roble", "720.000", "0.5000"),
        ("Coigue", "650.000", "0.5000"),
    ]

    for nombre, densidad, porcentaje_carbono in especies:
        especie_madera.objects.get_or_create(
            nombre=nombre,
            defaults={
                "densidad_kg_m3": densidad,
                "porcentaje_carbono": porcentaje_carbono,
            },
        )


def unseed_especies_madera(apps, schema_editor):
    especie_madera = apps.get_model("analytics", "EspecieMadera")
    especie_madera.objects.filter(
        nombre__in=["Pino radiata", "Eucalipto", "Roble", "Coigue"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_lote_emisiones_kg_co2e_emisionlote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieMadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('densidad_kg_m3', models.DecimalField(decimal_places=3, max_digits=8)),
                ('porcentaje_carbono', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(seed_especies_madera, unseed_especies_madera),
    ]
