# Generated by Django 6.0.1 on 2026-06-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_factoremision_activo_factoremision_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factoremision",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Materia prima", "Materia prima"),
                    ("Materiales", "Materiales"),
                    ("Produccion", "Produccion"),
                    ("Secado", "Secado"),
                    ("Transporte", "Transporte"),
                    ("Combustible", "Combustible"),
                    ("Rutas", "Rutas"),
                    ("Flota", "Flota"),
                    ("Mantencion", "Mantencion"),
                    ("Carga", "Carga"),
                    ("Maquinaria", "Maquinaria"),
                    ("Energia", "Energia"),
                    ("Agua", "Agua"),
                    ("Residuos", "Residuos"),
                    ("Subproductos", "Subproductos"),
                    ("Procesos", "Procesos"),
                    ("Procesos externos", "Procesos externos"),
                    ("Otros", "Otros"),
                ],
                default="Otros",
                max_length=40,
            ),
        ),
    ]
