# Generated by Django 6.0.4 on 2026-04-28 19:00

import apps.analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_especiemadera'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('guia_despacho', 'Guia de despacho'), ('factura_combustible', 'Factura de combustible'), ('boleta_electrica', 'Boleta electrica'), ('registro_produccion', 'Registro de produccion'), ('documento_origen', 'Documento de origen'), ('registro_transporte', 'Registro de transporte')], max_length=40)),
                ('archivo', models.FileField(upload_to=apps.analytics.models.documento_lote_upload_path)),
                ('fecha', models.DateField()),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='analytics.lote')),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
