# Generated by Django 6.0.4 on 2026-04-28 19:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_documentolote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=120)),
                ('patente', models.CharField(max_length=30)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('fecha_hora', models.DateTimeField()),
                ('ruta', models.CharField(max_length=240)),
                ('distancia_km', models.DecimalField(decimal_places=3, max_digits=12)),
                ('consumo_estimado_litro_km', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), max_digits=8)),
                ('litros_combustible', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('factor_diesel', models.DecimalField(decimal_places=6, default=Decimal('2.680000'), max_digits=12)),
                ('litros_calculados', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('emisiones_transporte_kg_co2e', models.DecimalField(decimal_places=3, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad_emision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporte', to='analytics.emisionlote')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='analytics.lote')),
            ],
            options={
                'ordering': ['-fecha_hora', '-created_at'],
            },
        ),
    ]
