# Generated by Django 6.0.4 on 2026-06-17 18:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_factoremision_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecieMadera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "densidad_kg_m3",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "porcentaje_carbono",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TransporteLoteForestal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(blank=True, null=True)),
                ("vehiculo", models.CharField(blank=True, max_length=120)),
                ("patente", models.CharField(blank=True, max_length=30)),
                ("conductor", models.CharField(blank=True, max_length=120)),
                ("origen", models.CharField(max_length=240)),
                ("destino", models.CharField(max_length=240)),
                ("distancia_km", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "litros_diesel",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "consumo_estimado_litro_km",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.3000"), max_digits=8
                    ),
                ),
                (
                    "factor_diesel",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("2.6800"), max_digits=8
                    ),
                ),
                (
                    "emisiones_transporte_kg_co2e",
                    models.DecimalField(
                        decimal_places=3, editable=False, max_digits=14
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoteForestal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote_id", models.CharField(max_length=80, unique=True)),
                ("fecha", models.DateField()),
                ("especie", models.CharField(max_length=120)),
                ("volumen_m3", models.DecimalField(decimal_places=3, max_digits=14)),
                ("origen", models.CharField(max_length=240)),
                ("destino", models.CharField(blank=True, max_length=240)),
                ("tipo_producto", models.CharField(blank=True, max_length=120)),
                (
                    "densidad_kg_m3",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "porcentaje_carbono",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=80)),
                ("observaciones", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constructora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_forestales",
                        to="analytics.constructora",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "lote_id"],
            },
        ),
        migrations.AddField(
            model_name="evidenciaobra",
            name="lote_forestal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidencias",
                to="analytics.loteforestal",
            ),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="lote_forestal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_emision",
                to="analytics.loteforestal",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenciaobra",
            index=models.Index(
                fields=["lote_forestal_id"], name="analytics_e_lote_fo_d2c00a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["lote_forestal_id"], name="analytics_r_lote_fo_690efa_idx"
            ),
        ),
        migrations.AddField(
            model_name="transporteloteforestal",
            name="lote_forestal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transportes",
                to="analytics.loteforestal",
            ),
        ),
        migrations.AddField(
            model_name="transporteloteforestal",
            name="registro_emision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transporte_lote_forestal",
                to="analytics.registroemision",
            ),
        ),
        migrations.AddIndex(
            model_name="loteforestal",
            index=models.Index(
                fields=["constructora_id", "fecha"],
                name="analytics_l_constru_11b591_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loteforestal",
            index=models.Index(
                fields=["constructora_id", "lote_id"],
                name="analytics_l_constru_ab9ed2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loteforestal",
            index=models.Index(
                fields=["constructora_id", "especie"],
                name="analytics_l_constru_12bef3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transporteloteforestal",
            index=models.Index(
                fields=["lote_forestal_id", "fecha"],
                name="analytics_t_lote_fo_b43d9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transporteloteforestal",
            index=models.Index(
                fields=["patente"], name="analytics_t_patente_8dbd34_idx"
            ),
        ),
    ]
