# Generated by Django 6.0.4 on 2026-04-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_transportelote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraccionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_extraido', models.TextField(blank=True)),
                ('datos_sugeridos', models.JSONField(default=dict)),
                ('datos_validados', models.JSONField(blank=True, default=dict)),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones', to='analytics.documentolote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
