# Generated by Django 6.0.4 on 2026-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0005_especiemadera_transporteloteforestal_loteforestal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidenciaobra",
            name="tipo_evidencia",
            field=models.CharField(
                choices=[
                    ("factura_material", "Factura de material"),
                    ("guia_despacho", "Guia de despacho"),
                    ("orden_compra", "Orden de compra"),
                    ("factura_combustible", "Factura de combustible"),
                    ("documento_origen", "Documento de origen"),
                    ("boleta_electrica", "Boleta electrica"),
                    ("ticket_pesaje", "Ticket de pesaje"),
                    ("ficha_tecnica_material", "Ficha tecnica de material"),
                    ("certificado_proveedor", "Certificado de proveedor"),
                    ("certificado_forestal", "Certificado forestal"),
                    ("registro_maquinaria", "Registro de maquinaria"),
                    ("registro_retiro_residuos", "Registro de retiro de residuos"),
                    ("registro_produccion", "Registro produccion"),
                    ("registro_secado", "Registro secado"),
                    ("documento_transporte", "Documento de transporte"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=40,
            ),
        ),
    ]
