# Generated by Django 6.0.1 on 2026-06-21 15:11

import apps.analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_accion_ambiental_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_documento", models.CharField(max_length=80)),
                ("industria", models.CharField(db_index=True, max_length=80)),
                ("nombre", models.CharField(max_length=240)),
                ("fecha_documento", models.DateField()),
                ("periodo_inicio", models.DateField(blank=True, null=True)),
                ("periodo_fin", models.DateField(blank=True, null=True)),
                (
                    "fuente_origen",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("pdf", "PDF"),
                            ("foto", "Foto"),
                            ("cems", "CEMS"),
                            ("laboratorio", "Laboratorio"),
                            ("otro", "Otro"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.analytics.models.documento_ambiental_upload_path,
                    ),
                ),
                (
                    "estado_procesamiento",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("extraido", "Extraido"),
                            ("observado", "Observado"),
                            ("validado", "Validado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "estado_validacion",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("valido", "Valido"),
                            ("observado", "Observado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("resumen", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constructora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_ambientales",
                        to="analytics.constructora",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_ambientales",
                        to="analytics.etapaobra",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_ambientales",
                        to="analytics.obra",
                    ),
                ),
                (
                    "registro_emision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_ambientales",
                        to="analytics.registroemision",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_documento", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LimiteNormativoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industria", models.CharField(db_index=True, max_length=80)),
                ("variable_id", models.CharField(db_index=True, max_length=80)),
                ("nombre", models.CharField(max_length=180)),
                (
                    "normativa",
                    models.CharField(
                        choices=[
                            ("RCA", "RCA"),
                            ("DS90", "DS90"),
                            ("DS38", "DS38"),
                            ("DS148", "DS148"),
                            ("RETC", "RETC"),
                            ("SIDREP", "SIDREP"),
                            ("SINADER", "SINADER"),
                            ("REP", "REP"),
                            ("CEMS", "CEMS"),
                            ("Sernageomin", "Sernageomin"),
                            ("Sernapesca", "Sernapesca"),
                            ("otro", "Otro"),
                        ],
                        max_length=40,
                    ),
                ),
                ("limite", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unidad", models.CharField(max_length=40)),
                (
                    "comparador",
                    models.CharField(
                        choices=[
                            ("<=", "<="),
                            (">=", ">="),
                            ("rango", "Rango"),
                            ("presencia", "Presencia"),
                            ("obligatorio", "Obligatorio"),
                        ],
                        default="<=",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constructora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limites_ambientales",
                        to="analytics.constructora",
                    ),
                ),
            ],
            options={
                "ordering": ["variable_id", "normativa", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VariableAmbientalExtraida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable_id", models.CharField(db_index=True, max_length=80)),
                ("nombre", models.CharField(max_length=180)),
                ("categoria", models.CharField(blank=True, max_length=80)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=40)),
                ("fecha_medicion", models.DateField(blank=True, null=True)),
                ("punto_medicion", models.CharField(blank=True, max_length=160)),
                (
                    "limite_aplicable",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("unidad_limite", models.CharField(blank=True, max_length=40)),
                (
                    "estado_cumplimiento",
                    models.CharField(
                        choices=[
                            ("sin_limite", "Sin limite"),
                            ("cumple", "Cumple"),
                            ("alerta", "Alerta"),
                            ("incumple", "Incumple"),
                            ("sin_dato", "Sin dato"),
                        ],
                        default="sin_dato",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_sobre_limite",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "confianza_extraccion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constructora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables_ambientales",
                        to="analytics.constructora",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables_extraidas",
                        to="analytics.documentoambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_medicion", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertaCumplimientoAmbiental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("verde", "Verde"),
                            ("amarillo", "Amarillo"),
                            ("rojo", "Rojo"),
                            ("gris", "Gris"),
                        ],
                        default="gris",
                        max_length=20,
                    ),
                ),
                ("tipo_alerta", models.CharField(max_length=80)),
                ("titulo", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_revision", "En revision"),
                            ("resuelta", "Resuelta"),
                            ("descartada", "Descartada"),
                        ],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                ("accion_sugerida", models.TextField(blank=True)),
                ("normativa", models.CharField(blank=True, max_length=80)),
                ("fecha_evento", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constructora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas_cumplimiento",
                        to="analytics.constructora",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_cumplimiento",
                        to="analytics.documentoambiental",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_cumplimiento",
                        to="analytics.variableambientalextraida",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_evento", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentoambiental",
            index=models.Index(
                fields=["constructora_id", "industria"],
                name="analytics_d_constru_6e7b4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentoambiental",
            index=models.Index(
                fields=["constructora_id", "estado_validacion"],
                name="analytics_d_constru_8fe830_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentoambiental",
            index=models.Index(
                fields=["constructora_id", "tipo_documento"],
                name="analytics_d_constru_f0c353_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="limitenormativoambiental",
            index=models.Index(
                fields=["constructora_id", "industria"],
                name="analytics_l_constru_724fab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="limitenormativoambiental",
            index=models.Index(
                fields=["constructora_id", "variable_id", "activo"],
                name="analytics_l_constru_73e4c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableambientalextraida",
            index=models.Index(
                fields=["constructora_id", "variable_id"],
                name="analytics_v_constru_ee0207_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableambientalextraida",
            index=models.Index(
                fields=["constructora_id", "estado_cumplimiento"],
                name="analytics_v_constru_0cbc4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableambientalextraida",
            index=models.Index(
                fields=["documento_id"], name="analytics_v_documen_e9b8ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertacumplimientoambiental",
            index=models.Index(
                fields=["constructora_id", "estado"],
                name="analytics_a_constru_d04989_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertacumplimientoambiental",
            index=models.Index(
                fields=["constructora_id", "severidad"],
                name="analytics_a_constru_9b3a7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertacumplimientoambiental",
            index=models.Index(
                fields=["variable_id", "tipo_alerta"],
                name="analytics_a_variabl_c3053b_idx",
            ),
        ),
    ]
