# Generated by Django after AccionAmbiental was mapped to the existing analytics table

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_accion_ambiental_links"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accionambiental",
            options={
                "managed": False,
                "ordering": ["-created_at"],
            },
        ),
    ]
