# Generated by Django 5.2.5 on 2026-08-13 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0011_organizacion_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etapaobra",
            options={"ordering": ["organizacion__nombre", "nombre"]},
        ),
        migrations.AlterModelOptions(
            name="usuarioorganizacion",
            options={
                "ordering": [
                    "organizacion__nombre",
                    "user__first_name",
                    "user__username",
                ]
            },
        ),
        migrations.AlterField(
            model_name="alertacumplimientoambiental",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="configuracionorganizacion",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="documentoambiental",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="especiemadera",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="etapaobra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="evidenciaobra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="factoremision",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="factoremision",
            name="preset",
            field=models.CharField(
                choices=[
                    ("construccion", "Construcción"),
                    ("forestal", "Forestal"),
                    ("transporte", "Transporte"),
                    ("industrial", "Industrial"),
                ],
                db_index=True,
                default="construccion",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="historialcambioobra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="limitenormativoambiental",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="loteforestal",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="materialconstruccion",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="obra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registroemision",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="transporteloteforestal",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="transporteobra",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usuarioorganizacion",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usuarioorganizacion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizaciones_perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="variableambientalextraida",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="alertacumplimientoambiental",
            index=models.Index(
                fields=["organizacion_id", "estado"],
                name="analytics_a_organiz_c41cea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertacumplimientoambiental",
            index=models.Index(
                fields=["organizacion_id", "severidad"],
                name="analytics_a_organiz_58b781_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentoambiental",
            index=models.Index(
                fields=["organizacion_id", "industria"],
                name="analytics_d_organiz_d2aee6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentoambiental",
            index=models.Index(
                fields=["organizacion_id", "estado_validacion"],
                name="analytics_d_organiz_ead0bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentoambiental",
            index=models.Index(
                fields=["organizacion_id", "tipo_documento"],
                name="analytics_d_organiz_9cbb0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenciaobra",
            index=models.Index(
                fields=["organizacion_id", "estado_documental"],
                name="analytics_e_organiz_08f80d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenciaobra",
            index=models.Index(
                fields=["organizacion_id", "tipo_evidencia"],
                name="analytics_e_organiz_9cf88c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="limitenormativoambiental",
            index=models.Index(
                fields=["organizacion_id", "industria"],
                name="analytics_l_organiz_e3ba9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="limitenormativoambiental",
            index=models.Index(
                fields=["organizacion_id", "variable_id", "activo"],
                name="analytics_l_organiz_58d3ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loteforestal",
            index=models.Index(
                fields=["organizacion_id", "fecha"],
                name="analytics_l_organiz_792ad0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loteforestal",
            index=models.Index(
                fields=["organizacion_id", "lote_id"],
                name="analytics_l_organiz_28e028_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loteforestal",
            index=models.Index(
                fields=["organizacion_id", "especie"],
                name="analytics_l_organiz_99f285_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "fecha"],
                name="analytics_r_organiz_aaad72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "categoria"],
                name="analytics_r_organiz_b5f969_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "actividad_key"],
                name="analytics_r_organiz_723620_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableambientalextraida",
            index=models.Index(
                fields=["organizacion_id", "variable_id"],
                name="analytics_v_organiz_781c44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variableambientalextraida",
            index=models.Index(
                fields=["organizacion_id", "estado_cumplimiento"],
                name="analytics_v_organiz_a4b7c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="usuarioorganizacion",
            constraint=models.UniqueConstraint(
                fields=("user", "organizacion"), name="unique_usuario_organizacion"
            ),
        ),
        migrations.AlterModelTable(
            name="accionambiental",
            table="analytics_accionambiental",
        ),
    ]
