# Generated by Django 6.0.4 on 2026-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_factor_catalog_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambiolote',
            name='tipo',
            field=models.CharField(choices=[('extraido', 'Dato extraído'), ('importado', 'Dato importado'), ('validado', 'Dato validado'), ('rechazado', 'Dato rechazado'), ('corregido', 'Dato corregido')], max_length=20),
        ),
    ]
