# Generated by Django 5.2.5 on 2026-08-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_alter_etapaobra_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factoremision",
            name="preset",
            field=models.CharField(
                choices=[
                    ("construccion", "Construcción"),
                    ("forestal", "Forestal"),
                    ("aserradero", "Aserradero"),
                    ("transporte", "Transporte"),
                    ("industrial", "Industrial"),
                ],
                db_index=True,
                default="construccion",
                max_length=40,
            ),
        ),
    ]
