# Generated by Django 6.0.4 on 2026-04-29 23:14

import django.db.models.deletion
from django.db import migrations, models


def normalize_identifier(value):
    import re
    import unicodedata

    normalized = unicodedata.normalize("NFKD", str(value or ""))
    without_accents = "".join(
        char for char in normalized if not unicodedata.combining(char)
    )
    key = re.sub(r"[^a-zA-Z0-9]+", "_", without_accents).strip("_").upper()
    return key or "GENERAL"


def backfill_empresa_unidad(apps, schema_editor):
    Empresa = apps.get_model("analytics", "Empresa")
    UnidadOperativa = apps.get_model("analytics", "UnidadOperativa")
    Lote = apps.get_model("analytics", "Lote")
    EmisionLote = apps.get_model("analytics", "EmisionLote")

    for lote in Lote.objects.all().order_by("id"):
        nombre = lote.empresa_aserradero or "Empresa sin nombre"
        empresa_id = normalize_identifier(nombre)
        empresa, _ = Empresa.objects.get_or_create(
            empresa_id=empresa_id,
            defaults={"nombre": nombre, "rubro": "Madera"},
        )
        unidad, _ = UnidadOperativa.objects.get_or_create(
            unidad_id=f"{empresa.empresa_id}_GENERAL",
            defaults={
                "empresa": empresa,
                "nombre": "Unidad General",
                "tipo": "Aserradero",
            },
        )
        lote.empresa_id = empresa.id
        lote.unidad_operativa_id = unidad.id
        lote.save(update_fields=["empresa", "unidad_operativa"])

    for actividad in EmisionLote.objects.select_related("lote").all().order_by("id"):
        if actividad.lote_id:
            actividad.empresa_id = actividad.lote.empresa_id
            actividad.unidad_operativa_id = actividad.lote.unidad_operativa_id
            actividad.tipo_asignacion = "lote"
        elif actividad.unidad_operativa_id:
            actividad.empresa_id = actividad.unidad_operativa.empresa_id
            actividad.tipo_asignacion = "unidad"
        elif actividad.empresa_id:
            actividad.tipo_asignacion = "empresa"
        actividad.save(
            update_fields=["empresa", "unidad_operativa", "tipo_asignacion"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_factoremision_metadata_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('rut', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('comuna', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=240)),
                ('rubro', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('contacto', models.CharField(blank=True, max_length=160)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='emisionlote',
            name='categoria',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='emisionlote',
            name='tipo_asignacion',
            field=models.CharField(choices=[('lote', 'Lote'), ('unidad', 'Unidad operativa'), ('empresa', 'Empresa')], default='lote', max_length=20),
        ),
        migrations.AlterField(
            model_name='emisionlote',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='analytics.lote'),
        ),
        migrations.AddField(
            model_name='emisionlote',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_emision', to='analytics.empresa'),
        ),
        migrations.AddField(
            model_name='lote',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='analytics.empresa'),
        ),
        migrations.CreateModel(
            name='UnidadOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_id', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('Planta', 'Planta'), ('Aserradero', 'Aserradero'), ('Secado', 'Secado'), ('Productos terminados', 'Productos terminados'), ('Bodega', 'Bodega'), ('Despacho', 'Despacho'), ('Mantencion', 'Mantencion'), ('Administracion', 'Administracion'), ('Otro', 'Otro')], default='Otro', max_length=40)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('comuna', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=240)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_operativas', to='analytics.empresa')),
            ],
            options={
                'ordering': ['empresa__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='emisionlote',
            name='unidad_operativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_emision', to='analytics.unidadoperativa'),
        ),
        migrations.AddField(
            model_name='lote',
            name='unidad_operativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='analytics.unidadoperativa'),
        ),
        migrations.RunPython(backfill_empresa_unidad, migrations.RunPython.noop),
    ]
