# Generated by Django 5.2.5 on 2026-08-13 01:14

from django.db import migrations, models


def classify_existing_origins(apps, schema_editor):
    RegistroEmision = apps.get_model("analytics", "RegistroEmision")
    for registro in RegistroEmision.objects.only("id", "metadata").iterator():
        metadata = registro.metadata if isinstance(registro.metadata, dict) else {}
        origin = str(metadata.get("origen") or metadata.get("fuente_dato") or "").lower()
        if origin == "iot_sensor":
            kind = "sensor_iot"
            source = str(metadata.get("dispositivo_id") or "iot_sensor")
            external_id = str(metadata.get("external_id") or "")
        elif "csv" in origin:
            kind, source, external_id = "csv", origin, str(metadata.get("registro_import_id") or "")
        elif origin:
            kind, source, external_id = "excel", origin, str(metadata.get("registro_import_id") or "")
        else:
            kind, source, external_id = "sistema", "legacy", ""
        RegistroEmision.objects.filter(pk=registro.pk).update(
            tipo_ingreso=kind,
            fuente_ingreso=source,
            identificador_externo=external_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_alter_factoremision_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroemision",
            name="area_operacional",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="estado_validacion",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("validado", "Validado"),
                    ("rechazado", "Rechazado"),
                ],
                db_index=True,
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="fuente_ingreso",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="identificador_externo",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="numero_documento",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="tipo_ingreso",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("excel", "Excel"),
                    ("csv", "CSV"),
                    ("documento", "Documento"),
                    ("api_externa", "API externa"),
                    ("sensor_iot", "Sensor IoT"),
                    ("sistema", "Sistema"),
                ],
                db_index=True,
                default="sistema",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="unidad_operacional",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.RunPython(classify_existing_origins, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "tipo_ingreso"],
                name="analytics_r_organiz_312e6e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "estado_validacion"],
                name="analytics_r_organiz_9c5dc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "identificador_externo"],
                name="analytics_r_organiz_dd4605_idx",
            ),
        ),
    ]
