# Generated by Django 5.2.5 on 2026-08-13 01:25

import django.db.models.deletion
import hashlib
import json
import re
import unicodedata
from decimal import Decimal
from django.db import migrations, models


def normalized_text(value):
    value = unicodedata.normalize("NFKD", str(value or "").casefold())
    value = "".join(char for char in value if not unicodedata.combining(char))
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9]+", " ", value)).strip()


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def migrate_links_and_fingerprints(apps, schema_editor):
    Registro = apps.get_model("analytics", "RegistroEmision")
    Evidencia = apps.get_model("analytics", "EvidenciaObra")
    Documento = apps.get_model("analytics", "DocumentoAmbiental")
    for evidence in Evidencia.objects.exclude(registro_emision_id=None).iterator():
        evidence.registros_emision.add(evidence.registro_emision_id)
    for document in Documento.objects.exclude(registro_emision_id=None).iterator():
        document.registros_emision.add(document.registro_emision_id)
    aliases = {"kgs": "kg", "kilogramos": "kg", "litros": "l", "lt": "l", "lts": "l", "ton": "t", "toneladas": "t", "kw h": "kwh"}
    canonical_by_core = {}
    for record in Registro.objects.order_by("id").iterator():
        unit = normalized_text(record.unidad).replace(" ", "")
        unit = aliases.get(unit, unit)
        core = {
            "organizacion": record.organizacion_id,
            "fecha": record.fecha.isoformat() if record.fecha else "",
            "actividad": normalized_text(record.fuente_emision),
            "categoria": normalized_text(record.categoria),
            "cantidad": format(Decimal(str(record.cantidad)).normalize(), "f"),
            "unidad": unit,
            "proveedor": normalized_text(record.proveedor),
            "area_operacional": normalized_text(record.area_operacional),
            "unidad_operacional": normalized_text(record.unidad_operacional),
        }
        full = {**core, "numero_documento": normalized_text(record.numero_documento), "identificador_externo": normalized_text(record.identificador_externo)}
        core_hash, full_hash = digest(core), digest(full)
        canonical = canonical_by_core.get((record.organizacion_id, core_hash))
        updates = {"fingerprint": full_hash, "fingerprint_nucleo": core_hash}
        if canonical:
            updates.update({"estado_gobernanza": "posible_duplicado", "registro_canonico_id": canonical, "contabilizable": False, "emisiones_kg_co2e": Decimal("0")})
        else:
            canonical_by_core[(record.organizacion_id, core_hash)] = record.id
        Registro.objects.filter(pk=record.pk).update(**updates)


def restore_primary_links(apps, schema_editor):
    Evidencia = apps.get_model("analytics", "EvidenciaObra")
    Documento = apps.get_model("analytics", "DocumentoAmbiental")
    for model in (Evidencia, Documento):
        for item in model.objects.prefetch_related("registros_emision").iterator():
            primary = item.registros_emision.order_by("id").first()
            if primary:
                model.objects.filter(pk=item.pk).update(registro_emision_id=primary.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0014_registroemision_area_operacional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoambiental",
            name="registros_emision",
            field=models.ManyToManyField(
                blank=True,
                related_name="documentos_ambientales",
                to="analytics.registroemision",
            ),
        ),
        migrations.AddField(
            model_name="evidenciaobra",
            name="registros_emision",
            field=models.ManyToManyField(
                blank=True, related_name="evidencias", to="analytics.registroemision"
            ),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="contabilizable",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="estado_gobernanza",
            field=models.CharField(
                choices=[
                    ("nuevo", "Nuevo"),
                    ("posible_duplicado", "Posible duplicado"),
                    ("duplicado_confirmado", "Duplicado confirmado"),
                    ("validado", "Validado"),
                ],
                db_index=True,
                default="nuevo",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="fingerprint_nucleo",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="registroemision",
            name="registro_canonico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicados_detectados",
                to="analytics.registroemision",
            ),
        ),
        migrations.RunPython(migrate_links_and_fingerprints, restore_primary_links),
        migrations.RemoveIndex(
            model_name="evidenciaobra",
            name="analytics_e_registr_1ec239_idx",
        ),
        migrations.RemoveField(
            model_name="documentoambiental",
            name="registro_emision",
        ),
        migrations.RemoveField(
            model_name="evidenciaobra",
            name="registro_emision",
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "fingerprint"],
                name="analytics_r_organiz_a29647_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registroemision",
            index=models.Index(
                fields=["organizacion_id", "fingerprint_nucleo"],
                name="analytics_r_organiz_6ca806_idx",
            ),
        ),
    ]
