# Generated by Django 6.0.4 on 2026-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_lote_destino_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unidadoperativa',
            name='tipo',
            field=models.CharField(choices=[('General', 'General'), ('Planta', 'Planta'), ('Aserradero', 'Aserradero'), ('Secado', 'Secado'), ('Productos terminados', 'Productos terminados'), ('Bodega', 'Bodega'), ('Despacho', 'Despacho'), ('Mantencion', 'Mantencion'), ('Administracion', 'Administracion'), ('Otro', 'Otro')], default='Otro', max_length=40),
        ),
    ]
