# Generated by Django 5.2.5 on 2026-08-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0015_remove_evidenciaobra_analytics_e_registr_1ec239_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionorganizacion",
            name="meta_emisiones_kg_co2e",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=16, null=True
            ),
        ),
        migrations.CreateModel(
            name="DatoACV",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_producto", models.CharField(max_length=240)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("materia_prima", "Materia prima"),
                            ("fabricacion", "Fabricacion"),
                            ("transporte", "Transporte"),
                            ("uso_operacion", "Uso / operacion"),
                            ("mantencion", "Mantencion"),
                            ("fin_vida", "Fin de vida"),
                            (
                                "reutilizacion_reciclaje_disposicion",
                                "Reutilizacion / reciclaje / disposicion",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=6, max_digits=16)),
                ("unidad", models.CharField(max_length=40)),
                ("fuente", models.CharField(max_length=240)),
                (
                    "calidad_dato",
                    models.CharField(
                        choices=[
                            ("medido", "Medido"),
                            ("calculado", "Calculado"),
                            ("referencial", "Referencial"),
                            ("desconocido", "Desconocido"),
                        ],
                        default="desconocido",
                        max_length=20,
                    ),
                ),
                ("origen_dato", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="datos_acv",
                        to="analytics.documentoambiental",
                    ),
                ),
                (
                    "evidencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="datos_acv",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "lote_forestal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datos_acv",
                        to="analytics.loteforestal",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datos_acv",
                        to="analytics.obra",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datos_acv",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["material_producto", "etapa"],
                "indexes": [
                    models.Index(
                        fields=["organizacion", "etapa"],
                        name="analytics_d_organiz_953013_idx",
                    )
                ],
            },
        ),
    ]
