# Generated by Django 5.2.5 on 2026-08-13 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0016_configuracionorganizacion_meta_emisiones_kg_co2e_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionMejoraAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=240)),
                ("descripcion", models.TextField()),
                ("responsable", models.CharField(blank=True, max_length=180)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_objetivo", models.DateField(blank=True, null=True)),
                ("implementada_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblematicaAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=240)),
                ("descripcion", models.TextField()),
                ("categoria", models.CharField(max_length=120)),
                (
                    "indicador",
                    models.CharField(default="co2e_total_kg", max_length=120),
                ),
                ("unidad_indicador", models.CharField(default="kgCO2e", max_length=40)),
                ("area_operacional", models.CharField(blank=True, max_length=180)),
                ("unidad_operacional", models.CharField(blank=True, max_length=180)),
                ("valor_inicial", models.DecimalField(decimal_places=6, max_digits=18)),
                ("objetivo_meta", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "valor_posterior",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "mejora_absoluta",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "mejora_porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("fecha_deteccion", models.DateField()),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                            ("critico", "Critico"),
                        ],
                        default="medio",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("detectada", "Detectada"),
                            ("en_analisis", "En analisis"),
                            ("accion_propuesta", "Accion propuesta"),
                            ("en_implementacion", "En implementacion"),
                            ("en_seguimiento", "En seguimiento"),
                            ("resuelta", "Resuelta"),
                            ("mejora_insuficiente", "Mejora insuficiente"),
                            ("no_resuelta", "No resuelta"),
                            ("escalada", "Escalada"),
                        ],
                        default="detectada",
                        max_length=30,
                    ),
                ),
                (
                    "resultado_evaluacion",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de medicion"),
                            ("efectiva", "Efectiva"),
                            ("parcialmente_efectiva", "Parcialmente efectiva"),
                            ("no_efectiva", "No efectiva"),
                        ],
                        default="pendiente",
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problematicas_ambientales",
                        to="analytics.obra",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problematicas_ambientales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_deteccion", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicionSeguimientoAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("valor", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unidad", models.CharField(max_length=40)),
                ("fuente", models.CharField(default="manual", max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mediciones",
                        to="analytics.accionmejoraambiental",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones",
                        to="analytics.problematicaambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialProblematicaAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=40)),
                ("estado_anterior", models.CharField(blank=True, max_length=30)),
                ("estado_nuevo", models.CharField(blank=True, max_length=30)),
                ("detalle", models.TextField(blank=True)),
                ("usuario", models.CharField(blank=True, max_length=150)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="analytics.problematicaambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="problematica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acciones",
                to="analytics.problematicaambiental",
            ),
        ),
        migrations.AddIndex(
            model_name="problematicaambiental",
            index=models.Index(
                fields=["organizacion", "estado"], name="analytics_p_organiz_390777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problematicaambiental",
            index=models.Index(
                fields=["organizacion", "categoria"],
                name="analytics_p_organiz_d67238_idx",
            ),
        ),
    ]
