# Generated by Django 5.2.5 on 2026-08-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0017_accionmejoraambiental_problematicaambiental_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecomendacionAgenteAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.TextField()),
                ("justificacion", models.TextField()),
                ("indicador_afectado", models.CharField(max_length=120)),
                ("resultado_esperado", models.TextField()),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Critica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("periodo_seguimiento", models.CharField(max_length=120)),
                (
                    "nivel_confianza",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("diagnostico", models.JSONField(blank=True, default=dict)),
                ("contexto_resumen", models.JSONField(blank=True, default=dict)),
                ("proveedor", models.CharField(blank=True, max_length=80)),
                ("modelo", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendaciones_agente",
                        to="analytics.problematicaambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["problematica", "prioridad"],
                        name="analytics_r_problem_16b32f_idx",
                    )
                ],
            },
        ),
    ]
