# Generated by Django 6.0.4 on 2026-05-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_capitalize_activity_display_names'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentolote',
            index=models.Index(fields=['lote_id', 'estado_validacion'], name='analytics_d_lote_id_a5e211_idx'),
        ),
        migrations.AddIndex(
            model_name='documentolote',
            index=models.Index(fields=['lote_id', 'tipo_documento'], name='analytics_d_lote_id_7e6e60_idx'),
        ),
        migrations.AddIndex(
            model_name='documentolote',
            index=models.Index(fields=['lote_id'], name='analytics_d_lote_id_dc8837_idx'),
        ),
        migrations.AddIndex(
            model_name='emisionlote',
            index=models.Index(fields=['empresa_id', 'fecha'], name='analytics_e_empresa_fd6d17_idx'),
        ),
        migrations.AddIndex(
            model_name='emisionlote',
            index=models.Index(fields=['empresa_id', 'categoria'], name='analytics_e_empresa_00bc57_idx'),
        ),
        migrations.AddIndex(
            model_name='emisionlote',
            index=models.Index(fields=['empresa_id', 'actividad_key'], name='analytics_e_empresa_311158_idx'),
        ),
        migrations.AddIndex(
            model_name='emisionlote',
            index=models.Index(fields=['empresa_id', 'unidad_operativa_id'], name='analytics_e_empresa_5a1434_idx'),
        ),
        migrations.AddIndex(
            model_name='emisionlote',
            index=models.Index(fields=['empresa_id', 'lote_id'], name='analytics_e_empresa_bff0bf_idx'),
        ),
    ]
