# Generated by Django 5.2.5 on 2026-08-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0018_recomendacionagenteambiental"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpedienteAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("contenido_procesado", models.JSONField(default=dict)),
                ("resumen_ejecutivo", models.TextField()),
                ("proveedor_resumen", models.CharField(blank=True, max_length=80)),
                ("modelo_resumen", models.CharField(blank=True, max_length=120)),
                ("generado_por", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="limitenormativoambiental",
            name="fuente_normativa",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="limitenormativoambiental",
            name="region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="limitenormativoambiental",
            name="tipo_instalacion",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="limitenormativoambiental",
            name="validado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="limitenormativoambiental",
            name="vigencia_desde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="limitenormativoambiental",
            name="vigencia_hasta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problematicaambiental",
            name="criterios_escalamiento",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problematicaambiental",
            name="escalada_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problematicaambiental",
            name="requiere_evaluacion_profesional",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="limitenormativoambiental",
            name="limite",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="limitenormativoambiental",
            name="normativa",
            field=models.CharField(
                choices=[
                    ("ISO 14001", "ISO 14001"),
                    ("ISO 14064-1", "ISO 14064-1"),
                    ("ISO 14067", "ISO 14067"),
                    ("ISO 14040/14044", "ISO 14040/14044"),
                    ("ISO 21930", "ISO 21930"),
                    ("Ley 21.455", "Ley 21.455"),
                    ("Ley 20.920", "Ley 20.920"),
                    ("Ley 19.300", "Ley 19.300"),
                    ("HuellaChile", "HuellaChile"),
                    ("RCA", "RCA"),
                    ("DS90", "DS90"),
                    ("DS38", "DS38"),
                    ("DS148", "DS148"),
                    ("RETC", "RETC"),
                    ("SIDREP", "SIDREP"),
                    ("SINADER", "SINADER"),
                    ("REP", "REP"),
                    ("CEMS", "CEMS"),
                    ("Sernageomin", "Sernageomin"),
                    ("Sernapesca", "Sernapesca"),
                    ("otro", "Otro"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="limitenormativoambiental",
            name="unidad",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name="limitenormativoambiental",
            index=models.Index(
                fields=["organizacion_id", "industria", "region", "validado"],
                name="analytics_l_organiz_7ea1a2_idx",
            ),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="problematica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expedientes",
                to="analytics.problematicaambiental",
            ),
        ),
        migrations.AddConstraint(
            model_name="expedienteambiental",
            constraint=models.UniqueConstraint(
                fields=("problematica", "version"),
                name="unique_expediente_problematica_version",
            ),
        ),
    ]
