# Generated by Django 6.0.4 on 2026-05-05 03:05

import apps.analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_documentolote_analytics_d_lote_id_a5e211_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('tipo_documento', models.CharField(choices=[('guia_despacho', 'Guia de despacho'), ('factura_combustible', 'Factura combustible'), ('factura_electrica', 'Factura electrica'), ('certificado_origen', 'Certificado de origen'), ('certificado_forestal', 'Certificado forestal'), ('documento_transporte', 'Documento transporte'), ('ticket_pesaje', 'Ticket pesaje'), ('registro_gps', 'Registro GPS'), ('fotografia', 'Fotografia'), ('ficha_tecnica', 'Ficha tecnica'), ('otro', 'Otro')], default='otro', max_length=40)),
                ('archivo', models.FileField(upload_to=apps.analytics.models.evidencia_upload_path)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('observada', 'Observada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='analytics.emisionlote')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='analytics.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='analytics.lote')),
                ('unidad_operativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='analytics.unidadoperativa')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa_id', 'estado'], name='analytics_e_empresa_a4cb0e_idx'), models.Index(fields=['empresa_id', 'tipo_documento'], name='analytics_e_empresa_f26f12_idx'), models.Index(fields=['empresa_id', 'lote_id'], name='analytics_e_empresa_3396e8_idx'), models.Index(fields=['empresa_id', 'unidad_operativa_id'], name='analytics_e_empresa_b74855_idx')],
            },
        ),
    ]
