# Generated by Django 6.0.4 on 2026-05-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='alcance',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('unidad', 'Unidad operativa'), ('lote', 'Lote'), ('emision', 'Emision'), ('transporte', 'Transporte')], default='empresa', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='estado_revision',
            field=models.CharField(choices=[('sin_revisar', 'Sin revisar'), ('validada', 'Validada'), ('observada', 'Observada'), ('rechazada', 'Rechazada')], default='sin_revisar', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='estado_sistema',
            field=models.CharField(choices=[('corporativa', 'Corporativa'), ('vinculada', 'Vinculada'), ('sin_vinculo', 'Sin vinculo')], default='sin_vinculo', max_length=20),
        ),
    ]
