# Generated by Django 5.2.5 on 2026-08-14 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0020_require_explicit_normative_validation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacidadAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.SlugField(max_length=60, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticoAmbientalInicial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En progreso"),
                            ("completado", "Completado"),
                            ("requiere_actualizacion", "Requiere actualizacion"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=30,
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_finalizacion", models.DateField(blank=True, null=True)),
                ("objetivo_principal", models.TextField(blank=True)),
                ("descripcion_contexto", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostico_ambiental",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosticos_ambientales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElementoDiagnosticoAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("proceso", "Proceso identificado"),
                            ("informacion_disponible", "Informacion disponible"),
                            ("informacion_faltante", "Informacion faltante"),
                            ("fuente", "Fuente conocida"),
                            ("brecha", "Brecha ambiental"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnostico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementos",
                        to="analytics.diagnosticoambientalinicial",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="UnidadOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("planta", "Planta"),
                            ("instalacion", "Instalacion"),
                            ("faena", "Faena"),
                            ("sucursal", "Sucursal"),
                            ("centro_operacional", "Centro operacional"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcesoOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("en_diseno", "En diseno"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procesos_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos",
                        to="analytics.unidadoperacional",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CapacidadOrganizacion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente_diagnostico", "Pendiente de diagnostico"),
                            ("aplica", "Aplica"),
                            ("no_aplica", "No aplica"),
                            ("sin_datos", "Sin datos"),
                            ("construyendo_linea_base", "Construyendo linea base"),
                            ("operativa", "Operativa"),
                        ],
                        db_index=True,
                        default="pendiente_diagnostico",
                        max_length=35,
                    ),
                ),
                ("recomendada_por_preset", models.BooleanField(default=False)),
                ("configuracion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capacidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizaciones",
                        to="analytics.capacidadambiental",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades_ambientales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organizacion", "capacidad"),
                        name="unique_capacidad_organizacion",
                    )
                ],
            },
        ),
    ]
