# Generated by Django 6.0.4 on 2026-05-05 21:41

import apps.analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_evidencia_alcance_evidencia_estado_revision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_emisiones', models.CharField(default='kg CO2e', max_length=20)),
                ('unidad_volumen_madera', models.CharField(default='m3', max_length=10)),
                ('porcentaje_carbono_default', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('densidad_madera_default', models.DecimalField(decimal_places=2, default=420, max_digits=8)),
                ('factor_electrico_default', models.CharField(blank=True, default='Factor electrico vigente', max_length=160)),
                ('region_electrica_default', models.CharField(blank=True, default='Biobio', max_length=120)),
                ('redondeo_decimales', models.PositiveSmallIntegerField(default=1)),
                ('mostrar_balance_neto', models.BooleanField(default=True)),
                ('permitir_co2_almacenado', models.BooleanField(default=True)),
                ('modo_importacion', models.CharField(choices=[('flexible', 'Flexible'), ('estricto', 'Estricto')], default='flexible', max_length=20)),
                ('crear_unidades_automaticamente', models.BooleanField(default=True)),
                ('crear_lotes_automaticamente', models.BooleanField(default=True)),
                ('permitir_actividades_sin_factor', models.BooleanField(default=False)),
                ('actualizar_registros_existentes', models.BooleanField(default=True)),
                ('bloquear_duplicados', models.BooleanField(default=True)),
                ('requerir_unidad_lote', models.BooleanField(default=False)),
                ('requerir_lote_actividad', models.BooleanField(default=False)),
                ('permitir_evidencias_sin_vinculo', models.BooleanField(default=True)),
                ('pasaporte_activo', models.BooleanField(default=True)),
                ('pasaporte_requiere_balance_favorable', models.BooleanField(default=True)),
                ('pasaporte_requiere_evidencia', models.BooleanField(default=True)),
                ('pasaporte_requiere_trazabilidad', models.BooleanField(default=True)),
                ('score_pasaporte_verde', models.PositiveSmallIntegerField(default=70)),
                ('score_pasaporte_plus', models.PositiveSmallIntegerField(default=90)),
                ('score_confianza_minimo', models.PositiveSmallIntegerField(default=75)),
                ('evidencia_requerida_pasaporte', models.BooleanField(default=True)),
                ('evidencia_requerida_lotes_criticos', models.BooleanField(default=True)),
                ('umbral_lote_critico', models.DecimalField(decimal_places=2, default=1000, max_digits=14)),
                ('permitir_evidencia_empresa', models.BooleanField(default=True)),
                ('permitir_evidencia_unidad', models.BooleanField(default=True)),
                ('permitir_evidencia_lote', models.BooleanField(default=True)),
                ('permitir_evidencia_emision', models.BooleanField(default=True)),
                ('formatos_evidencia_permitidos', models.JSONField(default=apps.analytics.models.evidencia_formatos_default)),
                ('max_file_size_mb', models.PositiveSmallIntegerField(default=10)),
                ('reporte_agrupacion_default', models.CharField(choices=[('dia', 'Dia'), ('semana', 'Semana'), ('mes', 'Mes'), ('trimestre', 'Trimestre'), ('anio', 'Anio')], default='mes', max_length=20)),
                ('reporte_periodo_default', models.CharField(choices=[('ultimos_30_dias', 'Ultimos 30 dias'), ('ultimos_3_meses', 'Ultimos 3 meses'), ('ultimos_6_meses', 'Ultimos 6 meses'), ('ultimos_12_meses', 'Ultimos 12 meses'), ('anio_actual', 'Anio actual')], default='ultimos_12_meses', max_length=30)),
                ('reporte_mostrar_categoria', models.BooleanField(default=True)),
                ('reporte_mostrar_unidad', models.BooleanField(default=True)),
                ('reporte_mostrar_tabla', models.BooleanField(default=True)),
                ('reporte_unidad_visual_emisiones', models.CharField(default='kg CO2e', max_length=20)),
                ('reporte_lectura_ejecutiva', models.BooleanField(default=True)),
                ('reporte_equivalencias', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='analytics.empresa')),
            ],
        ),
    ]
