# Generated by Django 5.2.5 on 2026-08-14 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0021_capacidadambiental_diagnosticoambientalinicial_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("transporte", "Transporte"),
                            ("consumo_energia", "Consumo de energia"),
                            ("consumo_agua", "Consumo de agua"),
                            ("consumo_combustible", "Consumo de combustible"),
                            ("operacion_maquinaria", "Operacion de maquinaria"),
                            ("movimiento_material", "Movimiento de material"),
                            ("gestion_residuo", "Gestion de residuo"),
                            ("generacion_energia", "Generacion de energia"),
                            ("proceso_productivo", "Proceso productivo"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="otro",
                        max_length=40,
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=180)),
                ("timestamp_inicio", models.DateTimeField(db_index=True)),
                ("timestamp_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("registrada", "Registrada"),
                            ("incompleta", "Incompleta"),
                            ("lista_para_evaluacion", "Lista para evaluacion"),
                            ("anulada", "Anulada"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=30,
                    ),
                ),
                ("referencia_externa", models.CharField(blank=True, max_length=180)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "proceso_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="analytics.procesooperacional",
                    ),
                ),
                (
                    "unidad_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="analytics.unidadoperacional",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp_inicio", "codigo"],
            },
        ),
        migrations.AddField(
            model_name="registroemision",
            name="actividad_operacional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_emision_legacy",
                to="analytics.actividadoperacional",
            ),
        ),
        migrations.CreateModel(
            name="FuenteDatos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("documento", "Documento"),
                            ("excel_csv", "Excel o CSV"),
                            ("api", "API"),
                            ("gps", "GPS"),
                            ("sensor", "Sensor"),
                            ("telemetria", "Telemetria"),
                            ("erp", "ERP"),
                            ("sistema_externo", "Sistema externo"),
                            ("sistema", "Sistema"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("identificador_externo", models.CharField(blank=True, max_length=180)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_datos",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Observacion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.SlugField(max_length=120)),
                (
                    "valor_numerico",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("valor_texto", models.TextField(blank=True)),
                ("unidad", models.CharField(blank=True, max_length=40)),
                ("timestamp_observacion", models.DateTimeField(db_index=True)),
                (
                    "metodo_captura",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("extraido_automaticamente", "Extraido automaticamente"),
                            ("importado", "Importado"),
                            ("api", "API"),
                            ("instrumental", "Instrumental"),
                            ("derivado", "Derivado"),
                        ],
                        default="manual",
                        max_length=35,
                    ),
                ),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[
                            ("declarativo", "Declarativo"),
                            ("documental", "Documental"),
                            ("instrumental", "Instrumental"),
                            ("extraido_automaticamente", "Extraido automaticamente"),
                        ],
                        default="declarativo",
                        max_length=35,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("validada", "Validada"),
                            ("rechazada", "Rechazada"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observaciones_operacionales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observaciones_operacionales",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observaciones",
                        to="analytics.fuentedatos",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp_observacion", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="actividadoperacional",
            index=models.Index(
                fields=["organizacion", "tipo", "estado"],
                name="analytics_a_organiz_000489_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="actividadoperacional",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"), name="unique_actividad_codigo_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="fuentedatos",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "nombre"), name="unique_fuente_datos_nombre_org"
            ),
        ),
        migrations.AddIndex(
            model_name="observacion",
            index=models.Index(
                fields=["organizacion", "concepto"],
                name="analytics_o_organiz_2adc96_idx",
            ),
        ),
    ]
