# Generated by Django 6.0.4 on 2026-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_empresaconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadoperativa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('suspendida', 'Suspendida'), ('en_mantenimiento', 'En Mantenimiento')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadoperativa',
            name='tipo',
            field=models.CharField(choices=[('Fundo Forestal', 'Fundo Forestal'), ('Transporte', 'Transporte'), ('Aserradero', 'Aserradero'), ('Acopio', 'Acopio'), ('Secado', 'Secado'), ('Administración', 'Administración'), ('Bodega', 'Bodega'), ('Planta Industrial', 'Planta Industrial'), ('Otro', 'Otro')], default='Otro', max_length=40),
        ),
    ]
