# Generated by Django 5.2.5 on 2026-08-14 18:10

import apps.analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0022_actividadoperacional_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaMapeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("formato", models.CharField(default="excel_csv", max_length=20)),
                ("version", models.PositiveIntegerField(default=1)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuente_datos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_mapeo",
                        to="analytics.fuentedatos",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_mapeo",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MapeoColumna",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("columna_origen", models.CharField(max_length=180)),
                ("columna_normalizada", models.SlugField(max_length=180)),
                ("concepto_normalizado", models.SlugField(max_length=120)),
                ("unidad_esperada", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeos",
                        to="analytics.plantillamapeo",
                    ),
                ),
            ],
            options={
                "ordering": ["columna_origen"],
            },
        ),
        migrations.CreateModel(
            name="ProcesoIngesta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ingesta",
                    models.CharField(default="transporte_excel_csv", max_length=30),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recibido", "Recibido"),
                            ("analizando", "Analizando"),
                            ("requiere_mapeo", "Requiere mapeo"),
                            ("listo_para_confirmar", "Listo para confirmar"),
                            ("procesando", "Procesando"),
                            ("completado", "Completado"),
                            (
                                "completado_con_observaciones",
                                "Completado con observaciones",
                            ),
                            ("fallido", "Fallido"),
                        ],
                        db_index=True,
                        default="recibido",
                        max_length=40,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("filas_detectadas", models.PositiveIntegerField(default=0)),
                ("filas_procesadas", models.PositiveIntegerField(default=0)),
                ("filas_con_error", models.PositiveIntegerField(default=0)),
                ("resumen_errores", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuente_datos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procesos_ingesta",
                        to="analytics.fuentedatos",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procesos_ingesta",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "plantilla_mapeo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos_ingesta",
                        to="analytics.plantillamapeo",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistroExtraido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_fila", models.PositiveIntegerField()),
                ("origen", models.CharField(blank=True, max_length=120)),
                ("datos_originales", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("extraido", "Extraido"),
                            ("valido", "Valido"),
                            ("error", "Error"),
                            ("procesado", "Procesado"),
                        ],
                        db_index=True,
                        default="extraido",
                        max_length=20,
                    ),
                ),
                ("errores", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actividad_creada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_origen",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "proceso_ingesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_extraidos",
                        to="analytics.procesoingesta",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_fila"],
            },
        ),
        migrations.CreateModel(
            name="VersionEvidencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "archivo",
                    models.FileField(
                        upload_to=apps.analytics.models.version_evidencia_upload_path
                    ),
                ),
                ("nombre_original", models.CharField(max_length=240)),
                ("tipo_documental", models.CharField(blank=True, max_length=80)),
                ("checksum_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "estado_procesamiento",
                    models.CharField(
                        choices=[
                            ("recibida", "Recibida"),
                            ("analizando", "Analizando"),
                            ("lista", "Lista"),
                            ("procesada", "Procesada"),
                            ("error", "Error"),
                        ],
                        default="recibida",
                        max_length=20,
                    ),
                ),
                ("metadata_tecnica", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones_evidencia",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="procesoingesta",
            name="version_evidencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos_ingesta",
                to="analytics.versionevidencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantillamapeo",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "fuente_datos", "nombre", "version"),
                name="unique_plantilla_mapeo_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="mapeocolumna",
            constraint=models.UniqueConstraint(
                fields=("plantilla", "columna_normalizada"),
                name="unique_mapeo_columna_plantilla",
            ),
        ),
        migrations.AddConstraint(
            model_name="registroextraido",
            constraint=models.UniqueConstraint(
                fields=("proceso_ingesta", "numero_fila"),
                name="unique_registro_extraido_fila",
            ),
        ),
        migrations.AddConstraint(
            model_name="versionevidencia",
            constraint=models.UniqueConstraint(
                fields=("evidencia", "version"), name="unique_version_evidencia"
            ),
        ),
    ]
