# Generated by Django 6.0.4 on 2026-05-08 17:22

from django.db import migrations


def populate_lote_unidad_operativa(apps, schema_editor):
    """Populate unidad_operativa for existing lotes without one"""
    Lote = apps.get_model('analytics', 'Lote')
    UnidadOperativa = apps.get_model('analytics', 'UnidadOperativa')
    Empresa = apps.get_model('analytics', 'Empresa')
    
    # Get or create default units for each empresa
    lotes_without_unidad = Lote.objects.filter(unidad_operativa__isnull=True)
    
    for lote in lotes_without_unidad:
        # Try to use the empresa if available
        if lote.empresa:
            empresa = lote.empresa
        else:
            # Create or get a default empresa
            empresa, _ = Empresa.objects.get_or_create(
                empresa_id="EMPRESA_GENERAL",
                defaults={"nombre": "Empresa General", "rubro": "Madera"}
            )
        
        # Get or create a default unidad for this empresa
        unidad, _ = UnidadOperativa.objects.get_or_create(
            unidad_id=f"{empresa.empresa_id}_GENERAL",
            defaults={
                "empresa": empresa,
                "nombre": "Unidad General",
                "tipo": UnidadOperativa.Tipo.OTRO,
                "estado": UnidadOperativa.Estado.ACTIVA,
            }
        )
        
        # Assign the unidad to the lote
        lote.unidad_operativa = unidad
        lote.empresa = empresa
        lote.save()


def reverse_populate(apps, schema_editor):
    """This is a data migration, reversal is a no-op"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_improve_unidad_operativa_tipos_y_estado'),
    ]

    operations = [
        migrations.RunPython(populate_lote_unidad_operativa, reverse_populate),
    ]
