# Generated by Django 5.2.5 on 2026-08-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0023_plantillamapeo_mapeocolumna_procesoingesta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observacion",
            name="version_evidencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observaciones_operacionales",
                to="analytics.versionevidencia",
            ),
        ),
    ]
