# Generated by Django 5.2.5 on 2026-08-14 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0024_observacion_version_evidencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observacion",
            name="actividad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observaciones",
                to="analytics.actividadoperacional",
            ),
        ),
        migrations.CreateModel(
            name="ActivoOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=180)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vehiculo", "Vehiculo"),
                            ("maquinaria", "Maquinaria"),
                            ("equipo", "Equipo"),
                            ("medidor", "Medidor"),
                            ("infraestructura", "Infraestructura"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="otro",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("operativo", "Operativo"),
                            ("requiere_revision", "Requiere revision"),
                            ("fuera_servicio", "Fuera de servicio"),
                            ("retirado", "Retirado"),
                        ],
                        db_index=True,
                        default="operativo",
                        max_length=30,
                    ),
                ),
                ("fecha_alta", models.DateField(blank=True, null=True)),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activos_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "proceso_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos",
                        to="analytics.procesooperacional",
                    ),
                ),
                (
                    "unidad_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos",
                        to="analytics.unidadoperacional",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="actividadoperacional",
            name="activos",
            field=models.ManyToManyField(
                blank=True, related_name="actividades", to="analytics.activooperacional"
            ),
        ),
        migrations.CreateModel(
            name="CondicionOperacionalActivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_inicio", models.DateTimeField(db_index=True)),
                ("timestamp_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("operativo", "Operativo"),
                            ("ralenti", "Ralenti"),
                            ("detenido", "Detenido"),
                            ("mantenimiento", "Mantenimiento"),
                            ("falla", "Falla"),
                            ("fuera_servicio", "Fuera de servicio"),
                        ],
                        max_length=30,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condiciones",
                        to="analytics.activooperacional",
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="condiciones_activos",
                        to="analytics.fuentedatos",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp_inicio"],
            },
        ),
        migrations.CreateModel(
            name="MantenimientoActivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                (
                    "fecha_programada",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("fecha_realizada", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en_proceso", "En proceso"),
                            ("realizado", "Realizado"),
                            ("vencido", "Vencido"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="programado",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "lectura_momento",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("unidad_lectura", models.CharField(blank=True, max_length=20)),
                ("proveedor_responsable", models.CharField(blank=True, max_length=180)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenimientos",
                        to="analytics.activooperacional",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenimientos_activos",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Maquinaria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(blank=True, max_length=80)),
                ("modelo", models.CharField(blank=True, max_length=80)),
                ("anio", models.PositiveIntegerField(blank=True, null=True)),
                ("tipo_maquinaria", models.CharField(blank=True, max_length=100)),
                ("combustible", models.CharField(blank=True, max_length=80)),
                (
                    "horometro_actual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "activo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maquinaria",
                        to="analytics.activooperacional",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patente", models.CharField(blank=True, max_length=30)),
                ("marca", models.CharField(blank=True, max_length=80)),
                ("modelo", models.CharField(blank=True, max_length=80)),
                ("anio", models.PositiveIntegerField(blank=True, null=True)),
                ("tipo_vehiculo", models.CharField(blank=True, max_length=80)),
                ("combustible", models.CharField(blank=True, max_length=80)),
                (
                    "capacidad_carga",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "numero_ejes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "activo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculo",
                        to="analytics.activooperacional",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="activooperacional",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"), name="unique_activo_codigo_org"
            ),
        ),
    ]
