# Generated by Django 6.0.4 on 2026-05-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_populate_lote_unidad_operativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='unidad_operativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='analytics.unidadoperativa'),
        ),
    ]
