# Generated by Django 5.2.5 on 2026-08-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0025_alter_observacion_actividad_activooperacional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observacion",
            name="actividad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observaciones",
                to="analytics.actividadoperacional",
            ),
        ),
    ]
