# Generated by Django 5.2.5 on 2026-08-14 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0026_alter_observacion_actividad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=100)),
                ("nombre", models.CharField(max_length=200)),
                ("categoria", models.CharField(db_index=True, max_length=80)),
                ("sustancia_impacto", models.CharField(default="CO2e", max_length=80)),
                ("unidad_entrada", models.CharField(max_length=60)),
                ("unidad_resultado", models.CharField(default="kgCO2e", max_length=60)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factores_ambientales_v2",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("transporte_tkm", "Masa x distancia x factor"),
                            ("transporte_vehiculo_km", "Distancia x factor vehiculo"),
                            ("transporte_combustible", "Combustible x factor"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expresion_legible", models.CharField(max_length=300)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "factor_ambiental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formulas",
                        to="analytics.factorambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalculoAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado", models.DecimalField(decimal_places=10, max_digits=24)),
                ("unidad_resultado", models.CharField(max_length=60)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("finalizado", "Finalizado"),
                            ("requiere_revision", "Requiere revision"),
                            ("fallido", "Fallido"),
                        ],
                        default="finalizado",
                        max_length=30,
                    ),
                ),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                ("version_interna", models.PositiveIntegerField(default=1)),
                ("formula_aplicada", models.CharField(max_length=300)),
                ("advertencias", models.JSONField(blank=True, default=list)),
                ("completitud", models.CharField(max_length=30)),
                ("snapshot_tecnico", models.JSONField(blank=True, default=dict)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculos_ambientales",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculos_ambientales_v2",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculos",
                        to="analytics.formulaambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_calculo"],
            },
        ),
        migrations.CreateModel(
            name="ImpactoAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("generado", "Generado"),
                            ("reduccion", "Reduccion"),
                            ("evitado", "Evitado"),
                            ("captura_remocion", "Captura/remocion"),
                            ("compensacion", "Compensacion"),
                        ],
                        default="generado",
                        max_length=30,
                    ),
                ),
                ("categoria", models.CharField(max_length=80)),
                ("valor", models.DecimalField(decimal_places=10, max_digits=24)),
                ("unidad", models.CharField(max_length=60)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impactos_ambientales",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impacto",
                        to="analytics.calculoambiental",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impactos_ambientales_v2",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetodologiaAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=100)),
                ("nombre", models.CharField(max_length=200)),
                ("categoria", models.CharField(db_index=True, max_length=80)),
                ("flujo", models.SlugField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metodologias_ambientales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariableFormula",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.SlugField(max_length=100)),
                ("concepto_observacion", models.SlugField(max_length=120)),
                ("unidad_esperada", models.CharField(max_length=40)),
                ("obligatoria", models.BooleanField(default=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("actividad", "Actividad"),
                            ("complementaria", "Complementaria"),
                        ],
                        default="actividad",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="analytics.formulaambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InputCalculoAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_utilizado",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("unidad", models.CharField(max_length=40)),
                ("concepto", models.SlugField(max_length=120)),
                (
                    "calculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs",
                        to="analytics.calculoambiental",
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs_calculo",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs_calculo",
                        to="analytics.fuentedatos",
                    ),
                ),
                (
                    "observacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs_calculo",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "version_evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs_calculo",
                        to="analytics.versionevidencia",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs_calculo",
                        to="analytics.variableformula",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionFactorAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("valor", models.DecimalField(decimal_places=10, max_digits=20)),
                ("fuente", models.TextField()),
                ("referencia", models.TextField(blank=True)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("vigencia_desde", models.DateField(blank=True, null=True)),
                ("vigencia_hasta", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("pruebas", "Pruebas"),
                            ("validado", "Validado"),
                            ("activo", "Activo"),
                            ("obsoleto", "Obsoleto"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="analytics.factorambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="calculoambiental",
            name="version_factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calculos",
                to="analytics.versionfactorambiental",
            ),
        ),
        migrations.CreateModel(
            name="VersionMetodologia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("pruebas", "Pruebas"),
                            ("validada", "Validada"),
                            ("activa", "Activa"),
                            ("obsoleta", "Obsoleta"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("descripcion_tecnica", models.TextField(blank=True)),
                ("fuente_referencia", models.TextField(blank=True)),
                ("vigencia_desde", models.DateField(blank=True, null=True)),
                ("vigencia_hasta", models.DateField(blank=True, null=True)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metodologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="analytics.metodologiaambiental",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metodologias_validadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="formulaambiental",
            name="version_metodologia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="formula",
                to="analytics.versionmetodologia",
            ),
        ),
        migrations.AddField(
            model_name="calculoambiental",
            name="version_metodologia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calculos",
                to="analytics.versionmetodologia",
            ),
        ),
        migrations.AddConstraint(
            model_name="factorambiental",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"),
                name="unique_factor_ambiental_codigo_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="metodologiaambiental",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"), name="unique_metodologia_codigo_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="variableformula",
            constraint=models.UniqueConstraint(
                fields=("formula", "clave"), name="unique_variable_formula"
            ),
        ),
        migrations.AddConstraint(
            model_name="versionfactorambiental",
            constraint=models.UniqueConstraint(
                fields=("factor", "version"), name="unique_version_factor_ambiental"
            ),
        ),
        migrations.AddConstraint(
            model_name="versionmetodologia",
            constraint=models.UniqueConstraint(
                fields=("metodologia", "version"), name="unique_version_metodologia"
            ),
        ),
    ]
