# Generated by Django 6.0.4 on 2026-05-10 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_emisionlote_tipo_consumo_combustible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name = 'analytics_usuarioempresa'
                ) THEN
                    DROP SEQUENCE IF EXISTS analytics_usuarioempresa_id_seq CASCADE;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista'), ('operador', 'Operador'), ('lector', 'Lector')], default='analista', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='analytics.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['empresa__nombre', 'user__first_name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'empresa'), name='unique_usuario_empresa')],
            },
        ),
    ]
