# Generated by Django 5.2.5 on 2026-08-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0027_factorambiental_formulaambiental_calculoambiental_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="factorambiental",
            name="unique_factor_ambiental_codigo_org",
        ),
        migrations.RemoveConstraint(
            model_name="metodologiaambiental",
            name="unique_metodologia_codigo_org",
        ),
        migrations.AddConstraint(
            model_name="factorambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", True)),
                fields=("codigo",),
                name="unique_factor_ambiental_codigo_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="factorambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", False)),
                fields=("organizacion", "codigo"),
                name="unique_factor_ambiental_codigo_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="metodologiaambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", True)),
                fields=("codigo",),
                name="unique_metodologia_codigo_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="metodologiaambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", False)),
                fields=("organizacion", "codigo"),
                name="unique_metodologia_codigo_tenant",
            ),
        ),
    ]
