# Generated by Django 5.2.5 on 2026-08-14 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0028_remove_factorambiental_unique_factor_ambiental_codigo_org_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscrepanciaDato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.SlugField(max_length=120)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("detectada", "Detectada"),
                            ("requiere_revision", "Requiere revision"),
                            ("resuelta", "Resuelta"),
                            ("aceptada", "Aceptada"),
                            ("descartada", "Descartada"),
                        ],
                        default="detectada",
                        max_length=30,
                    ),
                ),
                (
                    "diferencia_absoluta",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "diferencia_relativa",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=15,
                    ),
                ),
                ("resolucion", models.TextField(blank=True)),
                ("motivo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discrepancias",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "observacion_seleccionada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discrepancias_seleccionada",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "observaciones",
                    models.ManyToManyField(
                        related_name="discrepancias", to="analytics.observacion"
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancias_dato",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discrepancias_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluacionCalidadDato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("confiable", "Confiable"),
                            (
                                "confiable_con_observaciones",
                                "Confiable con observaciones",
                            ),
                            ("incompleto", "Incompleto"),
                            ("requiere_revision", "Requiere revision"),
                            ("no_confiable", "No confiable"),
                            ("no_calculable", "No calculable"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("motivos", models.JSONField(blank=True, default=list)),
                ("dimensiones", models.JSONField(blank=True, default=dict)),
                ("fecha_evaluacion", models.DateTimeField(auto_now_add=True)),
                (
                    "version_reglas",
                    models.CharField(default="calidad-v1", max_length=30),
                ),
                ("automatica", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluaciones_calidad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones_calidad",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_calidad",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=120)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("absoluto", "Absoluto"),
                            ("intensidad", "Intensidad"),
                            ("operacional", "Operacional"),
                            ("problematica", "Problematica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unidad", models.CharField(max_length=60)),
                ("descripcion", models.TextField(blank=True)),
                ("origen_numerador", models.CharField(max_length=120)),
                ("origen_denominador", models.CharField(blank=True, max_length=120)),
                (
                    "direccion_deseable",
                    models.CharField(
                        choices=[
                            ("menor_es_mejor", "Menor es mejor"),
                            ("mayor_es_mejor", "Mayor es mejor"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=25,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores_ambientales_v2",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineaBaseAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField(blank=True, null=True)),
                ("periodo_fin", models.DateField(blank=True, null=True)),
                (
                    "metodo",
                    models.CharField(default="promedio_periodos", max_length=80),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("construyendo", "Construyendo"),
                            ("suficiente", "Suficiente"),
                            ("requiere_revision", "Requiere revision"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="construyendo",
                        max_length=30,
                    ),
                ),
                (
                    "valor_base",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("cantidad_periodos", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas_base",
                        to="analytics.indicadorambiental",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas_base_ambientales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoComparable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_actual_inicio", models.DateField()),
                ("periodo_actual_fin", models.DateField()),
                ("periodo_referencia_inicio", models.DateField()),
                ("periodo_referencia_fin", models.DateField()),
                (
                    "regla",
                    models.CharField(
                        choices=[
                            ("mismo_mes_anio_anterior", "Mismo mes del ano anterior"),
                            (
                                "periodo_anterior_equivalente",
                                "Periodo anterior equivalente",
                            ),
                            ("manual", "Manual"),
                        ],
                        max_length=40,
                    ),
                ),
                ("motivo_comparabilidad", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_comparables",
                        to="analytics.indicadorambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliticaConfianzaFuente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.SlugField(max_length=120)),
                (
                    "tipo_fuente",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("documento", "Documento"),
                            ("excel_csv", "Excel o CSV"),
                            ("api", "API"),
                            ("gps", "GPS"),
                            ("sensor", "Sensor"),
                            ("telemetria", "Telemetria"),
                            ("erp", "ERP"),
                            ("sistema_externo", "Sistema externo"),
                            ("sistema", "Sistema"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prioridad", models.PositiveIntegerField()),
                ("activa", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="politicas_confianza_fuente",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValorIndicador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField(db_index=True)),
                ("periodo_fin", models.DateField()),
                ("valor", models.DecimalField(decimal_places=10, max_digits=24)),
                ("unidad", models.CharField(max_length=60)),
                ("fuente_calculo", models.CharField(max_length=160)),
                ("version", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores",
                        to="analytics.indicadorambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["periodo_inicio", "version"],
            },
        ),
        migrations.AddConstraint(
            model_name="indicadorambiental",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"), name="unique_indicador_codigo_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodocomparable",
            constraint=models.UniqueConstraint(
                fields=("indicador", "periodo_actual_inicio", "periodo_actual_fin"),
                name="unique_periodo_comparable_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="politicaconfianzafuente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", True)),
                fields=("concepto", "tipo_fuente"),
                name="unique_politica_fuente_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="politicaconfianzafuente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", False)),
                fields=("organizacion", "concepto", "tipo_fuente"),
                name="unique_politica_fuente_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="valorindicador",
            constraint=models.UniqueConstraint(
                fields=("indicador", "periodo_inicio", "periodo_fin", "version"),
                name="unique_valor_indicador_version",
            ),
        ),
    ]
