# Generated by Django 5.2.5 on 2026-08-14 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0029_discrepanciadato_evaluacioncalidaddato_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="estado",
            field=models.CharField(
                choices=[
                    ("propuesta", "Propuesta"),
                    ("ajustada", "Ajustada"),
                    ("seleccionada", "Seleccionada"),
                    ("en_implementacion", "En implementacion"),
                    ("seguimiento", "Seguimiento"),
                    ("evaluada", "Evaluada"),
                    ("descartada", "Descartada"),
                    ("cancelada", "Cancelada"),
                ],
                default="propuesta",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="fecha_inicio_efectiva",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="fecha_propuesta",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="fecha_seleccion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="fecha_termino_real",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="justificacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accionmejoraambiental",
            name="responsable_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acciones_mejora_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicionseguimientoambiental",
            name="evidencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mediciones_intervencion",
                to="analytics.evidenciaobra",
            ),
        ),
        migrations.AddField(
            model_name="medicionseguimientoambiental",
            name="indicador_v2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mediciones_intervencion",
                to="analytics.indicadorambiental",
            ),
        ),
        migrations.AddField(
            model_name="medicionseguimientoambiental",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicionseguimientoambiental",
            name="referencia",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="medicionseguimientoambiental",
            name="valor_indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mediciones_intervencion",
                to="analytics.valorindicador",
            ),
        ),
        migrations.AddField(
            model_name="problematicaambiental",
            name="objetivo_ambiental",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problematicaambiental",
            name="origen_deteccion",
            field=models.CharField(default="manual", max_length=40),
        ),
        migrations.AddField(
            model_name="problematicaambiental",
            name="responsable_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="problematicas_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="problematicaambiental",
            name="estado",
            field=models.CharField(
                choices=[
                    ("detectada", "Detectada"),
                    ("analizando", "Analizando"),
                    ("propuesta", "Propuesta"),
                    ("accion_seleccionada", "Accion seleccionada"),
                    ("implementando", "Implementando"),
                    ("seguimiento", "Seguimiento"),
                    ("evaluando", "Evaluando"),
                    ("escalada_profesional", "Escalada profesional"),
                    ("cerrada", "Cerrada"),
                    ("en_analisis", "En analisis"),
                    ("accion_propuesta", "Accion propuesta"),
                    ("en_implementacion", "En implementacion"),
                    ("en_seguimiento", "En seguimiento"),
                    ("resuelta", "Resuelta"),
                    ("mejora_insuficiente", "Mejora insuficiente"),
                    ("no_resuelta", "No resuelta"),
                    ("escalada", "Escalada"),
                ],
                default="detectada",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AlcanceProblematica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alcances_problematicas",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "activo_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alcances_problematicas",
                        to="analytics.activooperacional",
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alcances_problematicas",
                        to="analytics.indicadorambiental",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alcances_v2",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "proceso_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alcances_problematicas",
                        to="analytics.procesooperacional",
                    ),
                ),
                (
                    "unidad_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alcances_problematicas",
                        to="analytics.unidadoperacional",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorProblematica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("secundario", "Secundario"),
                            ("contexto", "Contexto"),
                        ],
                        default="principal",
                        max_length=20,
                    ),
                ),
                (
                    "valor_objetivo",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "direccion_deseada",
                    models.CharField(
                        choices=[
                            ("menor_es_mejor", "Menor es mejor"),
                            ("mayor_es_mejor", "Mayor es mejor"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=25,
                    ),
                ),
                ("obligatorio", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="problematicas_v2",
                        to="analytics.indicadorambiental",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores_v2",
                        to="analytics.problematicaambiental",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistorialMetaProblematica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("valor_nuevo", models.DecimalField(decimal_places=10, max_digits=24)),
                ("justificacion_tecnica", models.TextField()),
                ("motivo", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_metas",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cambios_meta_problematica",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicador_problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_metas",
                        to="analytics.indicadorproblematica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotIntervencion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciclo", models.PositiveIntegerField(default=1)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("base", "Base"), ("resultado", "Resultado")],
                        max_length=15,
                    ),
                ),
                ("fecha", models.DateField()),
                ("alcance_congelado", models.JSONField(default=dict)),
                ("indicadores_evaluados", models.JSONField(default=list)),
                ("metadata_tecnica", models.JSONField(blank=True, default=dict)),
                ("congelado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots_intervencion",
                        to="analytics.accionmejoraambiental",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots_intervencion",
                        to="analytics.problematicaambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoIntervencion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciclo", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("no_implementada", "No implementada"),
                            ("no_viable", "No viable"),
                            ("parcial", "Parcial"),
                            ("implementada_sin_efecto", "Implementada sin efecto"),
                            ("positiva", "Positiva"),
                            ("negativa", "Negativa"),
                            ("inconclusa", "Inconclusa"),
                        ],
                        max_length=35,
                    ),
                ),
                ("conclusion_estructurada", models.JSONField(default=dict)),
                ("fecha_evaluacion", models.DateField()),
                ("metricas_comparadas", models.JSONField(default=list)),
                ("limitaciones", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_intervencion",
                        to="analytics.accionmejoraambiental",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_intervencion",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "snapshot_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_como_base",
                        to="analytics.snapshotintervencion",
                    ),
                ),
                (
                    "snapshot_resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_como_resultado",
                        to="analytics.snapshotintervencion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CicloReevaluacionProblematica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_cierre", models.DateField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ciclos_reevaluacion",
                        to="analytics.accionmejoraambiental",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ciclos_reevaluacion",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ciclo_reevaluacion",
                        to="analytics.resultadointervencion",
                    ),
                ),
                (
                    "snapshot_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ciclos_como_base",
                        to="analytics.snapshotintervencion",
                    ),
                ),
                (
                    "snapshot_resultado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ciclos_como_resultado",
                        to="analytics.snapshotintervencion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotValorIndicador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=10, max_digits=24)),
                ("unidad", models.CharField(max_length=60)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores_snapshot",
                        to="analytics.indicadorambiental",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores",
                        to="analytics.snapshotintervencion",
                    ),
                ),
                (
                    "valor_indicador_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots_intervencion",
                        to="analytics.valorindicador",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="indicadorproblematica",
            constraint=models.UniqueConstraint(
                fields=("problematica", "indicador"),
                name="unique_indicador_problematica",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotintervencion",
            constraint=models.UniqueConstraint(
                fields=("problematica", "accion", "ciclo", "tipo"),
                name="unique_snapshot_intervencion_ciclo",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultadointervencion",
            constraint=models.UniqueConstraint(
                fields=("problematica", "accion", "ciclo"),
                name="unique_resultado_intervencion_ciclo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cicloreevaluacionproblematica",
            constraint=models.UniqueConstraint(
                fields=("problematica", "numero"), name="unique_ciclo_problematica"
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotvalorindicador",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "indicador"), name="unique_valor_snapshot_indicador"
            ),
        ),
    ]
