# Generated by Django 5.2.5 on 2026-08-14 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0030_accionmejoraambiental_estado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="estado",
            field=models.CharField(
                choices=[
                    ("propuesta", "Propuesta"),
                    ("ajustada", "Ajustada"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                    ("descartada", "Descartada"),
                    ("convertida_en_accion", "Convertida en accion"),
                ],
                default="propuesta",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="kpis_afectados",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="mensaje_usuario",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="propuesta_anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ajustes",
                to="analytics.recomendacionagenteambiental",
            ),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="referencias_contexto",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="requisitos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="restricciones_consideradas",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="riesgos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="titulo",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="recomendacionagenteambiental",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ComandoCopiloto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("prepare_action", "Preparar accion"),
                            ("prepare_reevaluation", "Preparar reevaluacion"),
                            ("prepare_restriction", "Preparar restriccion"),
                            ("prepare_escalation", "Preparar escalamiento"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("preparado", "Preparado"),
                            ("confirmado", "Confirmado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="preparado",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comandos_copiloto_confirmados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comandos_copiloto",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comandos_copiloto",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "propuesta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comandos",
                        to="analytics.recomendacionagenteambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HitoDecisionIA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contexto_consultado", "Contexto consultado"),
                            ("propuesta", "Propuesta"),
                            ("refutacion", "Refutacion"),
                            ("adaptacion", "Adaptacion"),
                            ("propuesta_final", "Propuesta final"),
                            ("decision_humana", "Decision humana"),
                            ("resultado_posterior", "Resultado posterior"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resumen", models.TextField()),
                ("referencias_contexto", models.JSONField(blank=True, default=list)),
                ("payload_auditable", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hitos_decision_ia",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hitos_decision_ia",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "propuesta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hitos",
                        to="analytics.recomendacionagenteambiental",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hitos_decision_ia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoriaOrganizacion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("solucion_intentada", "Solucion intentada"),
                            ("accion_aceptada", "Accion aceptada"),
                            ("accion_rechazada", "Accion rechazada"),
                            ("restriccion_operacional", "Restriccion operacional"),
                            ("activo_problematico", "Activo problematico"),
                            ("proceso_recurrente", "Proceso recurrente"),
                            ("evolucion_kpi", "Evolucion KPI"),
                            ("intervencion", "Intervencion"),
                            ("cambio_operacional", "Cambio operacional"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("contenido", models.JSONField(default=dict)),
                ("fuente_origen", models.CharField(max_length=80)),
                (
                    "vigente_desde",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("vigente_hasta", models.DateTimeField(blank=True, null=True)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoria_organizacional",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memorias_organizacionales",
                        to="analytics.problematicaambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestriccionContextual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.SlugField(max_length=80)),
                ("descripcion", models.TextField()),
                ("contenido", models.JSONField(blank=True, default=dict)),
                (
                    "vigente_desde",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("vigente_hasta", models.DateTimeField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restricciones_contextuales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restricciones_contextuales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restricciones_contextuales",
                        to="analytics.problematicaambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialRestriccionContextual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido_anterior", models.JSONField(default=dict)),
                ("contenido_nuevo", models.JSONField(default=dict)),
                ("motivo", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_restricciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restriccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="analytics.restriccioncontextual",
                    ),
                ),
            ],
        ),
    ]
