# Generated by Django 5.2.5 on 2026-08-14 22:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0031_recomendacionagenteambiental_descripcion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expedienteambiental",
            name="cerrado_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="cerrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expedientes_ambientales_cerrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="estado",
            field=models.CharField(
                choices=[
                    ("abierto", "Abierto"),
                    ("recopilando_antecedentes", "Recopilando antecedentes"),
                    ("en_revision", "En revision"),
                    ("requiere_antecedentes", "Requiere antecedentes"),
                    ("validado", "Validado"),
                    ("cerrado", "Cerrado"),
                    ("reabierto", "Reabierto"),
                ],
                default="abierto",
                max_length=35,
            ),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="motivo_reapertura",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="reabierto_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="reabierto_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expedientes_ambientales_reabiertos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="referencias",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="expedienteambiental",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expedientes_ambientales_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventoAuditoriaAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.SlugField(max_length=80)),
                ("entidad", models.CharField(max_length=80)),
                ("referencia", models.CharField(max_length=120)),
                ("resumen", models.TextField()),
                ("metadata_auditable", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_auditoria_ambiental",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_auditoria_ambiental",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InformeAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("actividad", "Actividad"),
                            ("problematica", "Problematica"),
                            ("intervencion", "Intervencion"),
                            ("expediente", "Expediente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("generado", "Generado"),
                            ("revisado", "Revisado"),
                            ("validado", "Validado"),
                            ("obsoleto", "Obsoleto"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, upload_to="informes_ambientales/%Y/%m/"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("validado_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="informes_ambientales",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="informes",
                        to="analytics.expedienteambiental",
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="informes_ambientales_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervencion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="informes_ambientales",
                        to="analytics.resultadointervencion",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes_ambientales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="informes_ambientales",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="informes_ambientales_validados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevisionProfesionalAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("evidencia", "Evidencia"),
                            ("observacion", "Observacion"),
                            ("calculo", "Calculo"),
                            ("indicador", "Indicador"),
                            ("problematica", "Problematica"),
                            ("intervencion", "Intervencion"),
                            ("expediente", "Expediente"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("validada", "Validada"),
                            (
                                "validada_con_observaciones",
                                "Validada con observaciones",
                            ),
                            ("solicita_antecedentes", "Solicita antecedentes"),
                            ("rechazada", "Rechazada"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=35,
                    ),
                ),
                ("profesional_nombre", models.CharField(blank=True, max_length=180)),
                ("profesional_cargo", models.CharField(blank=True, max_length=120)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                ("conclusion", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "antecedentes_solicitados",
                    models.JSONField(blank=True, default=list),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to="analytics.calculoambiental",
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to="analytics.expedienteambiental",
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to="analytics.indicadorambiental",
                    ),
                ),
                (
                    "intervencion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to="analytics.resultadointervencion",
                    ),
                ),
                (
                    "observacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisiones_profesionales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "problematica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to="analytics.problematicaambiental",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisiones_profesionales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HallazgoRevisionProfesional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("observacion", "Observacion"),
                            ("inconsistencia", "Inconsistencia"),
                            ("falta_antecedente", "Falta antecedente"),
                            ("correccion_requerida", "Correccion requerida"),
                            ("validacion", "Validacion"),
                            ("recomendacion", "Recomendacion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Critica"),
                        ],
                        default="media",
                        max_length=15,
                    ),
                ),
                ("observacion", models.TextField()),
                ("recomendacion", models.TextField(blank=True)),
                ("requerimiento", models.TextField(blank=True)),
                ("decision", models.TextField(blank=True)),
                ("referencia_tecnica", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hallazgos",
                        to="analytics.revisionprofesionalambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorreccionHistoricaAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                ("valor_estado_anterior", models.JSONField(default=dict)),
                ("propuesta_corregida", models.JSONField(default=dict)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_historicas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "calculo_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_historicas",
                        to="analytics.calculoambiental",
                    ),
                ),
                (
                    "impacto_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_historicas",
                        to="analytics.impactoambiental",
                    ),
                ),
                (
                    "observacion_afectada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_historicas",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correcciones_historicas",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "recalculo_generado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_origen",
                        to="analytics.calculoambiental",
                    ),
                ),
                (
                    "resultado_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_historicas",
                        to="analytics.resultadointervencion",
                    ),
                ),
                (
                    "snapshot_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_historicas",
                        to="analytics.snapshotintervencion",
                    ),
                ),
                (
                    "revision_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_historicas",
                        to="analytics.revisionprofesionalambiental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotInformeAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.JSONField(default=dict)),
                ("referencias", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "informe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshot",
                        to="analytics.informeambiental",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="informeambiental",
            constraint=models.UniqueConstraint(
                fields=(
                    "organizacion",
                    "tipo",
                    "actividad",
                    "problematica",
                    "intervencion",
                    "expediente",
                    "version",
                ),
                name="unique_informe_ambiental_version",
            ),
        ),
    ]
