# Generated by Django 5.2.5 on 2026-08-15 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0032_expedienteambiental_cerrado_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasoConocimientoAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preset", models.CharField(db_index=True, max_length=40)),
                ("tipo_problematica", models.SlugField(db_index=True, max_length=120)),
                ("categoria_ambiental", models.SlugField(db_index=True, max_length=120)),
                ("tipo_accion", models.SlugField(db_index=True, max_length=120)),
                ("contexto_operacional", models.JSONField(default=dict)),
                ("indicadores", models.JSONField(blank=True, default=list)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("exitoso", "Exitoso"),
                            ("parcialmente_exitoso", "Parcialmente exitoso"),
                            ("sin_efecto", "Sin efecto"),
                            ("negativo", "Negativo"),
                            ("no_viable", "No viable"),
                            ("no_implementado", "No implementado"),
                            ("inconcluso", "Inconcluso"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("metricas_comparadas", models.JSONField(default=list)),
                ("grado_implementacion", models.CharField(max_length=30)),
                ("viabilidad", models.CharField(max_length=30)),
                (
                    "fuerza_evidencia",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("fundamento_evidencia", models.JSONField(default=list)),
                (
                    "origen_conocimiento",
                    models.CharField(
                        choices=[
                            ("ia", "IA"),
                            ("profesional", "Profesional"),
                            ("usuario", "Usuario"),
                            ("mixto", "Mixto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_caso", models.DateField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("candidato", "Candidato"),
                            ("utilizable", "Utilizable"),
                            ("descartado", "Descartado"),
                            ("invalidado", "Invalidado"),
                        ],
                        db_index=True,
                        default="candidato",
                        max_length=20,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casos_conocimiento",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "resultado_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos_conocimiento",
                        to="analytics.resultadointervencion",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_caso", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resultado_origen", "version"),
                        name="unique_caso_conocimiento_version",
                    )
                ],
            },
        ),
    ]
