# Generated by Django 5.2.5 on 2026-08-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0033_casoconocimientoambiental"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="unidad_capacidad_carga",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="RutaOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(blank=True, max_length=180)),
                ("origen_nombre", models.CharField(max_length=240)),
                ("origen_referencia", models.CharField(blank=True, max_length=180)),
                ("origen_coordenadas", models.JSONField(blank=True, default=dict)),
                ("destino_nombre", models.CharField(max_length=240)),
                ("destino_referencia", models.CharField(blank=True, max_length=180)),
                ("destino_coordenadas", models.JSONField(blank=True, default=dict)),
                (
                    "distancia_planificada",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=16, null=True
                    ),
                ),
                ("unidad_distancia", models.CharField(default="km", max_length=20)),
                ("fuente_distancia", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutas_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViajeOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("origen_nombre", models.CharField(max_length=240)),
                ("origen_referencia", models.CharField(blank=True, max_length=180)),
                ("origen_coordenadas", models.JSONField(blank=True, default=dict)),
                ("destino_nombre", models.CharField(max_length=240)),
                ("destino_referencia", models.CharField(blank=True, max_length=180)),
                ("destino_coordenadas", models.JSONField(blank=True, default=dict)),
                ("fecha_salida", models.DateTimeField()),
                ("fecha_llegada", models.DateTimeField(blank=True, null=True)),
                (
                    "estado_carga",
                    models.CharField(
                        choices=[
                            ("cargado", "Cargado"),
                            ("parcialmente_cargado", "Parcialmente cargado"),
                            ("vacio", "Vacio"),
                            ("desconocido", "Desconocido"),
                        ],
                        default="desconocido",
                        max_length=25,
                    ),
                ),
                (
                    "tipo_trayecto",
                    models.CharField(
                        choices=[
                            ("ida", "Ida"),
                            ("retorno", "Retorno"),
                            ("interno", "Interno"),
                            ("otro", "Otro"),
                        ],
                        default="ida",
                        max_length=15,
                    ),
                ),
                (
                    "tipo_gestion",
                    models.CharField(
                        choices=[("propio", "Propio"), ("tercerizado", "Tercerizado")],
                        default="propio",
                        max_length=15,
                    ),
                ),
                (
                    "metodologia_tercerizado",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificado", "Planificado"),
                            ("en_curso", "En curso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planificado",
                        max_length=15,
                    ),
                ),
                ("metadata_tecnica", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actividad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viaje",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "observacion_carga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viajes_carga_seleccionada",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "observacion_combustible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viajes_combustible_seleccionado",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "observacion_distancia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viajes_distancia_seleccionada",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viajes",
                        to="analytics.rutaoperacional",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viajes",
                        to="analytics.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rutaoperacional",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"),
                name="unique_ruta_operacional_codigo_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="viajeoperacional",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"),
                name="unique_viaje_operacional_codigo_org",
            ),
        ),
    ]
