# Generated by Django 5.2.5 on 2026-08-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0034_vehiculo_unidad_capacidad_carga_rutaoperacional_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=180)),
                ("categoria", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("unidad_base", models.CharField(max_length=40)),
                ("proveedor_fabricante", models.CharField(blank=True, max_length=180)),
                ("especificacion_tecnica", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiales_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="LoteMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=120)),
                ("proveedor", models.CharField(blank=True, max_length=180)),
                ("referencia_documental", models.CharField(blank=True, max_length=180)),
                ("fecha", models.DateField(blank=True, null=True)),
                (
                    "cantidad_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lotes_materiales",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_materiales",
                        to="analytics.fuentedatos",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes_materiales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "version_evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lotes_materiales",
                        to="analytics.versionevidencia",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes",
                        to="analytics.materialoperacional",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="EventoMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("adquisicion", "Adquisicion"),
                            ("despacho", "Despacho"),
                            ("recepcion", "Recepcion"),
                            ("almacenamiento", "Almacenamiento"),
                            ("uso", "Uso"),
                            ("consumo", "Consumo"),
                            ("traslado", "Traslado"),
                            ("sobrante", "Sobrante"),
                            ("devolucion", "Devolucion"),
                            ("reutilizacion", "Reutilizacion"),
                            ("residuo", "Residuo"),
                            ("ajuste", "Ajuste"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(db_index=True)),
                ("origen", models.CharField(blank=True, max_length=240)),
                ("destino", models.CharField(blank=True, max_length=240)),
                (
                    "estado",
                    models.CharField(
                        choices=[("registrado", "Registrado"), ("anulado", "Anulado")],
                        db_index=True,
                        default="registrado",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actividad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evento_material",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "evento_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_derivados",
                        to="analytics.eventomaterial",
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_materiales",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_materiales",
                        to="analytics.fuentedatos",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_materiales",
                        to="analytics.obra",
                    ),
                ),
                (
                    "observacion_cantidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_material_cantidad_seleccionada",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_materiales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_materiales",
                        to="analytics.procesooperacional",
                    ),
                ),
                (
                    "version_evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_materiales",
                        to="analytics.versionevidencia",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="analytics.lotematerial",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="analytics.materialoperacional",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_hora", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialoperacional",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"),
                name="unique_material_operacional_codigo_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="lotematerial",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"),
                name="unique_lote_material_codigo_org",
            ),
        ),
        migrations.AddIndex(
            model_name="eventomaterial",
            index=models.Index(
                fields=["organizacion", "material", "fecha_hora"],
                name="analytics_e_organiz_5411c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventomaterial",
            index=models.Index(
                fields=["organizacion", "lote", "fecha_hora"],
                name="analytics_e_organiz_1a065b_idx",
            ),
        ),
    ]
