# Generated by Django 5.2.5 on 2026-08-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0035_materialoperacional_lotematerial_eventomaterial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadoperacional",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("transporte", "Transporte"),
                    ("consumo_energia", "Consumo de energia"),
                    ("consumo_agua", "Consumo de agua"),
                    ("consumo_combustible", "Consumo de combustible"),
                    (
                        "consumo_combustible_estacionario",
                        "Consumo de combustible estacionario",
                    ),
                    ("operacion_maquinaria", "Operacion de maquinaria"),
                    ("movimiento_material", "Movimiento de material"),
                    ("gestion_residuo", "Gestion de residuo"),
                    ("generacion_energia", "Generacion de energia"),
                    ("monitoreo_ruido", "Monitoreo de ruido"),
                    ("gestion_hidrica_suelo", "Gestion hidrica y suelo"),
                    ("proceso_productivo", "Proceso productivo"),
                    ("otro", "Otro"),
                ],
                db_index=True,
                default="otro",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PuntoAmbientalOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=180)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("medidor_energia", "Medidor de energia"),
                            ("punto_agua", "Punto de agua"),
                            ("sistema_generacion", "Sistema de generacion"),
                            ("punto_descarga", "Punto de descarga"),
                            ("punto_ruido", "Punto de ruido"),
                            ("punto_drenaje", "Punto de drenaje"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="otro",
                        max_length=30,
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=240)),
                ("descripcion", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("activo_registro", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntos_ambientales",
                        to="analytics.activooperacional",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntos_ambientales",
                        to="analytics.obra",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos_ambientales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "proceso_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntos_ambientales",
                        to="analytics.procesooperacional",
                    ),
                ),
                (
                    "unidad_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntos_ambientales",
                        to="analytics.unidadoperacional",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="RegistroFlujoAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flujo",
                    models.CharField(
                        choices=[
                            ("energia", "Energia"),
                            ("generacion_propia", "Generacion propia"),
                            ("agua", "Agua"),
                            ("combustible_estacionario", "Combustible estacionario"),
                            ("residuo", "Residuo"),
                            ("ruido", "Ruido"),
                            ("gestion_hidrica_suelo", "Gestion hidrica y suelo"),
                        ],
                        db_index=True,
                        max_length=35,
                    ),
                ),
                ("periodo_inicio", models.DateTimeField()),
                ("periodo_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "granularidad",
                    models.CharField(
                        choices=[
                            ("organizacion", "Organizacion"),
                            ("instalacion", "Instalacion"),
                            ("obra", "Obra"),
                            ("proceso", "Proceso"),
                            ("activo", "Activo"),
                            ("punto", "Punto de medicion"),
                        ],
                        default="organizacion",
                        max_length=20,
                    ),
                ),
                ("tipo_recurso", models.CharField(blank=True, max_length=120)),
                ("metrica", models.CharField(blank=True, max_length=80)),
                (
                    "destino_operacional",
                    models.CharField(
                        choices=[
                            ("sin_clasificar", "Sin clasificar"),
                            ("residuo", "Residuo"),
                            ("reutilizacion", "Reutilizacion"),
                            ("reciclaje", "Reciclaje"),
                            ("valorizacion", "Valorizacion"),
                            ("disposicion", "Disposicion"),
                            ("subproducto_reutilizado", "Subproducto reutilizado"),
                        ],
                        default="sin_clasificar",
                        max_length=30,
                    ),
                ),
                ("proveedor_gestor", models.CharField(blank=True, max_length=180)),
                ("ubicacion_contexto", models.CharField(blank=True, max_length=240)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actividad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registro_flujo_ambiental",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "activo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_flujos_ambientales",
                        to="analytics.activooperacional",
                    ),
                ),
                (
                    "evento_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_flujos_ambientales",
                        to="analytics.eventomaterial",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_flujos_ambientales",
                        to="analytics.obra",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_flujos_ambientales",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_flujos_ambientales",
                        to="analytics.procesooperacional",
                    ),
                ),
                (
                    "punto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros",
                        to="analytics.puntoambientaloperacional",
                    ),
                ),
                (
                    "unidad_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_flujos_ambientales",
                        to="analytics.unidadoperacional",
                    ),
                ),
            ],
            options={
                "ordering": ["-periodo_inicio", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="puntoambientaloperacional",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "codigo"),
                name="unique_punto_ambiental_codigo_org",
            ),
        ),
        migrations.AddIndex(
            model_name="registroflujoambiental",
            index=models.Index(
                fields=["organizacion", "flujo", "periodo_inicio"],
                name="analytics_r_organiz_3aba8c_idx",
            ),
        ),
    ]
