# Generated by Django 5.2.5 on 2026-08-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0036_alter_actividadoperacional_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculoambiental",
            name="motivo_recalculo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="calculoambiental",
            name="recalculo_de",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recalculos",
                to="analytics.calculoambiental",
            ),
        ),
        migrations.AddField(
            model_name="calculoambiental",
            name="tipo_resultado",
            field=models.CharField(default="emision", max_length=30),
        ),
        migrations.AddField(
            model_name="variableformula",
            name="criticidad",
            field=models.CharField(
                choices=[
                    ("critica", "Crítica"),
                    ("complementaria", "Complementaria"),
                    ("opcional", "Opcional"),
                ],
                default="critica",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="versionmetodologia",
            name="aplicabilidad",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="versionmetodologia",
            name="prioridad",
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name="versionmetodologia",
            name="requiere_revision_profesional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="versionmetodologia",
            name="tipo_resultado",
            field=models.CharField(default="emision", max_length=30),
        ),
        migrations.CreateModel(
            name="CompatibilidadVersionMetodologia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("compatible", "Compatible"),
                            ("incompatible", "Incompatible"),
                            ("requiere_revision", "Requiere revisión"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detalle", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilidades_destino",
                        to="analytics.versionmetodologia",
                    ),
                ),
                (
                    "version_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilidades_origen",
                        to="analytics.versionmetodologia",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version_origen", "version_destino"),
                        name="unique_compatibilidad_version_metodologia",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="impactoambiental",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("generado", "Generado"),
                    ("reduccion", "Reduccion"),
                    ("evitado", "Evitado"),
                    ("captura_remocion", "Captura/remocion"),
                    ("compensacion", "Compensacion"),
                    ("otro", "Otro"),
                ],
                default="generado",
                max_length=30,
            ),
        ),
    ]
