# Generated by Django 5.2.5 on 2026-08-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0037_calculoambiental_motivo_recalculo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionprofesionalambiental",
            name="version_metodologia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisiones_profesionales",
                to="analytics.versionmetodologia",
            ),
        ),
        migrations.AlterField(
            model_name="revisionprofesionalambiental",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("evidencia", "Evidencia"),
                    ("observacion", "Observacion"),
                    ("calculo", "Calculo"),
                    ("indicador", "Indicador"),
                    ("problematica", "Problematica"),
                    ("intervencion", "Intervencion"),
                    ("expediente", "Expediente"),
                    ("metodologia", "Version metodologica"),
                ],
                max_length=25,
            ),
        ),
    ]
