# Generated by Django 5.2.5 on 2026-08-15 17:14

import django.db.models.deletion
from django.db import migrations, models


def normalize_legacy_transport_ingestion(apps, schema_editor):
    Process = apps.get_model("analytics", "ProcesoIngesta")
    Template = apps.get_model("analytics", "PlantillaMapeo")
    Process.objects.filter(tipo_ingesta="transporte_excel_csv").update(
        tipo_ingesta="tabular", destino_operacional="transporte",
    )
    Template.objects.update(tipo_ingesta="tabular", destino_operacional="transporte")


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0038_revisionprofesionalambiental_version_metodologia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observacion",
            name="registro_extraido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observaciones_creadas",
                to="analytics.registroextraido",
            ),
        ),
        migrations.AddField(
            model_name="plantillamapeo",
            name="destino_operacional",
            field=models.CharField(default="actividad_generica", max_length=30),
        ),
        migrations.AddField(
            model_name="plantillamapeo",
            name="flujo",
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name="plantillamapeo",
            name="tipo_ingesta",
            field=models.CharField(default="tabular", max_length=30),
        ),
        migrations.AddField(
            model_name="procesoingesta",
            name="clasificacion_confirmada",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="procesoingesta",
            name="clasificacion_sugerida",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="procesoingesta",
            name="contexto_confirmado",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="procesoingesta",
            name="contexto_sugerido",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="procesoingesta",
            name="destino_operacional",
            field=models.CharField(
                choices=[
                    ("transporte", "Transporte"),
                    ("material", "Material"),
                    ("flujo_ambiental", "Flujo ambiental"),
                    ("actividad_generica", "Actividad generica"),
                ],
                default="transporte",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="procesoingesta",
            name="flujo",
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name="registroextraido",
            name="auto_confirmable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registroextraido",
            name="datos_normalizados",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="registroextraido",
            name="procesado_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroextraido",
            name="resultado_procesamiento",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="procesoingesta",
            name="tipo_ingesta",
            field=models.CharField(
                choices=[
                    ("tabular", "Tabular"),
                    ("documental", "Documental"),
                    ("manual_estructurado", "Manual estructurado"),
                    ("api", "API"),
                    ("telemetria", "Telemetria"),
                    ("sensor", "Sensor"),
                ],
                default="tabular",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="registroextraido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("extraido", "Extraido"),
                    ("normalizado", "Normalizado"),
                    ("requiere_mapeo", "Requiere mapeo"),
                    ("requiere_revision", "Requiere revision"),
                    ("listo", "Listo"),
                    ("valido", "Valido"),
                    ("error", "Error"),
                    ("procesado", "Procesado"),
                ],
                db_index=True,
                default="extraido",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_legacy_transport_ingestion, migrations.RunPython.noop),
    ]
