# Generated by Django 5.2.5 on 2026-08-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0039_observacion_registro_extraido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procesoingesta",
            name="destino_operacional",
            field=models.CharField(
                choices=[
                    ("transporte", "Transporte"),
                    ("material", "Material"),
                    ("flujo_ambiental", "Flujo ambiental"),
                    ("actividad_generica", "Actividad generica"),
                ],
                default="actividad_generica",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="procesoingesta",
            name="version_evidencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos_ingesta",
                to="analytics.versionevidencia",
            ),
        ),
    ]
