# Generated by Django 5.2.5 on 2026-08-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0040_alter_procesoingesta_destino_operacional_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadoperacional",
            name="obra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades_operacionales",
                to="analytics.obra",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticoambientalinicial",
            name="obra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnosticos_ambientales",
                to="analytics.obra",
            ),
        ),
        migrations.AddField(
            model_name="indicadorambiental",
            name="alcance",
            field=models.CharField(
                choices=[("organizacion", "Organizacion"), ("obra", "Obra")],
                db_index=True,
                default="organizacion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="indicadorambiental",
            name="obra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indicadores_ambientales",
                to="analytics.obra",
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="estado_ambiental",
            field=models.CharField(
                choices=[
                    ("configuracion", "Configuracion"),
                    ("monitoreo", "Monitoreo"),
                    ("requiere_atencion", "Requiere atencion"),
                    ("mejora_en_curso", "Mejora en curso"),
                    ("cierre_pendiente", "Cierre pendiente"),
                    ("cerrada", "Cerrada"),
                ],
                db_index=True,
                default="configuracion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="obra",
            name="fecha_cierre_ambiental",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="obra",
            name="observaciones_cierre_ambiental",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="obra",
            name="perfil_ambiental",
            field=models.CharField(
                choices=[
                    ("edificacion", "Edificacion"),
                    ("vial", "Vial"),
                    ("puente_infraestructura", "Puente o infraestructura"),
                    ("urbanizacion", "Urbanizacion"),
                    ("industrial", "Industrial"),
                    ("otro", "Otro"),
                ],
                db_index=True,
                default="otro",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="diagnosticoambientalinicial",
            name="organizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnosticos_ambientales",
                to="analytics.organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticoambientalinicial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("obra__isnull", True)),
                fields=("organizacion",),
                name="unique_diagnostico_general_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticoambientalinicial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("obra__isnull", False)),
                fields=("organizacion", "obra"),
                name="unique_diagnostico_obra_org",
            ),
        ),
    ]
