# Generated by Django 5.2.5 on 2026-08-15 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0041_actividadoperacional_obra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AplicabilidadCapacidadObra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("no_determinado", "No determinado"),
                            ("pendiente", "Pendiente"),
                            ("aplica", "Aplica"),
                            ("no_aplica", "No aplica"),
                            ("sin_datos", "Sin datos"),
                        ],
                        db_index=True,
                        default="no_determinado",
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="indicadorambiental",
            name="unique_indicador_codigo_org",
        ),
        migrations.AddConstraint(
            model_name="indicadorambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("alcance", "organizacion")),
                fields=("organizacion", "codigo"),
                name="unique_indicador_codigo_organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicadorambiental",
            constraint=models.UniqueConstraint(
                condition=models.Q(("alcance", "obra")),
                fields=("organizacion", "obra", "codigo"),
                name="unique_indicador_codigo_obra",
            ),
        ),
        migrations.AddField(
            model_name="aplicabilidadcapacidadobra",
            name="capacidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aplicabilidades_obras",
                to="analytics.capacidadambiental",
            ),
        ),
        migrations.AddField(
            model_name="aplicabilidadcapacidadobra",
            name="diagnostico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aplicabilidades_capacidades",
                to="analytics.diagnosticoambientalinicial",
            ),
        ),
        migrations.AddField(
            model_name="aplicabilidadcapacidadobra",
            name="obra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aplicabilidades_capacidades",
                to="analytics.obra",
            ),
        ),
        migrations.AddConstraint(
            model_name="aplicabilidadcapacidadobra",
            constraint=models.UniqueConstraint(
                fields=("obra", "capacidad"), name="unique_capacidad_obra"
            ),
        ),
    ]
