# Generated by Django 5.2.5 on 2026-08-24 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0043_usuarioorganizacion_alcance_usuarioobraacceso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoAuditoriaSaaS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(db_index=True, max_length=60)),
                ("detalle", models.TextField(blank=True)),
                ("estado_anterior", models.JSONField(blank=True, default=dict)),
                ("estado_nuevo", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_saas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditoria_saas",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuscripcionSaaS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("sin_plan", "Sin plan"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        default="sin_plan",
                        max_length=24,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("piloto", "Piloto"),
                            ("activo", "Activo"),
                            ("pago_pendiente", "Pago pendiente"),
                            ("suspendido", "Suspendido"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="piloto",
                        max_length=24,
                    ),
                ),
                (
                    "disponibilidad",
                    models.CharField(
                        choices=[
                            ("operativo", "Operativo"),
                            ("bloqueado", "Bloqueado"),
                        ],
                        db_index=True,
                        default="operativo",
                        max_length=16,
                    ),
                ),
                ("inicio_plan", models.DateField(blank=True, null=True)),
                ("fin_piloto", models.DateField(blank=True, null=True)),
                ("proximo_vencimiento", models.DateField(blank=True, null=True)),
                ("fecha_suspension", models.DateTimeField(blank=True, null=True)),
                ("fecha_cancelacion", models.DateTimeField(blank=True, null=True)),
                ("responsable_comercial", models.CharField(blank=True, max_length=160)),
                ("limites", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripcion_saas",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["organizacion__nombre"],
            },
        ),
    ]
