# Generated by Django 6.0.4 on 2026-08-24 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0044_eventoauditoriasaas_suscripcionsaas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenciaobra",
            name="metodo_captura",
            field=models.CharField(blank=True, default="documento", max_length=30),
        ),
        migrations.AddField(
            model_name="evidenciaobra",
            name="usuario_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidencias_originadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AreaOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bodega", "Bodega"),
                            ("maquinaria_operaciones", "Maquinaria y operaciones"),
                            ("logistica_transporte", "Logistica y transporte"),
                            ("administracion_compras", "Administracion y compras"),
                            ("medio_ambiente", "Medio ambiente"),
                            ("gestion_obra", "Gestion de obra"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="otro",
                        max_length=40,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas_operacionales",
                        to="analytics.organizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="evidenciaobra",
            name="area_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidencias_origen",
                to="analytics.areaoperacional",
            ),
        ),
        migrations.CreateModel(
            name="EspacioTrabajoOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=140)),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="espacios_trabajo",
                        to="analytics.areaoperacional",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espacios_operacionales",
                        to="analytics.obra",
                    ),
                ),
                (
                    "usuario_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espacios_trabajo",
                        to="analytics.usuarioorganizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["area__nombre", "obra__nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="areaoperacional",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "nombre"), name="unique_area_operacional_nombre"
            ),
        ),
        migrations.AddConstraint(
            model_name="espaciotrabajooperacional",
            constraint=models.UniqueConstraint(
                fields=("usuario_organizacion", "area", "obra"),
                name="unique_espacio_operacional_contexto",
            ),
        ),
    ]
