# Generated by Django 6.0.4 on 2026-08-24 15:54

import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_organizations(apps, schema_editor):
    apps.get_model("analytics", "Organizacion").objects.update(onboarding_completado=True, onboarding_step=5)


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0045_evidenciaobra_metodo_captura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacidadorganizacion",
            name="disponibilidad_inicial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular", "Informacion regular"),
                    ("parcial", "Informacion parcial"),
                    ("sin_informacion", "Sin informacion"),
                    ("no_seguro", "No estoy seguro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="nombre_comercial",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="onboarding_completado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="onboarding_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="pais",
            field=models.CharField(default="Chile", max_length=80),
        ),
        migrations.AlterField(
            model_name="areaoperacional",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("bodega", "Bodega"),
                    ("maquinaria_operaciones", "Maquinaria y operaciones"),
                    ("logistica_transporte", "Logistica y transporte"),
                    ("administracion_compras", "Administracion y compras"),
                    ("medio_ambiente", "Medio ambiente"),
                    ("gestion_obra", "Gestion de obra"),
                    ("mantenimiento", "Mantenimiento"),
                    ("produccion", "Produccion"),
                    ("calidad_laboratorio", "Calidad y laboratorio"),
                    ("otro", "Otro"),
                ],
                db_index=True,
                default="otro",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="AreaCapacidadAmbiental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sugerida", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flujos_asociados",
                        to="analytics.areaoperacional",
                    ),
                ),
                (
                    "capacidad_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas_origen",
                        to="analytics.capacidadorganizacion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("area", "capacidad_organizacion"),
                        name="unique_area_capacidad_ambiental",
                    )
                ],
            },
        ),
        migrations.RunPython(preserve_existing_organizations, migrations.RunPython.noop),
    ]
