# Generated by Django 6.0.4 on 2026-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0048_operational_atmospheric_emissions_and_soil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroflujoambiental",
            name="destino_operacional",
            field=models.CharField(
                choices=[
                    ("sin_clasificar", "Sin clasificar"),
                    ("generador", "Generador"),
                    ("maquinaria", "Maquinaria"),
                    ("vehiculo", "Vehiculo"),
                    ("equipo_menor", "Equipo menor"),
                    ("calefaccion", "Calefaccion"),
                    ("otro", "Otro"),
                    ("residuo", "Residuo"),
                    ("reutilizacion", "Reutilizacion"),
                    ("reciclaje", "Reciclaje"),
                    ("valorizacion", "Valorizacion"),
                    ("disposicion", "Disposicion"),
                    ("subproducto_reutilizado", "Subproducto reutilizado"),
                ],
                default="sin_clasificar",
                max_length=30,
            ),
        ),
    ]
