# Generated by Django 5.2.5 on 2026-08-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0049_alter_registroflujoambiental_destino_operacional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroflujoambiental",
            name="flujo",
            field=models.CharField(
                choices=[
                    ("energia", "Energia"),
                    ("generacion_propia", "Generacion propia"),
                    ("agua", "Agua"),
                    ("combustible", "Combustible por clasificar"),
                    ("combustible_estacionario", "Combustible estacionario"),
                    ("combustible_movil", "Combustible movil"),
                    ("residuo", "Residuo"),
                    ("ruido", "Ruido"),
                    ("emisiones_atmosfericas", "Emisiones atmosfericas"),
                    ("suelo", "Suelo"),
                    ("gestion_hidrica_suelo", "Gestion hidrica y suelo"),
                ],
                db_index=True,
                max_length=35,
            ),
        ),
    ]
