# Generated by Django 6.0.4 on 2026-08-29 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0050_alter_registroflujoambiental_flujo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioAreaOperacional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=120)),
                ("es_principal", models.BooleanField(db_index=True, default=False)),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios_asignados",
                        to="analytics.areaoperacional",
                    ),
                ),
                (
                    "usuario_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas_operacionales_asignadas",
                        to="analytics.usuarioorganizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-es_principal", "area__nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario_organizacion", "area"),
                        name="unique_usuario_area_operacional",
                    )
                ],
            },
        ),
    ]
