# Generated by Django 5.2.5 on 2026-09-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0051_usuarioareaoperacional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaambiental",
            name="factor_ambiental",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="formulas",
                to="analytics.factorambiental",
            ),
        ),
        migrations.AlterField(
            model_name="formulaambiental",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("transporte_tkm", "Masa x distancia x factor"),
                    ("transporte_vehiculo_km", "Distancia x factor vehiculo"),
                    ("transporte_combustible", "Combustible x factor"),
                    ("combustible_consumido", "Combustible consumido x factor"),
                ],
                max_length=40,
            ),
        ),
    ]
