# Generated by Django 5.2.5 on 2026-09-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0056_registroflujoambiental_waste_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaambiental",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("transporte_tkm", "Masa x distancia x factor"),
                    ("transporte_vehiculo_km", "Distancia x factor vehiculo"),
                    ("transporte_combustible", "Combustible x factor"),
                    ("combustible_consumido", "Combustible consumido x factor"),
                    ("energia_consumida", "Energia consumida x factor"),
                    ("material_cantidad", "Cantidad de material x factor"),
                ],
                max_length=40,
            ),
        ),
    ]
