# Generated by Django 5.2.5 on 2026-09-05 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0058_material_received_applicability"),
        ("knowledge", "0003_huellachileemissionfactorfact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalFactorCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detectado", "Detectado"),
                            ("requiere_mapping", "Requiere mapping"),
                            ("listo_revision", "Listo para revisión"),
                            ("rechazado", "Rechazado"),
                            ("promovido_borrador", "Promovido a borrador"),
                        ],
                        db_index=True,
                        default="detectado",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("mapping_type", models.CharField(blank=True, max_length=40)),
                ("mapping_context", models.JSONField(blank=True, default=dict)),
                ("compatibility", models.JSONField(blank=True, default=dict)),
                (
                    "promoted_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_candidates",
                        to="analytics.factorambiental",
                    ),
                ),
                (
                    "promoted_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_candidates",
                        to="analytics.versionfactorambiental",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="environmental_factor_candidates_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_fact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factor_candidate",
                        to="knowledge.huellachileemissionfactorfact",
                    ),
                ),
            ],
        ),
    ]
