# Generated by Django 5.2.5 on 2026-09-05 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0059_environmentalfactorcandidate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalFactorReconciliation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("preparado", "Preparado"), ("cambiado", "Cambiado")],
                        default="preparado",
                        max_length=20,
                    ),
                ),
                ("source_artifact_sha", models.CharField(max_length=64)),
                ("comparison", models.JSONField(default=dict)),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                ("switched_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation",
                        to="analytics.environmentalfactorcandidate",
                    ),
                ),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="analytics.factorambiental",
                    ),
                ),
                (
                    "legacy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_reconciliations",
                        to="analytics.versionfactorambiental",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factor_reconciliations_prepared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replacement_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_reconciliations",
                        to="analytics.versionfactorambiental",
                    ),
                ),
                (
                    "switched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factor_reconciliations_switched",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
