# Generated by Django 5.2.5 on 2026-09-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0060_environmentalfactorreconciliation"),
        ("knowledge", "0007_legalobligation_legalobligationversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalObligationApplicabilityAssessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_level",
                    models.CharField(
                        choices=[("organization", "Organization"), ("work", "Work")],
                        max_length=20,
                    ),
                ),
                ("evaluator_version", models.CharField(db_index=True, max_length=60)),
                ("revision", models.PositiveIntegerField()),
                ("is_latest", models.BooleanField(db_index=True, default=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("applicable", "Applicable"),
                            ("not_applicable", "Not applicable"),
                            ("undetermined", "Undetermined"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("context_snapshot", models.JSONField()),
                ("criteria_snapshot", models.JSONField(blank=True)),
                ("legal_snapshot", models.JSONField()),
                ("evaluation_details", models.JSONField()),
                ("context_hash", models.CharField(max_length=64)),
                ("input_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_applicability_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_assessments",
                        to="knowledge.legalobligation",
                    ),
                ),
                (
                    "obligation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_assessments",
                        to="knowledge.legalobligationversion",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_applicability_assessments",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_applicability_assessments",
                        to="analytics.obra",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluated_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("scope_level", "organization"),
                                ("work__isnull", True),
                            ),
                            models.Q(
                                ("scope_level", "work"),
                                ("work__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="analytics_legal_scope_work",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("work__isnull", True)),
                        fields=("organization", "obligation", "revision"),
                        name="analytics_legal_org_revision",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("work__isnull", False)),
                        fields=("work", "obligation", "revision"),
                        name="analytics_legal_work_revision",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_latest", True), ("work__isnull", True)),
                        fields=("organization", "obligation"),
                        name="analytics_legal_org_latest",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_latest", True), ("work__isnull", False)
                        ),
                        fields=("work", "obligation"),
                        name="analytics_legal_work_latest",
                    ),
                ],
            },
        ),
    ]
