# Generated by Django 5.2.5 on 2026-09-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0061_legalobligationapplicabilityassessment"),
        ("knowledge", "0008_legalevidencerequirement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalEvidenceOperationalMappingRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("is_latest", models.BooleanField(db_index=True, default=True)),
                ("mapping_items", models.JSONField()),
                ("mapping_hash", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legal_evidence_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_mapping_revisions",
                        to="knowledge.legalevidencerequirementversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegalEvidenceOperationalLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_evidence_class", models.CharField(max_length=40)),
                ("matched_evidence_type", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("linked", "Linked"), ("withdrawn", "Withdrawn")],
                        db_index=True,
                        default="linked",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("requirement_snapshot", models.JSONField()),
                ("mapping_snapshot", models.JSONField()),
                ("applicability_snapshot", models.JSONField()),
                ("evidence_snapshot", models.JSONField()),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                (
                    "applicability_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="analytics.legalobligationapplicabilityassessment",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_requirement_links",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "evidence_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_requirement_links",
                        to="analytics.versionevidencia",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legal_evidence_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_evidence_links",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "requirement_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_links",
                        to="knowledge.legalevidencerequirementversion",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawn_legal_evidence_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_evidence_links",
                        to="analytics.obra",
                    ),
                ),
                (
                    "mapping_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="analytics.legalevidenceoperationalmappingrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-linked_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="legalevidenceoperationalmappingrevision",
            constraint=models.UniqueConstraint(
                fields=("requirement_version", "revision"),
                name="analytics_legal_evidence_mapping_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalevidenceoperationalmappingrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("requirement_version",),
                name="analytics_legal_evidence_mapping_latest",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalevidenceoperationallink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "linked"), ("work__isnull", True)),
                fields=(
                    "organization",
                    "requirement_version",
                    "evidence_version",
                    "matched_evidence_class",
                ),
                name="analytics_active_legal_evidence_org_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalevidenceoperationallink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "linked"), ("work__isnull", False)),
                fields=(
                    "work",
                    "requirement_version",
                    "evidence_version",
                    "matched_evidence_class",
                ),
                name="analytics_active_legal_evidence_work_link",
            ),
        ),
    ]
