# Generated by Django 5.2.5 on 2026-09-06 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0062_legalevidenceoperationalmappingrevision_and_more"),
        ("knowledge", "0008_legalevidencerequirement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalEvidenceRequirementSufficiencyReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_level",
                    models.CharField(
                        choices=[("organization", "Organization"), ("work", "Work")],
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("is_latest", models.BooleanField(db_index=True, default=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sufficient", "Sufficient"),
                            ("insufficient", "Insufficient"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField()),
                ("reviewer_note", models.TextField(blank=True)),
                ("requirement_snapshot", models.JSONField()),
                ("mapping_snapshot", models.JSONField()),
                ("applicability_snapshot", models.JSONField()),
                ("evidence_bundle_snapshot", models.JSONField()),
                ("basis_hash", models.CharField(max_length=64)),
                ("review_hash", models.CharField(max_length=64)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicability_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_sufficiency_reviews",
                        to="analytics.legalobligationapplicabilityassessment",
                    ),
                ),
                (
                    "mapping_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sufficiency_reviews",
                        to="analytics.legalevidenceoperationalmappingrevision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_evidence_sufficiency_reviews",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sufficiency_reviews",
                        to="knowledge.legalevidencerequirement",
                    ),
                ),
                (
                    "requirement_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sufficiency_reviews",
                        to="knowledge.legalevidencerequirementversion",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_evidence_sufficiency_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_evidence_sufficiency_reviews",
                        to="analytics.obra",
                    ),
                ),
            ],
            options={
                "ordering": ["-revision"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("scope_level", "organization"), ("work__isnull", True)
                            ),
                            models.Q(("scope_level", "work"), ("work__isnull", False)),
                            _connector="OR",
                        ),
                        name="analytics_sufficiency_scope_work",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("work__isnull", True)),
                        fields=("organization", "requirement", "revision"),
                        name="analytics_sufficiency_org_revision",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("work__isnull", False)),
                        fields=("work", "requirement", "revision"),
                        name="analytics_sufficiency_work_revision",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_latest", True), ("work__isnull", True)),
                        fields=("organization", "requirement"),
                        name="analytics_sufficiency_org_latest",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_latest", True), ("work__isnull", False)
                        ),
                        fields=("work", "requirement"),
                        name="analytics_sufficiency_work_latest",
                    ),
                ],
            },
        ),
    ]
