# Generated by Django 5.2.5 on 2026-09-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0063_legal_evidence_sufficiency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkGeolocationRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("is_latest", models.BooleanField(default=True)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=13)),
                ("srid", models.PositiveIntegerField(default=4326)),
                (
                    "capture_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("gps", "GPS"),
                            ("survey", "Levantamiento"),
                            ("import", "Importación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "accuracy_m",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=500)),
                ("note", models.TextField(blank=True)),
                ("coordinate_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="geolocation_revisions",
                        to="analytics.obra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkTerritorialObservationRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "observation_contract_version",
                    models.CharField(
                        default="territorial-observation-1", max_length=80
                    ),
                ),
                ("geolocation_snapshot", models.JSONField()),
                ("source_snapshot", models.JSONField()),
                ("layer_catalog_snapshot", models.JSONField()),
                ("results_snapshot", models.JSONField()),
                ("summary_snapshot", models.JSONField()),
                ("basis_hash", models.CharField(max_length=64)),
                ("result_hash", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "geolocation_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.workgeolocationrevision",
                    ),
                ),
                (
                    "observed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="territorial_observations",
                        to="analytics.obra",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="workgeolocationrevision",
            constraint=models.UniqueConstraint(
                fields=("work", "revision"), name="analytics_geo_location_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="workgeolocationrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("work",),
                name="analytics_geo_one_latest_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="workterritorialobservationrevision",
            constraint=models.UniqueConstraint(
                fields=("work", "revision"), name="analytics_geo_observation_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="workterritorialobservationrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("work",),
                name="analytics_geo_one_latest_observation",
            ),
        ),
    ]
