# Generated by Django 6.0.4 on 2026-09-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0064_work_geolocation_territorial_observation"),
        ("knowledge", "0013_okobaudat_detail_history_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialEnvironmentalFactorCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("requires_review", "Requires review"),
                            ("ready_for_review", "Approved for promotion"),
                            ("rejected", "Rejected"),
                            ("promoted_to_draft", "Promoted to draft"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("normalization", models.JSONField(default=dict)),
                ("provenance", models.JSONField(default=dict)),
                ("functional_context", models.JSONField(default=dict)),
                ("initial_eligibility", models.JSONField(default=dict)),
                ("promoted_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promoted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_candidates_promoted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promoted_factor",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_source_candidate",
                        to="analytics.factorambiental",
                    ),
                ),
                (
                    "promoted_version",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_source_candidate",
                        to="analytics.versionfactorambiental",
                    ),
                ),
                (
                    "source_indicator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_factor_candidates",
                        to="knowledge.oekobaudatenvironmentalindicatorfact",
                    ),
                ),
                (
                    "source_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_factor_candidate",
                        to="knowledge.oekobaudatenvironmentalprofilefact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialFactorCandidateReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                ("context", models.JSONField(default=dict)),
                ("eligibility", models.JSONField(default=dict)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="analytics.materialenvironmentalfactorcandidate",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_factor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="materialenvironmentalfactorcandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "detected",
                            "requires_review",
                            "ready_for_review",
                            "rejected",
                            "promoted_to_draft",
                        ],
                    )
                ),
                name="material_candidate_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialenvironmentalfactorcandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("promoted_at__isnull", False),
                        ("promoted_by__isnull", False),
                        ("promoted_factor__isnull", False),
                        ("promoted_version__isnull", False),
                        ("status", "promoted_to_draft"),
                    ),
                    models.Q(
                        models.Q(("status", "promoted_to_draft"), _negated=True),
                        ("promoted_at__isnull", True),
                        ("promoted_by__isnull", True),
                        ("promoted_factor__isnull", True),
                        ("promoted_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="material_candidate_promotion_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialfactorcandidatereview",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ["approved", "rejected"])),
                name="material_review_valid_decision",
            ),
        ),
    ]
