# Generated by Django 6.0.4 on 2026-09-11 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0066_material_candidate_history_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialFactorMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("propuesto", "Propuesto"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("revocado", "Revocado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        db_index=True,
                        default="propuesto",
                        max_length=20,
                    ),
                ),
                ("vigencia_desde", models.DateField()),
                ("vigencia_hasta", models.DateField(blank=True, null=True)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                ("revocado_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeos_material",
                        to="analytics.factorambiental",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeos_factor",
                        to="analytics.materialoperacional",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeos_material_factor",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "propuesto_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeos_material_propuestos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reemplazado_por",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reemplaza_a",
                        to="analytics.materialfactormapping",
                    ),
                ),
                (
                    "revocado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeos_material_revocados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-vigencia_desde", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialFactorMappingDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("propuesto", "Propuesto"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("revocado", "Revocado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("nota", models.TextField(blank=True)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones_mapeo_material",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones",
                        to="analytics.materialfactormapping",
                    ),
                ),
            ],
            options={
                "ordering": ["mapping_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialfactormapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "estado__in",
                        [
                            "propuesto",
                            "aprobado",
                            "rechazado",
                            "revocado",
                            "reemplazado",
                        ],
                    )
                ),
                name="material_mapping_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialfactormapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vigencia_hasta__isnull", True),
                    ("vigencia_hasta__gte", models.F("vigencia_desde")),
                    _connector="OR",
                ),
                name="material_mapping_valid_validity_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialfactormapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estado", "reemplazado"), ("reemplazado_por__isnull", False)
                    ),
                    models.Q(
                        models.Q(("estado", "reemplazado"), _negated=True),
                        ("reemplazado_por__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="material_mapping_reemplazado_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialfactormapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "propuesto")),
                fields=("material", "factor", "vigencia_desde", "vigencia_hasta"),
                name="unique_material_mapping_pending_proposal",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialfactormappingdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "decision__in",
                        [
                            "propuesto",
                            "aprobado",
                            "rechazado",
                            "revocado",
                            "reemplazado",
                        ],
                    )
                ),
                name="material_mapping_decision_valid",
            ),
        ),
    ]
