# Generated by Django 6.0.4 on 2026-09-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0068_material_factor_mapping_guards"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="calculoambiental",
            constraint=models.UniqueConstraint(
                fields=("recalculo_de",), name="unique_calculo_recalculo_de"
            ),
        ),
    ]
