# Generated by Django 5.2.5 on 2026-09-12 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0069_calculo_recalculo_de_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialApplicationProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "cantidad_unidad_funcional",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("unidad_funcional", models.CharField(max_length=40)),
                ("requisitos", models.JSONField(blank=True, default=list)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("retirado", "Retirado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfiles_aplicacion_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfiles_aplicacion_material",
                        to="analytics.obra",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfiles_aplicacion_material",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "reemplaza_a",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reemplazado_por_perfil",
                        to="analytics.materialapplicationprofile",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfiles_aplicacion_retirados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfiles_aplicacion_revisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialApplicationProfileDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("creado", "Creado"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("retirado", "Retirado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("nota", models.TextField(blank=True)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones_perfil_aplicacion_material",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones",
                        to="analytics.materialapplicationprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["profile_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialapplicationprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "estado__in",
                        [
                            "borrador",
                            "aprobado",
                            "rechazado",
                            "retirado",
                            "reemplazado",
                        ],
                    )
                ),
                name="material_application_profile_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialapplicationprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_unidad_funcional__gt", 0)),
                name="material_application_profile_positive_functional_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialapplicationprofiledecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "decision__in",
                        ["creado", "aprobado", "rechazado", "retirado", "reemplazado"],
                    )
                ),
                name="material_application_profile_decision_valid",
            ),
        ),
    ]
