# Generated by Django 5.2.5 on 2026-09-12 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0071_material_application_profile_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialTechnicalPropertyAssertion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_key", models.CharField(max_length=100)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numérica"),
                            ("categorical", "Categórica"),
                            ("boolean", "Booleana"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=180)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=40)),
                (
                    "provenance_type",
                    models.CharField(
                        choices=[
                            ("manufacturer_datasheet", "Ficha técnica del fabricante"),
                            ("technical_spec", "Especificación técnica"),
                            ("certificate", "Certificado"),
                            ("lab_result", "Resultado de laboratorio"),
                            ("project_requirement", "Requisito de proyecto"),
                            (
                                "manual_professional_assertion",
                                "Aserción profesional manual",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("effective_date", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asserted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aserciones_propiedad_material_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aserciones_propiedad_material",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aserciones_propiedad_material",
                        to="analytics.fuentedatos",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aserciones_propiedad",
                        to="analytics.materialoperacional",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aserciones_propiedad_material",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aserciones_propiedad_material_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version_evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aserciones_propiedad_material",
                        to="analytics.versionevidencia",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialTechnicalPropertyAssertionDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("creado", "Creado"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("nota", models.TextField(blank=True)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones_propiedad_material",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assertion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones",
                        to="analytics.materialtechnicalpropertyassertion",
                    ),
                ),
            ],
            options={
                "ordering": ["assertion_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialtechnicalpropertyassertion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado__in", ["borrador", "aprobado", "rechazado", "reemplazado"])
                ),
                name="material_property_assertion_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialtechnicalpropertyassertion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("property_type", "numeric"),
                        ("value_boolean__isnull", True),
                        ("value_numeric__isnull", False),
                        ("value_text", ""),
                    ),
                    models.Q(
                        ("property_type", "categorical"),
                        ("value_boolean__isnull", True),
                        ("value_numeric__isnull", True),
                    ),
                    models.Q(
                        ("property_type", "boolean"),
                        ("value_boolean__isnull", False),
                        ("value_numeric__isnull", True),
                        ("value_text", ""),
                    ),
                    _connector="OR",
                ),
                name="material_property_assertion_typed_value_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialtechnicalpropertyassertiondecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision__in", ["creado", "aprobado", "rechazado", "reemplazado"])
                ),
                name="material_property_assertion_decision_valid",
            ),
        ),
    ]
