# Generated by Django 5.2.5 on 2026-09-12 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0073_material_technical_property_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialFunctionalUse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_por_unidad_funcional",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("unidad", models.CharField(max_length=40)),
                ("rationale", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_funcionales_material_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_funcionales_material",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_funcionales",
                        to="analytics.materialoperacional",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_funcionales_material",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_funcionales_material",
                        to="analytics.materialapplicationprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_funcionales_material_revisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialFunctionalUseDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("creado", "Creado"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("reemplazado", "Reemplazado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("nota", models.TextField(blank=True)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones_uso_funcional_material",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "functional_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones",
                        to="analytics.materialfunctionaluse",
                    ),
                ),
            ],
            options={
                "ordering": ["functional_use_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialApplicationAssessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("suitable_candidate", "Candidato adecuado"),
                            ("not_suitable", "No adecuado"),
                            ("requires_review", "Requiere revisión"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requirement_results", models.JSONField(blank=True, default=list)),
                ("missing_properties", models.JSONField(blank=True, default=list)),
                ("failed_requirements", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("profile_version", models.PositiveIntegerField()),
                ("assertion_ids_used", models.JSONField(blank=True, default=list)),
                (
                    "decision_humana",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado para la aplicación"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("decidido_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decidido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones_aplicacion_decididas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones_aplicacion_material_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones_aplicacion",
                        to="analytics.materialoperacional",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_aplicacion_material",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones_aplicacion_material",
                        to="analytics.materialapplicationprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "resultado__in",
                                [
                                    "suitable_candidate",
                                    "not_suitable",
                                    "requires_review",
                                ],
                            )
                        ),
                        name="material_application_assessment_valid_result",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "decision_humana__in",
                                ["pendiente", "aprobado", "rechazado"],
                            )
                        ),
                        name="material_application_assessment_valid_human_decision",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="materialfunctionaluse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado__in", ["borrador", "aprobado", "rechazado", "reemplazado"])
                ),
                name="material_functional_use_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialfunctionaluse",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_por_unidad_funcional__gt", 0)),
                name="material_functional_use_positive_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialfunctionalusedecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision__in", ["creado", "aprobado", "rechazado", "reemplazado"])
                ),
                name="material_functional_use_decision_valid",
            ),
        ),
    ]
