# Generated by Django 5.2.5 on 2026-09-12 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0075_material_functional_use_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialSubstitutionScenario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_version", models.PositiveIntegerField()),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("reception", "Recepción real"),
                            ("aggregate_quantity", "Cantidad agregada hipotética"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_quantity_input",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("source_quantity_unit", models.CharField(max_length=40)),
                (
                    "functional_units",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "baseline_quantity_per_functional_unit",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "alternative_quantity_per_functional_unit",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "alternative_quantity_equivalent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "baseline_impact_per_functional_unit",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "alternative_impact_per_functional_unit",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "absolute_delta",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "relative_delta",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            (
                                "lower_impact_alternative",
                                "Alternativa con menor impacto",
                            ),
                            (
                                "higher_impact_alternative",
                                "Alternativa con mayor impacto",
                            ),
                            ("equal_impact", "Impacto equivalente"),
                            ("not_comparable", "No comparable"),
                        ],
                        max_length=30,
                    ),
                ),
                ("not_comparable_reason", models.CharField(blank=True, max_length=60)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alternative_factor_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_alternativa",
                        to="analytics.versionfactorambiental",
                    ),
                ),
                (
                    "alternative_functional_use",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_alternativa",
                        to="analytics.materialfunctionaluse",
                    ),
                ),
                (
                    "alternative_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_como_alternativa",
                        to="analytics.materialoperacional",
                    ),
                ),
                (
                    "baseline_factor_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_base",
                        to="analytics.versionfactorambiental",
                    ),
                ),
                (
                    "baseline_functional_use",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_base",
                        to="analytics.materialfunctionaluse",
                    ),
                ),
                (
                    "baseline_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_como_base",
                        to="analytics.materialoperacional",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_sustitucion_material_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escenarios_sustitucion_material",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_sustitucion",
                        to="analytics.materialapplicationprofile",
                    ),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escenarios_sustitucion",
                        to="analytics.eventomaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("basis__in", ["reception", "aggregate_quantity"])
                        ),
                        name="material_substitution_scenario_valid_basis",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "resultado__in",
                                [
                                    "lower_impact_alternative",
                                    "higher_impact_alternative",
                                    "equal_impact",
                                    "not_comparable",
                                ],
                            )
                        ),
                        name="material_substitution_scenario_valid_result",
                    ),
                ],
            },
        ),
    ]
