import { useCallback, useEffect, useState } from "react";
import { ArrowRight, Building2, RefreshCw, Rocket, TriangleAlert, UsersRound, Workflow } from "lucide-react";
import { Link } from "react-router-dom";
import PlatformLoader from "@/shared/components/PlatformLoader";
import { Button, ErrorState, StatusBadge } from "@/shared/ui";
import { formatDateTime, formatNumber } from "@/shared/utils/formatters";
import { getSaaSDashboard } from "../services/saasApi";

const healthTone = { saludable: "success", observacion: "warning", riesgo: "danger", critico: "danger" };
const iconTones = { emerald: "bg-emerald-50 text-emerald-700", violet: "bg-violet-50 text-violet-700", amber: "bg-amber-50 text-amber-700", blue: "bg-blue-50 text-blue-700", cyan: "bg-cyan-50 text-cyan-700" };

export default function SaaSDashboardPage() {
  const [state, setState] = useState({ status: "loading", data: null });
  const load = useCallback(() => { setState({ status: "loading", data: null }); getSaaSDashboard().then((data) => setState({ status: "ready", data })).catch(() => setState({ status: "error", data: null })); }, []);
  useEffect(() => { load(); }, [load]);
  if (state.status === "loading") return <PlatformLoader title="Cargando centro SaaS" />;
  if (state.status === "error") return <ErrorState description="No fue posible cargar la administración global." onRetry={load} />;
  const { kpis, attention, organizations } = state.data;
  const cards = [["Organizaciones activas", kpis.operativas, Building2, "emerald"], ["Pilotos activos", kpis.pilotos, Rocket, "violet"], ["Requieren gestión", kpis.requieren_gestion, TriangleAlert, "amber"], ["Usuarios activos", kpis.usuarios_activos, UsersRound, "blue"], ["Obras activas", kpis.obras_activas, Workflow, "cyan"]];
  return <div className="space-y-7"><section className="relative overflow-hidden rounded-[30px] bg-gradient-to-br from-emerald-900 via-teal-800 to-cyan-800 p-7 text-white shadow-2xl sm:p-9"><div className="relative flex flex-col gap-6 xl:flex-row xl:items-center xl:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.17em] text-emerald-200">Centro de control SaaS</p><h2 className="mt-2 text-3xl font-black sm:text-4xl">Carbono Zero Global</h2><p className="mt-3 max-w-3xl leading-7 text-emerald-50/85">Controla organizaciones, planes, vencimientos, adopción, consumo y salud operacional de toda la plataforma desde una sola vista.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{kpis.operativas} organizaciones operativas</span><span className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{kpis.pilotos} pilotos</span><span className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{kpis.requieren_gestion} requieren atención</span></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" leftIcon={RefreshCw} onClick={load}>Actualizar</Button><Link className="inline-flex min-h-11 items-center rounded-xl bg-white px-4 text-sm font-black text-emerald-900" to="/saas/organizaciones">Gestionar organizaciones</Link></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label, value, Icon, color]) => <article key={label} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${iconTones[color]}`}><Icon size={19} /></span><p className="mt-5 text-3xl font-black">{formatNumber(value, 0)}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><div className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Qué requiere atención ahora</h2><p className="mt-1 text-sm text-slate-500">Priorización explicable basada en acceso, estado comercial y actividad real.</p><div className="mt-5 space-y-3">{attention.length ? attention.slice(0, 8).map((row) => <article key={row.organizacion_id} className="flex flex-col gap-3 rounded-2xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><b>{row.nombre}</b><StatusBadge tone={healthTone[row.salud.key]}>{row.salud.label}</StatusBadge></div><p className="mt-1 text-xs text-slate-500">{row.salud.reason}</p><p className="mt-1 text-xs text-slate-400">Actividad: {formatDateTime(row.ultima_actividad)}</p></div><Link className="inline-flex items-center gap-2 text-sm font-black text-emerald-700" to={`/saas/organizaciones?seleccion=${row.organizacion_id}`}>Ir a organización <ArrowRight size={16} /></Link></article>) : <p className="rounded-2xl bg-emerald-50 p-5 text-sm font-bold text-emerald-800">No existen organizaciones que requieran gestión según las reglas actuales.</p>}</div></div>
      <div className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Salud de organizaciones</h2><p className="mt-1 text-sm text-slate-500">Reglas visibles, sin clasificaciones arbitrarias.</p><div className="mt-5 space-y-3">{["saludable", "observacion", "riesgo", "critico"].map((key) => { const count = organizations.filter((row) => row.salud.key === key).length; const sample = organizations.find((row) => row.salud.key === key); return <div key={key} className="flex items-center justify-between rounded-2xl bg-slate-50 px-4 py-3"><div><StatusBadge tone={healthTone[key]}>{sample?.salud.label || ({ saludable: "Saludable", observacion: "En observación", riesgo: "En riesgo", critico: "Crítico" }[key])}</StatusBadge><p className="mt-1 text-xs text-slate-500">{{ saludable: "Uso reciente y acceso normal.", observacion: "Inactividad moderada o piloto próximo a vencer.", riesgo: "Inactividad prolongada o pago pendiente.", critico: "Acceso bloqueado, suspendido o cancelado." }[key]}</p></div><b className="text-2xl">{count}</b></div>; })}</div></div></section>
  </div>;
}
