export {
  calculateRouteDistance,
  createLote,
  createLoteActividad,
  createLoteTransporte,
  downloadLoteCertificado,
  extractDocumentJsonById,
  extractDocumentTextById,
  getEspeciesMadera,
  getHistorialLote,
  getLoteCarbono,
  getLoteDetail,
  getLotes,
  getVerificacionLote,
  rejectExtraccionDocumento,
  runDocumentoOcr,
  uploadLoteDocumento,
  validateExtraccionDocumento,
} from "@/shared/services/api";
