# Generated by Django 6.0.4 on 2026-09-12 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0076_material_substitution_scenario"),
        ("knowledge", "0013_okobaudat_detail_history_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RateBudget",
            fields=[
                (
                    "key",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("events", models.JSONField(default=list)),
                ("blocked_until", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ResponseCache",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="EpdVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upstream_version", models.PositiveIntegerField(null=True)),
                ("local_version", models.PositiveIntegerField()),
                ("evidence", models.JSONField()),
                ("evidence_checksum", models.CharField(max_length=64)),
                ("rights_reference", models.CharField(max_length=500)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ec3_versions",
                        to="knowledge.externalrecord",
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ec3_version",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ec3_candidate",
                        to="analytics.materialfactormapping",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ec3_candidates",
                        to="analytics.materialoperacional",
                    ),
                ),
                (
                    "promoted_version",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ec3_candidate",
                        to="analytics.versionfactorambiental",
                    ),
                ),
                (
                    "epd_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="ec3.epdversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=12,
                    ),
                ),
                ("lcia_method", models.CharField(blank=True, max_length=80)),
                ("context", models.JSONField()),
                ("evaluation", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="ec3.candidate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="epdversion",
            constraint=models.UniqueConstraint(
                fields=("record", "local_version"), name="ec3_record_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("material", "epd_version"),
                name="ec3_material_epd_candidate_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ["approved", "rejected"])),
                name="ec3_review_decision_valid",
            ),
        ),
    ]
