# Generated by Django 6.0.4 on 2026-09-12 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ec3", "0002_history_guards"),
        ("knowledge", "0013_okobaudat_detail_history_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="epdversion",
            name="retrieved_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="epdversion",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ec3_versions",
                to="knowledge.externalsnapshot",
            ),
        ),
    ]
