import { useState } from "react";
import { FileSpreadsheet, UploadCloud } from "lucide-react";
import { Alert, Button, Card, CardContent, StatusBadge } from "@/shared/ui";
import { analyzeImport, confirmImport, createImport, previewImport, saveImportMapping } from "../services/dataApi";

const concepts = ["", "identificador_actividad", "fecha_actividad", "periodo_inicio", "periodo_fin", "distancia_recorrida_km", "masa_transportada_t", "combustible_consumido_l", "consumo_energia", "consumo_agua", "material", "cantidad_material", "cantidad_residuo", "nivel_ruido", "unidad", "obra", "proceso", "activo", "punto_medicion"];
const destinations = [["actividad_generica", "Actividad operacional"], ["transporte", "Transporte"], ["material", "Materiales"], ["flujo_ambiental", "Flujo ambiental"]];
export default function ImportWorkflow({ organizationId, work }) {
  const [stage, setStage] = useState(1); const [process, setProcess] = useState(null); const [mappings, setMappings] = useState([]); const [preview, setPreview] = useState(null); const [result, setResult] = useState(null); const [source, setSource] = useState("Fuente operacional"); const [destination, setDestination] = useState("actividad_generica"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function upload(file) { if (!file) return; setBusy(true); setError(""); try { const created = await createImport(organizationId, file, source, { destination }); setProcess(created); setStage(2); const analyzed = await analyzeImport(organizationId, created.id); setMappings(analyzed.columnas || []); setStage(4); } catch (requestError) { setError(requestError?.response?.data?.error || "No se pudo analizar el archivo. El proceso conservado puede consultarse en el historial."); } finally { setBusy(false); } }
  async function mapAndPreview() { setBusy(true); setError(""); try { await saveImportMapping(organizationId, process.id, mappings, { destination, context: work ? { obra: work.id || work.codigo_obra } : {} }); setPreview(await previewImport(organizationId, process.id)); setStage(5); } catch (requestError) { setError(requestError?.response?.data?.error || "No se pudo preparar la previsualización."); } finally { setBusy(false); } }
  async function confirm() { setBusy(true); setError(""); try { setResult(await confirmImport(organizationId, process.id)); setStage(8); } catch (requestError) { setError(requestError?.response?.data?.error || "La confirmación falló. Revisa los errores antes de reintentar."); } finally { setBusy(false); } }
  const reviewRows = preview?.filas?.filter((row) => row.estado !== "valido" && row.estado !== "validado") || [];
  return <Card><CardContent><div className="flex items-center gap-3"><FileSpreadsheet className="text-[var(--brand-primary)]" /><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--brand-primary)]">Nueva importación</p><h2 className="text-xl font-bold">Archivo a datos operacionales trazables</h2></div></div>
    <ol className="mt-4 grid grid-cols-4 gap-1 text-center text-xs sm:grid-cols-8">{["Origen", "Archivo", "Contexto", "Mapping", "Preview", "Revisión", "Confirmar", "Resultado"].map((label, index) => <li key={label} className={`rounded-md p-2 ${stage >= index + 1 ? "bg-[var(--brand-primary)] text-white" : "bg-[var(--bg-surface-subtle)]"}`}><span className="sr-only">Paso </span>{index + 1}. {label}</li>)}</ol>
    {error && <div className="mt-4"><Alert tone="danger">{error}</Alert></div>}
    {!process && <div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Fuente de datos<input className="mt-1 w-full rounded-lg border p-2 font-normal" value={source} onChange={(event) => setSource(event.target.value)} /></label><label className="text-sm font-bold">Tipo de flujo<select className="mt-1 w-full rounded-lg border p-2 font-normal" value={destination} onChange={(event) => setDestination(event.target.value)}>{destinations.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed p-3 font-bold"><UploadCloud />{busy ? "Analizando…" : "Seleccionar CSV/XLS/XLSX"}<input aria-label="Seleccionar planilla para importar" accept=".csv,.xls,.xlsx" className="hidden" disabled={busy} type="file" onChange={(event) => upload(event.target.files?.[0])} /></label></div>}
    {process && <div className="mt-4 rounded-lg bg-[var(--info-bg)] p-3 text-sm"><b>Detectamos:</b> {process.clasificacion_sugerida || "tipo no determinado"}. <span className="ml-2">Requiere confirmación.</span><span className="block mt-1"><b>Contexto:</b> {work?.nombre || work?.codigo_obra || "Organización"}</span></div>}
    {!!mappings.length && !preview && <section className="mt-5"><h3 className="font-bold">Mapping detectado</h3><p className="text-sm text-[var(--text-muted)]">Confirma cómo cada columna se convierte en un concepto Carbono Zero.</p><div className="mt-3 max-h-80 space-y-2 overflow-auto">{mappings.map((item, index) => <div key={`${item.columna_origen}-${index}`} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1fr_1fr_110px]"><span><b>{item.columna_origen}</b><small className="block text-[var(--text-muted)]">Columna original</small></span><select aria-label={`Concepto para ${item.columna_origen}`} className="rounded-lg border p-2" value={item.concepto_normalizado || ""} onChange={(event) => setMappings((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, concepto_normalizado: event.target.value } : row))}>{concepts.map((value) => <option key={value} value={value}>{value ? value.replaceAll("_", " ") : "Sin mapear"}</option>)}</select><input aria-label={`Unidad para ${item.columna_origen}`} className="rounded-lg border p-2" placeholder="Unidad" value={item.unidad_esperada || ""} onChange={(event) => setMappings((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, unidad_esperada: event.target.value } : row))} /></div>)}</div><Button className="mt-4" disabled={busy || mappings.some((item) => !item.concepto_normalizado)} onClick={mapAndPreview}>Guardar mapping y previsualizar</Button></section>}
    {preview && !result && <section className="mt-5"><div className="flex flex-wrap gap-3"><StatusBadge label={`${preview.filas_validas} válidos`} tone="success" /><StatusBadge label={`${preview.filas_problematicas} requieren revisión`} tone="warning" /></div>{!!reviewRows.length && <div className="mt-4"><h3 className="font-bold">Requieren tu revisión</h3><div className="mt-2 max-h-64 space-y-2 overflow-auto">{reviewRows.slice(0, 20).map((row) => <article key={row.numero_fila} className="rounded-lg border p-3 text-sm"><b>Fila {row.numero_fila}</b>{row.problemas?.map((problem) => <p key={`${problem.codigo}-${problem.campo}`} className="text-[var(--status-danger)]">{problem.campo}: {problem.detalle}</p>)}</article>)}</div></div>}<details className="mt-4"><summary className="cursor-pointer font-bold">Vista previa de filas ({Math.min(preview.filas?.length || 0, 20)})</summary><div className="mt-2 max-h-80 overflow-auto">{preview.filas?.slice(0, 20).map((row) => <div key={row.numero_fila} className="grid gap-2 border-b p-2 text-xs md:grid-cols-2"><pre className="overflow-auto">Original: {JSON.stringify(row.datos_originales, null, 2)}</pre><pre className="overflow-auto">Normalizado: {JSON.stringify(row.datos_normalizados, null, 2)}</pre></div>)}</div></details><Alert tone="info"><b>Al confirmar:</b> se crearán {preview.filas_validas} registros operacionales. Los problemas informados no se convertirán en emisiones automáticamente.</Alert><Button className="mt-4" disabled={busy || preview.filas_validas === 0} onClick={confirm}>Confirmar importación</Button></section>}
    {result && <Alert tone="success"><b>Importación terminada.</b> {result.actividades_creadas || 0} actividades, {result.observaciones_creadas || 0} datos observados y {result.filas_con_error || 0} errores.</Alert>}
  </CardContent></Card>;
}
