import { useEffect,useMemo,useState } from "react";
import { Building2,ChevronDown } from "lucide-react";
import { NavLink,useLocation,useNavigate } from "react-router-dom";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { getActivePreset,getPresetLabel } from "@/presets/registry";
import { getNavigationForPreset } from "@/app/navigation";

export default function Sidebar({onNavigate}){const navigate=useNavigate();const {pathname}=useLocation();const {activeOrganizacion,activeOrganizacionId,clearActiveOrganizacion,organizaciones,loadingOrganizaciones,setActiveOrganizacion}=useOrganizacionActiva();const presetKey=activeOrganizacion?.preset||"construccion";const preset=useMemo(()=>getActivePreset(presetKey),[presetKey]);const navigation=useMemo(()=>getNavigationForPreset(preset),[preset]);const [expanded,setExpanded]=useState({});
 useEffect(()=>{const next={};navigation.groups.forEach(group=>group.items.forEach(item=>{if(item.children?.some(child=>pathname.startsWith(child.path)))next[item.id]=true;}));setExpanded(next);},[navigation.groups,pathname]);
 function switchOrganization(event){const selected=organizaciones.find(org=>String(org.organizacion_id)===event.target.value);if(selected){setActiveOrganizacion(selected);navigate("/inicio");}else clearActiveOrganizacion();onNavigate?.();}
 return <aside className="flex min-h-full w-full shrink-0 flex-col border-b border-[var(--sidebar-border)] bg-[var(--sidebar)] px-3 py-4 text-[var(--text-main)] shadow-[18px_0_50px_rgba(19,34,56,0.05)] lg:sticky lg:top-[72px] lg:h-[calc(100vh-72px)] lg:w-64 lg:border-b-0 lg:border-r">
  <section className="mb-4 px-2"><label className="sr-only" htmlFor="active-organization">Organización activa</label><div className="flex items-center gap-2"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[var(--radius-md)] bg-[var(--bg-surface-subtle)] text-[var(--brand-primary)]"><Building2 aria-hidden="true" size={17}/></span><div className="min-w-0 flex-1"><select id="active-organization" value={activeOrganizacionId||""} onChange={switchOrganization} className="w-full truncate border-0 bg-transparent p-0 text-sm font-black text-[var(--text-primary)] outline-none focus-visible:shadow-[var(--focus-ring)]"><option value="">Selecciona una organización</option>{organizaciones.map(org=><option key={org.organizacion_id} value={org.organizacion_id}>{org.nombre}</option>)}</select><p className="truncate text-xs text-[var(--text-muted)]">{getPresetLabel(presetKey)}</p></div></div>{loadingOrganizaciones&&<p className="mt-1 pl-11 text-xs text-[var(--text-muted)]">Actualizando organizaciones…</p>}</section>
  <nav aria-label="Navegación principal" className="min-h-0 flex-1 space-y-3 overflow-y-auto px-1 pb-2"><NavItem item={navigation.home} onNavigate={onNavigate}/>{navigation.groups.map(group=><section key={group.id} aria-labelledby={`nav-${group.id}`}><p id={`nav-${group.id}`} className="mb-1 px-2 text-[10px] font-black uppercase tracking-[0.15em] text-[var(--text-muted)]">{group.label}</p><div className="space-y-0.5">{group.items.map(item=>item.children?<div key={item.id}><button type="button" aria-expanded={Boolean(expanded[item.id])} onClick={()=>setExpanded(current=>({...current,[item.id]:!current[item.id]}))} className="flex w-full items-center gap-2.5 rounded-[var(--radius-md)] px-3 py-2 text-left text-sm font-bold text-[var(--text-secondary)] transition hover:bg-[var(--bg-surface-subtle)] hover:text-[var(--text-primary)]"><item.icon aria-hidden="true" size={17}/><span className="min-w-0 flex-1 truncate">{item.label}</span><ChevronDown aria-hidden="true" size={15} className={`transition ${expanded[item.id]?"rotate-180":""}`}/></button>{expanded[item.id]&&<div className="ml-5 border-l border-[var(--sidebar-border)] pl-2">{item.children.map(child=><NavItem compact item={child} key={child.path} onNavigate={onNavigate}/>)}</div>}</div>:<NavItem item={item} key={item.path} onNavigate={onNavigate}/>)}</div></section>)}</nav>
 </aside>}

function NavItem({compact=false,item,onNavigate}){const Icon=item.icon;return <NavLink end={item.path==="/inicio"} to={item.path} onClick={onNavigate} className={({isActive})=>`flex items-center gap-2.5 rounded-[var(--radius-md)] px-3 ${compact?"py-1.5 text-xs":"py-2 text-sm"} font-bold transition focus-visible:outline-none focus-visible:shadow-[var(--focus-ring)] ${isActive?"bg-[var(--sidebar-active)] text-[var(--brand-primary)]":"text-[var(--text-secondary)] hover:bg-[var(--bg-surface-subtle)] hover:text-[var(--text-primary)]"}`}><Icon aria-hidden="true" size={compact?15:17}/><span className="truncate">{item.label}</span></NavLink>}
