import { useEffect, useState } from "react";
import { AlertTriangle, BarChart3, ShieldCheck } from "lucide-react";
import { getEnvironmentalSummaryV2, getIndicatorComparison } from "../api/qualityV2Api";

export default function EnvironmentalSummaryV2({ organizacionId }) {
  const [summary, setSummary] = useState(null); const [comparisons, setComparisons] = useState({});
  useEffect(() => { let active = true; if (!organizacionId) return undefined;
    getEnvironmentalSummaryV2(organizacionId).then(async (data) => { if (!active) return; setSummary(data); const entries = await Promise.all((data.indicadores || []).map(async (item) => [item.id, await getIndicatorComparison(organizacionId, item.id)])); if (active) setComparisons(Object.fromEntries(entries)); }).catch(() => active && setSummary(null));
    return () => { active = false; }; }, [organizacionId]);
  if (!summary) return null;
  return <section className="rounded-[32px] border border-emerald-200 bg-white p-6 shadow-[var(--shadow-card)]"><div className="flex items-start gap-3"><BarChart3 className="text-emerald-700"/><div><p className="text-xs font-black uppercase tracking-[0.22em] text-emerald-700">Indicadores v2</p><h2 className="text-2xl font-black">Desempeño ambiental comparable</h2><p className="mt-1 text-sm text-slate-600">{summary.mensaje}</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-3">{(summary.indicadores || []).map((item) => { const comparison = comparisons[item.id] || {}; return <article key={item.id} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-slate-500">{item.tipo}</p><h3 className="mt-1 font-black">{item.nombre}</h3><p className="mt-2 text-xl font-black">{item.valor_actual ? `${Number(item.valor_actual.valor).toLocaleString()} ${item.unidad}` : "Sin valor actual"}</p><p className="mt-1 text-xs text-slate-500">Comparación: {comparison.estado || "sin_base"}{comparison.diferencia_porcentual != null ? ` · ${Number(comparison.diferencia_porcentual).toFixed(2)}%` : ""}</p></article>; })}</div>{!(summary.indicadores || []).length && <p className="mt-5 rounded-2xl border border-dashed p-5 text-sm text-slate-600">Carbono Zero está construyendo tu línea base ambiental. No hay tendencias ficticias disponibles.</p>}<div className="mt-4 flex flex-wrap gap-3 text-sm"><span className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-3 py-2"><ShieldCheck size={16}/> Calidad evaluada: {Object.values(summary.calidad || {}).reduce((a,b)=>a+b,0)}</span><span className="inline-flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2"><AlertTriangle size={16}/> Discrepancias abiertas: {summary.discrepancias_abiertas}</span></div></section>;
}
