import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Plus } from "lucide-react";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { Button, Card, CardContent, EmptyState, ErrorState, FilterBar, Input, LoadingState, Modal, PageHeader, SearchInput, Select, StatusBadge, TableBody, TableCell, TableHead, TableShell, Textarea } from "@/shared/ui";
import { createAsset, createMaintenance, getAssets, updateAsset } from "../api/assetsApi";

const blank = { codigo: "", nombre: "", tipo: "vehiculo", estado: "operativo", descripcion: "" };
export default function ActivosPage() { const { activeOrganizacionId } = useOrganizacionActiva(); const [state, setState] = useState({ loading: true, rows: [], error: "" }); const [filters, setFilters] = useState({ tipo: "", estado: "", query: "" }); const [dialog, setDialog] = useState(null); const [busy, setBusy] = useState(false);
  const load = useCallback(() => { setState((current) => ({ ...current, loading: true, error: "" })); getAssets(activeOrganizacionId, { tipo: filters.tipo, estado: filters.estado }).then((rows) => setState({ loading: false, rows, error: "" })).catch(() => setState({ loading: false, rows: [], error: "No fue posible cargar los activos." })); }, [activeOrganizacionId, filters.estado, filters.tipo]); useEffect(() => { load(); }, [load]);
  const rows = useMemo(() => state.rows.filter((item) => !filters.query || `${item.nombre} ${item.codigo}`.toLowerCase().includes(filters.query.toLowerCase())), [filters.query, state.rows]);
  async function save() { setBusy(true); try { if (dialog.id) await updateAsset(activeOrganizacionId, dialog.id, dialog); else await createAsset(activeOrganizacionId, dialog); setDialog(null); await load(); } finally { setBusy(false); } }
  async function maintenance() { setBusy(true); try { await createMaintenance(activeOrganizacionId, dialog.asset.id, dialog.form); setDialog(null); await load(); } finally { setBusy(false); } }
  return <main className="space-y-6"><PageHeader eyebrow="Operación · Mundo físico" title="Activos operacionales" description="Equipos físicos, condición operacional, mantenimiento y sensores asociados." actions={<Button leftIcon={Plus} onClick={() => setDialog({ ...blank })}>Crear activo</Button>} />
    <FilterBar><SearchInput label="Buscar" value={filters.query} onChange={(e) => setFilters({ ...filters, query: e.target.value })} /><Select label="Tipo" value={filters.tipo} onChange={(e) => setFilters({ ...filters, tipo: e.target.value })}><option value="">Todos</option>{["vehiculo", "maquinaria", "equipo", "medidor", "infraestructura", "otro"].map((v) => <option key={v}>{v}</option>)}</Select><Select label="Estado" value={filters.estado} onChange={(e) => setFilters({ ...filters, estado: e.target.value })}><option value="">Todos</option>{["operativo", "requiere_revision", "fuera_servicio", "retirado"].map((v) => <option key={v}>{v}</option>)}</Select></FilterBar>
    {state.error ? <ErrorState description={state.error} onRetry={load} /> : state.loading ? <LoadingState label="Cargando activos" /> : !rows.length ? <EmptyState title="No hay activos registrados." description="Registra un equipo cuando forme parte real de la operación." /> : <TableShell><TableHead><tr><TableCell as="th">Activo</TableCell><TableCell as="th">Tipo</TableCell><TableCell as="th">Estado</TableCell><TableCell as="th">Contexto</TableCell><TableCell as="th">Condición reciente</TableCell><TableCell as="th">Sensores</TableCell><TableCell as="th">Acciones</TableCell></tr></TableHead><TableBody columns={7}>{rows.map((item) => <tr key={item.id}><TableCell><b>{item.nombre}</b><span className="block text-xs text-[var(--text-muted)]">{item.codigo}</span></TableCell><TableCell>{item.tipo}</TableCell><TableCell><StatusBadge>{item.estado.replaceAll("_", " ")}</StatusBadge></TableCell><TableCell>{item.unidad_nombre || "Sin unidad"} · {item.proceso_nombre || "Sin proceso"}</TableCell><TableCell>{item.condiciones?.[0]?.estado?.replaceAll("_", " ") || "Sin registro"}</TableCell><TableCell><Link className="font-bold text-[var(--brand-primary)]" to="/operacion/sensores">{item.sensores_count ?? 0} sensores</Link></TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => setDialog({ ...item })}>Editar</Button><Button size="sm" variant="secondary" onClick={() => setDialog({ type: "maintenance", asset: item, form: { tipo: "Preventivo", fecha_programada: "", estado: "programado" } })}>Mantenimiento</Button></div></TableCell></tr>)}</TableBody></TableShell>}
    <Modal open={Boolean(dialog)} title={dialog?.type === "maintenance" ? `Mantenimiento · ${dialog.asset.nombre}` : dialog?.id ? "Editar activo" : "Crear activo"} onClose={() => setDialog(null)} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setDialog(null)}>Cancelar</Button><Button loading={busy} onClick={dialog?.type === "maintenance" ? maintenance : save}>Guardar</Button></div>}>{dialog?.type === "maintenance" ? <div className="space-y-4"><Input label="Tipo" value={dialog.form.tipo} onChange={(e) => setDialog({ ...dialog, form: { ...dialog.form, tipo: e.target.value } })} /><Input type="date" label="Fecha programada" value={dialog.form.fecha_programada} onChange={(e) => setDialog({ ...dialog, form: { ...dialog.form, fecha_programada: e.target.value } })} /><Select label="Estado" value={dialog.form.estado} onChange={(e) => setDialog({ ...dialog, form: { ...dialog.form, estado: e.target.value } })}>{["programado", "realizado", "vencido"].map((v) => <option key={v}>{v}</option>)}</Select></div> : <div className="space-y-4"><Input required label="Código" value={dialog?.codigo || ""} onChange={(e) => setDialog({ ...dialog, codigo: e.target.value })} /><Input required label="Nombre" value={dialog?.nombre || ""} onChange={(e) => setDialog({ ...dialog, nombre: e.target.value })} /><Select label="Tipo" value={dialog?.tipo || "vehiculo"} onChange={(e) => setDialog({ ...dialog, tipo: e.target.value })}>{["vehiculo", "maquinaria", "equipo", "medidor", "infraestructura", "otro"].map((v) => <option key={v}>{v}</option>)}</Select><Select label="Estado" value={dialog?.estado || "operativo"} onChange={(e) => setDialog({ ...dialog, estado: e.target.value })}>{["operativo", "requiere_revision", "fuera_servicio", "retirado"].map((v) => <option key={v}>{v}</option>)}</Select><Textarea label="Descripción" value={dialog?.descripcion || ""} onChange={(e) => setDialog({ ...dialog, descripcion: e.target.value })} /></div>}</Modal>
  </main>; }
