import { ArrowRight, BarChart3, Database, Factory, FileOutput, History, Leaf, LockKeyhole } from "lucide-react";
import { Link } from "react-router-dom";
import SettingsNav from "../components/SettingsNav";

const content = {
  operacion: { title: "Operación", description: "Administra la estructura operacional con los módulos existentes.", icon: Factory, rows: [["/obras", "Obras", "Unidades de trabajo y ciclo operacional."], ["/administracion/estructura", "Etapas", "Estructura y etapas disponibles para la organización."], ["/operacion/activos", "Activos y maquinaria", "Equipos, vehículos, medidores y generadores."], ["/operacion/sensores", "Sensores", "Dispositivos y seguimiento de mediciones."]] },
  ambiental: { title: "Gestión ambiental", description: "Configura contexto y aplicabilidad sin mezclarlo con la operación diaria.", icon: Leaf, rows: [["/administracion/diagnostico", "Perfil ambiental de la obra", "Contexto, fuentes, brechas y aplicabilidad por obra."], ["/gobernanza/calidad", "Requisitos y calidad", "Revisión gobernada de calidad y documentación."], ["/gobernanza/factores", "Metodologías gobernadas", "Consulta fuentes y factores sin alterar ecuaciones globales."]] },
  calculo: { title: "Cálculo e indicadores", description: "Separa preferencias del tenant de la gobernanza científica global.", icon: BarChart3, rows: [["/gobernanza/factores", "Metodologías y factores", "Consulta versiones, vigencia y fuentes gobernadas."], ["/administracion/configuracion", "Unidades de presentación", "Configura kgCO2e o tCO2e y precisión visual sin cambiar el cálculo canónico."], ["/obras", "Indicadores y líneas base", "Selecciona una obra para administrar sus indicadores existentes."]] },
  reportes: { title: "Reportes", description: "Preferencias de presentación disponibles; no constituye un motor de reportes.", icon: FileOutput, rows: [["/administracion/configuracion", "Presentación y periodo", "Agrupación, periodo, unidad visual y contenido soportado."], ["/gobernanza/expedientes", "Expedientes disponibles", "Consulta salidas documentales y trazabilidad existentes."]] },
  datos: { title: "Datos", description: "Gobierna preferencias de captura y accede a flujos existentes.", icon: Database, rows: [["/administracion/configuracion", "Preferencias de datos", "Validación, duplicados, archivos y vínculos documentales."], ["/datos/importaciones", "Administrar importaciones", "Centro guiado de incorporación ambiental."], ["/datos/evidencias", "Administrar evidencias", "Documentos y antecedentes del tenant."]] },
  auditoria: { title: "Auditoría", description: "Reutiliza únicamente la trazabilidad que el backend registra actualmente.", icon: History, rows: [["/gobernanza/auditoria", "Abrir auditoría", "Consulta eventos reales disponibles en el módulo gobernado."]] },
};

export default function SettingsSectionPage({ section }) {
  const current = content[section]; const Icon = current.icon;
  return <main className="space-y-6"><header className="flex items-start gap-3 border-b border-[var(--border-default)] pb-5"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><Icon aria-hidden="true" size={21} /></span><div><p className="text-xs font-black uppercase tracking-[0.14em] text-emerald-700">Configuración</p><h1 className="mt-1 text-2xl font-black">{current.title}</h1><p className="mt-1 text-sm text-[var(--text-muted)]">{current.description}</p></div></header><div className="grid items-start gap-5 lg:grid-cols-[230px_minmax(0,1fr)]"><SettingsNav /><section className="overflow-hidden rounded-[22px] border border-[var(--border-default)] bg-white"><div className="divide-y divide-[var(--border-default)]">{current.rows.map(([to, title, description]) => <Link key={`${to}-${title}`} to={to} className="group flex items-center gap-4 p-5 hover:bg-emerald-50/40"><span className="min-w-0 flex-1"><b>{title}</b><span className="mt-1 block text-sm text-[var(--text-muted)]">{description}</span></span><ArrowRight aria-hidden="true" className="text-emerald-700" size={17} /></Link>)}</div>{section === "calculo" && <div className="flex gap-3 border-t border-[var(--border-default)] bg-slate-50 p-5"><LockKeyhole aria-hidden="true" className="shrink-0 text-slate-600" size={19} /><p className="text-sm text-[var(--text-muted)]">Las fórmulas CO2e y los factores globales permanecen bajo Gobernanza. El tenant solo controla preferencias y capacidades expresamente soportadas.</p></div>}</section></div></main>;
}
