export {
  calculateRouteDistance,
  createObra,
  downloadObraFichaAmbiental,
  extractDocumentJsonById,
  extractDocumentTextById,
  getMaterialesConstruccion,
  getHistorialObra,
  getObraBalanceAmbiental,
  getObras,
  getVerificacionObra,
  rejectExtraccionEvidencia,
  runEvidenciaOcr,
  uploadObraEvidencia,
  validateExtraccionEvidencia,
} from "@/shared/services/api";
