<<<<<<< HEAD
export const environmentalPresetMatrix = {
  construccion: {
    key: "construccion",
    label: "Construccion",
    purpose: "Controlar trazabilidad de obras, consumos, residuos y documentos que sostienen la huella y la ficha ambiental.",
    criticalDocuments: ["Facturas de materiales criticos", "Guias de despacho", "Tickets de pesaje de residuos", "Certificados de gestor autorizado", "Declaraciones ambientales de producto", "RCA o permisos aplicables"],
    criticalVariables: ["m3 de hormigon", "ton de acero", "litros de diesel", "kWh consumidos", "ton de residuos", "km de transporte"],
    regulations: ["RETC", "RCA si aplica", "DS 1/2013 MMA", "Ley REP para residuos aplicables"],
    riskSignals: ["Materiales sin respaldo documental", "Residuos sin destino trazable", "Consumos de combustible sin etapa asociada", "Obras con ficha ambiental incompleta"],
    recommendedActions: ["Vincular facturas y guias a cada registro critico.", "Cerrar trazabilidad de residuos con gestor y ticket de pesaje.", "Priorizar calculo de emisiones en materiales de mayor impacto."],
    regulatoryOutputs: ["Resumen de emisiones por obra y etapa", "Ficha ambiental verificable", "Matriz de evidencias por fuente", "Preparacion de antecedentes RETC/RCA cuando corresponda"],
    copilotQuestions: ["Que obras tienen mayor riesgo documental?", "Que materiales explican la mayor parte de la huella?", "Que evidencias faltan para cerrar la ficha ambiental?", "Que acciones reducen riesgo regulatorio este mes?"],
  },
  forestal_aserradero: {
    key: "forestal_aserradero",
    label: "Forestal y aserradero",
    purpose: "Conectar origen forestal, produccion, secado, energia, transporte y residuos para trazabilidad operacional y ambiental.",
    criticalDocuments: ["Guias de recepcion de trozas", "Documentos de lote forestal", "Bitacoras de secado", "Facturas de energia y combustible", "Bitacoras de transporte forestal", "Certificados de valorizacion o disposicion de residuos"],
    criticalVariables: ["m3 de trozas", "humedad inicial y final", "kWh consumidos", "litros de combustible", "km de transporte forestal", "ton de residuos o subproductos"],
    regulations: ["RETC", "RCA si aplica", "Ley REP si aplica", "Normativa forestal y sanitaria aplicable"],
    riskSignals: ["Lotes sin origen documentado", "Secado sin energia asociada", "Viajes forestales sin ruta o patente", "Residuos sin valorizacion o destino registrado"],
    recommendedActions: ["Completar origen, especie, volumen y humedad por lote.", "Asociar energia y combustible a produccion y secado.", "Documentar destino de subproductos y residuos."],
    regulatoryOutputs: ["Resumen ambiental por lote y proceso", "Trazabilidad de transporte forestal", "Indicadores de energia por produccion", "Matriz de residuos y destino"],
    copilotQuestions: ["Que lotes tienen trazabilidad incompleta?", "Que proceso concentra mayor consumo energetico?", "Que viajes forestales requieren respaldo documental?", "Que residuos deberian priorizar valorizacion?"],
  },
  industrial_agroindustria: {
    key: "industrial_agroindustria",
    label: "Industrial y agroindustria",
    purpose: "Ordenar consumos, procesos, insumos, residuos y permisos para controlar indicadores ambientales y preparacion regulatoria.",
    criticalDocuments: ["Facturas de energia", "Facturas de combustibles", "Registros de produccion", "Analisis de efluentes o emisiones", "Certificados de residuos", "RCA, permisos sectoriales o planes de monitoreo"],
    criticalVariables: ["kWh por proceso", "litros o m3 de combustible", "unidades producidas", "consumo de agua", "ton de residuos", "parametros de efluentes o emisiones"],
    regulations: ["RETC", "RCA si aplica", "Normas de emision aplicables", "Ley REP si aplica"],
    riskSignals: ["Procesos sin produccion asociada", "Consumos energeticos fuera de patron", "Monitoreos incompletos", "Residuos sin certificado de destino"],
    recommendedActions: ["Cruzar energia y combustible contra produccion del periodo.", "Completar monitoreos exigidos por RCA o permisos.", "Priorizar residuos con trazabilidad incompleta."],
    regulatoryOutputs: ["Indicadores por proceso productivo", "Resumen de emisiones y residuos", "Estado de obligaciones RETC/RCA", "Bitacora de evidencias regulatorias"],
    copilotQuestions: ["Que procesos muestran desviaciones de consumo?", "Que obligaciones RCA tienen evidencia pendiente?", "Que residuos tienen brechas de destino?", "Que variables faltan para calcular indicadores regulatorios?"],
  },
  mineria: {
    key: "mineria",
    label: "Mineria",
    purpose: "Controlar combustible, energia, agua, residuos, transporte y obligaciones RCA para operaciones con alto riesgo ambiental.",
    criticalDocuments: ["Facturas de combustible", "Facturas de energia", "Registros de extraccion o procesamiento", "Monitoreos ambientales", "Manifiestos y certificados de residuos", "RCA y reportes de cumplimiento"],
    criticalVariables: ["litros de diesel", "kWh consumidos", "ton procesadas", "m3 de agua", "ton de residuos peligrosos", "horas de maquinaria"],
    regulations: ["RETC", "RCA", "Normas de emision aplicables", "Ley REP si aplica"],
    riskSignals: ["Alto consumo de diesel sin frente operativo", "Monitoreos RCA atrasados", "Residuos peligrosos sin destino", "Agua sin balance operacional"],
    recommendedActions: ["Asociar combustible y maquinaria a frente o proceso.", "Revisar calendario de monitoreos RCA.", "Cerrar trazabilidad de residuos peligrosos con certificados."],
    regulatoryOutputs: ["Tablero de obligaciones RCA", "Resumen de combustible y energia", "Matriz de residuos peligrosos", "Indicadores de agua y proceso"],
    copilotQuestions: ["Que obligaciones RCA estan en riesgo?", "Donde se concentra el consumo de diesel?", "Que residuos peligrosos no tienen respaldo?", "Que datos faltan para preparar el reporte mensual?"],
  },
  energia: {
    key: "energia",
    label: "Energia",
    purpose: "Dar trazabilidad a generacion, consumo, combustibles, mantencion y obligaciones ambientales de activos energeticos.",
    criticalDocuments: ["Facturas de combustible", "Mediciones de generacion o consumo", "Bitacoras de mantencion", "Monitoreos de emisiones", "Certificados de residuos", "RCA o permisos aplicables"],
    criticalVariables: ["MWh generados", "kWh consumidos", "litros o m3 de combustible", "horas de operacion", "eventos de mantencion", "residuos por activo"],
    regulations: ["RETC", "RCA si aplica", "Normas de emision aplicables", "Ley REP si aplica"],
    riskSignals: ["Generacion sin medicion respaldada", "Combustible sin conciliacion operacional", "Mantencion critica pendiente", "Monitoreo de emisiones incompleto"],
    recommendedActions: ["Conciliar combustible contra generacion y horas de operacion.", "Actualizar bitacoras de mantencion critica.", "Vincular monitoreos a obligaciones ambientales."],
    regulatoryOutputs: ["Indicadores de emisiones por MWh", "Estado de monitoreos", "Matriz de mantenciones ambientales", "Resumen de cumplimiento RCA/RETC"],
    copilotQuestions: ["Que activos tienen monitoreo ambiental pendiente?", "Como varia la emision por MWh?", "Que mantenciones reducen riesgo operativo?", "Que evidencias faltan para RETC?"],
  },
  acuicultura: {
    key: "acuicultura",
    label: "Acuicultura",
    purpose: "Ordenar alimento, energia, combustible, biomasa, residuos y monitoreos para controlar impactos y obligaciones ambientales.",
    criticalDocuments: ["Registros de alimento", "Facturas de energia y combustible", "Registros de biomasa", "Monitoreos ambientales", "Certificados de residuos", "RCA o permisos sectoriales"],
    criticalVariables: ["ton de alimento", "biomasa producida", "kWh consumidos", "litros de combustible", "mortalidad", "residuos generados"],
    regulations: ["RETC", "RCA si aplica", "Normativa sectorial acuicola", "Ley REP si aplica"],
    riskSignals: ["Alimento sin centro o lote asociado", "Monitoreos ambientales incompletos", "Residuos sin destino", "Combustible sin operacion vinculada"],
    recommendedActions: ["Vincular alimento, biomasa y centro operativo.", "Revisar monitoreos exigidos por permiso o RCA.", "Cerrar destino documental de residuos."],
    regulatoryOutputs: ["Indicadores por centro", "Estado de monitoreos", "Matriz de residuos y mortalidad", "Resumen de obligaciones ambientales"],
    copilotQuestions: ["Que centros tienen evidencia incompleta?", "Que variable explica mayor presion ambiental?", "Que monitoreos requieren seguimiento?", "Que residuos tienen brecha de destino?"],
  },
  transporte: {
    key: "transporte",
    label: "Transporte",
    purpose: "Trazar combustible, rutas, flota, mantencion y residuos REP para controlar emisiones logisticas y riesgos documentales.",
    criticalDocuments: ["Facturas de combustible", "Documentos de ruta", "Bitacoras de mantencion", "Registros de neumaticos y residuos", "Certificados de destino de aceites o neumaticos", "RCA si aplica"],
    criticalVariables: ["litros de diesel", "km recorridos", "rendimiento por vehiculo", "mantencion de flota", "carga transportada", "residuos REP como neumaticos o aceites"],
    regulations: ["RETC", "Ley REP", "RCA si aplica"],
    riskSignals: ["Alto consumo de combustible", "Trazabilidad de rutas faltante", "Brechas de mantencion", "Destino de residuos no documentado"],
    recommendedActions: ["Conciliar litros de diesel contra km y rutas.", "Actualizar bitacoras de mantencion por vehiculo.", "Vincular neumaticos, aceites y otros residuos a gestor autorizado."],
    regulatoryOutputs: ["Indicadores de emisiones por km", "Matriz de trazabilidad de rutas", "Estado de mantenciones ambientales", "Resumen REP de residuos aplicables"],
    copilotQuestions: ["Que rutas tienen peor rendimiento por litro?", "Que vehiculos tienen mantencion pendiente?", "Que residuos REP no tienen destino respaldado?", "Que datos faltan para reportar emisiones logisticas?"],
  },
};

export const DEFAULT_ENVIRONMENTAL_MATRIX_KEY = "industrial_agroindustria";
=======
export const DEFAULT_ENVIRONMENTAL_MATRIX_KEY = "industrial_agroindustria";

export const environmentalPresetMatrix = {
  construccion: {
    key: "construccion",
    id: "construccion",
    label: "Construcción",
    name: "Construcción e inmobiliaria",
    shortName: "Construcción",
    purpose:
      "Controlar obras, materiales, maquinaria, transporte, residuos, combustible, agua, energía y documentos que sostienen la huella ambiental de obra.",
    dashboardBlueprint: {
      mainPain:
        "La obra genera datos dispersos en materiales, maquinaria, transporte, residuos, combustible, agua, energía y documentos sueltos.",
      dashboardTitle: "Estado ambiental de obra",
      dashboardSubtitle: "Huella, residuos, documentos y trazabilidad ambiental de la obra.",
      operationalFocus: "Obra + materiales + maquinaria + residuos",
      starKpi: "kgCO₂e/m²",
      sellableReportName: "Reporte mensual de huella y trazabilidad ambiental de obra",
      requiredModules: [
        moduleItem("obras", "Obras", "Nombre, ubicación, mandante, superficie, fechas y responsable."),
        moduleItem("materiales", "Materiales", "Hormigón, cemento, acero, áridos, madera, asfalto y otros."),
        moduleItem("maquinaria", "Maquinaria", "Equipos, generadores, excavadoras, grúas y horas de operación."),
        moduleItem("combustible", "Combustible", "Diésel, bencina, litros, proveedor, factura y equipo asociado."),
        moduleItem("transporte", "Transporte", "Viajes, kilómetros, origen-destino, camiones, carga y proveedor."),
        moduleItem("rcd", "Residuos RCD", "Escombros, madera, fierro, cartón, plásticos, tierra y residuos peligrosos."),
        moduleItem("agua_energia", "Agua y energía", "kWh, m³ de agua, boletas y medidores."),
        moduleItem("documentos", "Documentos", "Facturas, guías, certificados, fotos y contratos."),
        moduleItem("cumplimiento", "Cumplimiento", "RCA, compromisos, PAS, alertas y vencimientos si aplica."),
      ],
      kpiCards: [
        kpi("huella_total_obra", "Huella total de obra", "tCO₂e", "Emisiones acumuladas por obra."),
        kpi("huella_m2", "Huella por m² construido", "kgCO₂e/m²", "Intensidad ambiental por superficie."),
        kpi("emisiones_material", "Emisiones por material", "tCO₂e", "Hormigón, acero, cemento y otros materiales críticos."),
        kpi("combustible_mes", "Consumo de combustible", "L/mes", "Litros mensuales por maquinaria y transporte."),
        kpi("rcd_generado", "Residuos generados", "ton", "Toneladas de RCD por periodo."),
        kpi("valorizacion", "% residuos valorizados", "%", "Reciclaje, reutilización o valorización."),
        kpi("docs_faltantes", "Documentos faltantes", "n°", "Respaldos pendientes para trazabilidad."),
      ],
      priorityFocus: ["RCD sin destino", "materiales de alto impacto", "documentos faltantes", "combustible por maquinaria"],
      emptyStateGuidance: "Carga facturas, guías de despacho, vales RCD y consumos de combustible para activar el tablero de obra.",
    },
    criticalDocuments: [
      "Facturas de materiales críticos",
      "Guías de despacho",
      "Vales de pesaje RCD",
      "Certificados de disposición autorizada",
      "Boletas de agua y energía",
      "RCA o permisos aplicables",
    ],
    criticalVariables: [
      "m³ de hormigón",
      "ton de acero",
      "litros de diésel",
      "kWh consumidos",
      "m³ de agua",
      "ton de RCD",
      "km de transporte",
    ],
    regulations: ["RETC / Ventanilla Única", "SINADER", "DS 38 ruido", "RCA si aplica", "Ley REP si aplica"],
    riskSignals: [
      "Residuos sin destino autorizado",
      "Materiales críticos sin respaldo",
      "Ruido cercano al límite",
      "Consumo de combustible sin equipo asociado",
    ],
    recommendedActions: [
      "Vincular cada retiro de RCD con vale, patente y gestor autorizado.",
      "Priorizar cálculo de emisiones en hormigón, acero y combustible.",
      "Cerrar documentos faltantes antes del reporte mensual de obra.",
    ],
    regulatoryOutputs: [
      "Reporte mensual ambiental de obra",
      "Resumen de huella por obra y etapa",
      "Matriz de evidencias por fuente",
      "Preparación de antecedentes RETC/SINADER cuando corresponda",
    ],
    copilotQuestions: [
      "¿Qué obra tiene mayor riesgo documental?",
      "¿Qué materiales explican la mayor parte de la huella?",
      "¿Qué evidencias faltan para cerrar el reporte mensual?",
      "¿Qué acciones reducen riesgo ambiental esta semana?",
    ],
  },

  industrial_agroindustria: {
    key: "industrial_agroindustria",
    id: "industrial_agroindustria",
    label: "Industrial / Agroindustria",
    name: "Industrial y agroindustria",
    shortName: "Industrial / Agro",
    purpose:
      "Ordenar procesos, energía, combustibles, fuentes fijas, residuos, sustancias peligrosas, RILES, documentos y cumplimiento operacional.",
    dashboardBlueprint: {
      mainPain:
        "La empresa industrial debe controlar procesos, energía, combustibles, residuos, sustancias peligrosas, RILES y fiscalización más exigente.",
      dashboardTitle: "Estado ambiental de planta",
      dashboardSubtitle: "Emisiones, residuos, energía, RILES y respaldo documental de planta.",
      operationalFocus: "Planta + procesos + energía + residuos + fuentes fijas",
      starKpi: "tCO₂e/unidad producida",
      sellableReportName: "Reporte de gestión ambiental industrial con emisiones, residuos, energía y respaldo documental",
      requiredModules: [
        moduleItem("plantas", "Plantas / instalaciones", "Ubicación, procesos, responsables y áreas."),
        moduleItem("procesos", "Procesos productivos", "Líneas, turnos y producción mensual."),
        moduleItem("energia", "Energía", "kWh, medidores, boletas y consumo por área."),
        moduleItem("combustibles", "Combustibles", "Gas, diésel, GLP, biomasa, petróleo y consumo por equipo."),
        moduleItem("fuentes_fijas", "Fuentes fijas", "Calderas, hornos, generadores y chimeneas."),
        moduleItem("residuos", "Residuos", "Residuos no peligrosos y peligrosos."),
        moduleItem("sustancias", "Sustancias peligrosas", "Inventario, cantidades, ubicación y HDS."),
        moduleItem("riles", "RILES / agua", "Consumo, descarga, tratamiento y mediciones."),
        moduleItem("documentos", "Documentos", "Facturas, certificados, declaraciones y permisos."),
        moduleItem("cumplimiento", "Cumplimiento", "RETC, SINADER, RUEA/F138, RCA si aplica."),
      ],
      kpiCards: [
        kpi("huella_planta", "Huella total planta", "tCO₂e/mes", "Emisiones mensuales consolidadas."),
        kpi("emisiones_fuente", "Emisiones por fuente", "tCO₂e", "Caldera, horno, generador o chimenea."),
        kpi("energia_produccion", "Energía por producción", "kWh/unidad", "Eficiencia energética por unidad producida."),
        kpi("combustible_produccion", "Combustible por producción", "L/unidad", "Consumo asociado a producción."),
        kpi("respel", "Residuos peligrosos", "kg/mes", "RESPEL generado en el periodo."),
        kpi("residuos_no_peligrosos", "Residuos no peligrosos", "ton/mes", "Residuos declarables no peligrosos."),
        kpi("agua", "Consumo de agua", "m³/mes", "Consumo mensual por planta."),
        kpi("docs_vencidos", "Documentos vencidos", "n°", "Permisos, certificados o declaraciones atrasadas."),
      ],
      priorityFocus: ["RILES fuera de límite", "RESPEL sin destino", "fuentes fijas", "documentos vencidos"],
      emptyStateGuidance: "Carga informes RILES, residuos, energía y combustibles para activar el control ambiental de planta.",
    },
    criticalDocuments: [
      "Informes de RILES",
      "Manifiestos SIDREP / RESPEL",
      "Registros SINADER",
      "Facturas de energía y combustibles",
      "Hojas de datos de seguridad",
      "RCA, permisos o planes de monitoreo",
    ],
    criticalVariables: ["pH", "temperatura RIL", "DBO5", "DQO", "SST", "kg RESPEL", "kWh", "m³ de agua"],
    regulations: ["DS 90 RILES", "DS 148 RESPEL", "SIDREP", "SINADER", "RETC / Ventanilla Única", "RCA"],
    riskSignals: ["Parámetro RIL sobre límite", "RESPEL sin destino final", "Monitoreo incompleto", "Sustancia peligrosa sin HDS"],
    recommendedActions: [
      "Cargar informe RILES mensual y comparar contra límites configurados.",
      "Validar manifiestos RESPEL con transportista, patente y destino.",
      "Cruzar energía y combustible contra producción mensual.",
    ],
    regulatoryOutputs: ["Reporte ambiental mensual de planta", "Preparación RETC", "Preparación SINADER", "Libro SIDREP / RESPEL", "Matriz RILES"],
    copilotQuestions: [
      "¿Qué procesos muestran desviaciones de consumo?",
      "¿Qué parámetros RILES están cerca del límite?",
      "¿Qué residuos tienen brechas de destino?",
      "¿Qué documentos faltan para preparar RETC?",
    ],
  },

  forestal_aserradero: {
    key: "forestal_aserradero",
    id: "forestal_aserradero",
    label: "Forestal / Aserradero",
    name: "Forestal y aserraderos",
    shortName: "Forestal / Aserradero",
    purpose:
      "Conectar predios, operaciones forestales, producción, energía, biomasa, transporte y residuos para trazabilidad operacional y ambiental.",
    dashboardBlueprint: {
      mainPain:
        "El rubro mezcla terreno, transporte, maquinaria, combustible, cosecha, caminos, biodiversidad, residuos, agua y trazabilidad de operación.",
      dashboardTitle: "Estado ambiental por predio y planta",
      dashboardSubtitle: "Trazabilidad forestal, producción, energía, biomasa, transporte y residuos.",
      operationalFocus: "Predio + faena + producción + transporte",
      starKpi: "kgCO₂e/m³ madera",
      sellableReportName: "Reporte ambiental por predio, faena, planta y transporte",
      requiredModules: [
        moduleItem("predios", "Predios / zonas", "Ubicación, superficie, especie y responsable."),
        moduleItem("operaciones", "Operaciones forestales", "Cosecha, raleo, poda y preparación de terreno."),
        moduleItem("maquinaria", "Maquinaria", "Skidders, harvesters, forwarders, motosierras y tractores."),
        moduleItem("combustible", "Combustible", "Litros por máquina, faena y operador."),
        moduleItem("transporte_madera", "Transporte de madera", "Origen, destino, km, camión y volumen."),
        moduleItem("produccion", "Producción", "m³ cosechados, toneladas y especie."),
        moduleItem("caminos", "Caminos y faenas", "Apertura, mantención y uso de maquinaria."),
        moduleItem("residuos", "Residuos", "Aceites, envases y restos operacionales."),
        moduleItem("agua_suelo", "Agua / suelo", "Registros básicos y zonas sensibles."),
        moduleItem("documentos", "Documentos", "Guías, facturas, certificados y fotos georreferenciadas."),
      ],
      kpiCards: [
        kpi("huella_predio", "Huella por predio", "tCO₂e", "Emisiones por predio o zona."),
        kpi("huella_m3_madera", "Huella por m³ de madera", "kgCO₂e/m³", "Intensidad por volumen producido."),
        kpi("combustible_faena", "Combustible por faena", "L/faena", "Consumo por operación forestal."),
        kpi("combustible_m3", "Combustible por m³", "L/m³", "Eficiencia por volumen."),
        kpi("transporte", "Emisiones por transporte", "tCO₂e/ruta", "Impacto por ruta forestal."),
        kpi("produccion", "Producción mensual", "m³", "Volumen mensual producido."),
        kpi("residuos", "Residuos generados", "kg/mes", "Residuos operacionales."),
        kpi("docs_faltantes", "Documentos faltantes", "n°", "Guías, fotos o certificados pendientes."),
      ],
      priorityFocus: ["trazabilidad de origen", "combustible por faena", "transporte forestal", "residuos operacionales"],
      emptyStateGuidance: "Carga predios, guías de madera, combustible, producción y transporte para activar el tablero forestal.",
    },
    criticalDocuments: ["Guías de despacho de madera", "Documentos de lote forestal", "Bitácoras de producción", "Facturas de energía y combustible", "Bitácoras de transporte", "Certificados de residuos"],
    criticalVariables: ["m³ de madera", "litros de combustible", "kWh", "ton biomasa", "km transporte", "kg residuos", "dB(A) ruido"],
    regulations: ["RETC / Ventanilla Única", "SINADER", "DS 38 ruido", "RCA si aplica", "Trazabilidad FSC si aplica"],
    riskSignals: ["Lotes sin origen documentado", "Biomasa acumulada", "Caldera sin bitácora", "Ruido industrial cercano al límite"],
    recommendedActions: ["Completar origen, especie y volumen por lote.", "Asociar energía y biomasa a producción.", "Documentar destino de subproductos y residuos."],
    regulatoryOutputs: ["Reporte ambiental por predio/faena", "Trazabilidad de transporte forestal", "Indicadores de energía por producción", "Matriz de residuos y destino"],
    copilotQuestions: ["¿Qué lotes tienen trazabilidad incompleta?", "¿Qué proceso consume más energía?", "¿Qué viajes forestales requieren respaldo?", "¿Qué residuos deberían valorizarse?"],
  },

  mineria: {
    key: "mineria",
    id: "mineria",
    label: "Minería",
    name: "Minería",
    shortName: "Minería",
    purpose: "Controlar faenas, RCA, agua, relaves, material particulado, combustible, energía, residuos, monitoreos y contratistas.",
    dashboardBlueprint: {
      mainPain: "Minería tiene alta presión regulatoria, RCA, monitoreos, agua, energía, combustibles, residuos, relaves, contratistas y comunidades.",
      dashboardTitle: "Estado ambiental de faena",
      dashboardSubtitle: "Cumplimiento, agua, relaves, monitoreos, contratistas y desempeño ambiental de faena.",
      operationalFocus: "Faena + RCA + maquinaria + agua + contratistas",
      starKpi: "tCO₂e/ton procesada",
      sellableReportName: "Reporte de cumplimiento y desempeño ambiental de faena minera",
      requiredModules: [
        moduleItem("faenas", "Faenas", "Mina, planta, botadero, campamento y caminos."),
        moduleItem("rca", "RCA / compromisos", "Obligaciones, frecuencia, responsable y evidencia."),
        moduleItem("maquinaria", "Maquinaria pesada", "Camiones, cargadores, perforadoras y excavadoras."),
        moduleItem("combustible", "Combustible", "Diésel por equipo, litros y rendimiento."),
        moduleItem("energia", "Energía", "kWh por proceso, área o contrato."),
        moduleItem("agua", "Agua", "Extracción, consumo, recirculación y descargas."),
        moduleItem("residuos", "Residuos", "Industriales, peligrosos, aceites, neumáticos y envases."),
        moduleItem("sustancias", "Sustancias peligrosas", "Reactivos, químicos y HDS."),
        moduleItem("monitoreos", "Monitoreos", "Aire, polvo, ruido, agua y biodiversidad si aplica."),
        moduleItem("contratistas", "Contratistas", "Emisiones y documentos por proveedor."),
      ],
      kpiCards: [
        kpi("huella_faena", "Huella total faena", "tCO₂e/mes", "Emisiones mensuales de la faena."),
        kpi("diesel_ton", "Diésel por tonelada movida", "L/ton", "Intensidad de combustible."),
        kpi("energia_ton", "Energía por tonelada procesada", "kWh/ton", "Eficiencia energética."),
        kpi("agua_ton", "Agua por tonelada procesada", "m³/ton", "Intensidad hídrica."),
        kpi("cumplimiento_rca", "Cumplimiento RCA", "%", "Compromisos cumplidos."),
        kpi("monitoreos", "Monitoreos pendientes", "n°", "Mediciones o reportes pendientes."),
        kpi("contratistas", "Emisiones por contratista", "tCO₂e/proveedor", "Impacto por proveedor."),
        kpi("respel", "Residuos peligrosos", "kg/mes", "RESPEL mensual."),
      ],
      priorityFocus: ["RCA", "agua", "relaves", "monitoreos", "contratistas"],
      emptyStateGuidance: "Carga compromisos RCA, consumo de agua, combustible, monitoreos y contratistas para activar el tablero minero.",
    },
    criticalDocuments: ["RCA y compromisos", "Registros hidrológicos", "Reportes de relaves", "Monitoreos MP10/MP2.5", "Facturas de combustible", "Certificados de residuos"],
    criticalVariables: ["m³ agua captada", "% recirculación", "m³ relaves", "MP10", "MP2.5", "litros de diésel", "kg RESPEL"],
    regulations: ["RCA", "SMA", "Sernageomin", "RETC / Ventanilla Única", "Ley REP si aplica"],
    riskSignals: ["Consumo hídrico sobre umbral", "Riesgo en depósito de relaves", "Peak de material particulado", "Monitoreos RCA atrasados"],
    recommendedActions: ["Configurar límites RCA de agua, polvo y relaves.", "Vincular reportes hidrológicos y relaves con evidencia.", "Crear alertas por monitoreos pendientes o peaks MP."],
    regulatoryOutputs: ["Reporte de cumplimiento y desempeño ambiental", "Tablero de obligaciones RCA", "Matriz de monitoreos", "Resumen de agua, energía y combustible"],
    copilotQuestions: ["¿Qué obligaciones RCA están en riesgo?", "¿Dónde se concentra el consumo de diésel?", "¿Qué monitoreos están pendientes?", "¿Qué contratistas explican mayor huella?"],
  },

  energia: {
    key: "energia",
    id: "energia",
    label: "Energía",
    name: "Energía y termoeléctricas",
    shortName: "Energía",
    purpose: "Controlar CEMS, chimeneas, gases regulados, combustible, cenizas, continuidad operacional e impuesto verde cuando aplique.",
    dashboardBlueprint: {
      mainPain: "La operación energética requiere monitoreo continuo de emisiones, combustible, fuentes fijas, mantención y cumplimiento de límites.",
      dashboardTitle: "Estado ambiental de generación",
      dashboardSubtitle: "CEMS, emisiones atmosféricas, combustible, continuidad y cumplimiento por unidad generadora.",
      operationalFocus: "CEMS + fuente fija + combustible + cumplimiento",
      starKpi: "kgCO₂e/MWh",
      sellableReportName: "Reporte ambiental de generación y monitoreo continuo",
      requiredModules: [
        moduleItem("cems", "CEMS", "Logs de chimenea, continuidad y contaminantes."),
        moduleItem("fuentes", "Fuentes fijas", "Calderas, turbinas, generadores y chimeneas."),
        moduleItem("combustible", "Combustible", "Consumo por unidad generadora."),
        moduleItem("energia", "Generación", "MWh generados y operación."),
        moduleItem("mantencion", "Mantenciones", "Eventos críticos y respaldo operacional."),
        moduleItem("documentos", "Documentos", "Reportes, certificados, bitácoras y permisos."),
      ],
      kpiCards: [
        kpi("co2_mwh", "CO₂ por MWh", "kgCO₂e/MWh", "Intensidad de generación."),
        kpi("so2", "SO₂", "mg/m³", "Concentración de dióxido de azufre."),
        kpi("nox", "NOx", "mg/m³", "Óxidos de nitrógeno."),
        kpi("opacidad", "Opacidad", "%", "Opacidad de humo."),
        kpi("continuidad", "Continuidad CEMS", "%", "Disponibilidad de datos."),
        kpi("combustible", "Combustible", "unidad/mes", "Consumo por unidad generadora."),
      ],
      priorityFocus: ["continuidad CEMS", "peaks SO₂/NOx", "combustible", "impuesto verde"],
      emptyStateGuidance: "Carga logs CEMS, combustible y generación para activar el tablero de energía.",
    },
    criticalDocuments: ["Logs CEMS", "Registros de combustible", "Mediciones de generación", "Bitácoras de mantención", "Monitoreos de emisiones", "RCA o permisos aplicables"],
    criticalVariables: ["CO₂ ppm", "SO₂ mg/m³", "NOx mg/m³", "opacidad %", "flujo m³/h", "combustible", "MWh generados"],
    regulations: ["CEMS", "RETC / Ventanilla Única", "Impuesto Verde", "RCA", "Normas de emisión aplicables"],
    riskSignals: ["Peak SO₂", "Peak NOx", "Brecha de continuidad CEMS", "Combustible sin conciliación"],
    recommendedActions: ["Validar continuidad de logs CEMS.", "Configurar límites por contaminante.", "Generar alertas ante peaks o pérdida de datos."],
    regulatoryOutputs: ["Reporte ambiental de generación", "Base impuesto verde", "Estado de monitoreos", "Resumen de cumplimiento RCA/RETC"],
    copilotQuestions: ["¿Hubo anomalías CEMS esta semana?", "¿Qué contaminante está más cerca del límite?", "¿Qué unidad generadora requiere revisión?", "¿Qué evidencias faltan para RETC?"],
  },

  acuicultura: {
    key: "acuicultura",
    id: "acuicultura",
    label: "Acuicultura",
    name: "Acuicultura y salmoneras",
    shortName: "Acuicultura",
    purpose: "Controlar INFFA, fondo marino, oxígeno, redox, antibióticos, mortalidad, escapes, residuos y compromisos ambientales.",
    dashboardBlueprint: {
      mainPain: "La acuicultura debe controlar fondo marino, tratamientos, biomasa, mortalidad, residuos, escapes y monitoreos sectoriales.",
      dashboardTitle: "Estado ambiental de centro acuícola",
      dashboardSubtitle: "INFFA, fondo marino, tratamientos, mortalidad, residuos y cumplimiento por centro.",
      operationalFocus: "Centro + jaula + fondo marino + tratamientos",
      starKpi: "gr antibiótico/ton biomasa",
      sellableReportName: "Reporte ambiental de centro acuícola",
      requiredModules: [
        moduleItem("centros", "Centros / jaulas", "Centro, jaula, biomasa y responsable."),
        moduleItem("inffa", "INFFA", "Oxígeno, redox, macrofauna y condición de fondo."),
        moduleItem("tratamientos", "Tratamientos", "Fármaco, gramos, biomasa y jaula."),
        moduleItem("mortalidad", "Mortalidad", "Biomasa retirada y destino."),
        moduleItem("residuos", "Residuos", "Residuos operacionales y destino."),
        moduleItem("documentos", "Documentos", "Informes, bitácoras, permisos y evidencias."),
      ],
      kpiCards: [
        kpi("oxigeno", "Oxígeno disuelto", "mg/L", "Condición del fondo."),
        kpi("redox", "Potencial redox", "mV", "Degradación orgánica."),
        kpi("antibioticos", "Antibióticos", "gr/ton", "Uso por biomasa."),
        kpi("mortalidad", "Mortalidad", "kg", "Biomasa muerta retirada."),
        kpi("escapes", "Escapes", "individuos", "Eventos de escape."),
      ],
      priorityFocus: ["INFFA", "fondo anaeróbico", "antibióticos", "escapes"],
      emptyStateGuidance: "Carga INFFA, tratamientos y biomasa para activar el tablero acuícola.",
    },
    criticalDocuments: ["Informes INFFA", "Bitácoras veterinarias", "Registros de alimento", "Registros de biomasa", "Certificados de residuos", "RCA o permisos sectoriales"],
    criticalVariables: ["oxígeno mg/L", "redox mV", "gr antibiótico/ton", "mortalidad kg", "escapes", "biomasa ton"],
    regulations: ["Sernapesca", "INFFA", "RCA", "Normativa sectorial acuícola"],
    riskSignals: ["Fondo marino anaeróbico", "Uso intensivo de antibióticos", "Escape de peces", "Monitoreos incompletos"],
    recommendedActions: ["Cargar INFFA por centro y jaula.", "Controlar tratamientos por biomasa.", "Crear protocolo ante escapes o fondo anaeróbico."],
    regulatoryOutputs: ["Reporte ambiental de centro", "Estado INFFA", "Matriz de tratamientos", "Resumen de obligaciones ambientales"],
    copilotQuestions: ["¿Qué centros tienen evidencia incompleta?", "¿Qué jaulas tienen peor condición de fondo?", "¿Qué tratamientos superan intensidad esperada?", "¿Qué monitoreos requieren seguimiento?"],
  },

  transporte: {
    key: "transporte",
    id: "transporte",
    label: "Transporte",
    name: "Empresas de transporte",
    shortName: "Transporte",
    purpose: "Trazar combustible, kilómetros, vehículos, rutas, carga, mantenciones, clientes y residuos REP para controlar la huella logística.",
    dashboardBlueprint: {
      mainPain: "El transporte tiene un dato rey: combustible + kilómetros + vehículo + ruta + carga.",
      dashboardTitle: "Huella logística de flota",
      dashboardSubtitle: "Emisiones por vehículo, viaje, cliente, ruta y rendimiento operacional.",
      operationalFocus: "Flota + combustible + GPS + clientes",
      starKpi: "kgCO₂e/km o kgCO₂e/viaje",
      sellableReportName: "Reporte de huella logística por vehículo, ruta y cliente",
      requiredModules: [
        moduleItem("flota", "Flota", "Camiones, camionetas, buses o maquinaria móvil."),
        moduleItem("conductores", "Conductores", "Responsable, turnos y asignación."),
        moduleItem("viajes", "Viajes", "Origen, destino, kilómetros, carga y cliente."),
        moduleItem("combustible", "Combustible", "Litros, estación, factura y vehículo."),
        moduleItem("gps", "GPS", "Rutas, km reales, desvíos y ralentí."),
        moduleItem("mantenciones", "Mantenciones", "Fechas, repuestos y rendimiento."),
        moduleItem("clientes", "Clientes", "Emisiones por servicio o contrato."),
        moduleItem("carga", "Carga transportada", "Toneladas, volumen y tipo de carga."),
        moduleItem("documentos", "Documentos", "Facturas, guías, hojas de ruta y respaldo GPS."),
        moduleItem("reportes", "Reportes", "Huella por vehículo, viaje, cliente y ruta."),
      ],
      kpiCards: [
        kpi("huella_flota", "Huella total flota", "tCO₂e/mes", "Emisiones mensuales de la flota."),
        kpi("vehiculo", "Emisiones por vehículo", "kgCO₂e/camión", "Impacto por unidad."),
        kpi("viaje", "Emisiones por viaje", "kgCO₂e/viaje", "Impacto por servicio."),
        kpi("cliente", "Emisiones por cliente", "tCO₂e/cliente", "Huella por contrato."),
        kpi("rendimiento", "Rendimiento", "km/L", "Eficiencia de combustible."),
        kpi("litros", "Litros consumidos", "L/mes", "Consumo mensual."),
        kpi("km", "Km recorridos", "km/mes", "Actividad logística."),
        kpi("ralenti", "Ralentí / uso improductivo", "horas", "Horas improductivas."),
        kpi("costo", "Costo combustible", "$/km", "Costo operacional por distancia."),
      ],
      priorityFocus: ["combustible", "km reales", "rutas", "mantenciones", "residuos REP"],
      emptyStateGuidance: "Carga flota, viajes, combustible y GPS para activar la huella logística.",
    },
    criticalDocuments: ["Facturas de combustible", "Documentos de ruta", "Hojas de ruta", "Respaldo GPS", "Bitácoras de mantención", "Registros de neumáticos y aceites"],
    criticalVariables: ["litros de diésel", "km recorridos", "km/L", "horas ralentí", "ton carga", "kg neumáticos", "kg aceites"],
    regulations: ["RETC", "Ley REP", "RCA si aplica"],
    riskSignals: ["Alto consumo de combustible", "Ruta sin trazabilidad", "Mantención pendiente", "Destino de residuos no documentado"],
    recommendedActions: ["Conciliar litros de diésel contra km y rutas.", "Actualizar mantenciones por vehículo.", "Vincular neumáticos y aceites a gestor autorizado."],
    regulatoryOutputs: ["Reporte de huella logística", "Indicadores de emisiones por km", "Matriz de trazabilidad de rutas", "Resumen REP de residuos aplicables"],
    copilotQuestions: ["¿Qué rutas tienen peor rendimiento?", "¿Qué vehículos tienen mantención pendiente?", "¿Qué cliente concentra más huella?", "¿Qué datos faltan para reportar emisiones logísticas?"],
  },
};

function moduleItem(id, name, description) {
  return {
    id,
    name,
    description,
    expectedData: description,
    whyItMatters: "Permite calcular indicadores, controlar riesgos y respaldar reportes ambientales.",
  };
}

function kpi(id, label, unit, description) {
  return {
    id,
    label,
    unit,
    description,
    sourceHint: "Requiere datos operacionales y documentos validados.",
    priority: "core",
  };
}

export default environmentalPresetMatrix;
>>>>>>> 5970f50377041bafdb1683dd81766dd712cf418f
