# Generated by Django 6.0.4 on 2026-05-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructora', models.CharField(max_length=180)),
                ('etapa_obra', models.CharField(max_length=180)),
                ('sensor', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('diesel_litros', 'Diesel litros'), ('gasolina_litros', 'Gasolina litros'), ('electricidad_kwh', 'Electricidad kWh'), ('horas_maquinaria', 'Horas maquinaria'), ('temperatura', 'Temperatura'), ('humedad', 'Humedad')], max_length=40)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidad', models.CharField(max_length=40)),
                ('co2e_estimado', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['fecha_registro'], name='iot_lectura_fecha_r_263a50_idx'), models.Index(fields=['sensor', 'fecha_registro'], name='iot_lectura_sensor_85a983_idx'), models.Index(fields=['constructora', 'fecha_registro'], name='iot_lectura_constru_f3498f_idx'), models.Index(fields=['tipo', 'fecha_registro'], name='iot_lectura_tipo_a3faf7_idx')],
            },
        ),
    ]
