# Generated by Django 5.2.5 on 2026-08-13 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_alter_etapaobra_options_and_more"),
        ("iot", "0003_organizacion_tenant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispositivosensor",
            options={"ordering": ["organizacion__nombre", "nombre"]},
        ),
        migrations.AlterField(
            model_name="dispositivosensor",
            name="organizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivos_iot",
                to="analytics.organizacion",
            ),
        ),
        migrations.AlterField(
            model_name="dispositivosensor",
            name="tipo_sensor",
            field=models.CharField(
                choices=[
                    ("combustible", "Combustible"),
                    ("energia", "Energia"),
                    ("maquinaria", "Maquinaria"),
                    ("agua", "Agua"),
                    ("gps", "GPS"),
                    ("ambiente", "Ambiente"),
                    ("mixto", "Mixto"),
                ],
                default="mixto",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="lecturasensor",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("diesel_litros", "Diesel litros"),
                    ("gasolina_litros", "Gasolina litros"),
                    ("electricidad_kwh", "Electricidad kWh"),
                    ("horas_maquinaria", "Horas maquinaria"),
                    ("horas_encendido", "Horas encendido"),
                    ("agua_litros", "Agua litros"),
                    ("gps_evento", "GPS evento"),
                    ("temperatura", "Temperatura"),
                    ("humedad", "Humedad"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="registrosensor",
            name="estado_procesamiento",
            field=models.CharField(
                choices=[
                    ("recibido", "Recibido"),
                    ("consolidado", "Consolidado como emision"),
                    ("solo_telemetria", "Solo telemetria"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="recibido",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="registrosensor",
            name="organizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_iot",
                to="analytics.organizacion",
            ),
        ),
        migrations.AlterField(
            model_name="registrosensor",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("diesel_litros", "Diesel litros"),
                    ("gasolina_litros", "Gasolina litros"),
                    ("electricidad_kwh", "Electricidad kWh"),
                    ("horas_maquinaria", "Horas maquinaria"),
                    ("horas_encendido", "Horas encendido"),
                    ("agua_litros", "Agua litros"),
                    ("gps_evento", "GPS evento"),
                    ("temperatura", "Temperatura"),
                    ("humedad", "Humedad"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="dispositivosensor",
            index=models.Index(
                fields=["organizacion", "activo"], name="iot_disposi_organiz_c639dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispositivosensor",
            index=models.Index(
                fields=["dispositivo_id"], name="iot_disposi_disposi_d63083_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispositivosensor",
            index=models.Index(
                fields=["tipo_sensor", "activo"], name="iot_disposi_tipo_se_bfacf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lecturasensor",
            index=models.Index(
                fields=["organizacion", "fecha_registro"],
                name="iot_lectura_organiz_7f9067_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrosensor",
            index=models.Index(
                fields=["organizacion", "timestamp_sensor"],
                name="iot_registr_organiz_4f0ea2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrosensor",
            index=models.Index(
                fields=["dispositivo", "timestamp_sensor"],
                name="iot_registr_disposi_930a4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrosensor",
            index=models.Index(
                fields=["tipo", "timestamp_sensor"], name="iot_registr_tipo_0cb957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrosensor",
            index=models.Index(
                fields=["estado_procesamiento"], name="iot_registr_estado__f4790d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrosensor",
            index=models.Index(
                fields=["external_id"], name="iot_registr_externa_f77ab8_idx"
            ),
        ),
    ]
