# Generated by Django 5.2.5 on 2026-08-14 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0025_alter_observacion_actividad_activooperacional_and_more"),
        ("iot", "0004_alter_dispositivosensor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivosensor",
            name="activo_operacional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensores",
                to="analytics.activooperacional",
            ),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="estado",
            field=models.CharField(
                choices=[
                    ("operativo", "Operativo"),
                    ("requiere_revision", "Requiere revision"),
                    ("fuera_servicio", "Fuera de servicio"),
                    ("calibracion_vencida", "Calibracion vencida"),
                ],
                db_index=True,
                default="operativo",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="fabricante",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="fecha_alta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="fuente_datos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensores",
                to="analytics.fuentedatos",
            ),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="modelo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="proceso_operacional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensores",
                to="analytics.procesooperacional",
            ),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="unidad_operacional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensores",
                to="analytics.unidadoperacional",
            ),
        ),
        migrations.CreateModel(
            name="CalibracionSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("tipo", models.CharField(max_length=100)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("aprobada", "Aprobada"),
                            (
                                "aprobada_con_observaciones",
                                "Aprobada con observaciones",
                            ),
                            ("rechazada", "Rechazada"),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "fecha_proxima_calibracion",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("responsable", models.CharField(blank=True, max_length=180)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibraciones_sensor",
                        to="analytics.evidenciaobra",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibraciones",
                        to="iot.dispositivosensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstalacionSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_instalacion", models.DateField()),
                ("fecha_retiro", models.DateField(blank=True, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=240)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("retirada", "Retirada"),
                            ("suspendida", "Suspendida"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("responsable", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instalaciones_sensor",
                        to="analytics.activooperacional",
                    ),
                ),
                (
                    "proceso_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instalaciones_sensor",
                        to="analytics.procesooperacional",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instalaciones",
                        to="iot.dispositivosensor",
                    ),
                ),
                (
                    "unidad_operacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instalaciones_sensor",
                        to="analytics.unidadoperacional",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_instalacion", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LecturaSensorV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("concepto", models.SlugField(max_length=120)),
                (
                    "valor_numerico",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("unidad", models.CharField(max_length=40)),
                ("metadata_tecnica", models.JSONField(blank=True, default=dict)),
                (
                    "calidad_tecnica",
                    models.CharField(
                        choices=[
                            ("valida", "Valida"),
                            ("requiere_revision", "Requiere revision"),
                        ],
                        default="valida",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lecturas_sensor",
                        to="analytics.actividadoperacional",
                    ),
                ),
                (
                    "observacion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lectura_sensor_v2",
                        to="analytics.observacion",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lecturas_v2",
                        to="iot.dispositivosensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
