# Generated by Django 5.2.5 on 2026-08-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0005_dispositivosensor_activo_operacional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrosensor",
            name="lectura_v2",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registro_ingesta",
                to="iot.lecturasensorv2",
            ),
        ),
        migrations.AlterField(
            model_name="lecturasensor",
            name="co2e_estimado",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="registrosensor",
            name="co2e_estimado",
            field=models.DecimalField(
                blank=True, decimal_places=3, editable=False, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="registrosensor",
            name="estado_procesamiento",
            field=models.CharField(
                choices=[
                    ("recibido", "Recibido"),
                    ("consolidado", "Consolidado como emision"),
                    ("solo_telemetria", "Solo telemetria"),
                    ("hecho_operacional", "Hecho operacional V2"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="recibido",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="registrosensor",
            name="factor_emision_usado",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
