# Generated by Django 6.0.4 on 2026-08-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0042_aplicabilidadcapacidadobra_and_more"),
        ("iot", "0006_registrosensor_lectura_v2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivosensor",
            name="ambito_operacional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("energia", "Energia"),
                    ("agua", "Agua"),
                    ("combustibles", "Combustibles"),
                    ("transporte", "Transporte"),
                    ("materiales", "Materiales"),
                    ("residuos", "Residuos"),
                    ("ruido", "Ruido"),
                    ("hidrica-suelo", "Hidrica y suelo"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="dispositivosensor",
            name="punto_ambiental",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensores",
                to="analytics.puntoambientaloperacional",
            ),
        ),
    ]
