import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, CalendarDays, Factory, Gauge, Leaf, TrendingDown, TrendingUp } from "lucide-react";
import { formatNumber, formatPercent } from "@/shared/utils/formatters";
import { REPORT_CATEGORY_COLORS } from "../utils/reportAdapters";

const emission = (value) => value === null || value === undefined ? "Sin datos" : `${formatNumber(value)} kg CO2e`;
const KPI_TONES = { rose: ["border-rose-200", "bg-rose-500"], emerald: ["border-emerald-200", "bg-emerald-500"], orange: ["border-orange-200", "bg-orange-500"], amber: ["border-amber-200", "bg-amber-500"], blue: ["border-blue-200", "bg-blue-500"], slate: ["border-slate-200", "bg-slate-500"] };
const trend = (variation) => variation === null ? { label: "Sin comparación", tone: "text-slate-700", Icon: Gauge } : variation > 0 ? { label: "Al alza", tone: "text-rose-700", Icon: TrendingUp } : variation < 0 ? { label: "A la baja", tone: "text-emerald-700", Icon: TrendingDown } : { label: "Sin variación", tone: "text-slate-700", Icon: Gauge };

export function ExecutiveSummary({ report, workName }) {
  const behavior = trend(report.variation);
  const title = !report.records ? "Aún no existe una lectura de emisiones para este período" : report.variation === null ? "La obra ya cuenta con una base ambiental consolidada" : report.variation > 0 ? "Las emisiones recientes aumentaron y requieren atención" : report.variation < 0 ? "Las emisiones recientes disminuyeron" : "Las emisiones recientes se mantienen estables";
  return <section className="grid gap-6 rounded-[28px] border border-emerald-100 bg-white p-6 shadow-[0_18px_48px_rgba(15,23,42,0.07)] xl:grid-cols-[1.35fr_0.65fr]">
    <div><p className="text-xs font-black uppercase tracking-[0.15em] text-emerald-700">Resumen ejecutivo</p><h2 className="mt-2 max-w-3xl text-2xl font-black leading-tight sm:text-3xl">{title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]">{report.records ? `${workName} registra ${emission(report.total)} en ${report.records} resultados ambientales trazables dentro del período seleccionado.` : `No hay resultados en kg CO2e disponibles para ${workName} bajo el filtro actual. La ausencia de datos no se interpreta como cero.`}</p>
      <ul className="mt-5 space-y-2 text-sm text-[var(--text-secondary)]">
        <li className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />{report.dominantSource ? `La fuente prioritaria es ${report.dominantSource.name}, con ${formatPercent(report.dominantSource.percentage)} del total.` : "No hay una fuente prioritaria determinable."}</li>
        <li className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-500" />{report.dominantCategory ? `${report.dominantCategory.name} concentra la mayor contribución ambiental del período.` : "No existe distribución por categoría disponible."}</li>
        <li className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-indigo-500" />{report.excludedRecords ? `${report.excludedRecords} resultados con otras unidades quedaron fuera de la suma para no mezclar magnitudes.` : "Todos los resultados incluidos utilizan una unidad compatible con CO2e."}</li>
      </ul>
    </div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1">
      <SummarySignal label="Comportamiento reciente" value={behavior.label} tone={behavior.tone} />
      <SummarySignal label="Fuente prioritaria" value={report.dominantSource?.name || "Sin datos"} tone="text-blue-700" />
      <SummarySignal label="Etapa prioritaria" value="Sin etapa informada" tone="text-slate-700" />
      <SummarySignal label="Período con mayor emisión" value={report.peak?.label || "Sin datos"} tone="text-orange-700" />
    </div>
  </section>;
}

function SummarySignal({ label, value, tone }) { return <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface-subtle)] px-4 py-3"><p className="text-[10px] font-black uppercase tracking-[0.12em] text-[var(--text-muted)]">{label}</p><p className={`mt-1 font-black ${tone}`}>{value}</p></div>; }

export function ReportKpis({ report }) {
  const behavior = trend(report.variation);
  const rows = [
    { label: "Emisiones del período", value: emission(report.total), helper: `${report.records} resultados`, icon: Leaf, color: "rose" },
    { label: "Comportamiento reciente", value: behavior.label, helper: report.variation === null ? "Se requieren dos períodos" : `${formatPercent(Math.abs(report.variation))} vs. mes anterior`, icon: behavior.Icon, color: report.variation > 0 ? "rose" : "emerald" },
    { label: "Período con mayor emisión", value: report.peak?.label || "Sin datos", helper: emission(report.peak?.value), icon: CalendarDays, color: "orange" },
    { label: "Fuente prioritaria", value: report.dominantSource?.name || "Sin datos", helper: emission(report.dominantSource?.value), icon: AlertTriangle, color: "amber" },
    { label: "Etapa prioritaria", value: "Sin etapa informada", helper: "El contrato actual no expone esta dimensión", icon: Factory, color: "blue" },
    { label: "Emisión promedio", value: emission(report.average), helper: "Promedio por período agrupado", icon: Gauge, color: "slate" },
  ];
  return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map(({ icon: Icon, ...row }) => <article key={row.label} className={`relative overflow-hidden rounded-[22px] border ${KPI_TONES[row.color][0]} bg-white p-5 shadow-[0_12px_34px_rgba(15,23,42,0.06)]`}><span className={`absolute inset-x-0 top-0 h-1 ${KPI_TONES[row.color][1]}`} /><div className="flex items-center gap-2 text-[var(--text-muted)]"><Icon size={18} aria-hidden="true" /><p className="text-[10px] font-black uppercase tracking-[0.13em]">{row.label}</p></div><p className="mt-5 text-xl font-black leading-tight">{row.value}</p><p className="mt-2 text-xs text-[var(--text-muted)]">{row.helper}</p></article>)}</section>;
}

export function CategoryGrid({ categories, total }) { return <section><Heading eyebrow="Estado de emisiones" title="Distribución ambiental por categoría" description="Las categorías se ordenan por contribución sin mezclar unidades ambientales incompatibles." /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map((row) => <article key={row.name} className="relative overflow-hidden rounded-[20px] border border-[var(--border-default)] bg-white p-5 text-center shadow-sm"><span className="absolute inset-x-0 top-0 h-1" style={{ background: REPORT_CATEGORY_COLORS[row.name] }} /><p className="text-[10px] font-black uppercase tracking-[0.13em] text-[var(--text-muted)]">{row.name}</p><p className="mt-4 text-xl font-black" style={{ color: REPORT_CATEGORY_COLORS[row.name] }}>{emission(row.value)}</p><p className="mt-2 text-xs font-bold text-[var(--text-secondary)]">{total > 0 ? formatPercent(row.percentage) : "0%"} del período</p></article>)}</div></section>; }

export function SourceParticipation({ report }) {
  const pie = report.sources.filter((row) => row.value > 0);
  return <section className="rounded-[26px] border border-sky-100 bg-gradient-to-br from-white via-sky-50/40 to-white p-6 shadow-sm"><Heading eyebrow="Lectura visual" title="Participación de emisiones por fuente" description="El tamaño de cada segmento representa su contribución relativa dentro del período seleccionado." badge={report.dominantSource ? `Fuente dominante: ${report.dominantSource.name}` : undefined} /><div className="mt-5 grid items-center gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div className="relative h-72">{pie.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={72} outerRadius={106} paddingAngle={1}>{pie.map((row) => <Cell key={row.name} fill={REPORT_CATEGORY_COLORS[row.category] || "#64748b"} />)}</Pie><Tooltip formatter={(value) => emission(value)} /></PieChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-[var(--text-muted)]">Sin distribución disponible</div>}<div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)]">Total</span><b className="mt-1 text-lg">{formatNumber(report.total)}</b><span className="text-xs text-[var(--text-muted)]">kg CO2e</span></div></div><div className="space-y-3">{report.sources.slice(0, 6).map((row) => <div key={row.name} className="rounded-2xl border border-[var(--border-default)] bg-white p-4"><div className="flex items-start justify-between gap-3"><div><b>{row.name}</b><p className="text-xs text-[var(--text-muted)]">{row.category}</p></div><div className="text-right"><b>{emission(row.value)}</b><p className="text-xs text-[var(--text-muted)]">{formatPercent(row.percentage)}</p></div></div><Progress value={row.percentage} color={REPORT_CATEGORY_COLORS[row.category]} /></div>)}</div></div></section>;
}

export function CriticalSources({ report }) { return <section><Heading eyebrow="Fuentes críticas" title="Top 5 fuentes de mayor impacto" description="Estos focos concentran la mayor contribución y orientan las primeras decisiones de reducción." badge={`${Math.min(5, report.sources.length)} focos`} /><div className="mt-4 grid gap-4 lg:grid-cols-5">{report.sources.slice(0, 5).map((row, index) => <article key={row.name} className="relative overflow-hidden rounded-[22px] border border-[var(--border-default)] bg-white p-5 text-center shadow-sm"><span className="absolute inset-x-0 top-0 h-1" style={{ background: REPORT_CATEGORY_COLORS[row.category] }} /><span className="inline-flex h-9 w-9 items-center justify-center rounded-xl border text-sm font-black" style={{ color: REPORT_CATEGORY_COLORS[row.category], borderColor: `${REPORT_CATEGORY_COLORS[row.category]}55` }}>#{index + 1}</span><p className="mt-4 text-[10px] font-black uppercase tracking-[0.13em] text-[var(--text-muted)]">{row.category}</p><h3 className="mt-2 text-lg font-black" style={{ color: REPORT_CATEGORY_COLORS[row.category] }}>{row.name}</h3><p className="mt-2 text-sm font-bold">{emission(row.value)}</p><Progress value={row.percentage} color={REPORT_CATEGORY_COLORS[row.category]} /><p className="mt-2 text-xs font-bold">{formatPercent(row.percentage)} del total</p></article>)}</div></section>; }

export function ReportCharts({ report }) { const categoryData = report.categories.filter((row) => row.value > 0); return <section className="grid gap-4 xl:grid-cols-2"><Chart title="Emisiones en el tiempo" description="Evolución mensual de los resultados filtrados."><ResponsiveContainer width="100%" height="100%"><AreaChart data={report.timeline} margin={{ top: 15, right: 10, left: 5, bottom: 5 }}><defs><linearGradient id="reportArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0891b2" stopOpacity={0.4} /><stop offset="100%" stopColor="#0891b2" stopOpacity={0.03} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" /><YAxis tickFormatter={(value) => formatNumber(value, 0)} width={68} /><Tooltip formatter={(value) => emission(value)} /><Area type="monotone" dataKey="value" name="Emisiones" stroke="#0891b2" strokeWidth={3} fill="url(#reportArea)" /></AreaChart></ResponsiveContainer></Chart><Chart title="Emisiones por categoría" description="Comparación para detectar el foco ambiental principal."><ResponsiveContainer width="100%" height="100%"><BarChart data={categoryData} margin={{ top: 15, right: 10, left: 5, bottom: 5 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" interval={0} angle={-15} textAnchor="end" height={58} /><YAxis tickFormatter={(value) => formatNumber(value, 0)} width={68} /><Tooltip formatter={(value) => emission(value)} /><Bar dataKey="value" name="Emisiones" radius={[8, 8, 0, 0]}>{categoryData.map((row) => <Cell key={row.name} fill={REPORT_CATEGORY_COLORS[row.name]} />)}</Bar></BarChart></ResponsiveContainer></Chart></section>; }

function Chart({ title, description, children }) { return <article className="rounded-[24px] border border-[var(--border-default)] bg-white p-5 shadow-sm"><h3 className="text-lg font-black">{title}</h3><p className="mt-1 text-xs text-[var(--text-muted)]">{description}</p><div className="mt-5 h-80">{children}</div></article>; }
function Progress({ value, color }) { return <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${Math.min(100, Math.max(0, value))}%`, background: color }} /></div>; }
function Heading({ eyebrow, title, description, badge }) { return <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-emerald-700">{eyebrow}</p><h2 className="mt-1 text-xl font-black">{title}</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-[var(--text-muted)]">{description}</p></div>{badge && <span className="rounded-full border border-sky-200 bg-sky-50 px-3 py-2 text-xs font-black text-sky-800">{badge}</span>}</div>; }
