import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Download } from "lucide-react";
import { useAuth } from "@/features/auth/context/AuthContext";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { closeDossier, generateDossierReport, getDossier, getEnvironmentalAudit, reopenDossier, reportPdfUrl, validateProfessionalReport } from "../api/professionalV2Api";
import { Alert, Button, Card, CardContent, EmptyState, ErrorState, LoadingState, Modal, PageHeader, Textarea } from "@/shared/ui";
import ConfirmationModal from "@/shared/components/ConfirmationModal";
import { formatDateTime } from "@/shared/utils/formatters";
import { human, isProfessionalValidation, Section, State } from "../components/GovernanceShared";
const REFERENCE_GROUPS = [["Evidencias", "evidencias"], ["Observaciones", "observaciones"], ["Alcances", "alcance"], ["Indicadores", "indicadores"], ["Actividades", "actividades"], ["Cálculos", "calculos"], ["Impactos", "impactos"], ["Discrepancias", "discrepancias"], ["Acciones", "acciones"], ["Ciclos", "ciclos"], ["Snapshots", "snapshots"], ["Resultados", "resultados"], ["Propuestas de IA", "propuestas_ia"], ["Decisiones humanas", "decisiones_humanas"], ["Revisiones", "revisiones"], ["Correcciones", "correcciones"]];
export default function DossierDetailPage() {
  const { dossierId } = useParams(); const { activeOrganizacionId } = useOrganizacionActiva(); const { user } = useAuth(); const [state, setState] = useState({ scopeKey: "", dossier: { status: "loading", data: null }, audit: { status: "loading", data: [] } }); const [mutationError, setMutationError] = useState(""); const [confirm, setConfirm] = useState(null); const [reopen, setReopen] = useState(""); const [busy, setBusy] = useState(false); const requestRef = useRef(0);
  const load = useCallback(async () => { if (!activeOrganizacionId || !dossierId) return; const scopeKey = `${activeOrganizacionId}:${dossierId}`; const requestId = ++requestRef.current; setState({ scopeKey, dossier: { status: "loading", data: null }, audit: { status: "loading", data: [] } }); const [dossier, audit] = await Promise.allSettled([getDossier(activeOrganizacionId, dossierId), getEnvironmentalAudit(activeOrganizacionId)]); if (requestRef.current !== requestId) return; setState({ scopeKey, dossier: dossier.status === "fulfilled" ? { status: "ready", data: dossier.value } : { status: "error", data: null }, audit: audit.status === "fulfilled" ? { status: "ready", data: audit.value } : { status: "error", data: [] } }); }, [activeOrganizacionId, dossierId]);
  useEffect(() => { load(); return () => { requestRef.current += 1; }; }, [load]); async function mutate(call) { setBusy(true); setMutationError(""); try { await call(); setConfirm(null); setReopen(""); await load(); } catch (error) { setMutationError(error.response?.data?.detail || "No se pudo completar la operación."); } finally { setBusy(false); } }
  const requestedScopeKey = activeOrganizacionId && dossierId ? `${activeOrganizacionId}:${dossierId}` : ""; if (state.scopeKey !== requestedScopeKey || state.dossier.status === "loading") return <LoadingState label="Cargando expediente" />; if (state.dossier.status === "error") return <ErrorState description="No se pudo cargar el expediente solicitado." onRetry={load} />;
  const item = state.dossier.data; const refs = item.referencias || {}; const latestReview = item.ultima_revision; const professionallyValidated = isProfessionalValidation(latestReview); const dossierAudit = state.audit.data.filter((event) => event.entidad === "ExpedienteAmbiental" && String(event.referencia) === String(item.id)); const work = refs.obra; const referenceCount = REFERENCE_GROUPS.reduce((total, [, key]) => total + (Array.isArray(refs[key]) ? refs[key].length : 0), 0);
  return <main className="space-y-8"><PageHeader eyebrow="Gobernanza · Expediente" title={item.problematica_titulo || `Expediente #${item.id}`} description={`Expediente #${item.id} · Versión ${item.version}. Paquete gobernado de antecedentes del problema.`} status={<State value={item.estado} />} actions={!user?.is_demo && (item.estado === "cerrado" ? <Button variant="secondary" onClick={() => setReopen(" ")}>Reabrir</Button> : <Button variant="danger" onClick={() => setConfirm("close")}>Cerrar expediente</Button>)} />{user?.is_demo && <Alert title="Solo lectura en modo demo">El expediente y sus decisiones pueden revisarse, pero las acciones formales están deshabilitadas.</Alert>}{mutationError && <Alert tone="danger">{String(mutationError)}</Alert>}
    <Section title="Estado" description="El estado del expediente y la validación profesional son dimensiones distintas."><div className="grid gap-3 md:grid-cols-3"><Info label="Estado del expediente" value={<State value={item.estado} />} /><Info label="Validación profesional" value={latestReview ? <><State value={latestReview.estado} /><p className="mt-1 text-xs text-[var(--text-muted)]">{professionallyValidated ? "Decisión profesional registrada" : "No equivale a validación profesional"}</p></> : "Sin revisión profesional registrada"} /><Info label="Antecedentes referenciados" value={referenceCount} /></div></Section>
    <Section title="Alcance"><div className="grid gap-3 md:grid-cols-2"><Info label="Problema" value={<Link className="font-bold text-[var(--brand-primary)]" to={`/inteligencia/problemas/${item.problematica}`}>{item.problematica_titulo || `Problema #${item.problematica}`}</Link>} /><Info label="Unidad" value={work?.nombre ? `${work.nombre}${work.codigo ? ` · ${work.codigo}` : ""}` : "Sin unidad vinculada en el expediente"} /></div></Section>
    <Section title="Antecedentes" description="Se muestran las relaciones que el expediente congeló al crearse; los IDs no se presentan como contenido principal.">{referenceCount === 0 ? <EmptyState title="Sin antecedentes referenciados" description="El contrato no entrega antecedentes vinculados para este expediente." /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{REFERENCE_GROUPS.map(([label, key]) => <Info key={key} label={label} value={Array.isArray(refs[key]) ? refs[key].length : 0} />)}</div>}</Section>
    <Section title="Revisión y decisiones">{latestReview ? <Card><CardContent><div className="flex flex-wrap items-start justify-between gap-3"><div><b>Última revisión profesional</b><p className="mt-1 text-sm text-[var(--text-muted)]">{latestReview.profesional || "Profesional no informado"}{latestReview.fecha ? ` · ${formatDateTime(latestReview.fecha)}` : ""}</p></div><State value={latestReview.estado} /></div></CardContent></Card> : <EmptyState title="Sin revisión profesional" description="Completar o cerrar un expediente no implica una validación profesional." />}</Section>
    <Section title="Informe vigente" description="Cada generación crea una nueva versión; no sobrescribe la anterior." action={!user?.is_demo && <Button onClick={() => setConfirm("generate")}>Generar nueva versión</Button>}>{item.informe_vigente ? <Card><CardContent><div className="flex flex-wrap justify-between gap-4"><div><b>Informe v{item.informe_vigente.version}</b><p className="mt-1"><State value={item.informe_vigente.estado} /></p><p className="mt-2 font-mono text-xs text-[var(--text-muted)]">SHA-256 {shortHash(item.informe_vigente.checksum)}</p></div><div className="flex flex-wrap items-center gap-3"><a className="inline-flex items-center gap-2 font-bold text-[var(--brand-primary)]" href={reportPdfUrl(activeOrganizacionId, item.informe_vigente.id)}><Download size={16} aria-hidden="true" />Descargar PDF</a>{!user?.is_demo && item.informe_vigente.estado !== "validado" && <Button onClick={() => setConfirm("validate")}>Validar informe</Button>}</div></div></CardContent></Card> : <EmptyState title="Sin informe generado" description="El expediente puede existir sin un informe vigente." />}</Section>
    <Section title="Historial" description="Eventos registrados sin ofrecer edición o borrado."><div className="space-y-2"><History label="Expediente creado" date={item.created_at} />{item.cerrado_at && <History label="Expediente cerrado" date={item.cerrado_at} />}{item.reabierto_at && <History label="Expediente reabierto" date={item.reabierto_at} detail={item.motivo_reapertura} />}{state.audit.status === "error" ? <ErrorState description="No fue posible cargar la auditoría. El resto del expediente permanece disponible." /> : dossierAudit.map((event) => <History key={event.id} label={human(event.tipo)} date={event.timestamp} detail={event.resumen} actor={event.actor_nombre || "Sistema"} />)}</div></Section>
    {confirm && <ConfirmationModal title={confirm === "close" ? "Cerrar expediente" : confirm === "validate" ? "Validar informe" : "Generar nueva versión"} description={confirm === "close" ? "El cierre quedará registrado en el historial del expediente." : confirm === "validate" ? "La validación del informe quedará registrada y no sobrescribirá versiones anteriores." : "Se generará una nueva versión del informe; la anterior permanecerá histórica."} confirmLabel="Confirmar" loading={busy} onCancel={() => setConfirm(null)} onConfirm={() => mutate(() => confirm === "close" ? closeDossier(activeOrganizacionId, dossierId) : confirm === "validate" ? validateProfessionalReport(activeOrganizacionId, item.informe_vigente.id) : generateDossierReport(activeOrganizacionId, dossierId))} />}
    <Modal open={Boolean(reopen)} title="Reabrir expediente" description="La reapertura conserva el cierre anterior y registra un nuevo evento." onClose={() => setReopen("")} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setReopen("")}>Cancelar</Button><Button loading={busy} disabled={!reopen.trim()} onClick={() => mutate(() => reopenDossier(activeOrganizacionId, dossierId, reopen.trim()))}>Reabrir</Button></div>}><Textarea label="Motivo de reapertura" required rows={4} value={reopen.trimStart()} onChange={(event) => setReopen(event.target.value)} /></Modal>
  </main>;
}
function Info({ label, value }) { return <Card><CardContent><p className="text-xs font-bold uppercase text-[var(--text-muted)]">{label}</p><div className="mt-1 font-semibold">{value ?? "Sin datos"}</div></CardContent></Card>; }
function History({ label, date, detail, actor }) { return <Card><CardContent><div className="flex flex-wrap justify-between gap-2"><b>{label}</b><span className="text-xs text-[var(--text-muted)]">{formatDateTime(date)}</span></div>{detail && <p className="mt-1 text-sm">{detail}</p>}{actor && <p className="mt-1 text-xs text-[var(--text-muted)]">{actor}</p>}</CardContent></Card>; }
function shortHash(value) { return value ? `${value.slice(0, 8)}…${value.slice(-6)}` : "Sin checksum"; }
