import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, BookOpenCheck, ClipboardCheck, Database, FileCheck2, ShieldCheck } from "lucide-react";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { getDiscrepancies, getDossiers, getProfessionalReviews } from "../api/professionalV2Api";
import { Card, CardContent, LoadingState, PageHeader } from "@/shared/ui";
import { DossierLink, State, isOpenDiscrepancy, reviewReference } from "../components/GovernanceShared";
const resource = (status = "loading", data = []) => ({ status, data });
function Metric({ label, resourceState, value, to }) { const content = resourceState.status === "loading" ? "Cargando…" : resourceState.status === "error" ? "No disponible" : value; return <Link to={to} className="block rounded-[var(--radius-lg)] focus-visible:outline-none focus-visible:shadow-[var(--focus-ring)]"><Card className="h-full transition hover:border-[var(--brand-primary)]"><CardContent><p className="text-sm font-bold text-[var(--text-muted)]">{label}</p><p className="mt-1 text-3xl font-black">{content}</p></CardContent></Card></Link>; }
export default function GovernanceOverviewPage() {
  const { activeOrganizacionId } = useOrganizacionActiva(); const [state, setState] = useState({ scopeKey: "", reviews: resource(), discrepancies: resource(), dossiers: resource() }); const requestRef = useRef(0);
  useEffect(() => { if (!activeOrganizacionId) return undefined; const scopeKey = String(activeOrganizacionId); const requestId = ++requestRef.current; setState({ scopeKey, reviews: resource(), discrepancies: resource(), dossiers: resource() }); Promise.allSettled([getProfessionalReviews(activeOrganizacionId, { estado: "pendiente" }), getDiscrepancies(activeOrganizacionId), getDossiers(activeOrganizacionId)]).then(([reviews, discrepancies, dossiers]) => { if (requestRef.current !== requestId) return; setState({ scopeKey, reviews: reviews.status === "fulfilled" ? resource("ready", reviews.value) : resource("error"), discrepancies: discrepancies.status === "fulfilled" ? resource("ready", discrepancies.value) : resource("error"), dossiers: dossiers.status === "fulfilled" ? resource("ready", dossiers.value) : resource("error") }); }); return () => { requestRef.current += 1; }; }, [activeOrganizacionId]);
  const requestedScopeKey = activeOrganizacionId ? String(activeOrganizacionId) : ""; if (state.scopeKey !== requestedScopeKey) return <LoadingState label="Cargando gobernanza" />;
  const openDiscrepancies = state.discrepancies.status === "ready" ? state.discrepancies.data.filter(isOpenDiscrepancy) : []; const activeDossiers = state.dossiers.status === "ready" ? state.dossiers.data.filter((item) => item.estado !== "cerrado") : [];
  const attention = []; if (state.reviews.status === "ready") state.reviews.data.forEach((review) => attention.push({ kind: "review", item: review })); if (state.discrepancies.status === "ready") openDiscrepancies.forEach((item) => attention.push({ kind: "discrepancy", item })); if (state.dossiers.status === "ready") state.dossiers.data.filter((item) => item.estado === "requiere_antecedentes").forEach((item) => attention.push({ kind: "dossier", item })); const visibleAttention = attention.slice(0, 5);
  const resources = [state.reviews, state.discrepancies, state.dossiers]; const anyLoading = resources.some((item) => item.status === "loading"); const anyError = resources.some((item) => item.status === "error"); const allReady = resources.every((item) => item.status === "ready");
  return <main className="space-y-7"><PageHeader eyebrow="Gobernanza ambiental" title="Gobernanza" description="Revisa decisiones, discrepancias y antecedentes que necesitan validación." />
    <section className="grid gap-4 md:grid-cols-3" aria-label="Resumen de gobernanza"><Metric label="Revisiones pendientes" resourceState={state.reviews} value={state.reviews.data.length} to="/gobernanza/revision" /><Metric label="Discrepancias abiertas" resourceState={state.discrepancies} value={openDiscrepancies.length} to="/gobernanza/calidad" /><Metric label="Expedientes activos" resourceState={state.dossiers} value={activeDossiers.length} to="/gobernanza/expedientes" /></section>
    <section className="space-y-3"><div><h2 className="text-xl font-black">Requiere atención</h2><p className="text-sm text-[var(--text-muted)]">Trabajo formal que hoy necesita revisión o antecedentes.</p></div>{anyLoading && !visibleAttention.length ? <LoadingState inline label="Revisando pendientes" /> : !visibleAttention.length && anyError ? <Card><CardContent><p className="font-bold">Atención no completamente disponible.</p><p className="mt-1 text-sm text-[var(--text-muted)]">Uno o más recursos no pudieron verificarse. Los recursos disponibles siguen visibles.</p></CardContent></Card> : !visibleAttention.length && allReady ? <Card><CardContent><p className="font-bold">No hay elementos pendientes registrados.</p><p className="mt-1 text-sm text-[var(--text-muted)]">Esto no certifica que todo esté validado.</p></CardContent></Card> : <div className="grid gap-3">{visibleAttention.map(({ kind, item }) => { if (kind === "review") { const ref = reviewReference(item); return <Link key={`r-${item.id}`} to="/gobernanza/revision" className="rounded-[var(--radius-lg)] focus-visible:outline-none focus-visible:shadow-[var(--focus-ring)]"><Card><CardContent className="flex flex-wrap items-center justify-between gap-3"><div><b>{ref.title}</b><p className="text-sm text-[var(--text-muted)]">Revisión profesional pendiente</p></div><State value={item.estado} /></CardContent></Card></Link>; } if (kind === "discrepancy") return <Link key={`d-${item.id}`} to="/gobernanza/calidad" className="rounded-[var(--radius-lg)] focus-visible:outline-none focus-visible:shadow-[var(--focus-ring)]"><Card><CardContent className="flex flex-wrap items-center justify-between gap-3"><div><b>{item.concepto || `Discrepancia #${item.id}`}</b><p className="text-sm text-[var(--text-muted)]">Dato que requiere revisión</p></div><State value={item.estado} /></CardContent></Card></Link>; return <Card key={`e-${item.id}`}><CardContent className="flex flex-wrap items-center justify-between gap-3"><div><DossierLink id={item.id}>{item.problematica_titulo || `Expediente #${item.id}`}</DossierLink><p className="text-sm text-[var(--text-muted)]">Faltan antecedentes para continuar</p></div><State value={item.estado} /></CardContent></Card>; })}</div>}</section>
    <section className="grid gap-4 lg:grid-cols-3"><Card><CardContent><div className="flex items-center gap-2"><ClipboardCheck size={18} aria-hidden="true" /><h2 className="font-black">Revisión profesional</h2></div><p className="mt-2 text-sm text-[var(--text-muted)]">Decisiones formales y hallazgos registrados por personas autorizadas.</p><Link className="mt-4 inline-flex font-bold text-[var(--brand-primary)]" to="/gobernanza/revision">Ver revisiones</Link></CardContent></Card><Card><CardContent><div className="flex items-center gap-2"><AlertTriangle size={18} aria-hidden="true" /><h2 className="font-black">Calidad y discrepancias</h2></div><p className="mt-2 text-sm text-[var(--text-muted)]">{state.discrepancies.status === "error" ? "No disponible." : `${openDiscrepancies.length} discrepancias abiertas registradas.`}</p><Link className="mt-4 inline-flex font-bold text-[var(--brand-primary)]" to="/gobernanza/calidad">Revisar calidad</Link></CardContent></Card><Card><CardContent><div className="flex items-center gap-2"><FileCheck2 size={18} aria-hidden="true" /><h2 className="font-black">Expedientes recientes</h2></div>{state.dossiers.status === "error" ? <p className="mt-2 text-sm text-[var(--text-muted)]">No disponible.</p> : state.dossiers.data.slice(0, 3).map((item) => <p key={item.id} className="mt-2 text-sm"><DossierLink id={item.id}>{item.problematica_titulo || `Expediente #${item.id}`}</DossierLink></p>)}<Link className="mt-4 inline-flex font-bold text-[var(--brand-primary)]" to="/gobernanza/expedientes">Ver expedientes</Link></CardContent></Card></section>
    <section className="space-y-3"><h2 className="text-lg font-black">Herramientas de control</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Quick icon={Database} to="/gobernanza/factores" label="Factores y metodologías" /><Quick icon={ShieldCheck} to="/gobernanza/auditoria" label="Auditoría" /><Quick icon={BookOpenCheck} to="/gobernanza/conocimiento" label="Conocimiento" /><Quick icon={FileCheck2} to="/gobernanza/informes" label="Informes" /></div></section>
  </main>;
}
function Quick({ icon: Icon, to, label }) { return <Link className="flex items-center gap-3 rounded-[var(--radius-lg)] border border-[var(--border-default)] bg-[var(--bg-surface)] p-4 text-sm font-bold focus-visible:outline-none focus-visible:shadow-[var(--focus-ring)]" to={to}><Icon size={18} aria-hidden="true" />{label}</Link>; }
