import { useCallback,useEffect,useMemo,useState } from "react";
import { useAuth } from "@/features/auth/context/AuthContext";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { addReviewFinding,decideReview,getProfessionalReviews } from "../api/professionalV2Api";
import { Button,EmptyState,ErrorState,Modal,PageHeader,Select,TableBody,TableCell,TableHead,TableShell,Textarea } from "@/shared/ui";
import { formatDateTime } from "@/shared/utils/formatters";
import { human,State } from "../components/GovernanceShared";

const initial={kind:"finding",review:null,estado:"validada",tipo:"observacion",severidad:"media",text:""};
export default function ReviewQueuePage(){const {activeOrganizacionId}=useOrganizacionActiva();const {user}=useAuth();const [rows,setRows]=useState([]);const [filters,setFilters]=useState({tipo:"",estado:"pendiente"});const [dialog,setDialog]=useState(null);const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{if(!activeOrganizacionId)return;setError("");try{setRows(await getProfessionalReviews(activeOrganizacionId,Object.fromEntries(Object.entries(filters).filter(([,v])=>v))));}catch(e){setError(e.response?.data?.detail||"No se pudo cargar la cola profesional.");}},[activeOrganizacionId,filters]);useEffect(()=>{load();},[load]);
 const pending=useMemo(()=>rows.filter(x=>x.estado==="pendiente").length,[rows]);
 async function submit(){setSaving(true);setError("");try{if(dialog.kind==="finding")await addReviewFinding(activeOrganizacionId,dialog.review.id,{tipo:dialog.tipo,severidad:dialog.severidad,observacion:dialog.text});else await decideReview(activeOrganizacionId,dialog.review.id,{estado:dialog.estado,conclusion:dialog.text,observaciones:dialog.text,antecedentes_solicitados:dialog.estado==="solicita_antecedentes"?[dialog.text]:[]});setDialog(null);await load();}catch(e){setError(e.response?.data?.detail||"No se pudo registrar la decisión profesional.");}finally{setSaving(false)}}
 return <main className="space-y-6"><PageHeader eyebrow="Gobernanza · Revisión" title="Cola de revisión profesional" description="Elementos que requieren una decisión profesional gobernada. Las revisiones decididas permanecen históricas." metadata={`${pending} revisiones pendientes`} />
 <div className="grid gap-3 sm:grid-cols-2"><Select label="Tipo" value={filters.tipo} onChange={e=>setFilters(f=>({...f,tipo:e.target.value}))}><option value="">Todos</option>{["evidencia","observacion","calculo","indicador","problematica","intervencion","expediente","metodologia"].map(x=><option key={x} value={x}>{human(x)}</option>)}</Select><Select label="Estado" value={filters.estado} onChange={e=>setFilters(f=>({...f,estado:e.target.value}))}><option value="">Todos</option>{["pendiente","validada","validada_con_observaciones","solicita_antecedentes","rechazada"].map(x=><option key={x} value={x}>{human(x)}</option>)}</Select></div>
 {error&&<ErrorState description={String(error)}/>}<TableShell><TableHead><tr><TableCell as="th">Objeto</TableCell><TableCell as="th">Estado</TableCell><TableCell as="th">Versión y fecha</TableCell><TableCell as="th">Hallazgos</TableCell><TableCell as="th">Profesional</TableCell><TableCell as="th">Acciones</TableCell></tr></TableHead><TableBody columns={6} empty={!rows.length}>{rows.map(r=><tr key={r.id}><TableCell><b>{human(r.tipo)} #{r.id}</b><span className="block text-xs text-[var(--text-muted)]">Referencia gobernada</span></TableCell><TableCell><State value={r.estado}/></TableCell><TableCell>v{r.version}<span className="block text-xs">{formatDateTime(r.created_at)}</span></TableCell><TableCell>{r.hallazgos?.length||0}{r.hallazgos?.map(h=><p key={h.id} className="mt-1 text-xs"><b>{human(h.severidad)}:</b> {h.observacion}</p>)}</TableCell><TableCell>{r.profesional_nombre||"Sin asignar"}</TableCell><TableCell>{r.estado==="pendiente"&&!user?.is_demo?<div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={()=>setDialog({...initial,review:r})}>Hallazgo</Button><Button size="sm" onClick={()=>setDialog({...initial,kind:"decision",review:r})}>Decidir</Button></div>:<span className="text-xs text-[var(--text-muted)]">Histórica / sólo lectura</span>}</TableCell></tr>)}</TableBody></TableShell>
 <Modal open={Boolean(dialog)} title={dialog?.kind==="finding"?"Agregar hallazgo estructurado":"Registrar decisión profesional"} description="Esta acción queda asociada a la revisión y no modifica datos históricos." onClose={()=>setDialog(null)} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setDialog(null)}>Cancelar</Button><Button loading={saving} disabled={!dialog?.text.trim()} onClick={submit}>Registrar</Button></div>}>{dialog?.kind==="finding"?<div className="grid gap-4 sm:grid-cols-2"><Select label="Tipo" value={dialog.tipo} onChange={e=>setDialog(d=>({...d,tipo:e.target.value}))}><option value="observacion">Observación</option><option value="inconsistencia">Inconsistencia</option><option value="antecedente_faltante">Antecedente faltante</option></Select><Select label="Severidad" value={dialog.severidad} onChange={e=>setDialog(d=>({...d,severidad:e.target.value}))}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option><option value="critica">Crítica</option></Select></div>:<Select label="Decisión" value={dialog?.estado||"validada"} onChange={e=>setDialog(d=>({...d,estado:e.target.value}))}>{["validada","validada_con_observaciones","solicita_antecedentes","rechazada"].map(x=><option key={x} value={x}>{human(x)}</option>)}</Select>}<Textarea className="mt-4" label={dialog?.kind==="finding"?"Observación":"Conclusión profesional"} rows={5} required value={dialog?.text||""} onChange={e=>setDialog(d=>({...d,text:e.target.value}))}/></Modal></main>}
