import { useCallback, useEffect, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { Building2, Check, ChevronLeft, ChevronRight, LogOut, Plus, X } from "lucide-react";
import PlatformLoader from "@/shared/components/PlatformLoader";
import { Button, Input, SelectField } from "@/shared/ui";
import { EmptyState, ErrorState } from "@/shared/ui/Feedback";
import { formatChileanPhone, formatChileanRut, isValidChileanRut, isValidEmail, isValidPhone } from "@/shared/utils/validators";
import ChileLocationFields from "@/shared/components/ChileLocationFields";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { resolveOnboardingScreen } from "@/features/organizaciones/context/organizationResolution";
import { useAuth } from "@/features/auth/context/AuthContext";
import { getOnboarding, saveOnboardingStep } from "../services/onboardingApi";

const steps = ["Empresa", "Estructura", "Flujos", "Revisión"];
const recommendedFlows = { construccion: ["materiales", "transporte", "combustibles", "energia", "agua", "residuos_no_peligrosos", "residuos_peligrosos", "ruido", "emisiones_atmosfericas"] };

export default function OnboardingPage() {
  const navigate = useNavigate(); const { logout, refreshAuth } = useAuth(); const { activeOrganizacionId, organizaciones, loadingOrganizaciones, errorOrganizaciones, refreshOrganizaciones } = useOrganizacionActiva(); const [state, setState] = useState(null); const [draft, setDraft] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [onboardingStatus, setOnboardingStatus] = useState("idle");
  const loadOnboarding = useCallback(async () => { if (!activeOrganizacionId) return; setOnboardingStatus("loading"); setError(""); try { const data = await getOnboarding(activeOrganizacionId); setState(data); seedDraft(data, setDraft); setOnboardingStatus("ready"); } catch { setState(null); setError("No pudimos cargar la configuración inicial."); setOnboardingStatus("error"); } }, [activeOrganizacionId]);
  useEffect(() => { if (activeOrganizacionId) loadOnboarding(); else { setState(null); setOnboardingStatus("idle"); } }, [activeOrganizacionId, loadOnboarding]);
  const step = Math.min(4, state?.step || 1);
  const save = async () => { setError(""); if (step === 1 && (!draft.nombre?.trim() || !isValidChileanRut(draft.rut) || !draft.preset)) { setError("Completa razón social, un RUT válido y sector."); return; } if (step === 2 && !(draft.areas || []).length) { setError("Selecciona al menos un área para continuar."); return; } if (step === 3 && !Object.keys(draft.flujos || {}).length) { setError("Selecciona al menos un aspecto ambiental para continuar."); return; } setSaving(true); try { const data = await saveOnboardingStep(activeOrganizacionId, step, payloadFor(step, draft)); setState(data); seedDraft(data, setDraft); if (data.completado) { await Promise.all([refreshOrganizaciones(activeOrganizacionId), refreshAuth()]); navigate("/inicio", { replace: true }); } } catch (requestError) { setError(requestError.response?.data?.detail || "No pudimos guardar esta etapa."); } finally { setSaving(false); } };
  const screen = resolveOnboardingScreen({ organizationLoading: loadingOrganizaciones, organizationError: errorOrganizaciones, activeOrganizationId: activeOrganizacionId, organizationCount: organizaciones.length, onboardingStatus, hasState: Boolean(state) });
  if (screen === "resolving-organization" || screen === "loading-onboarding") return <PlatformLoader fullScreen title="Preparando configuración inicial" />;
  if (screen === "organization-error") return <OnboardingStatus><ErrorState title="No pudimos preparar tu organización" description="Ocurrió un problema al cargar tu acceso. Inténtalo nuevamente." onRetry={() => refreshOrganizaciones()} /></OnboardingStatus>;
  if (screen === "organization-selector") return <Navigate to="/seleccionar-organizacion" replace />;
  if (screen === "no-organization") return <OnboardingStatus><EmptyState icon={Building2} title="No encontramos una organización disponible" description="Tu cuenta está activa, pero todavía no tiene una organización asignada." primaryAction={<Button leftIcon={LogOut} onClick={async () => { await logout(); navigate("/login", { replace: true }); }}>Cerrar sesión</Button>} /></OnboardingStatus>;
  if (screen === "onboarding-error") return <OnboardingStatus><ErrorState title="No pudimos cargar la configuración inicial" description="Ocurrió un problema al preparar el onboarding. Inténtalo nuevamente." onRetry={loadOnboarding} /></OnboardingStatus>;
  return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><section className="mx-auto max-w-5xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><header className="border-b border-slate-200 bg-slate-950 px-6 py-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Configuración inicial</p><div className="mt-5 grid grid-cols-4 gap-2">{steps.map((label, index) => <div key={label}><div className={`h-1.5 rounded-full ${index + 1 <= step ? "bg-emerald-400" : "bg-slate-700"}`} /><p className="mt-2 hidden text-xs sm:block">{label}</p></div>)}</div></header><div className="p-6 sm:p-9">{step === 1 && <CompanyStep draft={draft} setDraft={setDraft} />}{step === 2 && <StructureStep draft={draft} setDraft={setDraft} />}{step === 3 && <FlowStep rows={state.catalogos.flujos} draft={draft} setDraft={setDraft} recommended={recommendedFlows[draft.preset] || []} />}{step === 4 && <Review state={state} draft={draft} onEdit={(targetStep) => { setError(""); setState({ ...state, step: targetStep }); }} />}{error && <p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<footer className="mt-8 flex justify-between border-t border-slate-200 pt-5"><Button variant="secondary" disabled={step === 1} leftIcon={ChevronLeft} onClick={() => { setError(""); setState({ ...state, step: step - 1 }); }}>Anterior</Button><Button loading={saving} rightIcon={ChevronRight} onClick={save}>{step === 4 ? "Finalizar configuración" : "Guardar y continuar"}</Button></footer></div></section></main>;
}
function OnboardingStatus({ children }) { return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-5"><div className="w-full max-w-xl">{children}</div></main>; }
function CompanyStep({ draft, setDraft }) { const [touched, setTouched] = useState({}); const touch = (key) => () => setTouched((current) => ({ ...current, [key]: true })); const set = (key) => (event) => setDraft({ ...draft, [key]: key === "rut" ? formatChileanRut(event.target.value) : event.target.value }); const rutError = touched.rut && (!draft.rut ? "Este campo es obligatorio." : !isValidChileanRut(draft.rut) ? "El RUT ingresado no es válido. Revisa el número y su dígito verificador." : undefined); const emailError = touched.email && !isValidEmail(draft.email) ? "El formato del correo electrónico no es válido." : undefined; const phoneError = touched.telefono && !isValidPhone(draft.telefono) ? "El formato del teléfono no es válido." : undefined; return <><h1 className="text-3xl font-black">Cuéntanos sobre tu organización</h1><p className="mt-2 text-slate-600">Esta información permitirá preparar Carbono Zero para su operación en Chile.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Razón social" required value={draft.nombre || ""} onChange={set("nombre")} /><Input label="Nombre comercial" value={draft.nombre_comercial || ""} onChange={set("nombre_comercial")} /><Input label="RUT" required maxLength={12} error={rutError} value={draft.rut || ""} onChange={set("rut")} onBlur={touch("rut")} /><Input label="Giro" value={draft.rubro || ""} onChange={set("rubro")} /><SelectField label="Sector principal" required value={draft.preset || ""} options={[["construccion", "Construcción"], ["forestal", "Forestal"], ["aserradero", "Aserradero"], ["transporte", "Transporte"], ["industrial", "Industrial"]].map(([value, label]) => ({ value, label }))} onChange={(preset) => setDraft({ ...draft, preset })} placeholder="Selecciona un sector" /><ChileLocationFields region={draft.region} comuna={draft.comuna} onChange={(location) => setDraft({ ...draft, ...location })} /><Input label="Dirección" value={draft.direccion || ""} onChange={set("direccion")} /><Input label="Email corporativo" type="email" value={draft.email || ""} onChange={set("email")} onBlur={touch("email")} error={emailError} /><Input label="Teléfono" value={draft.telefono || ""} onChange={set("telefono")} onBlur={() => { touch("telefono")(); if (isValidPhone(draft.telefono)) setDraft({ ...draft, telefono: formatChileanPhone(draft.telefono) }); }} error={phoneError} /><Input label="Contacto principal" value={draft.contacto || ""} onChange={set("contacto")} /></div></> }
function StructureStep({ draft, setDraft }) {
  const [adding, setAdding] = useState(false);
  const [name, setName] = useState("");
  const [inputError, setInputError] = useState("");
  const rows = draft.areaCatalog || [];
  const selected = draft.areas || [];
  const addArea = () => {
    const clean = name.trim();
    if (!clean) { setInputError("Escribe el nombre del área."); return; }
    if (clean.length > 120) { setInputError("El nombre no puede superar los 120 caracteres."); return; }
    if (rows.some((row) => normalizeAreaName(row.nombre) === normalizeAreaName(clean))) { setInputError("Esta área ya está incluida."); return; }
    const tipo = `personalizada_${Date.now()}`;
    setDraft({ ...draft, areaCatalog: [...rows, { tipo, nombre: clean, personalizada: true }], areas: [...selected, tipo] });
    setName(""); setInputError(""); setAdding(false);
  };
  const removeCustom = (key) => setDraft({ ...draft, areaCatalog: rows.filter((row) => row.tipo !== key), areas: selected.filter((item) => item !== key) });
  return <><h1 className="text-3xl font-black">¿Cómo se organiza tu operación?</h1><p className="mt-2 max-w-3xl text-slate-600">Selecciona las áreas o unidades que generan, administran o validan información relevante para tu organización.</p><p className="mt-2 text-sm text-slate-500">Podrás relacionarlas posteriormente con flujos ambientales y procesos específicos.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{rows.map((row) => { const checked = selected.includes(row.tipo); return <div key={row.tipo} className={`relative flex min-h-24 items-center gap-3 rounded-2xl border p-4 transition ${checked ? "border-emerald-500 bg-emerald-50 shadow-sm" : "border-slate-200 bg-white hover:border-emerald-300"}`}><button type="button" aria-pressed={checked} onClick={() => setDraft({ ...draft, areas: toggle(selected, row.tipo) })} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span aria-hidden="true" className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-md border ${checked ? "border-emerald-600 bg-emerald-600 text-white" : "border-slate-300 bg-white"}`}>{checked && <Check size={15} />}</span><span className="min-w-0"><span className="font-bold">{row.nombre}</span>{row.recomendada && <span className="ml-2 inline-flex rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-800">Recomendado</span>}<small className="mt-1 block text-slate-500">Área que genera, administra o valida información.</small></span></button>{row.personalizada && <button type="button" aria-label={`Quitar ${row.nombre}`} onClick={() => removeCustom(row.tipo)} className="rounded-full p-1 text-slate-400 hover:bg-red-50 hover:text-red-700"><X size={16} /></button>}</div>})}</div><div className="mt-5">{adding ? <div className="max-w-xl rounded-2xl border border-slate-200 bg-slate-50 p-4"><Input label="Nombre del área" required autoFocus maxLength={120} value={name} error={inputError} placeholder="Ej. Abastecimiento" onChange={(event) => { setName(event.target.value); setInputError(""); }} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); addArea(); } }} /><div className="mt-3 flex gap-2"><Button onClick={addArea}>Agregar área</Button><Button variant="secondary" onClick={() => { setAdding(false); setName(""); setInputError(""); }}>Cancelar</Button></div></div> : <Button variant="secondary" leftIcon={Plus} onClick={() => setAdding(true)}>Agregar otra área</Button>}</div><p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">Las áreas representan dónde se genera o administra la información. No es necesario replicar exactamente el organigrama completo de la empresa.</p></>;
}
function SelectionStep({ title, description, rows, selected, recommended, onToggle, keyField }) { return <><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-slate-600">{description}</p><div className="mt-6 grid gap-3 md:grid-cols-2">{rows.map((row) => { const key = row[keyField]; const checked = selected.includes(key); return <button key={key} type="button" aria-pressed={checked} onClick={() => onToggle(key)} className={`flex min-h-24 items-start gap-3 rounded-2xl border p-4 text-left ${checked ? "border-emerald-500 bg-emerald-50" : "border-slate-200"}`}><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md border ${checked ? "border-emerald-600 bg-emerald-600 text-white" : "border-slate-300"}`}>{checked && <Check size={15} />}</span><span><b>{row.nombre}</b>{recommended.includes(key) && <em className="ml-2 rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold not-italic text-emerald-800">Recomendado</em>}<small className="mt-1 block text-slate-500">{row.descripcion}</small></span></button>})}</div></> }
function FlowStep({ rows, draft, setDraft, recommended }) { const selected = Object.keys(draft.flujos || {}); return <SelectionStep title="¿Qué aspectos ambientales forman parte de tu operación?" description="Selecciona los aspectos ambientales que necesitas gestionar. Podrás relacionarlos posteriormente con tus áreas y procesos." rows={rows} selected={selected} recommended={recommended} keyField="clave" onToggle={(key) => toggleFlowSelection(draft, setDraft, key)} /> }
/* Diagnóstico declarativo retirado del onboarding. Se conserva su historial únicamente en backend.
function DiagnosticStep({ rows, draft, setDraft, phase, showErrors }) {
  const selectedRows = rows.filter((row) => Object.hasOwn(draft.flujos || {}, row.clave));
  const answers = draft.diagnostico?.flujos || {};
  const update = (key, changes) => setDraft({ ...draft, diagnostico: { ...(draft.diagnostico || {}), subfase: phase, flujos: { ...answers, [key]: { ...(answers[key] || {}), ...changes } } } });
  return <><div className="mb-7"><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Diagnóstico</p><div className="mt-3 grid grid-cols-4 gap-2">{["Disponibilidad", "Fuentes", "Trazabilidad", "Resultado"].map((label, index) => <div key={label}><div className={`h-1 rounded-full ${index + 1 <= phase ? "bg-emerald-600" : "bg-slate-200"}`} /><p className={`mt-2 hidden text-xs sm:block ${index + 1 === phase ? "font-bold text-emerald-800" : "text-slate-500"}`}>{index + 1} {label}</p></div>)}</div></div>{phase === 1 && <AvailabilityPhase rows={selectedRows} answers={answers} update={update} showErrors={showErrors} />}{phase === 2 && <SourcesPhase rows={selectedRows} answers={answers} update={update} showErrors={showErrors} />}{phase === 3 && <TraceabilityPhase rows={selectedRows} answers={answers} update={update} showErrors={showErrors} />}{phase === 4 && <DiagnosticResult rows={selectedRows} answers={answers} />}</>;
}
function AvailabilityPhase({ rows, answers, update, showErrors }) { return <><h1 className="text-3xl font-black">¿Qué información tienes actualmente?</h1><p className="mt-2 text-slate-600">Indica qué tan disponible está hoy la información para cada aspecto ambiental seleccionado.</p><div className="mt-6 space-y-4">{rows.map((row) => <DiagnosticCard key={row.clave} title={row.nombre} error={showErrors && !answers[row.clave]?.disponibilidad}><OptionGroup value={answers[row.clave]?.disponibilidad} options={availability} onChange={(value) => update(row.clave, { disponibilidad: value })} /></DiagnosticCard>)}</div></>; }
const sourceOptions = [["sistema_interno", "Sistema interno / ERP"], ["planillas", "Excel / planillas"], ["documentos", "Documentos"], ["terreno", "Registros de terreno"], ["medidores", "Medidores"], ["sensores", "Sensores"], ["proveedor", "Proveedor / tercero"], ["manual", "Registro manual"], ["otro", "Otro"]];
function SourcesPhase({ rows, answers, update, showErrors }) { const applicable = rows.filter((row) => ["suficiente", "parcial"].includes(answers[row.clave]?.disponibilidad)); return <><h1 className="text-3xl font-black">¿De dónde proviene la información?</h1><p className="mt-2 text-slate-600">Identifica las principales fuentes utilizadas y si existe evidencia que permita respaldar los datos.</p><div className="mt-6 space-y-4">{applicable.length ? applicable.map((row) => { const selected = answers[row.clave]?.fuentes || []; const incomplete = !selected.length || !answers[row.clave]?.evidencia; return <DiagnosticCard key={row.clave} title={row.nombre} error={showErrors && incomplete}><p className="mb-2 text-sm font-bold">Fuentes utilizadas</p><div className="flex flex-wrap gap-2">{sourceOptions.map(([value, label]) => <button key={value} type="button" aria-pressed={selected.includes(value)} onClick={() => update(row.clave, { fuentes: toggle(selected, value) })} className={`rounded-full border px-3 py-2 text-xs font-bold ${selected.includes(value) ? "border-emerald-600 bg-emerald-100 text-emerald-900" : "border-slate-200 bg-white text-slate-600"}`}>{selected.includes(value) ? "✓ " : ""}{label}</button>)}</div><p className="mb-2 mt-5 text-sm font-bold">¿La información conserva respaldo verificable?</p><OptionGroup value={answers[row.clave]?.evidencia} options={[["si", "Sí"], ["parcial", "Parcialmente"], ["no", "No"], ["no_seguro", "No estoy seguro"]]} onChange={(value) => update(row.clave, { evidencia: value })} /></DiagnosticCard>; }) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-600">No hay aspectos con información suficiente o parcial. Puedes continuar a trazabilidad.</p>}</div></>; }
const traceQuestions = [["origen", "¿Se conoce el origen del dato?"], ["fecha", "¿Se identifica cuándo ocurrió?"], ["responsable", "¿Se conoce quién lo registró o entregó?"], ["historico", "¿Puede reconstruirse históricamente?"]];
function TraceabilityPhase({ rows, answers, update, showErrors }) { const applicable = rows.filter((row) => ["suficiente", "parcial"].includes(answers[row.clave]?.disponibilidad)); return <><h1 className="text-3xl font-black">¿Qué tan fácil es reconstruir esta información?</h1><p className="mt-2 text-slate-600">Evalúa si los datos pueden relacionarse con su origen y reconstruirse posteriormente.</p><div className="mt-6 space-y-4">{applicable.map((row) => { const incomplete = traceQuestions.some(([key]) => !answers[row.clave]?.trazabilidad?.[key]) || !answers[row.clave]?.validacion_profesional; return <details key={row.clave} open aria-invalid={showErrors && incomplete || undefined} className={`rounded-2xl border bg-white p-5 transition ${showErrors && incomplete ? "border-red-400 bg-red-50/30 shadow-[0_0_0_1px_rgba(248,113,113,0.15)]" : "border-slate-200"}`}><summary className={`cursor-pointer font-black ${showErrors && incomplete ? "text-red-700" : ""}`}>{row.nombre}</summary><div className="mt-5 space-y-5">{traceQuestions.map(([key, label]) => <div key={key}><p className="mb-2 text-sm font-bold">{label}</p><OptionGroup value={answers[row.clave]?.trazabilidad?.[key]} options={[["si", "Sí"], ["parcial", "Parcial"], ["no", "No"]]} onChange={(value) => update(row.clave, { trazabilidad: { ...(answers[row.clave]?.trazabilidad || {}), [key]: value } })} /></div>)}<div><p className="mb-2 text-sm font-bold">¿Requiere revisión profesional antes de una interpretación ambiental?</p><OptionGroup value={answers[row.clave]?.validacion_profesional} options={[["si", "Sí"], ["no", "No"], ["no_seguro", "No estoy seguro"]]} onChange={(value) => update(row.clave, { validacion_profesional: value })} /></div></div></details>; })}</div></>; }
function DiagnosticResult({ rows, answers }) { return <><h1 className="text-3xl font-black">Así está preparada actualmente tu organización</h1><p className="mt-2 text-slate-600">Este diagnóstico inicial muestra fortalezas y brechas de información. Podrás mejorar esta configuración posteriormente.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{rows.map((row) => { const answer = answers[row.clave] || {}; const result = diagnosticSummary(answer); return <article key={row.clave} className="rounded-2xl border border-slate-200 p-5"><h2 className="font-black uppercase tracking-wide">{row.nombre}</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><ResultTerm label="Disponibilidad" value={result.disponibilidad} /><ResultTerm label="Fuentes" value={(answer.fuentes || []).map((key) => Object.fromEntries(sourceOptions)[key]).join(" + ") || "Sin fuente identificada"} /><ResultTerm label="Evidencia" value={result.evidencia} /><ResultTerm label="Trazabilidad" value={result.trazabilidad} /><ResultTerm label="Validación profesional" value={answer.validacion_profesional === "si" ? "Requerida" : answer.validacion_profesional === "no" ? "No declarada" : "Por confirmar"} /></dl>{result.message && <p className={`mt-4 rounded-xl p-3 text-xs font-medium ${result.strength ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-900"}`}>{result.message}</p>}</article>; })}</div><p className="mt-6 text-sm text-slate-500">Esta síntesis describe capacidad de información. No evalúa cumplimiento ni desempeño ambiental.</p></>; }
function DiagnosticCard({ title, children, error = false }) { return <article aria-invalid={error || undefined} className={`rounded-2xl border bg-white p-5 transition ${error ? "border-red-400 bg-red-50/30 shadow-[0_0_0_1px_rgba(248,113,113,0.15)]" : "border-slate-200"}`}><h2 className={`mb-4 font-black ${error ? "text-red-700" : ""}`}>{title}</h2>{children}</article>; }
function OptionGroup({ value, options, onChange }) { return <div className="grid gap-2 sm:grid-cols-2">{options.map(([key, label]) => <button key={key} type="button" aria-pressed={value === key} onClick={() => onChange(key)} className={`rounded-xl border px-3 py-2.5 text-left text-sm font-bold ${value === key ? "border-emerald-600 bg-emerald-50 text-emerald-900" : "border-slate-200 bg-white text-slate-600 hover:border-emerald-300"}`}>{value === key ? "● " : "○ "}{label}</button>)}</div>; }
function ResultTerm({ label, value }) { return <div><dt className="text-xs font-bold text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
*/
function Review({ state, draft, onEdit }) { const selectedAreas = (draft.areaCatalog || []).filter((area) => (draft.areas || []).includes(area.tipo)); const selectedFlows = state.catalogos.flujos.filter((row) => Object.hasOwn(draft.flujos || {}, row.clave)); const sector = { construccion: "Construcción", forestal: "Forestal", aserradero: "Aserradero", transporte: "Transporte", industrial: "Industrial" }[draft.preset] || draft.preset; return <><h1 className="text-3xl font-black">Revisa tu configuración</h1><p className="mt-2 max-w-3xl text-slate-600">Confirma que esta información representa correctamente cómo se organiza tu operación y qué aspectos ambientales necesitas gestionar.</p><div className="mt-7 space-y-4"><ReviewSection title="Organización" onEdit={() => onEdit(1)}><p className="text-xl font-black tracking-tight text-slate-950">{draft.nombre}</p><p className="mt-1.5 text-sm font-medium text-slate-600">{sector} · {draft.region || "Región sin informar"} · {draft.comuna || "Comuna sin informar"}</p></ReviewSection><ReviewSection title="Estructura" description="Áreas que generan, administran o validan información relevante." onEdit={() => onEdit(2)}><p className="font-black text-slate-950">{selectedAreas.length} áreas configuradas</p><div className="mt-4 flex flex-wrap gap-2">{selectedAreas.map((area) => <span key={area.tipo} className="rounded-full border border-slate-200 bg-slate-100/80 px-3 py-1.5 text-xs font-bold text-slate-800 shadow-sm">{area.nombre}</span>)}</div></ReviewSection><ReviewSection title="Aspectos ambientales" description="Aspectos que Carbono Zero gestionará inicialmente." onEdit={() => onEdit(3)}><p className="font-black text-slate-950">{selectedFlows.length} aspectos seleccionados</p><div className="mt-4 flex flex-wrap gap-2">{selectedFlows.map((flow) => <span key={flow.clave} className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-900 shadow-sm">{flow.nombre}</span>)}</div></ReviewSection></div><p className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50/80 p-5 text-sm font-medium leading-6 text-emerald-950">Esta configuración define la base inicial de tu operación en Carbono Zero. Podrás modificarla más adelante según evolucen tus procesos.</p></> }
function ReviewSection({ title, description, onEdit, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_30px_rgba(15,23,42,0.035)] sm:p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="font-black text-slate-950">{title}</h2>{description && <p className="mt-1.5 max-w-2xl text-sm leading-5 text-slate-500">{description}</p>}</div><Button variant="secondary" onClick={onEdit}>Editar</Button></div>{children}</section>; }
function toggle(values = [], key) { return values.includes(key) ? values.filter((item) => item !== key) : [...values, key]; }
function seedDraft(data, setter) { const customAreas = data.areas.filter((area) => !data.catalogos.areas.some((row) => row.tipo === area.tipo)).map((area) => ({ ...area, personalizada: true })); setter((current) => ({ ...current, ...data.organizacion, preset: data.organizacion.sector, areaCatalog: [...data.catalogos.areas, ...customAreas], sugerencias: data.catalogos.sugerencias, areas: data.data?.["2"]?.areas?.map((row) => typeof row === "string" ? row : row.tipo) || data.areas.filter((row) => row.activa).map((row) => row.tipo), flujos: data.data?.["3"]?.flujos || Object.fromEntries(data.flujos.map((row) => [row.clave, row.disponibilidad])), relaciones: data.data?.["3"]?.relaciones || data.relaciones || {}, diagnostico: data.data?.["4"] || {} })); }
function payloadFor(step, draft) { if (step === 1) return { nombre: draft.nombre, nombre_comercial: draft.nombre_comercial, rut: draft.rut, rubro: draft.rubro, region: draft.region, comuna: draft.comuna, direccion: draft.direccion, email: draft.email, telefono: draft.telefono, contacto: draft.contacto, preset: draft.preset }; if (step === 2) return { areas: (draft.areaCatalog || []).filter((row) => (draft.areas || []).includes(row.tipo)).map(({ tipo, nombre }) => ({ tipo, nombre })) }; if (step === 3) return { flujos: draft.flujos }; return { confirmado: true }; }
function normalizeAreaName(value = "") { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("es-CL").trim(); }
function toggleFlowSelection(draft, setDraft, key) { const flows = { ...(draft.flujos || {}) }; if (flows[key]) delete flows[key]; else flows[key] = "no_seguro"; setDraft({ ...draft, flujos: flows }); }
