import { useCallback, useEffect, useMemo, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { Building2, Check, ChevronLeft, ChevronRight, LogOut, Plus, X } from "lucide-react";
import PlatformLoader from "@/shared/components/PlatformLoader";
import { Button, Input, Select, SelectField } from "@/shared/ui";
import { EmptyState, ErrorState } from "@/shared/ui/Feedback";
import { formatChileanPhone, formatChileanRut, isValidChileanRut, isValidEmail, isValidPhone } from "@/shared/utils/validators";
import ChileLocationFields from "@/shared/components/ChileLocationFields";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { resolveOnboardingScreen } from "@/features/organizaciones/context/organizationResolution";
import { useAuth } from "@/features/auth/context/AuthContext";
import { getOnboarding, saveOnboardingStep } from "../services/onboardingApi";
import AreaFlowMatrix from "../components/AreaFlowMatrix";

const steps = ["Empresa", "Estructura", "Flujos", "Diagnóstico", "Revisión"];
const availability = [["regular", "Tenemos información regular"], ["parcial", "Tenemos información parcial"], ["sin_informacion", "Todavía no tenemos información"], ["no_seguro", "No estoy seguro"]];
const recommendedFlows = { construccion: ["materiales", "transporte", "combustibles", "maquinaria", "energia", "agua", "residuos", "ruido", "hidrica_suelo"] };

export default function OnboardingPage() {
  const navigate = useNavigate(); const { logout, refreshAuth } = useAuth(); const { activeOrganizacionId, organizaciones, loadingOrganizaciones, errorOrganizaciones, refreshOrganizaciones } = useOrganizacionActiva(); const [state, setState] = useState(null); const [draft, setDraft] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [onboardingStatus, setOnboardingStatus] = useState("idle");
  const loadOnboarding = useCallback(async () => { if (!activeOrganizacionId) return; setOnboardingStatus("loading"); setError(""); try { const data = await getOnboarding(activeOrganizacionId); setState(data); seedDraft(data, setDraft); setOnboardingStatus("ready"); } catch { setState(null); setError("No pudimos cargar la configuración inicial."); setOnboardingStatus("error"); } }, [activeOrganizacionId]);
  useEffect(() => { if (activeOrganizacionId) loadOnboarding(); else { setState(null); setOnboardingStatus("idle"); } }, [activeOrganizacionId, loadOnboarding]);
  const step = state?.step || 1; const selectedFlows = useMemo(() => Object.keys(draft.flujos || {}), [draft.flujos]);
  const save = async () => { setError(""); if (step === 1 && (!draft.nombre?.trim() || !isValidChileanRut(draft.rut) || !draft.preset)) { setError("Completa razón social, un RUT válido y sector."); return; } if (step === 2 && !(draft.areas || []).length) { setError("Selecciona al menos un área para continuar."); return; } setSaving(true); try { const data = await saveOnboardingStep(activeOrganizacionId, step, payloadFor(step, draft)); setState(data); seedDraft(data, setDraft); if (data.completado) { await Promise.all([refreshOrganizaciones(activeOrganizacionId), refreshAuth()]); } } catch (requestError) { setError(requestError.response?.data?.detail || "No pudimos guardar esta etapa."); } finally { setSaving(false); } };
  const screen = resolveOnboardingScreen({ organizationLoading: loadingOrganizaciones, organizationError: errorOrganizaciones, activeOrganizationId: activeOrganizacionId, organizationCount: organizaciones.length, onboardingStatus, hasState: Boolean(state) });
  if (screen === "resolving-organization" || screen === "loading-onboarding") return <PlatformLoader fullScreen title="Preparando configuración inicial" />;
  if (screen === "organization-error") return <OnboardingStatus><ErrorState title="No pudimos preparar tu organización" description="Ocurrió un problema al cargar tu acceso. Inténtalo nuevamente." onRetry={() => refreshOrganizaciones()} /></OnboardingStatus>;
  if (screen === "organization-selector") return <Navigate to="/seleccionar-organizacion" replace />;
  if (screen === "no-organization") return <OnboardingStatus><EmptyState icon={Building2} title="No encontramos una organización disponible" description="Tu cuenta está activa, pero todavía no tiene una organización asignada." primaryAction={<Button leftIcon={LogOut} onClick={async () => { await logout(); navigate("/login", { replace: true }); }}>Cerrar sesión</Button>} /></OnboardingStatus>;
  if (screen === "onboarding-error") return <OnboardingStatus><ErrorState title="No pudimos cargar la configuración inicial" description="Ocurrió un problema al preparar el onboarding. Inténtalo nuevamente." onRetry={loadOnboarding} /></OnboardingStatus>;
  return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><section className="mx-auto max-w-5xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><header className="border-b border-slate-200 bg-slate-950 px-6 py-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Configuración inicial</p><div className="mt-5 grid grid-cols-5 gap-2">{steps.map((label, index) => <div key={label}><div className={`h-1.5 rounded-full ${index + 1 <= step ? "bg-emerald-400" : "bg-slate-700"}`} /><p className="mt-2 hidden text-xs sm:block">{label}</p></div>)}</div></header><div className="p-6 sm:p-9">{step === 1 && <CompanyStep draft={draft} setDraft={setDraft} />}{step === 2 && <StructureStep draft={draft} setDraft={setDraft} />}{step === 3 && <FlowStep rows={state.catalogos.flujos} draft={draft} setDraft={setDraft} recommended={recommendedFlows[draft.preset] || []} />}{step === 4 && <DiagnosticStep draft={draft} setDraft={setDraft} />}{step === 5 && <Review state={state} draft={draft} />}{error && <p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<footer className="mt-8 flex justify-between border-t border-slate-200 pt-5"><Button variant="secondary" disabled={step === 1} leftIcon={ChevronLeft} onClick={() => setState({ ...state, step: step - 1 })}>Anterior</Button>{state.completado ? <div className="flex gap-2"><Button variant="secondary" onClick={() => navigate("/inicio")}>Ir al inicio</Button><Button onClick={() => navigate("/obras")}>Crear primera obra</Button></div> : <Button loading={saving} rightIcon={ChevronRight} onClick={save}>{step === 5 ? "Completar configuración" : "Guardar y continuar"}</Button>}</footer></div></section></main>;
}
function OnboardingStatus({ children }) { return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-5"><div className="w-full max-w-xl">{children}</div></main>; }
function CompanyStep({ draft, setDraft }) { const [touched, setTouched] = useState({}); const touch = (key) => () => setTouched((current) => ({ ...current, [key]: true })); const set = (key) => (event) => setDraft({ ...draft, [key]: key === "rut" ? formatChileanRut(event.target.value) : event.target.value }); const rutError = touched.rut && (!draft.rut ? "Este campo es obligatorio." : !isValidChileanRut(draft.rut) ? "El RUT ingresado no es válido. Revisa el número y su dígito verificador." : undefined); const emailError = touched.email && !isValidEmail(draft.email) ? "El formato del correo electrónico no es válido." : undefined; const phoneError = touched.telefono && !isValidPhone(draft.telefono) ? "El formato del teléfono no es válido." : undefined; return <><h1 className="text-3xl font-black">Cuéntanos sobre tu organización</h1><p className="mt-2 text-slate-600">Esta información permitirá preparar Carbono Zero para su operación en Chile.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Razón social" required value={draft.nombre || ""} onChange={set("nombre")} /><Input label="Nombre comercial" value={draft.nombre_comercial || ""} onChange={set("nombre_comercial")} /><Input label="RUT" required maxLength={12} error={rutError} value={draft.rut || ""} onChange={set("rut")} onBlur={touch("rut")} /><Input label="Giro" value={draft.rubro || ""} onChange={set("rubro")} /><SelectField label="Sector principal" required value={draft.preset || ""} options={[["construccion", "Construcción"], ["forestal", "Forestal"], ["aserradero", "Aserradero"], ["transporte", "Transporte"], ["industrial", "Industrial"]].map(([value, label]) => ({ value, label }))} onChange={(preset) => setDraft({ ...draft, preset })} placeholder="Selecciona un sector" /><ChileLocationFields region={draft.region} comuna={draft.comuna} onChange={(location) => setDraft({ ...draft, ...location })} /><Input label="Dirección" value={draft.direccion || ""} onChange={set("direccion")} /><Input label="Email corporativo" type="email" value={draft.email || ""} onChange={set("email")} onBlur={touch("email")} error={emailError} /><Input label="Teléfono" value={draft.telefono || ""} onChange={set("telefono")} onBlur={() => { touch("telefono")(); if (isValidPhone(draft.telefono)) setDraft({ ...draft, telefono: formatChileanPhone(draft.telefono) }); }} error={phoneError} /><Input label="Contacto principal" value={draft.contacto || ""} onChange={set("contacto")} /></div></> }
function StructureStep({ draft, setDraft }) {
  const [adding, setAdding] = useState(false);
  const [name, setName] = useState("");
  const [inputError, setInputError] = useState("");
  const rows = draft.areaCatalog || [];
  const selected = draft.areas || [];
  const addArea = () => {
    const clean = name.trim();
    if (!clean) { setInputError("Escribe el nombre del área."); return; }
    if (clean.length > 120) { setInputError("El nombre no puede superar los 120 caracteres."); return; }
    if (rows.some((row) => normalizeAreaName(row.nombre) === normalizeAreaName(clean))) { setInputError("Esta área ya está incluida."); return; }
    const tipo = `personalizada_${Date.now()}`;
    setDraft({ ...draft, areaCatalog: [...rows, { tipo, nombre: clean, personalizada: true }], areas: [...selected, tipo] });
    setName(""); setInputError(""); setAdding(false);
  };
  const removeCustom = (key) => setDraft({ ...draft, areaCatalog: rows.filter((row) => row.tipo !== key), areas: selected.filter((item) => item !== key) });
  return <><h1 className="text-3xl font-black">¿Cómo se organiza tu operación?</h1><p className="mt-2 max-w-3xl text-slate-600">Selecciona las áreas o unidades que generan, administran o validan información relevante para tu organización.</p><p className="mt-2 text-sm text-slate-500">Podrás relacionarlas posteriormente con flujos ambientales y procesos específicos.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{rows.map((row) => { const checked = selected.includes(row.tipo); return <div key={row.tipo} className={`relative flex min-h-24 items-start gap-3 rounded-2xl border p-4 transition ${checked ? "border-emerald-500 bg-emerald-50 shadow-sm" : "border-slate-200 bg-white hover:border-emerald-300"}`}><button type="button" aria-pressed={checked} onClick={() => setDraft({ ...draft, areas: toggle(selected, row.tipo) })} className="flex min-w-0 flex-1 items-start gap-3 text-left"><span aria-hidden="true" className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md border ${checked ? "border-emerald-600 bg-emerald-600 text-white" : "border-slate-300 bg-white"}`}>{checked && <Check size={15} />}</span><span className="min-w-0"><span className="font-bold">{row.nombre}</span>{row.recomendada && <span className="ml-2 inline-flex rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-800">Recomendado</span>}<small className="mt-1 block text-slate-500">Área que genera, administra o valida información.</small></span></button>{row.personalizada && <button type="button" aria-label={`Quitar ${row.nombre}`} onClick={() => removeCustom(row.tipo)} className="rounded-full p-1 text-slate-400 hover:bg-red-50 hover:text-red-700"><X size={16} /></button>}</div>})}</div><div className="mt-5">{adding ? <div className="max-w-xl rounded-2xl border border-slate-200 bg-slate-50 p-4"><Input label="Nombre del área" required autoFocus maxLength={120} value={name} error={inputError} placeholder="Ej. Abastecimiento" onChange={(event) => { setName(event.target.value); setInputError(""); }} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); addArea(); } }} /><div className="mt-3 flex gap-2"><Button onClick={addArea}>Agregar área</Button><Button variant="secondary" onClick={() => { setAdding(false); setName(""); setInputError(""); }}>Cancelar</Button></div></div> : <Button variant="secondary" leftIcon={Plus} onClick={() => setAdding(true)}>Agregar otra área</Button>}</div><p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">Las áreas representan dónde se genera o administra la información. No es necesario replicar exactamente el organigrama completo de la empresa.</p></>;
}
function SelectionStep({ title, description, rows, selected, recommended, onToggle, keyField }) { return <><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-slate-600">{description}</p><div className="mt-6 grid gap-3 md:grid-cols-2">{rows.map((row) => { const key = row[keyField]; const checked = selected.includes(key); return <button key={key} type="button" aria-pressed={checked} onClick={() => onToggle(key)} className={`flex min-h-24 items-start gap-3 rounded-2xl border p-4 text-left ${checked ? "border-emerald-500 bg-emerald-50" : "border-slate-200"}`}><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md border ${checked ? "border-emerald-600 bg-emerald-600 text-white" : "border-slate-300"}`}>{checked && <Check size={15} />}</span><span><b>{row.nombre}</b>{recommended.includes(key) && <em className="ml-2 rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold not-italic text-emerald-800">Recomendado</em>}<small className="mt-1 block text-slate-500">{row.descripcion}</small></span></button>})}</div></> }
function FlowStep({ rows, draft, setDraft, recommended }) { const selected = Object.keys(draft.flujos || {}); const selectedRows = rows.filter((row) => selected.includes(row.clave)); const selectedAreas = (draft.areaCatalog || []).filter((row) => (draft.areas || []).includes(row.tipo)); return <><SelectionStep title="¿Qué aspectos ambientales forman parte de tu operación?" description="Tú decides qué flujos habilitar. Esto no crea resultados ambientales." rows={rows} selected={selected} recommended={recommended} keyField="clave" onToggle={(key) => toggleFlowSelection(draft, setDraft, key)} />{selected.length > 0 && <div className="mt-8 space-y-3"><h2 className="text-xl font-black">¿Qué información tienes actualmente?</h2>{selectedRows.map((row) => <Select key={row.clave} label={row.nombre} value={draft.flujos[row.clave]} onChange={(event) => setDraft({ ...draft, flujos: { ...draft.flujos, [row.clave]: event.target.value } })}>{availability.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>)}</div>}{selected.length > 0 && <AreaFlowMatrix areas={selectedAreas} flows={selectedRows} relations={draft.relaciones || {}} suggestions={draft.sugerencias || {}} onChange={(relaciones) => setDraft({ ...draft, relaciones })} />}</> }
function DiagnosticStep({ draft, setDraft }) { const set = (key) => (event) => setDraft({ ...draft, diagnostico: { ...(draft.diagnostico || {}), [key]: event.target.value } }); return <><h1 className="text-3xl font-black">Diagnóstico ambiental inicial</h1><p className="mt-2 text-slate-600">Esta lectura describe capacidades de información; todavía no evalúa desempeño ni cumplimiento.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="¿Cómo registran actualmente esta información?" value={draft.diagnostico?.metodos || ""} placeholder="PDF, Excel, ERP..." onChange={set("metodos")} /><Select label="¿La información está centralizada?" value={draft.diagnostico?.centralizacion || "no_se"} onChange={set("centralizacion")}><option value="si">Sí</option><option value="parcial">Parcialmente</option><option value="no">No</option><option value="no_se">No lo sé</option></Select><Select label="¿Quién revisa la información ambiental?" value={draft.diagnostico?.revision || "sin_revision"} onChange={set("revision")}><option value="medio_ambiente">Área medioambiental interna</option><option value="externo">Profesional externo</option><option value="obra">Encargado de obra/faena</option><option value="administracion">Administración</option><option value="sin_revision">No existe revisión formal</option></Select><Select label="¿Con qué frecuencia la consolidan?" value={draft.diagnostico?.frecuencia || "sin_frecuencia"} onChange={set("frecuencia")}><option value="diaria">Diariamente</option><option value="semanal">Semanalmente</option><option value="mensual">Mensualmente</option><option value="hito">Por proyecto/hito</option><option value="solicitud">Solo cuando se solicita</option><option value="sin_frecuencia">Sin frecuencia definida</option></Select></div></> }
function Review({ state, draft }) { const counts = Object.values(draft.flujos || {}).reduce((acc, value) => ({ ...acc, [value]: (acc[value] || 0) + 1 }), {}); const flowNames = Object.fromEntries(state.catalogos.flujos.map((row) => [row.clave, row.nombre])); return <><h1 className="text-3xl font-black">Tu organización está preparada</h1><div className="mt-6 grid gap-4 sm:grid-cols-2"><Summary title="Identidad" value={`${draft.nombre} · ${draft.preset} · ${draft.pais}`} /><Summary title="Estructura" value={`${draft.areas?.length || state.areas.length} áreas`} /><Summary title="Flujos ambientales" value={`${Object.keys(draft.flujos || {}).length} habilitados`} /><Summary title="Información" value={`${counts.regular || 0} regulares · ${counts.parcial || 0} parciales · ${counts.sin_informacion || 0} sin datos`} /></div><section className="mt-6 rounded-2xl border border-slate-200 p-5"><h2 className="font-black">Cómo se distribuirá la información</h2><div className="mt-4 space-y-3">{(draft.areaCatalog || []).filter((area) => (draft.areas || []).includes(area.tipo)).map((area) => <div key={area.tipo}><b>{area.nombre}</b><p className="text-sm text-slate-600">→ {(draft.relaciones?.[area.tipo] || []).map((key) => flowNames[key]).filter(Boolean).join(" · ") || "Sin relaciones definidas todavía"}</p></div>)}</div></section><p className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-900"><b>Preparación inicial:</b> base suficiente para comenzar a crear obras e incorporar información real.</p></> }
function Summary({ title, value }) { return <article className="rounded-2xl border border-slate-200 p-5"><p className="text-xs font-black uppercase tracking-wide text-emerald-700">{title}</p><p className="mt-2 font-bold">{value}</p></article> }
function toggle(values = [], key) { return values.includes(key) ? values.filter((item) => item !== key) : [...values, key]; }
function seedDraft(data, setter) { const customAreas = data.areas.filter((area) => !data.catalogos.areas.some((row) => row.tipo === area.tipo)).map((area) => ({ ...area, personalizada: true })); setter((current) => ({ ...current, ...data.organizacion, preset: data.organizacion.sector, areaCatalog: [...data.catalogos.areas, ...customAreas], sugerencias: data.catalogos.sugerencias, areas: data.data?.["2"]?.areas?.map((row) => typeof row === "string" ? row : row.tipo) || data.areas.filter((row) => row.activa).map((row) => row.tipo), flujos: data.data?.["3"]?.flujos || Object.fromEntries(data.flujos.map((row) => [row.clave, row.disponibilidad])), relaciones: data.data?.["3"]?.relaciones || data.relaciones || {}, diagnostico: data.data?.["4"] || {} })); }
function payloadFor(step, draft) { if (step === 1) return { nombre: draft.nombre, nombre_comercial: draft.nombre_comercial, rut: draft.rut, rubro: draft.rubro, region: draft.region, comuna: draft.comuna, direccion: draft.direccion, email: draft.email, telefono: draft.telefono, contacto: draft.contacto, preset: draft.preset }; if (step === 2) return { areas: (draft.areaCatalog || []).filter((row) => (draft.areas || []).includes(row.tipo)).map(({ tipo, nombre }) => ({ tipo, nombre })) }; if (step === 3) return { flujos: draft.flujos, relaciones: draft.relaciones }; if (step === 4) return draft.diagnostico; return { confirmado: true }; }
function normalizeAreaName(value = "") { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("es-CL").trim(); }
function toggleFlowSelection(draft, setDraft, key) { const flows = { ...(draft.flujos || {}) }; const relations = Object.fromEntries(Object.entries(draft.relaciones || {}).map(([area, values]) => [area, [...values]])); if (flows[key]) { delete flows[key]; Object.keys(relations).forEach((area) => { relations[area] = relations[area].filter((item) => item !== key); }); } else { flows[key] = "no_seguro"; (draft.areas || []).forEach((area) => { if ((draft.sugerencias?.[area] || []).includes(key)) relations[area] = [...new Set([...(relations[area] || []), key])]; }); } setDraft({ ...draft, flujos: flows, relaciones: relations }); }
