import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { CheckCircle2, LockKeyhole } from "lucide-react";
import { Button, Input } from "@/shared/ui";
import { activateAccount, confirmPasswordReset, requestPasswordReset } from "../services/onboardingApi";

export default function PasswordLifecyclePage({ mode }) {
  const { uid, token } = useParams(); const [form, setForm] = useState({ email: "", password: "", confirmation: "" }); const [state, setState] = useState({ loading: false, error: "", done: false, invalid: false, message: "" });
  const submit = async (event) => { event.preventDefault(); setState({ loading: true, error: "", done: false, invalid: false, message: "" }); try { const result = mode === "request" ? await requestPasswordReset(form.email) : mode === "activate" ? await activateAccount(uid, token, form) : await confirmPasswordReset(uid, token, form); setState({ loading: false, error: "", done: true, invalid: false, message: result.detail }); } catch (error) { const data = error.response?.data; const detail = data?.password?.[0] || data?.confirmation?.[0] || data?.detail || "No pudimos completar la solicitud."; const invalid = mode !== "request" && error.response?.status === 400 && /enlace|token|v[aá]lid|expir/i.test(detail); setState({ loading: false, done: false, invalid, message: "", error: detail }); } };
  const title = mode === "request" ? "Recupera tu acceso" : mode === "activate" ? "Activa tu cuenta" : "Crea una nueva contraseña";
  return <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-950 via-emerald-950 to-slate-900 p-5"><section className="w-full max-w-lg rounded-3xl border border-white/10 bg-white p-7 shadow-2xl sm:p-9"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-800">{state.done ? <CheckCircle2 /> : <LockKeyhole />}</div><h1 className="mt-5 text-3xl font-black">{state.invalid ? "Este enlace ya no es válido" : state.done ? (mode === "request" ? "Revisa tu correo" : "Contraseña actualizada") : title}</h1>{state.invalid ? <><p className="mt-3 text-slate-600">El enlace puede haber vencido o ya haber sido utilizado. Solicita uno nuevo para proteger tu cuenta.</p><Button className="mt-6 w-full" onClick={() => window.location.assign(mode === "reset" ? "/recuperar-contrasena" : "/login")}>{mode === "reset" ? "Solicitar un nuevo enlace" : "Volver al inicio de sesión"}</Button></> : state.done ? <><p className="mt-3 text-slate-600">{state.message}</p><Button className="mt-6 w-full" onClick={() => window.location.assign("/login")}>Iniciar sesión</Button></> : <form onSubmit={submit} className="mt-6 space-y-4">{mode === "request" ? <Input label="Correo electrónico" type="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /> : <><Input label="Nueva contraseña" type="password" required helper="Usa al menos 8 caracteres y evita contraseñas comunes." value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><Input label="Confirmación" type="password" required value={form.confirmation} onChange={(event) => setForm({ ...form, confirmation: event.target.value })} /></>}{state.error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{state.error}</p>}<Button type="submit" loading={state.loading} className="w-full">{mode === "request" ? "Enviar instrucciones" : "Guardar contraseña"}</Button><Link className="block text-center text-sm font-bold text-emerald-700" to="/login">Volver al inicio de sesión</Link></form>}</section></main>;
}
