import { useEffect, useMemo, useState } from "react";
import { Save } from "lucide-react";
import { Button, Select } from "@/shared/ui";
import PlatformLoader from "@/shared/components/PlatformLoader";
import Toast from "@/shared/components/Toast";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import AreaFlowMatrix, { suggestedRelations } from "../components/AreaFlowMatrix";
import { getOnboarding, saveOnboardingStep } from "../services/onboardingApi";

const availability = [["regular", "Información regular"], ["parcial", "Información parcial"], ["sin_informacion", "Sin información"], ["no_seguro", "No estoy seguro"]];

export default function StructureSettingsPage() {
  const { activeOrganizacionId } = useOrganizacionActiva();
  const [data, setData] = useState(null); const [areas, setAreas] = useState([]); const [flows, setFlows] = useState({}); const [relations, setRelations] = useState({}); const [saving, setSaving] = useState(false); const [toast, setToast] = useState(null);
  useEffect(() => { if (!activeOrganizacionId) return; getOnboarding(activeOrganizacionId).then((result) => { const areaKeys = result.areas.filter((row) => row.activa).map((row) => row.tipo); const flowValues = Object.fromEntries(result.flujos.map((row) => [row.clave, row.disponibilidad])); setData(result); setAreas(areaKeys); setFlows(flowValues); setRelations(result.relaciones || suggestedRelations(areaKeys, Object.keys(flowValues), result.catalogos.sugerencias)); }).catch(() => setToast({ id: Date.now(), tone: "error", message: "No pudimos cargar la estructura", subtitle: "Actualiza la página e inténtalo nuevamente." })); }, [activeOrganizacionId]);
  const areaRows = useMemo(() => (data?.catalogos.areas || []).filter((row) => areas.includes(row.tipo)), [areas, data]); const flowRows = useMemo(() => (data?.catalogos.flujos || []).filter((row) => Object.hasOwn(flows, row.clave)), [flows, data]);
  const toggleArea = (key) => { const next = areas.includes(key) ? areas.filter((item) => item !== key) : [...areas, key]; const nextRelations = { ...relations }; if (!next.includes(key)) delete nextRelations[key]; else nextRelations[key] = (data.catalogos.sugerencias[key] || []).filter((flow) => Object.hasOwn(flows, flow)); setAreas(next); setRelations(nextRelations); };
  const toggleFlow = (key) => { const next = { ...flows }; const nextRelations = Object.fromEntries(Object.entries(relations).map(([area, values]) => [area, values.filter((flow) => flow !== key)])); if (Object.hasOwn(next, key)) delete next[key]; else { next[key] = "no_seguro"; areas.forEach((area) => { if ((data.catalogos.sugerencias[area] || []).includes(key)) nextRelations[area] = [...new Set([...(nextRelations[area] || []), key])]; }); } setFlows(next); setRelations(nextRelations); };
  const save = async () => { setSaving(true); setToast({ id: Date.now(), loading: true, message: "Guardando configuración", subtitle: "Estamos actualizando la estructura de tu organización." }); try { await saveOnboardingStep(activeOrganizacionId, 2, { areas }); await saveOnboardingStep(activeOrganizacionId, 3, { flujos: flows, relaciones: relations }); setToast({ id: Date.now(), message: "Estructura actualizada", subtitle: "Las áreas, flujos y relaciones quedaron guardados." }); } catch (error) { setToast({ id: Date.now(), tone: "error", message: "No pudimos guardar los cambios", subtitle: error.response?.data?.detail || "Revisa la configuración e inténtalo nuevamente." }); } finally { setSaving(false); } };
  if (!data) return <PlatformLoader title="Cargando estructura operacional" />;
  return <main className="space-y-6"><Toast {...toast} toastKey={toast?.id} onClose={() => setToast(null)} /><header><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Configuración</p><h1 className="mt-1 text-3xl font-black">Estructura operacional y flujos ambientales</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Actualiza dónde se origina o administra la información. Estas relaciones no asignan permisos ni responsabilidad legal.</p></header><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Áreas activas</h2><div className="mt-4 flex flex-wrap gap-2">{data.catalogos.areas.map((row) => <button type="button" key={row.tipo} aria-pressed={areas.includes(row.tipo)} onClick={() => toggleArea(row.tipo)} className={`rounded-full border px-4 py-2 text-sm font-bold ${areas.includes(row.tipo) ? "border-emerald-500 bg-emerald-100 text-emerald-900" : "border-slate-200 text-slate-600"}`}>{row.nombre}</button>)}</div><h2 className="mt-8 text-xl font-black">Flujos ambientales</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.catalogos.flujos.map((row) => { const selected = Object.hasOwn(flows, row.clave); return <div key={row.clave} className={`rounded-2xl border p-4 ${selected ? "border-emerald-300 bg-emerald-50/50" : "border-slate-200"}`}><button type="button" className="w-full text-left font-black" onClick={() => toggleFlow(row.clave)}>{selected ? "✓ " : ""}{row.nombre}</button>{selected && <Select className="mt-3" label="Disponibilidad" value={flows[row.clave]} onChange={(event) => setFlows({ ...flows, [row.clave]: event.target.value })}>{availability.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>}</div>})}</div>{areas.length > 0 && flowRows.length > 0 && <AreaFlowMatrix areas={areaRows} flows={flowRows} relations={relations} suggestions={data.catalogos.sugerencias} onChange={setRelations} />}<div className="mt-8 flex justify-end border-t border-slate-200 pt-5"><Button leftIcon={Save} loading={saving} onClick={save}>Guardar cambios</Button></div></section></main>;
}
