import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { Alert, Card, CardContent, ErrorState, LoadingState, PageHeader, StatusBadge } from "@/shared/ui";
import { getImport } from "../services/dataApi";

export default function ImportDetailPage() {
  const { processId } = useParams(); const { activeOrganizacionId } = useOrganizacionActiva(); const [state, setState] = useState({ loading: true, data: null, error: "" });
  useEffect(() => { let current = true; getImport(activeOrganizacionId, processId).then((data) => current && setState({ loading: false, data, error: "" })).catch(() => current && setState({ loading: false, data: null, error: "La importación no existe o no está disponible en esta organización." })); return () => { current = false; }; }, [activeOrganizacionId, processId]);
  if (state.loading) return <LoadingState label="Cargando importación" />; if (state.error) return <ErrorState description={state.error} />; const item = state.data; const records = item.registros_extraidos || [];
  return <main className="space-y-6"><Link className="inline-flex items-center gap-2 text-sm font-bold" to="/datos/importaciones"><ArrowLeft size={16} />Importaciones</Link><PageHeader eyebrow="Datos · Importaciones" title={item.version_evidencia_detalle?.nombre_original || item.fuente_nombre || "Detalle de importación"} description="Archivo recibido → extracción → normalización → revisión → confirmación." status={<StatusBadge label={item.estado?.replaceAll("_", " ")} />} />
    {!!item.resumen_errores?.length && <Alert tone="danger" title="La importación necesita atención">{item.resumen_errores.join?.(" · ") || JSON.stringify(item.resumen_errores)}</Alert>}
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardContent><h2 className="font-bold">Pipeline</h2><ol className="mt-3 space-y-3">{["Archivo recibido", "Extracción", "Normalización", "Revisión", "Confirmación"].map((label, index) => <li key={label} className="flex gap-3 text-sm"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[var(--info-bg)] font-bold">{index + 1}</span>{label}</li>)}</ol></CardContent></Card><Card><CardContent><h2 className="font-bold">Resumen</h2><dl className="mt-3 space-y-3 text-sm"><div><dt className="text-[var(--text-muted)]">Fuente de datos</dt><dd>{item.fuente_nombre || "Sin nombre"}</dd></div><div><dt className="text-[var(--text-muted)]">Evidencia</dt><dd>{item.version_evidencia_detalle?.evidencia_nombre || "Sin evidencia documental"}</dd></div><div><dt className="text-[var(--text-muted)]">Mapping</dt><dd>{item.plantilla?.nombre || "Mapping del proceso"}</dd></div><div><dt className="text-[var(--text-muted)]">Detectados / errores</dt><dd>{item.filas_detectadas || 0} / {item.filas_con_error || 0}</dd></div></dl></CardContent></Card></div>
    <Card><CardContent><h2 className="font-bold">Datos detectados</h2><div className="mt-3 max-h-96 space-y-2 overflow-auto">{records.slice(0, 50).map((record) => <details key={record.id} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-bold">Fila {record.numero_fila} · {record.estado?.replaceAll("_", " ")}</summary><div className="mt-2 grid gap-2 text-xs md:grid-cols-2"><pre className="overflow-auto rounded bg-[var(--bg-surface-subtle)] p-2">Original: {JSON.stringify(record.datos_originales, null, 2)}</pre><pre className="overflow-auto rounded bg-[var(--info-bg)] p-2">Normalizado: {JSON.stringify(record.datos_normalizados, null, 2)}</pre></div></details>)}</div></CardContent></Card>
  </main>;
}
