# Generated by Django 5.2.5 on 2026-09-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0076_material_substitution_scenario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_conversations",
                        to="analytics.obra",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="analytics.organizacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "Sistema"),
                            ("user", "Usuario"),
                            ("assistant", "Asistente"),
                            ("tool", "Herramienta"),
                        ],
                        max_length=12,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("tool_name", models.CharField(blank=True, max_length=80)),
                ("tool_call_id", models.CharField(blank=True, max_length=80)),
                ("tool_result", models.JSONField(blank=True, null=True)),
                ("provenance", models.JSONField(blank=True, default=list)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("tokens_input", models.PositiveIntegerField(blank=True, null=True)),
                ("tokens_output", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["organizacion", "usuario", "-updated_at"],
                name="ai_conversa_organiz_56950b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="ai_message_convers_0cc073_idx",
            ),
        ),
    ]
