from django.urls import path

from .views import (
    ai_advisor,
    auth_bootstrap,
    auth_csrf_token,
    auth_login,
    auth_logout,
    auth_me,
    calcular_distancia_ruta,
    constructora_configuracion,
    constructora_dashboard,
    constructora_estado,
    constructora_evidencias,
    constructora_obras,
    constructora_registros_emision,
    constructora_reportes,
    constructora_usuarios,
    constructoras,
    dashboard_data,
    factores_catalogo,
    factores_emision,
    materiales_construccion,
    obra_detail,
    obra_evidencias,
    obra_registros_emision,
    obra_transportes,
    obras,
    sistema_estado,
    verificar_obra,
)
from .views_constructoras import constructora_detail_safe
from .views_emisiones import constructora_emisiones
from .views_etapas import constructora_etapas
from .views_importaciones import (
    importacion_completa_confirm,
    importacion_completa_preview,
    importacion_confirm,
    importacion_preview,
    plantilla_importacion_construccion,
)

urlpatterns = [
    path("auth/me/", auth_me),
    path("auth/csrf-token/", auth_csrf_token),
    path("auth/login/", auth_login),
    path("auth/logout/", auth_logout),
    path("auth/bootstrap/", auth_bootstrap),
    path("dashboard/", dashboard_data),
    path("constructoras/", constructoras),
    path("constructoras/<str:constructora_id>/", constructora_detail_safe),
    path("constructoras/<str:constructora_id>/estado/", constructora_estado),
    path("constructoras/<str:constructora_id>/configuracion/", constructora_configuracion),
    path("constructoras/<str:constructora_id>/dashboard/", constructora_dashboard),
    path("constructoras/<str:constructora_id>/etapas/", constructora_etapas),
    path("constructoras/<str:constructora_id>/usuarios/", constructora_usuarios),
    path("constructoras/<str:constructora_id>/obras/", constructora_obras),
    path("constructoras/<str:constructora_id>/registros-emision/", constructora_registros_emision),
    path("constructoras/<str:constructora_id>/emisiones/", constructora_emisiones),
    path("constructoras/<str:constructora_id>/evidencias/", constructora_evidencias),
    path("constructoras/<str:constructora_id>/reportes/", constructora_reportes),
    path("importaciones/completa/preview/", importacion_completa_preview),
    path("importaciones/completa/confirm/", importacion_completa_confirm),
    path("importaciones/plantilla-construccion/", plantilla_importacion_construccion),
    path("constructoras/<str:constructora_id>/importaciones/<str:kind>/preview/", importacion_preview),
    path("constructoras/<str:constructora_id>/importaciones/<str:kind>/confirm/", importacion_confirm),
    path("importaciones/<str:kind>/preview/", importacion_preview),
    path("importaciones/<str:kind>/confirm/", importacion_confirm),
    path("obras/", obras),
    path("obras/<str:codigo_obra>/", obra_detail),
    path("obras/<str:codigo_obra>/registros-emision/", obra_registros_emision),
    path("obras/<str:codigo_obra>/evidencias/", obra_evidencias),
    path("obras/<str:codigo_obra>/transportes/", obra_transportes),
    path("verificar/obra/<str:codigo_obra>/", verificar_obra),
    path("factores-emision/", factores_emision),
    path("factores/catalogo/", factores_catalogo),
    path("materiales-construccion/", materiales_construccion),
    path("rutas/calcular-distancia/", calcular_distancia_ruta),
    path("sistema/estado/", sistema_estado),
    path("ai-advisor/", ai_advisor),
]
