from django.urls import path

from .views import (
    ai_advisor,
    auth_bootstrap,
    auth_csrf_token,
    auth_login,
    auth_logout,
    auth_me,
    calcular_distancia_ruta,
    constructora_configuracion,
    constructora_dashboard,
    constructora_estado,
    constructora_evidencias,
    constructora_evidencia_extraer,
    constructora_obras,
    constructora_registro_aplicar_factor,
    constructora_registros_emision,
    constructora_reportes,
    constructora_usuarios,
    constructoras,
    dashboard_data,
    factores_catalogo,
    factores_emision,
    factores_emision_detail,
    materiales_construccion,
    obra_detail,
    obra_evidencias,
    obra_registros_emision,
    obra_transportes,
    obras,
    sistema_estado,
    verificar_obra,
)
from .views_acciones import (
    constructora_accion_ambiental_detail,
    constructora_acciones_ambientales,
    constructora_acciones_ambientales_resumen,
)
from .views_constructoras import constructora_detail_safe
from .views_emisiones import constructora_emisiones
from .views_etapas import constructora_etapas
from .views_environmental_compliance import (
    alerta_cumplimiento_detail,
    alertas_cumplimiento,
    cumplimiento_ambiental_resumen,
    documento_ambiental_detail,
    documentos_ambientales,
    limite_ambiental_detail,
    limites_ambientales,
    variable_ambiental_detail,
    variables_ambientales,
)
from .views_environmental_action_closure import (
    environmental_action_attach_evidence,
    environmental_action_close,
    environmental_action_closure_status,
)
from .views_environmental_decision_actions import (
    environmental_decision_action_preview,
    environmental_decision_create_action,
)
from .views_environmental_decisions import environmental_decision_priorities
from .views_environmental_executive_report import environmental_executive_report
from .views_environmental_ingestion import environmental_ingestion_readiness
from .views_environmental_kpis import environmental_kpis
from .views_environmental_recommendations import environmental_recommendations
from .views_environmental_scenarios import environmental_scenarios
from .views_forestal import (
    constructora_lote_forestal_detail,
    constructora_lote_forestal_transportes,
    constructora_lotes_forestales,
    constructora_lotes_forestales_resumen,
)
from .views_importaciones import (
    importacion_completa_confirm,
    importacion_completa_preview,
    importacion_confirm,
    importacion_generica_preview,
    importacion_preview,
    plantilla_importacion_construccion,
    plantilla_importacion_generica,
)
from .views_recommendations import recommendation_context, recomendaciones

urlpatterns = [
    path("auth/me/", auth_me),
    path("auth/csrf-token/", auth_csrf_token),
    path("auth/login/", auth_login),
    path("auth/logout/", auth_logout),
    path("auth/bootstrap/", auth_bootstrap),
    path("dashboard/", dashboard_data),
    path("constructoras/", constructoras),
    path("constructoras/<str:constructora_id>/", constructora_detail_safe),
    path("constructoras/<str:constructora_id>/estado/", constructora_estado),
    path("constructoras/<str:constructora_id>/configuracion/", constructora_configuracion),
    path("constructoras/<str:constructora_id>/dashboard/", constructora_dashboard),
    path("constructoras/<str:constructora_id>/etapas/", constructora_etapas),
    path("constructoras/<str:constructora_id>/usuarios/", constructora_usuarios),
    path("constructoras/<str:constructora_id>/obras/", constructora_obras),
    path("constructoras/<str:constructora_id>/registros-emision/", constructora_registros_emision),
    path("constructoras/<str:constructora_id>/registros-emision/<int:registro_id>/aplicar-factor/", constructora_registro_aplicar_factor),
    path("constructoras/<str:constructora_id>/emisiones/", constructora_emisiones),
    path("constructoras/<str:constructora_id>/acciones-ambientales/resumen/", constructora_acciones_ambientales_resumen),
    path("constructoras/<str:constructora_id>/acciones-ambientales/", constructora_acciones_ambientales),
    path("constructoras/<str:constructora_id>/acciones-ambientales/<int:action_id>/", constructora_accion_ambiental_detail),
    path("constructoras/<str:constructora_id>/lotes-forestales/", constructora_lotes_forestales),
    path("constructoras/<str:constructora_id>/lotes-forestales/resumen/", constructora_lotes_forestales_resumen),
    path("constructoras/<str:constructora_id>/lotes-forestales/<str:lote_id>/transportes/", constructora_lote_forestal_transportes),
    path("constructoras/<str:constructora_id>/lotes-forestales/<str:lote_id>/", constructora_lote_forestal_detail),
    path("constructoras/<str:constructora_id>/evidencias/", constructora_evidencias),
    path("constructoras/<str:constructora_id>/evidencias/extraer/", constructora_evidencia_extraer),
    path("constructoras/<str:constructora_id>/reportes/", constructora_reportes),
    path("constructoras/<str:constructora_id>/documentos-ambientales/", documentos_ambientales),
    path("constructoras/<str:constructora_id>/documentos-ambientales/<int:documento_id>/", documento_ambiental_detail),
    path("constructoras/<str:constructora_id>/variables-ambientales/", variables_ambientales),
    path("constructoras/<str:constructora_id>/variables-ambientales/<int:variable_id>/", variable_ambiental_detail),
    path("constructoras/<str:constructora_id>/limites-ambientales/", limites_ambientales),
    path("constructoras/<str:constructora_id>/limites-ambientales/<int:limite_id>/", limite_ambiental_detail),
    path("constructoras/<str:constructora_id>/alertas-cumplimiento/", alertas_cumplimiento),
    path("constructoras/<str:constructora_id>/alertas-cumplimiento/<int:alerta_id>/", alerta_cumplimiento_detail),
    path("constructoras/<str:constructora_id>/cumplimiento-ambiental/resumen/", cumplimiento_ambiental_resumen),
    path("environmental/kpis/<str:constructora_id>/", environmental_kpis),
    path("environmental/recommendations/<str:constructora_id>/", environmental_recommendations),
    path("environmental/scenarios/<str:constructora_id>/", environmental_scenarios),
    path("environmental/decisions/priorities/<str:constructora_id>/", environmental_decision_priorities),
    path("environmental/executive-report/<str:constructora_id>/", environmental_executive_report),
    path("environmental/ingestion-readiness/<str:constructora_id>/", environmental_ingestion_readiness),
    path("environmental/decisions/priorities/<str:constructora_id>/<str:priority_id>/action-preview/", environmental_decision_action_preview),
    path("environmental/decisions/priorities/<str:constructora_id>/<str:priority_id>/create-action/", environmental_decision_create_action),
    path("environmental/actions/<int:action_id>/closure-status/", environmental_action_closure_status),
    path("environmental/actions/<int:action_id>/attach-evidence/", environmental_action_attach_evidence),
    path("environmental/actions/<int:action_id>/close/", environmental_action_close),
    path("importaciones/completa/preview/", importacion_completa_preview),
    path("importaciones/completa/confirm/", importacion_completa_confirm),
    path("importaciones/plantilla-construccion/", plantilla_importacion_construccion),
    path("importaciones/plantilla-generica/", plantilla_importacion_generica),
    path("importaciones/generica/preview/", importacion_generica_preview),
    path("constructoras/<str:constructora_id>/importaciones/<str:kind>/preview/", importacion_preview),
    path("constructoras/<str:constructora_id>/importaciones/<str:kind>/confirm/", importacion_confirm),
    path("importaciones/<str:kind>/preview/", importacion_preview),
    path("importaciones/<str:kind>/confirm/", importacion_confirm),
    path("obras/", obras),
    path("obras/<str:codigo_obra>/", obra_detail),
    path("obras/<str:codigo_obra>/registros-emision/", obra_registros_emision),
    path("obras/<str:codigo_obra>/evidencias/", obra_evidencias),
    path("obras/<str:codigo_obra>/transportes/", obra_transportes),
    path("verificar/obra/<str:codigo_obra>/", verificar_obra),
    path("factores-emision/", factores_emision),
    path("factores-emision/<int:factor_id>/", factores_emision_detail),
    path("factores/catalogo/", factores_catalogo),
    path("materiales-construccion/", materiales_construccion),
    path("rutas/calcular-distancia/", calcular_distancia_ruta),
    path("sistema/estado/", sistema_estado),
    path("ai-advisor/", ai_advisor),
    path("intelligence/context/", recommendation_context),
    path("intelligence/recommendations/", recomendaciones),
]
