# Generated by Django 5.2.5 on 2026-09-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvironmentalSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=80, unique=True)),
                ("nombre", models.CharField(max_length=160)),
                ("organismo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("connector_key", models.SlugField(max_length=80)),
                (
                    "tipo_acceso",
                    models.CharField(
                        choices=[
                            ("REST", "REST"),
                            ("CKAN", "CKAN"),
                            ("SPARQL", "SPARQL"),
                            ("ARCGIS_REST", "ArcGIS REST"),
                            ("WFS", "WFS"),
                            ("WMS", "WMS"),
                            ("FILE", "File"),
                            ("DOCUMENT_INDEX", "Document index"),
                        ],
                        max_length=30,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("licencia_nombre", models.CharField(blank=True, max_length=160)),
                ("licencia_url", models.URLField(blank=True)),
                ("atribucion_requerida", models.BooleanField(default=True)),
                ("nivel_autoridad", models.CharField(max_length=60)),
                ("pais", models.CharField(blank=True, max_length=80)),
                ("cadencia_sugerida", models.CharField(blank=True, max_length=80)),
                ("stale_after_hours", models.PositiveIntegerField(default=168)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nunca_sincronizada", "Nunca sincronizada"),
                            ("sincronizando", "Sincronizando"),
                            ("actualizada", "Actualizada"),
                            ("sin_cambios", "Sin cambios"),
                            ("parcial", "Parcial"),
                            ("error", "Error"),
                            ("desactualizada", "Desactualizada"),
                        ],
                        default="nunca_sincronizada",
                        max_length=30,
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("upstream_updated_at", models.DateTimeField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("upstream_version", models.CharField(blank=True, max_length=200)),
                ("cursor", models.JSONField(blank=True, null=True)),
                ("etag", models.CharField(blank=True, max_length=300)),
                ("last_modified", models.CharField(blank=True, max_length=300)),
                ("last_checksum", models.CharField(blank=True, max_length=64)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_state",
                        to="knowledge.environmentalsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("bootstrap", "Bootstrap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(default="sincronizando", max_length=30)),
                ("upstream_version", models.CharField(blank=True, max_length=200)),
                ("received", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("modified", models.PositiveIntegerField(default=0)),
                ("unchanged", models.PositiveIntegerField(default=0)),
                ("disappeared", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                ("initial_cursor", models.JSONField(blank=True, null=True)),
                ("final_cursor", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_runs",
                        to="knowledge.environmentalsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=300)),
                ("record_kind", models.CharField(max_length=100)),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("upstream_updated_at", models.DateTimeField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField()),
                ("content_hash", models.CharField(max_length=64)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="knowledge.environmentalsource",
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="knowledge.syncrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=300)),
                ("kind", models.CharField(max_length=100)),
                ("canonical_key", models.CharField(blank=True, max_length=300)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("upstream_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("no_observado", "No observado"),
                            ("retirado", "Retirado"),
                        ],
                        default="activo",
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="knowledge.environmentalsource",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_for",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="knowledge_record_identity",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="externalsnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id", "content_hash"),
                name="knowledge_snapshot_dedupe",
            ),
        ),
    ]
