# Generated by Django 5.2.5 on 2026-09-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalFileArtifact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_resource_id", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=500)),
                ("source_url", models.URLField()),
                ("format", models.CharField(max_length=30)),
                ("content_type", models.CharField(blank=True, max_length=160)),
                (
                    "expected_size",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("byte_size", models.PositiveBigIntegerField()),
                ("upstream_created_at", models.DateTimeField(blank=True, null=True)),
                ("upstream_modified_at", models.DateTimeField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField()),
                ("content_sha256", models.CharField(max_length=64)),
                (
                    "estado",
                    models.CharField(
                        choices=[("importado", "Importado")],
                        default="importado",
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_current", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField()),
                (
                    "parent_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_artifacts",
                        to="knowledge.externalrecord",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_artifacts",
                        to="knowledge.environmentalsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetcHazardousWasteFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_resource_id", models.CharField(max_length=300)),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                ("source_row_number", models.PositiveIntegerField()),
                ("row_hash", models.CharField(max_length=64)),
                ("id_vu", models.BigIntegerField()),
                ("id_rol_establecimiento", models.BigIntegerField()),
                ("rol_establecimiento", models.CharField(max_length=300)),
                ("rut_razon_social", models.CharField(max_length=30)),
                ("razon_social", models.CharField(blank=True, max_length=500)),
                ("ciiu6_id", models.CharField(blank=True, max_length=30)),
                ("ciiu6", models.CharField(blank=True, max_length=500)),
                ("ciiu4_id", models.CharField(blank=True, max_length=30)),
                ("ciiu4", models.CharField(blank=True, max_length=500)),
                ("rubro", models.CharField(blank=True, max_length=300)),
                ("rubro_id", models.BigIntegerField()),
                ("codigo_unico_territorial", models.BigIntegerField()),
                ("comuna", models.CharField(db_index=True, max_length=200)),
                ("provincia", models.CharField(max_length=200)),
                ("region", models.CharField(db_index=True, max_length=200)),
                ("latitud_raw", models.CharField(max_length=100)),
                ("longitud_raw", models.CharField(max_length=100)),
                (
                    "cantidad_kilos",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=24, null=True
                    ),
                ),
                (
                    "cantidad_toneladas",
                    models.DecimalField(decimal_places=9, max_digits=24),
                ),
                ("id_contaminantes", models.TextField(blank=True)),
                ("contaminantes", models.TextField(blank=True)),
                ("id_peligrosidad", models.TextField(blank=True)),
                ("peligrosidad", models.TextField(blank=True)),
                ("id_lista_a", models.TextField(blank=True)),
                ("lista_a", models.TextField(blank=True)),
                ("id_estado_materia", models.BigIntegerField()),
                ("estado_materia", models.CharField(max_length=100)),
                ("raw_row", models.JSONField()),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retc_hazardous_waste_facts",
                        to="knowledge.externalfileartifact",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="externalfileartifact",
            constraint=models.UniqueConstraint(
                fields=("source", "external_resource_id", "content_sha256"),
                name="knowledge_file_artifact_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalfileartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source", "external_resource_id"),
                name="knowledge_current_file_artifact",
            ),
        ),
        migrations.AddIndex(
            model_name="retchazardouswastefact",
            index=models.Index(
                fields=["artifact", "year", "region", "comuna"],
                name="knowledge_retc_fact_filter",
            ),
        ),
        migrations.AddConstraint(
            model_name="retchazardouswastefact",
            constraint=models.UniqueConstraint(
                fields=("artifact", "source_row_number"),
                name="knowledge_retc_fact_source_row",
            ),
        ),
    ]
