# Generated by Django 5.2.5 on 2026-09-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_externalfileartifact_retchazardouswastefact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HuellaChileEmissionFactorFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_name", models.CharField(max_length=200)),
                ("source_row_number", models.PositiveIntegerField()),
                ("row_hash", models.CharField(max_length=64)),
                ("raw_row", models.JSONField()),
                (
                    "publisher",
                    models.CharField(
                        default="Programa HuellaChile / Ministerio del Medio Ambiente",
                        max_length=200,
                    ),
                ),
                ("dataset_year", models.PositiveSmallIntegerField(db_index=True)),
                ("alcance", models.CharField(db_index=True, max_length=200)),
                ("categoria", models.CharField(db_index=True, max_length=300)),
                ("subcategoria", models.CharField(max_length=500)),
                ("actividad", models.CharField(db_index=True, max_length=500)),
                ("auxiliar", models.CharField(blank=True, max_length=500)),
                ("unidad_actividad", models.CharField(db_index=True, max_length=200)),
                (
                    "factor_value",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=30, null=True
                    ),
                ),
                ("published_value_raw", models.CharField(max_length=200)),
                ("unidad_factor", models.CharField(max_length=300)),
                ("technical_source_1", models.TextField(blank=True)),
                ("technical_source_2", models.TextField(blank=True)),
                ("technical_source_3", models.TextField(blank=True)),
                ("formula_original", models.TextField(blank=True)),
                ("cached_value_available", models.BooleanField(default=False)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="huellachile_emission_factor_facts",
                        to="knowledge.externalfileartifact",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["artifact", "dataset_year", "alcance", "categoria"],
                        name="knowledge_hc_factor_filter",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artifact", "sheet_name", "source_row_number"),
                        name="knowledge_hc_factor_source_row",
                    )
                ],
            },
        ),
    ]
