# Generated by Django 5.2.5 on 2026-09-06 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_huellachileemissionfactorfact"),
    ]

    operations = [
        migrations.CreateModel(
            name="BcnLegalNormFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("norm_uri", models.URLField(max_length=500)),
                ("identifier", models.CharField(blank=True, max_length=200)),
                ("number", models.CharField(db_index=True, max_length=60)),
                ("title", models.CharField(max_length=1000)),
                ("norm_type_uri", models.URLField(max_length=500)),
                ("norm_type_name", models.CharField(db_index=True, max_length=200)),
                ("issuer_uri", models.URLField(blank=True, max_length=500)),
                (
                    "issuer_name",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("promulgation_date", models.DateField(blank=True, null=True)),
                ("latest_version_uri", models.URLField(max_length=500)),
                ("latest_version_date", models.DateField(blank=True, null=True)),
                ("scope_tags", models.JSONField(blank=True, default=list)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bcn_legal_norm_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BcnLegalNormRelationFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=40)),
                ("target_uri", models.URLField(max_length=500)),
                ("target_number", models.CharField(blank=True, max_length=60)),
                ("target_title", models.CharField(blank=True, max_length=1000)),
                (
                    "norm_fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relations",
                        to="knowledge.bcnlegalnormfact",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("norm_fact", "relation_type", "target_uri"),
                        name="knowledge_bcn_relation_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BcnLegalNormSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("norm_type", models.CharField(max_length=30)),
                ("number", models.CharField(max_length=60)),
                ("label", models.CharField(max_length=300)),
                ("scope_tags", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_norm_subscriptions",
                        to="knowledge.environmentalsource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "norm_type", "number"),
                        name="knowledge_bcn_subscription_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BcnLegalNormVersionFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_uri", models.URLField(max_length=500)),
                ("version_date", models.DateField(blank=True, null=True)),
                ("is_latest", models.BooleanField(default=False)),
                ("xml_document_url", models.URLField(blank=True, max_length=500)),
                ("html_document_url", models.URLField(blank=True, max_length=500)),
                (
                    "norm_fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="knowledge.bcnlegalnormfact",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("norm_fact", "version_uri"),
                        name="knowledge_bcn_version_identity",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_latest", True)),
                        fields=("norm_fact",),
                        name="knowledge_bcn_one_latest_version",
                    ),
                ],
            },
        ),
    ]
