# Generated by Django 5.2.5 on 2026-09-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_bcnlegalnormfact_bcnlegalnormrelationfact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BcnLegalTextSourceDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_bytes", models.BinaryField()),
                ("detected_encoding", models.CharField(max_length=60)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bcn_legal_source_document",
                        to="knowledge.externalfileartifact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BcnLegalTextParse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parser_version", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        max_length=20,
                    ),
                ),
                ("parsed_at", models.DateTimeField()),
                ("article_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parses",
                        to="knowledge.bcnlegaltextsourcedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BcnLegalArticleFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_key", models.CharField(max_length=300)),
                (
                    "article_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "article_label",
                    models.CharField(blank=True, db_index=True, max_length=300),
                ),
                ("heading", models.TextField(blank=True)),
                ("order_index", models.PositiveIntegerField()),
                ("source_path", models.CharField(max_length=1000)),
                ("text_plain", models.TextField()),
                ("text_hash", models.CharField(max_length=64)),
                ("raw_fragment", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "parse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="knowledge.bcnlegaltextparse",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parse", "article_key"),
                        name="knowledge_bcn_article_identity",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bcnlegaltextparse",
            constraint=models.UniqueConstraint(
                fields=("source_document", "parser_version"),
                name="knowledge_bcn_text_parse_version",
            ),
        ),
    ]
