# Generated by Django 5.2.5 on 2026-09-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_bcnlegaltextsourcedocument_bcnlegaltextparse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BcnLegalObligationExtractionRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extractor_version", models.CharField(db_index=True, max_length=60)),
                ("extractor_method", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        max_length=20,
                    ),
                ),
                ("executed_at", models.DateTimeField()),
                ("source_text_hash", models.CharField(max_length=64)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligation_extraction_runs",
                        to="knowledge.bcnlegalarticlefact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BcnLegalObligationCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_key", models.CharField(db_index=True, max_length=64)),
                ("order_index", models.PositiveIntegerField()),
                (
                    "modality_hint",
                    models.CharField(
                        choices=[
                            ("obligation", "Obligation"),
                            ("prohibition", "Prohibition"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("trigger_text", models.TextField()),
                ("trigger_start", models.PositiveIntegerField()),
                ("trigger_end", models.PositiveIntegerField()),
                ("source_quote", models.TextField()),
                ("source_start", models.PositiveIntegerField()),
                ("source_end", models.PositiveIntegerField()),
                ("source_quote_hash", models.CharField(max_length=64)),
                ("subject_hint", models.TextField(blank=True)),
                ("subject_start", models.PositiveIntegerField(blank=True, null=True)),
                ("subject_end", models.PositiveIntegerField(blank=True, null=True)),
                ("action_hint", models.TextField(blank=True)),
                ("action_start", models.PositiveIntegerField(blank=True, null=True)),
                ("action_end", models.PositiveIntegerField(blank=True, null=True)),
                ("condition_hint", models.TextField(blank=True)),
                ("condition_start", models.PositiveIntegerField(blank=True, null=True)),
                ("condition_end", models.PositiveIntegerField(blank=True, null=True)),
                ("temporal_hint", models.TextField(blank=True)),
                ("temporal_start", models.PositiveIntegerField(blank=True, null=True)),
                ("temporal_end", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="knowledge.bcnlegalobligationextractionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.AddIndex(
            model_name="bcnlegalobligationextractionrun",
            index=models.Index(
                fields=["extractor_version", "status"],
                name="knowledge_bcn_obl_run_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="bcnlegalobligationextractionrun",
            constraint=models.UniqueConstraint(
                fields=("article", "extractor_version"),
                name="knowledge_bcn_obligation_run_version",
            ),
        ),
        migrations.AddIndex(
            model_name="bcnlegalobligationcandidate",
            index=models.Index(
                fields=["modality_hint", "candidate_key"],
                name="knowledge_bcn_obl_cand_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bcnlegalobligationcandidate",
            constraint=models.UniqueConstraint(
                fields=("extraction_run", "candidate_key"),
                name="knowledge_bcn_obligation_candidate_key",
            ),
        ),
    ]
