# Generated by Django 5.2.5 on 2026-09-06 14:25

import apps.knowledge.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0006_bcnlegalobligationextractionrun_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalObligation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.knowledge.models.legal_obligation_code,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalObligationVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validated", "Validated"),
                            ("active", "Active"),
                            ("obsolete", "Obsolete"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("obligation", "Obligation"),
                            ("prohibition", "Prohibition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("canonical_statement", models.TextField(blank=True)),
                ("subject_text", models.TextField(blank=True)),
                ("action_text", models.TextField(blank=True)),
                ("object_text", models.TextField(blank=True)),
                ("condition_text", models.TextField(blank=True)),
                ("temporal_text", models.TextField(blank=True)),
                (
                    "applicability_level",
                    models.CharField(
                        choices=[("organization", "Organization"), ("work", "Work")],
                        max_length=20,
                    ),
                ),
                (
                    "applicability_mode",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("unconditional", "Unconditional"),
                            ("conditional", "Conditional"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source_provenance", models.JSONField()),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("obsoleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activated_legal_obligation_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legal_obligation_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="knowledge.legalobligation",
                    ),
                ),
                (
                    "source_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promoted_version",
                        to="knowledge.bcnlegalobligationcandidate",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validated_legal_obligation_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegalObligationApplicabilityCriterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveIntegerField()),
                ("dimension", models.CharField(max_length=60)),
                (
                    "operator",
                    models.CharField(
                        choices=[("equals", "Equals"), ("in", "In")], max_length=20
                    ),
                ),
                ("values", models.JSONField()),
                ("note", models.TextField(blank=True)),
                (
                    "obligation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criteria",
                        to="knowledge.legalobligationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="BcnLegalObligationCandidateReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="knowledge.bcnlegalobligationcandidate",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_candidate_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promoted_obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_reviews",
                        to="knowledge.legalobligation",
                    ),
                ),
                (
                    "promoted_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_reviews",
                        to="knowledge.legalobligationversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="legalobligationversion",
            constraint=models.UniqueConstraint(
                fields=("obligation", "version"),
                name="knowledge_legal_obligation_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalobligationversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("obligation",),
                name="knowledge_one_active_legal_obligation",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalobligationapplicabilitycriterion",
            constraint=models.UniqueConstraint(
                fields=("obligation_version", "order_index"),
                name="knowledge_legal_criterion_order",
            ),
        ),
    ]
