# Generated by Django 5.2.5 on 2026-09-06 19:30

import apps.knowledge.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_legalobligation_legalobligationversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalEvidenceRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.knowledge.models.legal_evidence_requirement_code,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_requirements",
                        to="knowledge.legalobligation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegalEvidenceRequirementVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validated", "Validated"),
                            ("active", "Active"),
                            ("obsolete", "Obsolete"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("requirement_statement", models.TextField()),
                ("proof_objective", models.TextField()),
                (
                    "evidence_mode",
                    models.CharField(
                        choices=[("any_of", "Any of"), ("all_of", "All of")],
                        max_length=20,
                    ),
                ),
                ("evidence_classes", models.JSONField()),
                ("accepted_evidence_descriptions", models.JSONField()),
                (
                    "temporal_scope",
                    models.CharField(
                        choices=[
                            ("unspecified", "Unspecified"),
                            ("one_time", "One time"),
                            ("event_based", "Event based"),
                            ("periodic", "Periodic"),
                            ("current", "Current"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("legal_basis_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("obsoleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activated_legal_evidence_requirement_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legal_evidence_requirement_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_obligation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_requirement_versions",
                        to="knowledge.legalobligationversion",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="knowledge.legalevidencerequirement",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validated_legal_evidence_requirement_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("requirement", "version"),
                        name="knowledge_legal_evidence_req_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state", "active")),
                        fields=("requirement",),
                        name="knowledge_one_active_legal_evidence_req",
                    ),
                ],
            },
        ),
    ]
