# Generated by Django 5.2.5 on 2026-09-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0008_legalevidencerequirement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeaProjectFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_key", models.CharField(db_index=True, max_length=300)),
                ("folio", models.CharField(blank=True, db_index=True, max_length=200)),
                ("name", models.CharField(max_length=1000)),
                ("holder_name", models.CharField(blank=True, max_length=500)),
                ("region", models.CharField(blank=True, db_index=True, max_length=200)),
                ("communes", models.JSONField(blank=True, default=list)),
                (
                    "presentation_type_raw",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "status_raw",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                (
                    "sector_raw",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("project_type_raw", models.CharField(blank=True, max_length=1000)),
                ("admission_reason_raw", models.CharField(blank=True, max_length=1000)),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("qualification_date", models.DateField(blank=True, null=True)),
                ("project_url", models.URLField(max_length=1000)),
                ("expediente_url", models.URLField(blank=True, max_length=1000)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_project_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SnifaOpenDatasetFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_code", models.CharField(db_index=True, max_length=160)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("publisher", models.CharField(max_length=300)),
                ("source_url", models.URLField(max_length=1000)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snifa_open_dataset_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SnifaRegulatoryReferenceFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("inspection", "Inspection"),
                            ("sanctioning", "Sanctioning"),
                            ("final_sanction", "Final sanction"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("external_key", models.CharField(db_index=True, max_length=300)),
                (
                    "expediente",
                    models.CharField(blank=True, db_index=True, max_length=300),
                ),
                ("unit_external_key", models.CharField(blank=True, max_length=300)),
                ("unit_name", models.CharField(blank=True, max_length=500)),
                ("holder_name", models.CharField(blank=True, max_length=500)),
                ("category", models.CharField(blank=True, max_length=300)),
                ("region", models.CharField(blank=True, db_index=True, max_length=200)),
                (
                    "commune",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "status_raw",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("sanction_amount_raw", models.CharField(blank=True, max_length=300)),
                ("payment_status_raw", models.CharField(blank=True, max_length=300)),
                ("instrument_references", models.JSONField(blank=True, default=list)),
                ("source_url", models.URLField(max_length=1000)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snifa_regulatory_reference_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeaProjectSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_key", models.CharField(max_length=300)),
                ("project_url", models.URLField(max_length=1000)),
                ("label", models.CharField(max_length=500)),
                ("scope_tags", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_project_subscriptions",
                        to="knowledge.environmentalsource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "project_key"),
                        name="knowledge_sea_subscription_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeaRcaReferenceFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_key", models.CharField(max_length=300)),
                ("rca_number_raw", models.CharField(blank=True, max_length=300)),
                ("title", models.CharField(max_length=1000)),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "qualification_result_raw",
                    models.CharField(blank=True, max_length=500),
                ),
                ("document_url", models.URLField(max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "project_fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rca_references",
                        to="knowledge.seaprojectfact",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project_fact", "document_key"),
                        name="knowledge_sea_rca_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SnifaReferenceSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("inspection", "Inspection"),
                            ("sanctioning", "Sanctioning"),
                            ("final_sanction", "Final sanction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("external_key", models.CharField(max_length=300)),
                ("source_url", models.URLField(max_length=1000)),
                ("label", models.CharField(max_length=500)),
                ("scope_tags", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snifa_reference_subscriptions",
                        to="knowledge.environmentalsource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "reference_type", "external_key"),
                        name="knowledge_snifa_subscription_identity",
                    )
                ],
            },
        ),
    ]
