# Generated by Django 5.2.5 on 2026-09-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0009_snifa_sea_regulatory_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeMmaDatasetFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=300)),
                ("title", models.CharField(db_index=True, max_length=1000)),
                ("summary", models.TextField(blank=True)),
                ("metadata_standard", models.CharField(blank=True, max_length=300)),
                ("metadata_date", models.DateField(blank=True, null=True)),
                ("resource_date", models.DateField(blank=True, null=True)),
                ("organization_name", models.CharField(blank=True, max_length=500)),
                ("role_raw", models.CharField(blank=True, max_length=300)),
                (
                    "status_raw",
                    models.CharField(blank=True, db_index=True, max_length=300),
                ),
                ("resource_type_raw", models.CharField(blank=True, max_length=300)),
                ("language_raw", models.CharField(blank=True, max_length=100)),
                (
                    "geometry_type_raw",
                    models.CharField(blank=True, db_index=True, max_length=300),
                ),
                (
                    "feature_count",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("size_raw", models.CharField(blank=True, max_length=200)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("categories", models.JSONField(blank=True, default=list)),
                (
                    "bbox_west",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=15, null=True
                    ),
                ),
                (
                    "bbox_east",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=15, null=True
                    ),
                ),
                (
                    "bbox_south",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=15, null=True
                    ),
                ),
                (
                    "bbox_north",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=15, null=True
                    ),
                ),
                ("metadata_url", models.URLField(max_length=1000)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ide_mma_dataset_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdeMmaDownloadResourceFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_key", models.CharField(db_index=True, max_length=300)),
                ("title", models.CharField(db_index=True, max_length=1000)),
                (
                    "category_raw",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("declared_size_raw", models.CharField(blank=True, max_length=200)),
                ("download_url", models.URLField(max_length=1000)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ide_mma_download_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimbioGeoLayerFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_code", models.CharField(db_index=True, max_length=120)),
                ("service_name", models.CharField(max_length=300)),
                ("service_url", models.URLField(max_length=1000)),
                ("layer_id", models.PositiveIntegerField()),
                ("layer_name", models.CharField(db_index=True, max_length=500)),
                ("layer_url", models.URLField(max_length=1000)),
                ("geometry_type", models.CharField(db_index=True, max_length=100)),
                (
                    "spatial_reference_wkid",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("display_field", models.CharField(blank=True, max_length=300)),
                ("object_id_field", models.CharField(blank=True, max_length=300)),
                (
                    "max_record_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("supports_pagination", models.BooleanField(default=False)),
                ("supports_distance_query", models.BooleanField(default=False)),
                ("query_formats", models.JSONField(default=list)),
                ("fields_schema", models.JSONField(default=list)),
                ("service_item_id", models.CharField(blank=True, max_length=200)),
                ("provider_metadata", models.JSONField(default=dict)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simbio_geo_layer_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
