# Generated by Django 5.2.5 on 2026-09-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0010_geospatial_source_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="OekobaudatDataStockFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datastock_uuid", models.UUIDField(db_index=True)),
                ("short_name", models.CharField(db_index=True, max_length=240)),
                ("display_name", models.CharField(blank=True, max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("release_label", models.CharField(blank=True, max_length=240)),
                ("version_label", models.CharField(blank=True, max_length=120)),
                ("source_url", models.URLField()),
                ("upstream_metadata", models.JSONField(default=dict)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="okobaudat_datastock_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OekobaudatProcessFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datastock_uuid", models.UUIDField(db_index=True)),
                ("process_uuid", models.UUIDField(db_index=True)),
                ("dataset_version", models.CharField(db_index=True, max_length=40)),
                ("name", models.CharField(db_index=True, max_length=1000)),
                ("base_name", models.CharField(blank=True, max_length=1000)),
                (
                    "location_raw",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "dataset_type_raw",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "owner_raw",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("classification", models.JSONField(default=list)),
                ("languages", models.JSONField(default=dict)),
                (
                    "compliance_standard_raw",
                    models.CharField(db_index=True, default="unknown", max_length=160),
                ),
                ("compliance_source_uuid", models.CharField(blank=True, max_length=40)),
                ("permanent_uri", models.URLField(blank=True)),
                ("source_url", models.URLField()),
                ("process_metadata", models.JSONField(default=dict)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="okobaudat_process_fact",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "datastock_uuid",
                            "process_uuid",
                            "dataset_version",
                            "snapshot",
                        ),
                        name="knowledge_okobaudat_process_identity",
                    )
                ],
            },
        ),
    ]
