# Generated by Django 5.2.5 on 2026-09-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0011_oekobaudat_material_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OekobaudatEnvironmentalProfileFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_uuid", models.UUIDField(db_index=True)),
                ("dataset_version", models.CharField(db_index=True, max_length=40)),
                ("standard", models.CharField(db_index=True, max_length=20)),
                ("declared_amount", models.CharField(max_length=160)),
                ("declared_unit", models.CharField(max_length=160)),
                ("reference_metadata", models.JSONField(default=dict)),
                ("provenance", models.JSONField(default=dict)),
                (
                    "parser_version",
                    models.CharField(default="okobaudat-detail-1", max_length=60),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="environmental_profiles",
                        to="knowledge.oekobaudatprocessfact",
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="okobaudat_environmental_profile",
                        to="knowledge.externalsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OekobaudatEnvironmentalIndicatorFact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_uuid", models.UUIDField(db_index=True)),
                ("dataset_version", models.CharField(db_index=True, max_length=40)),
                ("standard", models.CharField(db_index=True, max_length=20)),
                ("upstream_uuid", models.UUIDField(db_index=True)),
                ("upstream_version", models.CharField(blank=True, max_length=40)),
                ("indicator_kind", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=1000)),
                ("code", models.CharField(db_index=True, max_length=80)),
                (
                    "module",
                    models.CharField(db_index=True, default="A1-A3", max_length=10),
                ),
                ("value", models.CharField(max_length=160)),
                ("unit", models.CharField(max_length=160)),
                ("unit_uuid", models.UUIDField()),
                ("unit_version", models.CharField(blank=True, max_length=40)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="okobaudat_environmental_indicators",
                        to="knowledge.externalsnapshot",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicators",
                        to="knowledge.oekobaudatenvironmentalprofilefact",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="oekobaudatenvironmentalprofilefact",
            constraint=models.UniqueConstraint(
                fields=("process_uuid", "dataset_version"),
                name="knowledge_obd_profile_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="oekobaudatenvironmentalindicatorfact",
            constraint=models.UniqueConstraint(
                fields=("profile", "indicator_kind", "upstream_uuid", "module"),
                name="knowledge_obd_indicator_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="oekobaudatenvironmentalindicatorfact",
            constraint=models.CheckConstraint(
                condition=models.Q(("module", "A1-A3")), name="knowledge_obd_a1a3_only"
            ),
        ),
    ]
