# Generated by Django 5.2.5 on 2026-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0013_okobaudat_detail_history_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalsource",
            name="cadencia_horas",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="environmentalsource",
            name="permite_poll_automatico",
            field=models.BooleanField(default=True),
        ),
    ]
