# Generated by Django 5.2.5 on 2026-09-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0014_source_watch_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrecord",
            name="missing_since_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disappearances_observed",
                to="knowledge.syncrun",
            ),
        ),
        migrations.AddField(
            model_name="syncrun",
            name="snapshot_autoritativo",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
