# Generated by Django 5.2.5 on 2026-09-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0015_change_observation_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrecord",
            name="reappeared_via_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reappearances_observed",
                to="knowledge.syncrun",
            ),
        ),
    ]
