# Generated by Django 5.2.5 on 2026-09-12 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0016_reappearance_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceWatchReviewItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=300)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("domain", models.CharField(max_length=40)),
                ("classification", models.CharField(max_length=60)),
                ("severity", models.CharField(max_length=20)),
                ("impact_level", models.CharField(max_length=30)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("affected_objects", models.JSONField(blank=True, default=list)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_items",
                        to="knowledge.environmentalsource",
                    ),
                ),
                (
                    "superseded_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="knowledge.sourcewatchreviewitem",
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_items",
                        to="knowledge.syncrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SourceWatchReviewDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_watch_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisiones",
                        to="knowledge.sourcewatchreviewitem",
                    ),
                ),
            ],
            options={
                "ordering": ["review_item_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="sourcewatchreviewitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado__in", ["open", "acknowledged", "resolved", "superseded"])
                ),
                name="knowledge_review_item_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcewatchreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decision__in", ["acknowledged", "resolved", "superseded"])
                ),
                name="knowledge_review_decision_valid",
            ),
        ),
    ]
