import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { Alert, Button, Card, CardContent, EmptyState, ErrorState, LoadingState, Modal, PageHeader, Select, StatusBadge, Textarea } from "@/shared/ui";
import { listProblems } from "@/features/mejora/services/improvementApi";
import { confirmCommand, createProposal, getProblemContext, getProposals, sendFeedback } from "../services/copilotApi";

export default function CopilotPage() {
  const { activeOrganizacionId } = useOrganizacionActiva(); const [problems, setProblems] = useState([]); const [problemId, setProblemId] = useState(""); const [state, setState] = useState({ loading: false, context: null, proposals: [], error: "" }); const [message, setMessage] = useState(""); const [dialog, setDialog] = useState(null); const [busy, setBusy] = useState(false);
  useEffect(() => { listProblems(activeOrganizacionId).then((items) => { setProblems(items); setProblemId((current) => current || String(items[0]?.id || "")); }).catch(() => setProblems([])); }, [activeOrganizacionId]);
  const load = useCallback(() => { if (!problemId) return; setState((current) => ({ ...current, loading: true, error: "" })); Promise.allSettled([getProblemContext(problemId), getProposals(problemId)]).then(([context, proposals]) => setState({ loading: false, context: context.status === "fulfilled" ? context.value : null, proposals: proposals.status === "fulfilled" ? proposals.value : [], error: context.status === "rejected" && proposals.status === "rejected" ? "Copiloto no disponible." : "" })); }, [problemId]);
  useEffect(() => { load(); }, [load]);
  async function propose() { setBusy(true); try { await createProposal(problemId, message); setMessage(""); load(); } catch { setState((current) => ({ ...current, error: "Copiloto no disponible. El dominio ambiental continúa operativo." })); } finally { setBusy(false); } }
  async function feedback(proposal, decision, refutation = "") { setBusy(true); try { const result = await sendFeedback(problemId, proposal.id, decision, refutation); if (result.requiere_confirmacion && result.comando) setDialog({ type: "command", command: result.comando, proposal }); else { setDialog(null); load(); } } catch { setState((current) => ({ ...current, error: "No se pudo procesar la decisión." })); } finally { setBusy(false); } }
  async function confirmDialog() { if (dialog.type !== "command") return feedback(dialog.proposal, "refutar", dialog.message); setBusy(true); try { await confirmCommand(dialog.command); setDialog(null); load(); } catch (error) { setState((current) => ({ ...current, error: error?.response?.data?.detail || "No se pudo confirmar la acción formal." })); } finally { setBusy(false); } }
  return <main className="space-y-6"><PageHeader eyebrow="Asesor ambiental contextual" title="Copiloto ambiental" description="Interpreta contexto preparado por backend; no calcula factores, balances, KPI ni CO₂e." />
    <Select label="Problema que aporta contexto" value={problemId} onChange={(event) => setProblemId(event.target.value)}><option value="">Selecciona un problema</option>{problems.map((item) => <option key={item.id} value={item.id}>{item.titulo}</option>)}</Select>
    {!problemId ? <EmptyState title="Selecciona un problema." description="El Copiloto necesita un contexto real y acotado." /> : state.loading ? <LoadingState label="Preparando contexto mínimo" /> : <><>{state.error && <ErrorState description={state.error} />}</><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><section className="space-y-4"><Card><CardContent><Textarea label="Consulta o restricción operacional" placeholder="Describe qué necesitas interpretar…" value={message} onChange={(event) => setMessage(event.target.value)} /><Button className="mt-3" disabled={!message.trim()} loading={busy} onClick={propose}>Preparar propuesta</Button></CardContent></Card>{!state.proposals.length ? <EmptyState title="No hay propuestas para este contexto." description="Una propuesta sólo se crea cuando el agente responde correctamente." /> : state.proposals.map((proposal) => <Card key={proposal.id}><CardContent><div className="flex justify-between gap-3"><h2 className="font-bold">{proposal.titulo}</h2><StatusBadge>{proposal.estado} · v{proposal.version}</StatusBadge></div><p className="mt-2 text-sm">{proposal.justificacion}</p><p className="mt-3 text-xs text-[var(--text-muted)]">KPIs: {proposal.kpis_afectados?.join(", ") || "Sin referencias KPI"}</p><p className="text-xs text-[var(--text-muted)]">Referencias: {proposal.referencias_contexto?.join(", ") || "Problema actual"}</p><p className="text-xs text-[var(--text-muted)]">Restricciones: {proposal.restricciones_consideradas?.join(", ") || "Ninguna informada"}</p>{["propuesta", "ajustada"].includes(proposal.estado) && <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={() => feedback(proposal, "aceptar")}>Aceptar</Button><Button size="sm" variant="secondary" onClick={() => setDialog({ type: "refute", proposal, message: "" })}>Refutar</Button><Button size="sm" variant="ghost" onClick={() => feedback(proposal, "rechazar")}>Rechazar</Button></div>}</CardContent></Card>)}</section><aside><Card><CardContent><h2 className="font-bold">Contexto considerado</h2><p className="mt-2 text-sm">Indicadores: {state.context?.kpis?.length ?? 0}</p><p className="text-sm">Acciones anteriores: {state.context?.acciones_probadas?.length ?? 0}</p><p className="text-sm">Restricciones: {state.context?.restricciones?.length ?? 0}</p><p className="text-sm">Evidencias resumidas: {state.context?.evidencia?.totales?.evidencias ?? 0}</p><p className="mt-3 text-xs text-[var(--text-muted)]">Se muestran referencias estructuradas, nunca razonamiento interno.</p><Link className="mt-4 inline-flex text-sm font-bold text-[var(--brand-primary)]" to={`/inteligencia/problemas/${problemId}`}>Ver ciclo de mejora</Link></CardContent></Card></aside></div></>}
    <Modal open={Boolean(dialog)} title={dialog?.type === "command" ? "Confirmar acción formal" : "Refutar propuesta"} description={dialog?.type === "command" ? "Se creará y seleccionará una acción formal dentro del ciclo UX-07." : "La restricción quedará registrada y podrá producir una alternativa."} onClose={() => setDialog(null)} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setDialog(null)}>Cancelar</Button><Button loading={busy} onClick={confirmDialog}>Confirmar</Button></div>}>{dialog?.type === "command" ? <Alert tone="warning">La IA no ejecuta la acción automáticamente. Esta confirmación humana crea el comando gobernado.</Alert> : <Textarea required label="Restricción o alternativa" value={dialog?.message || ""} onChange={(event) => setDialog({ ...dialog, message: event.target.value })} />}</Modal>
  </main>;
}
