import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { Card, CardContent, EmptyState, ErrorState, LoadingState, PageHeader, SectionHeader, StatusBadge } from "@/shared/ui";
import { getEnvironmentalDecisionPriorities } from "@/features/environmental/services/environmentalDecisionPriorityApi";
import { getEnvironmentalRecommendations } from "@/features/environmental/services/environmentalRecommendationApi";
import { getEnvironmentalScenarios } from "@/features/environmental/services/environmentalScenarioApi";

const rows = (value) => Array.isArray(value) ? value : value?.results || value?.items || [];
function Block({ title, description, resource, empty, render }) { return <section><SectionHeader title={title} description={description} />{resource.status === "loading" ? <LoadingState label={`Cargando ${title.toLowerCase()}`} /> : resource.status === "error" ? <ErrorState description={`No fue posible cargar ${title.toLowerCase()}. Las demás señales permanecen disponibles.`} /> : !resource.data.length ? <EmptyState title={empty} description="Carbono Zero no completa este espacio con contenido ficticio." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{resource.data.map(render)}</div>}</section>; }
export default function IntelligencePage() {
  const { activeOrganizacionId } = useOrganizacionActiva(); const [state, setState] = useState({ priorities: { status: "loading", data: [] }, recommendations: { status: "loading", data: [] }, scenarios: { status: "loading", data: [] } });
  useEffect(() => { let current = true; Promise.allSettled([getEnvironmentalDecisionPriorities(activeOrganizacionId), getEnvironmentalRecommendations(activeOrganizacionId), getEnvironmentalScenarios(activeOrganizacionId)]).then((results) => { if (!current) return; const names = ["priorities", "recommendations", "scenarios"]; setState(Object.fromEntries(results.map((result, index) => [names[index], result.status === "fulfilled" ? { status: "ready", data: rows(result.value) } : { status: "error", data: [] }]))); }); return () => { current = false; }; }, [activeOrganizacionId]);
  return <main className="space-y-8"><PageHeader eyebrow="Inteligencia operacional" title="Señales que merecen atención" description="Análisis determinístico producido por backend a partir de los datos disponibles." actions={<><Link className="rounded-lg border px-4 py-2 text-sm font-bold" to="/inteligencia/problemas">Problemas y mejora</Link><Link className="rounded-lg bg-[var(--brand-primary)] px-4 py-2 text-sm font-bold text-white" to="/inteligencia/copiloto">Abrir Copiloto</Link></>} />
    <Block title="Prioridades" description="Decisiones pendientes entregadas por el motor." resource={state.priorities} empty="No hay prioridades disponibles con los datos actuales." render={(item, index) => <Card key={item.id || index}><CardContent><div className="flex justify-between gap-2"><h3 className="font-bold">{item.titulo || item.nombre || item.area || "Prioridad ambiental"}</h3>{item.prioridad && <StatusBadge tone="warning">{item.prioridad}</StatusBadge>}</div><p className="mt-2 text-sm text-[var(--text-secondary)]">{item.descripcion || item.justificacion || item.motivo || "Sin descripción adicional."}</p>{item.problematica && <Link className="mt-3 inline-flex text-sm font-bold text-[var(--brand-primary)]" to={`/inteligencia/problemas/${item.problematica}`}>Ver problema</Link>}</CardContent></Card>} />
    <Block title="Recomendaciones determinísticas" description="No son propuestas de IA ni acciones implementadas." resource={state.recommendations} empty="No hay recomendaciones disponibles con los datos actuales." render={(item, index) => <Card key={item.id || index}><CardContent><h3 className="font-bold">{item.titulo || item.nombre || "Recomendación"}</h3><p className="mt-2 text-sm text-[var(--text-secondary)]">{item.descripcion || item.recomendacion || item.detalle}</p><p className="mt-3 text-xs text-[var(--text-muted)]">{item.fuente || item.origen || "Motor determinístico"}</p></CardContent></Card>} />
    <Block title="Escenarios" description="Resultados producidos por backend; no se generan escenarios visuales de relleno." resource={state.scenarios} empty="No hay escenarios disponibles con los datos actuales." render={(item, index) => <Card key={item.id || index}><CardContent><div className="flex justify-between gap-2"><h3 className="font-bold">{item.nombre || item.titulo || "Escenario"}</h3>{item.estado && <StatusBadge>{item.estado}</StatusBadge>}</div><p className="mt-2 text-sm text-[var(--text-secondary)]">{item.descripcion || item.resumen || "Sin resumen disponible."}</p>{item.valor !== null && item.valor !== undefined && <p className="mt-3 font-bold">{item.valor} {item.unidad || ""}</p>}</CardContent></Card>} />
  </main>;
}
