import { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronDown, Search, X } from "lucide-react";
import { filterSelectOptions } from "@/shared/utils/search";

export default function SelectField({ label, value = "", options = [], onChange, placeholder = "Selecciona una opción", searchPlaceholder = "Buscar...", searchable = false, required = false, disabled = false, error, helper, clearable = false, onBlur, id }) {
  const generatedId = useId(); const inputId = id || generatedId; const listId = `${inputId}-listbox`; const messageId = `${inputId}-message`;
  const triggerRef = useRef(null); const panelRef = useRef(null); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [activeIndex, setActiveIndex] = useState(0); const [position, setPosition] = useState(null);
  const selected = options.find((option) => String(option.value) === String(value));
  const filtered = useMemo(() => filterSelectOptions(options, query), [options, query]);
  const close = useCallback(() => { setOpen(false); setQuery(""); onBlur?.(); }, [onBlur]);
  const choose = (option) => { if (!options.some((item) => String(item.value) === String(option.value))) return; onChange?.(option.value, option); close(); triggerRef.current?.focus(); };
  const place = useCallback(() => { const rect = triggerRef.current?.getBoundingClientRect(); if (!rect) return; const roomBelow = window.innerHeight - rect.bottom; const above = roomBelow < 340 && rect.top > roomBelow; const height = Math.min(320, above ? rect.top - 12 : roomBelow - 12); setPosition({ left: Math.max(8, Math.min(rect.left, window.innerWidth - rect.width - 8)), width: rect.width, maxHeight: Math.max(180, height), ...(above ? { bottom: window.innerHeight - rect.top + 6 } : { top: rect.bottom + 6 }) }); }, []);
  useEffect(() => { if (!open) return undefined; place(); const outside = (event) => { if (!triggerRef.current?.contains(event.target) && !panelRef.current?.contains(event.target)) close(); }; window.addEventListener("resize", place); window.addEventListener("scroll", place, true); document.addEventListener("mousedown", outside); return () => { window.removeEventListener("resize", place); window.removeEventListener("scroll", place, true); document.removeEventListener("mousedown", outside); }; }, [close, open, place]);
  useEffect(() => { setActiveIndex(0); }, [query, open]);
  const keyDown = (event) => { if (disabled) return; if (event.key === "Escape" && open) { event.preventDefault(); event.stopPropagation(); close(); triggerRef.current?.focus(); } else if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); if (!open) { setOpen(true); return; } setActiveIndex((current) => Math.max(0, Math.min(filtered.length - 1, current + (event.key === "ArrowDown" ? 1 : -1)))); } else if (event.key === "Enter" || event.key === " ") { if (!open) { event.preventDefault(); setOpen(true); } else if (!searchable || event.key === "Enter") { event.preventDefault(); if (filtered[activeIndex]) choose(filtered[activeIndex]); } } else if (event.key === "Tab") close(); };
  const panel = open && position && createPortal(<div ref={panelRef} style={position} className="fixed z-[90] flex flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl" onKeyDown={keyDown}>{searchable && <div className="relative border-b border-slate-100 p-2"><Search aria-hidden="true" className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input autoFocus role="searchbox" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={searchPlaceholder} className="min-h-10 w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-emerald-600" /></div>}<div id={listId} role="listbox" className="min-h-0 overflow-y-auto p-1.5">{filtered.length ? filtered.map((option, index) => { const isSelected = String(option.value) === String(value); return <button id={`${listId}-${index}`} key={option.value} type="button" role="option" aria-selected={isSelected} onMouseEnter={() => setActiveIndex(index)} onClick={() => choose(option)} className={`flex w-full items-center justify-between gap-3 rounded-lg px-3 py-2.5 text-left text-sm outline-none ${index === activeIndex ? "bg-emerald-50 text-emerald-950" : "hover:bg-slate-50"} ${isSelected ? "font-bold" : ""}`}><span className="truncate">{option.label}</span>{isSelected && <Check className="shrink-0 text-emerald-700" size={16} />}</button>; }) : <p className="px-3 py-8 text-center text-sm text-slate-500">No encontramos resultados</p>}</div></div>, document.body);
  return <div className="block text-sm"><label id={`${inputId}-label`} htmlFor={inputId} className={`mb-1.5 block font-bold ${error ? "text-[var(--status-danger)]" : "text-[var(--text-secondary)]"}`}>{label}{required && <><span aria-hidden="true"> *</span><span className="sr-only"> (obligatorio)</span></>}</label><div className="relative"><button ref={triggerRef} id={inputId} type="button" role="combobox" aria-labelledby={`${inputId}-label`} aria-expanded={open} aria-controls={listId} aria-haspopup="listbox" aria-activedescendant={open && filtered[activeIndex] ? `${listId}-${activeIndex}` : undefined} aria-invalid={error ? "true" : undefined} aria-describedby={error || helper ? messageId : undefined} disabled={disabled} onClick={() => { setOpen((current) => !current); }} onKeyDown={keyDown} className={`flex min-h-11 w-full items-center justify-between gap-2 rounded-[var(--radius-md)] border bg-[var(--bg-surface)] px-3 py-2.5 text-left text-sm shadow-sm transition focus-visible:outline-none focus-visible:shadow-[var(--focus-ring)] disabled:cursor-not-allowed disabled:bg-[var(--bg-surface-subtle)] disabled:text-[var(--text-muted)] ${error ? "border-[var(--status-danger)]" : "border-[var(--border-default)] hover:border-[var(--border-strong)]"}`}><span className={`truncate ${selected ? "text-[var(--text-primary)]" : "text-[var(--text-muted)]"}`}>{selected?.label || placeholder}</span><span className="flex shrink-0 items-center gap-1">{clearable && selected && !required && <span role="button" tabIndex={-1} aria-label="Limpiar selección" onClick={(event) => { event.stopPropagation(); onChange?.(""); }}><X size={15} /></span>}<ChevronDown size={17} className={`transition ${open ? "rotate-180" : ""}`} /></span></button></div>{error ? <span id={messageId} role="alert" className="mt-1.5 block text-xs font-medium text-[var(--status-danger)]">{error}</span> : helper && <span id={messageId} className="mt-1.5 block text-xs text-[var(--text-muted)]">{helper}</span>}{panel}</div>;
}
