import { useCallback, useEffect, useState } from "react";
import { ClipboardCheck, Download, FileCheck2 } from "lucide-react";
import { addReviewFinding, closeDossier, decideReview, generateDossierReport, getDossier, getDossiers, getEnvironmentalAudit, getProfessionalReviews, reopenDossier, reportPdfUrl, validateProfessionalReport } from "../api/professionalV2Api";

const dossierTabs=["resumen","antecedentes","calculos","intervenciones","revisiones","informes","auditoria"];

export default function ProfessionalReviewWorkspace({organizationId}){
  const [reviews,setReviews]=useState([]); const [dossiers,setDossiers]=useState([]); const [audit,setAudit]=useState([]); const [selected,setSelected]=useState(null); const [tab,setTab]=useState("resumen"); const [filters,setFilters]=useState({tipo:"",estado:"pendiente"}); const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!organizationId)return; const [reviewRows,dossierRows,auditRows]=await Promise.all([getProfessionalReviews(organizationId,Object.fromEntries(Object.entries(filters).filter(([,v])=>v))),getDossiers(organizationId),getEnvironmentalAudit(organizationId)]); setReviews(reviewRows);setDossiers(dossierRows);setAudit(auditRows);if(dossierRows.length)setSelected(await getDossier(organizationId,dossierRows[0].id));},[organizationId,filters]);
  useEffect(()=>{load().catch(()=>setError("No se pudo cargar la revisión profesional."));},[load]);
  async function finding(review){const observation=window.prompt("Hallazgo profesional:");if(!observation)return;await addReviewFinding(organizationId,review.id,{tipo:"observacion",severidad:"media",observacion:observation});await load();}
  async function decision(review,state){const conclusion=window.prompt("Conclusión profesional:");if(!conclusion)return;await decideReview(organizationId,review.id,{estado:state,conclusion});await load();}
  async function generate(){const report=await generateDossierReport(organizationId,selected.id);setSelected({...selected,informe_vigente:{id:report.id,version:report.version,estado:report.estado,checksum:report.checksum_sha256}});}
  async function validateReport(){await validateProfessionalReport(organizationId,selected.informe_vigente.id);await load();}
  return <section className="mt-8 space-y-6"><div className="rounded-[32px] border border-blue-200 bg-white p-6 shadow-[var(--shadow-card)]"><div className="flex items-start gap-3"><ClipboardCheck className="text-blue-700"/><div><p className="text-xs font-black uppercase tracking-[0.22em] text-blue-700">Revisión profesional</p><h2 className="text-2xl font-black">Pendientes de revisión</h2><p className="text-sm text-slate-600">Las decisiones requieren un usuario autorizado y nunca editan datos históricos.</p></div></div><div className="mt-4 flex gap-2"><select value={filters.tipo} onChange={e=>setFilters({...filters,tipo:e.target.value})} className="rounded-xl border p-2 text-sm"><option value="">Todos los tipos</option>{["evidencia","observacion","calculo","indicador","problematica","intervencion","expediente"].map(x=><option key={x}>{x}</option>)}</select><select value={filters.estado} onChange={e=>setFilters({...filters,estado:e.target.value})} className="rounded-xl border p-2 text-sm"><option value="">Todos los estados</option>{["pendiente","validada","validada_con_observaciones","solicita_antecedentes","rechazada"].map(x=><option key={x}>{x}</option>)}</select></div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-4 grid gap-3 md:grid-cols-2">{reviews.map(review=><article key={review.id} className="rounded-2xl border p-4"><div className="flex justify-between"><b>{review.tipo} #{review.id}</b><span className="text-xs font-black">{review.estado}</span></div><p className="mt-2 text-xs text-slate-500">Versión {review.version} · {review.hallazgos.length} hallazgos</p>{review.estado==="pendiente"&&<div className="mt-3 flex flex-wrap gap-2"><Button onClick={()=>finding(review)}>Agregar hallazgo</Button><Button onClick={()=>decision(review,"validada")}>Validar</Button><Button onClick={()=>decision(review,"validada_con_observaciones")}>Validar con observaciones</Button><Button onClick={()=>decision(review,"solicita_antecedentes")}>Solicitar antecedentes</Button><Button onClick={()=>decision(review,"rechazada")}>Rechazar</Button></div>}</article>)}</div></div>
  <div className="rounded-[32px] border border-slate-200 bg-white p-6 shadow-[var(--shadow-card)]"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><FileCheck2/><div><p className="text-xs font-black uppercase text-slate-500">Expediente técnico</p><h2 className="text-2xl font-black">Versiones, informes y auditoría</h2></div></div><select value={selected?.id||""} onChange={async e=>setSelected(await getDossier(organizationId,e.target.value))} className="rounded-xl border p-3">{dossiers.map(item=><option key={item.id} value={item.id}>{item.problematica_titulo} · v{item.version}</option>)}</select></div>{selected&&<><div className="mt-4 flex flex-wrap gap-2">{dossierTabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-xl px-3 py-2 text-xs font-black uppercase ${tab===item?"bg-slate-900 text-white":"bg-slate-100"}`}>{item}</button>)}</div>{tab==="resumen"&&<Grid data={{Estado:selected.estado,Problemática:selected.problematica_titulo,Responsable:selected.responsable||"—",Ciclos:selected.referencias?.ciclos?.length||0,"Última revisión":selected.ultima_revision?.estado||"Pendiente"}}/>}{tab==="antecedentes"&&<Json value={selected.referencias}/>} {tab==="calculos"&&<Json value={{calculos:selected.referencias?.calculos||[],impactos:selected.referencias?.impactos||[]}}/>}{tab==="intervenciones"&&<Json value={{ciclos:selected.referencias?.ciclos||[],snapshots:selected.referencias?.snapshots||[],resultados:selected.referencias?.resultados||[]}}/>}{tab==="revisiones"&&<Json value={selected.ultima_revision||{estado:"Sin revisión"}}/>}{tab==="auditoria"&&<Json value={audit.slice(0,30)}/>} {tab==="informes"&&<div className="mt-5 rounded-2xl bg-slate-50 p-4">{selected.informe_vigente?<><p className="font-black">Informe v{selected.informe_vigente.version} · {selected.informe_vigente.estado}</p><p className="mt-2 break-all font-mono text-xs">SHA-256: {selected.informe_vigente.checksum}</p><div className="mt-3 flex gap-2"><a href={reportPdfUrl(organizationId,selected.informe_vigente.id)} className="inline-flex items-center gap-2 rounded-lg bg-blue-700 px-3 py-2 text-xs font-black text-white"><Download size={15}/>Descargar PDF</a>{selected.informe_vigente.estado!=="validado"&&<Button onClick={validateReport}>Validar versión</Button>}</div></>:<p className="text-sm text-slate-500">Sin informe generado.</p>}<Button onClick={generate}>Generar nueva versión</Button></div>}<div className="mt-4 flex gap-2">{selected.estado!=="cerrado"?<Button onClick={async()=>{await closeDossier(organizationId,selected.id);await load();}}>Cerrar expediente</Button>:<Button onClick={async()=>{const reason=window.prompt("Motivo de reapertura:");if(reason){await reopenDossier(organizationId,selected.id,reason);await load();}}}>Reabrir</Button>}</div></>}</div></section>;
}
function Button({children,onClick}){return <button type="button" onClick={onClick} className="mt-2 rounded-lg border bg-white px-3 py-2 text-xs font-black">{children}</button>}
function Grid({data}){return <div className="mt-5 grid gap-3 md:grid-cols-3">{Object.entries(data).map(([key,value])=><div key={key} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">{key}</p><p className="font-bold">{value}</p></div>)}</div>}
function Json({value}){return <pre className="mt-5 max-h-80 overflow-auto rounded-2xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(value,null,2)}</pre>}
