import { useCallback, useEffect, useState } from "react";
import { Boxes } from "lucide-react";
import { getOrganizacionEvidencias, getOrganizacionObras } from "@/shared/services/api";
import { getActividades, getFuentes } from "../api/activityCoreApi";
import { createMaterial, createMaterialEvent, createMaterialLot, getMaterialBalance, getMaterialEvents, getMaterialLineage, getMaterialLots, getMaterials } from "../api/materialsV2Api";

const MATERIAL = { codigo: "", nombre: "", categoria: "", unidad_base: "" };
const LOT = { codigo: "", proveedor: "", referencia_documental: "", cantidad_inicial: "", unidad: "" };
const EVENT = { lote: "", actividad: "", tipo: "recepcion", fecha_hora: new Date().toISOString().slice(0, 16), cantidad: "", unidad: "", origen: "", destino: "", obra: "", proceso: "", fuente: "", evidencia: "", evento_origen: "" };
const TYPES = ["adquisicion", "despacho", "recepcion", "almacenamiento", "uso", "consumo", "traslado", "sobrante", "devolucion", "reutilizacion", "residuo", "ajuste"];
const clean = (data) => Object.fromEntries(Object.entries(data).filter(([, value]) => value !== ""));

export default function MaterialsOperationalPanel({ organizacionId }) {
  const [materials, setMaterials] = useState([]); const [lots, setLots] = useState([]); const [events, setEvents] = useState([]);
  const [activities, setActivities] = useState([]); const [sources, setSources] = useState([]); const [works, setWorks] = useState([]); const [evidence, setEvidence] = useState([]);
  const [selected, setSelected] = useState(""); const [balance, setBalance] = useState(null); const [lineage, setLineage] = useState(null);
  const [materialForm, setMaterialForm] = useState(MATERIAL); const [lotForm, setLotForm] = useState(LOT); const [eventForm, setEventForm] = useState(EVENT); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!organizacionId) return; const [m, a, f, w, e] = await Promise.all([getMaterials(organizacionId), getActividades(organizacionId, { tipo: "movimiento_material" }), getFuentes(organizacionId), getOrganizacionObras(organizacionId), getOrganizacionEvidencias(organizacionId)]); setMaterials(m); setActivities(a); setSources(f); setWorks(w); setEvidence(e); }, [organizacionId]);
  const loadTrace = useCallback(async (id) => { if (!id) return; const [l, e, b, t] = await Promise.all([getMaterialLots(organizacionId, id), getMaterialEvents(organizacionId, id), getMaterialBalance(organizacionId, id), getMaterialLineage(organizacionId, id)]); setLots(l); setEvents(e); setBalance(b); setLineage(t); }, [organizacionId]);
  useEffect(() => { load().catch(() => setError("No se pudieron cargar los materiales.")); }, [load]);
  useEffect(() => { if (selected) loadTrace(selected).catch(() => setError("No se pudo cargar la trazabilidad.")); }, [loadTrace, selected]);
  const bind = (form, setter, key) => (event) => setter({ ...form, [key]: event.target.value });
  async function addMaterial() { try { const row = await createMaterial(organizacionId, materialForm); setMaterialForm(MATERIAL); await load(); setSelected(String(row.id)); } catch (e) { setError(JSON.stringify(e?.response?.data || "No se pudo registrar.")); } }
  async function addLot() { try { await createMaterialLot(organizacionId, clean({ ...lotForm, material: selected })); setLotForm(LOT); await loadTrace(selected); } catch (e) { setError(JSON.stringify(e?.response?.data || "No se pudo registrar el lote.")); } }
  async function addEvent() { try { await createMaterialEvent(organizacionId, clean({ ...eventForm, material: selected })); setEventForm(EVENT); await loadTrace(selected); } catch (e) { setError(JSON.stringify(e?.response?.data || "No se pudo registrar el evento.")); } }
  return <section className="rounded-[32px] border border-amber-200 bg-white p-6 shadow-[var(--shadow-card)]"><div className="flex gap-3"><Boxes className="text-amber-700"/><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-700">Materiales operacionales</p><h2 className="text-2xl font-black">Trazabilidad de materiales</h2><p className="text-sm text-slate-600">Compra, recepción y uso permanecen como hechos distintos con fuente y evidencia.</p></div></div>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}
  <div className="mt-5 grid gap-2 md:grid-cols-5"><Input label="Código" value={materialForm.codigo} onChange={bind(materialForm,setMaterialForm,"codigo")}/><Input label="Nombre" value={materialForm.nombre} onChange={bind(materialForm,setMaterialForm,"nombre")}/><Input label="Categoría" value={materialForm.categoria} onChange={bind(materialForm,setMaterialForm,"categoria")}/><Input label="Unidad base" value={materialForm.unidad_base} onChange={bind(materialForm,setMaterialForm,"unidad_base")}/><Button onClick={addMaterial}>Registrar material</Button></div>
  <Select label="Material" value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Seleccionar</option>{materials.map((x) => <option key={x.id} value={x.id}>{x.codigo} · {x.nombre}</option>)}</Select>
  {selected && <><div className="mt-4 grid gap-2 md:grid-cols-6"><Input label="Lote/partida" value={lotForm.codigo} onChange={bind(lotForm,setLotForm,"codigo")}/><Input label="Proveedor" value={lotForm.proveedor} onChange={bind(lotForm,setLotForm,"proveedor")}/><Input label="Referencia documental" value={lotForm.referencia_documental} onChange={bind(lotForm,setLotForm,"referencia_documental")}/><Input label="Cantidad inicial" type="number" step="any" value={lotForm.cantidad_inicial} onChange={bind(lotForm,setLotForm,"cantidad_inicial")}/><Input label="Unidad" value={lotForm.unidad} onChange={bind(lotForm,setLotForm,"unidad")}/><Button onClick={addLot}>Agregar lote</Button></div>
  <div className="mt-4 grid gap-2 md:grid-cols-4"><Select label="Tipo" value={eventForm.tipo} onChange={bind(eventForm,setEventForm,"tipo")}>{TYPES.map((x) => <option key={x}>{x}</option>)}</Select><Select label="Actividad" value={eventForm.actividad} onChange={bind(eventForm,setEventForm,"actividad")}><option value="">Seleccionar</option>{activities.map((x) => <option key={x.id} value={x.id}>{x.codigo} · {x.nombre}</option>)}</Select><Select label="Lote opcional" value={eventForm.lote} onChange={bind(eventForm,setEventForm,"lote")}><option value="">Sin lote</option>{lots.map((x) => <option key={x.id} value={x.id}>{x.codigo}</option>)}</Select><Input label="Fecha/hora" type="datetime-local" value={eventForm.fecha_hora} onChange={bind(eventForm,setEventForm,"fecha_hora")}/><Input label="Cantidad" type="number" step="any" value={eventForm.cantidad} onChange={bind(eventForm,setEventForm,"cantidad")}/><Input label="Unidad" value={eventForm.unidad} onChange={bind(eventForm,setEventForm,"unidad")}/><Select label="Fuente" value={eventForm.fuente} onChange={bind(eventForm,setEventForm,"fuente")}><option value="">Seleccionar</option>{sources.map((x) => <option key={x.id} value={x.id}>{x.nombre}</option>)}</Select><Select label="Evidencia" value={eventForm.evidencia} onChange={bind(eventForm,setEventForm,"evidencia")}><option value="">Sin evidencia</option>{evidence.map((x) => <option key={x.id} value={x.id}>{x.nombre}</option>)}</Select><Input label="Origen" value={eventForm.origen} onChange={bind(eventForm,setEventForm,"origen")}/><Input label="Destino" value={eventForm.destino} onChange={bind(eventForm,setEventForm,"destino")}/><Select label="Obra" value={eventForm.obra} onChange={bind(eventForm,setEventForm,"obra")}><option value="">Sin obra</option>{works.map((x) => <option key={x.id} value={x.id}>{x.nombre}</option>)}</Select><Select label="Proceso" value={eventForm.proceso} onChange={bind(eventForm,setEventForm,"proceso")}><option value="">Sin proceso</option>{activities.filter((x) => x.proceso_operacional).map((x) => <option key={x.proceso_operacional} value={x.proceso_operacional}>{x.proceso_nombre}</option>)}</Select><Select label="Evento origen" value={eventForm.evento_origen} onChange={bind(eventForm,setEventForm,"evento_origen")}><option value="">Sin vínculo</option>{events.map((x) => <option key={x.id} value={x.id}>{x.tipo} · {String(x.fecha_hora).slice(0,10)}</option>)}</Select><Button onClick={addEvent}>Registrar evento</Button></div>
  <div className="mt-5 grid gap-2 md:grid-cols-3">{(balance?.balances || []).map((x,i) => <div key={`${x.unidad}-${i}`} className="rounded-xl bg-amber-50 p-3"><b>{x.unidad || "Sin unidad"} · {x.calidad_balance}</b><p>Recibido {x.cantidad_recibida ?? "—"} · Usado {x.cantidad_utilizada ?? "—"} · Stock {x.stock_restante ?? "—"}</p></div>)}</div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left"><th>Fecha</th><th>Evento</th><th>Lote</th><th>Cantidad</th><th>Origen → destino</th><th>Obra/proceso</th></tr></thead><tbody>{(lineage?.eventos || []).map((x) => <tr key={x.id} className="border-b"><td className="py-3">{String(x.fecha_hora).slice(0,10)}</td><td className="font-black">{x.tipo}</td><td>{x.lote_id || "—"}</td><td>{x.cantidad ?? "—"} {x.unidad || ""}</td><td>{x.origen || "—"} → {x.destino || "—"}</td><td>{x.obra_id || "—"} / {x.proceso_id || "—"}</td></tr>)}</tbody></table></div></>}
  </section>;
}
const Input=({label,...props})=><label className="text-xs font-black">{label}<input {...props} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label>;
const Select=({label,children,...props})=><label className="text-xs font-black">{label}<select {...props} className="mt-1 w-full rounded-xl border p-3 font-normal">{children}</select></label>;
const Button=({children,...props})=><button {...props} type="button" className="self-end rounded-xl bg-amber-700 px-4 py-3 font-black text-white">{children}</button>;
