import { useCallback, useEffect, useState } from "react";
import { Truck } from "lucide-react";
import { getAssets } from "@/features/activos/api/assetsApi";
import { getActividades, getFuentes } from "../api/activityCoreApi";
import { createJourney, getJourneys, getTransportIndicators, updateJourney } from "../api/transportV2Api";

const initial={actividad:"",codigo:"",vehiculo:"",origen_nombre:"",destino_nombre:"",fecha_salida:new Date().toISOString().slice(0,16),distancia:"",carga:"",combustible:"",fuente:"",estado_carga:"desconocido",tipo_trayecto:"ida",tipo_gestion:"propio",estado:"completado"};
export default function TransportJourneyPanel({organizacionId}){
  const [rows,setRows]=useState([]);const [summary,setSummary]=useState(null);const [activities,setActivities]=useState([]);const [assets,setAssets]=useState([]);const [sources,setSources]=useState([]);const [form,setForm]=useState(initial);const [editing,setEditing]=useState(null);const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!organizacionId)return;const [journeys,indicators,activityRows,assetRows,sourceRows]=await Promise.all([getJourneys(organizacionId),getTransportIndicators(organizacionId),getActividades(organizacionId,{tipo:"transporte"}),getAssets(organizacionId,{tipo:"vehiculo"}),getFuentes(organizacionId)]);setRows(journeys);setSummary(indicators);setActivities(activityRows);setAssets(assetRows.filter(x=>x.vehiculo));setSources(sourceRows);},[organizacionId]);
  useEffect(()=>{load().catch(()=>setError("No se pudo cargar transporte operacional."));},[load]);
  const set=(key)=>(event)=>setForm({...form,[key]:event.target.value});
  async function save(){try{const payload=Object.fromEntries(Object.entries(form).filter(([,v])=>v!==""));if(editing)await updateJourney(organizacionId,editing,payload);else await createJourney(organizacionId,payload);setForm(initial);setEditing(null);await load();}catch(requestError){setError(JSON.stringify(requestError?.response?.data||"No se pudo guardar el viaje."));}}
  function edit(row){setEditing(row.id);setForm({...initial,...row,actividad:row.actividad,vehiculo:row.vehiculo,distancia:"",carga:"",combustible:"",fuente:"",fecha_salida:String(row.fecha_salida).slice(0,16)});}
  return <section className="mt-8 rounded-[32px] border border-cyan-200 bg-white p-6 shadow-[var(--shadow-card)]"><div className="flex items-start gap-3"><Truck className="text-cyan-700"/><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-700">Transporte operacional</p><h2 className="text-2xl font-black">Viajes reales</h2><p className="text-sm text-slate-600">Las variables conservan su fuente como observaciones de Activity Core.</p></div></div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}
  {summary&&<div className="mt-4 grid gap-2 md:grid-cols-5"><Metric label="Viajes" value={summary.numero_viajes}/><Metric label="Km totales" value={summary.km_totales}/><Metric label="Km vacíos" value={summary.km_sin_carga}/><Metric label="t·km" value={summary.toneladas_km}/><Metric label="Combustible L" value={summary.combustible_total}/></div>}
  <div className="mt-5 grid gap-2 md:grid-cols-4"> <Select label="Actividad" value={form.actividad} onChange={set("actividad")}><option value="">Seleccionar</option>{activities.map(x=><option key={x.id} value={x.id}>{x.codigo}</option>)}</Select><Input label="Código" value={form.codigo} onChange={set("codigo")}/><Select label="Vehículo" value={form.vehiculo} onChange={set("vehiculo")}><option value="">Seleccionar</option>{assets.map(x=><option key={x.vehiculo.id} value={x.vehiculo.id}>{x.codigo} · {x.vehiculo.patente||"sin patente"}</option>)}</Select><Select label="Fuente variables" value={form.fuente} onChange={set("fuente")}><option value="">Seleccionar</option>{sources.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</Select><Input label="Origen" value={form.origen_nombre} onChange={set("origen_nombre")}/><Input label="Destino" value={form.destino_nombre} onChange={set("destino_nombre")}/><Input label="Salida" type="datetime-local" value={form.fecha_salida} onChange={set("fecha_salida")}/><Input label="Km" type="number" step="any" value={form.distancia} onChange={set("distancia")}/><Input label="Carga t" type="number" step="any" value={form.carga} onChange={set("carga")}/><Input label="Combustible L" type="number" step="any" value={form.combustible} onChange={set("combustible")}/><Select label="Carga" value={form.estado_carga} onChange={set("estado_carga")}>{["desconocido","cargado","parcialmente_cargado","vacio"].map(x=><option key={x}>{x}</option>)}</Select><Select label="Trayecto" value={form.tipo_trayecto} onChange={set("tipo_trayecto")}>{["ida","retorno","interno","otro"].map(x=><option key={x}>{x}</option>)}</Select><Select label="Gestión" value={form.tipo_gestion} onChange={set("tipo_gestion")}><option value="propio">propio</option><option value="tercerizado">tercerizado</option></Select><button onClick={save} className="rounded-xl bg-cyan-700 px-4 py-3 font-black text-white">{editing?"Actualizar":"Guardar viaje"}</button></div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left"><th>Viaje</th><th>Ruta</th><th>Vehículo</th><th>Km</th><th>Carga</th><th>Combustible</th><th>Retorno</th><th>Fuente</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>edit(x)} className="cursor-pointer border-b"><td className="py-3 font-black">{x.codigo}</td><td>{x.origen_nombre} → {x.destino_nombre}</td><td>{x.vehiculo_detalle?.patente||x.vehiculo_detalle?.codigo}</td><td>{x.metricas.distancia_km??"—"}</td><td>{x.metricas.carga_t??"—"}</td><td>{x.metricas.combustible_l??"—"}</td><td>{x.tipo_trayecto} · {x.estado_carga}</td><td>{x.distancia_detalle?.fuente_detalle?.nombre||x.carga_detalle?.fuente_detalle?.nombre||"—"}</td></tr>)}</tbody></table></div></section>;
}
const Input=({label,...props})=><label className="text-xs font-black">{label}<input {...props} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label>;
const Select=({label,children,...props})=><label className="text-xs font-black">{label}<select {...props} className="mt-1 w-full rounded-xl border p-3 font-normal">{children}</select></label>;
const Metric=({label,value})=><div className="rounded-xl bg-cyan-50 p-3"><p className="text-xs font-black uppercase text-cyan-800">{label}</p><p className="text-lg font-black">{value??"—"}</p></div>;
