import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import TraceabilityDrawer from "@/features/datos/components/TraceabilityDrawer";
import { Button, Card, CardContent, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, SectionHeader, StatusBadge, TableBody, TableCell, TableHead, TableShell, TraceabilityLink } from "@/shared/ui";
import { formatDate, formatDateTime, formatNumber } from "@/shared/utils/formatters";
import { createCalibration, createInstallation, createReading, getSensor } from "../api/sensorsApi";

export default function SensorDetailPage() { const { sensorId } = useParams(); const { activeOrganizacionId } = useOrganizacionActiva(); const [state, setState] = useState({ loading: true, sensor: null, error: "" }); const [dialog, setDialog] = useState(null); const [trace, setTrace] = useState(null); const [busy, setBusy] = useState(false); const load = useCallback(() => { getSensor(activeOrganizacionId, sensorId).then((sensor) => setState({ loading: false, sensor, error: "" })).catch(() => setState({ loading: false, sensor: null, error: "El sensor no existe o no está disponible." })); }, [activeOrganizacionId, sensorId]); useEffect(() => { load(); }, [load]); async function save(call) { setBusy(true); try { await call(); setDialog(null); load(); } finally { setBusy(false); } }
  if (state.loading) return <LoadingState label="Cargando sensor" />; if (state.error) return <ErrorState description={state.error} />; const sensor = state.sensor;
  return <main className="space-y-7"><Link className="inline-flex items-center gap-2 text-sm font-bold" to="/operacion/sensores"><ArrowLeft size={16} />Sensores</Link><PageHeader eyebrow="Telemetría operacional" title={sensor.nombre} description={`${sensor.dispositivo_id} · ${sensor.tipo_sensor}. Las lecturas son hechos observados, no cálculos ambientales.`} status={<StatusBadge>{sensor.estado.replaceAll("_", " ")}</StatusBadge>} />
    <section><SectionHeader title="Resumen" /><div className="grid gap-4 md:grid-cols-3"><Card><CardContent><p className="text-xs text-[var(--text-muted)]">Activo asociado</p><p className="font-bold">{sensor.activo_nombre || "Sin activo"}</p></CardContent></Card><Card><CardContent><p className="text-xs text-[var(--text-muted)]">Última comunicación</p><p className="font-bold">{formatDateTime(sensor.last_seen_at)}</p></CardContent></Card><Card><CardContent><p className="text-xs text-[var(--text-muted)]">Próxima calibración</p><p className="font-bold">{sensor.proxima_calibracion || "Sin datos"}</p></CardContent></Card></div></section>
    <section><SectionHeader title="Instalación" action={<Button variant="secondary" onClick={() => setDialog({ type: "installation", activo: sensor.activo_operacional || "", fecha_instalacion: new Date().toISOString().slice(0, 10), ubicacion: sensor.ubicacion || "", estado: "activa" })}>Registrar instalación</Button>} />{!sensor.instalaciones?.length ? <EmptyState title="Sin instalaciones registradas." description="El activo actual no sustituye el historial de instalación." /> : <div className="grid gap-3 md:grid-cols-2">{sensor.instalaciones.map((item) => <Card key={item.id}><CardContent><b>{item.activo_nombre || item.ubicacion || "Instalación"}</b><p className="text-sm">{formatDate(item.fecha_instalacion)} · {item.estado}</p></CardContent></Card>)}</div>}</section>
    <section><SectionHeader title="Calibración" action={<Button variant="secondary" onClick={() => setDialog({ type: "calibration", fecha: new Date().toISOString().slice(0, 10), tipo: "Verificación", resultado: "aprobada", fecha_proxima_calibracion: "" })}>Registrar calibración</Button>} />{!sensor.calibraciones?.length ? <EmptyState title="Sin calibraciones registradas." description="No se afirma validez científica sin resultado backend." /> : <TableShell><TableHead><tr><TableCell as="th">Fecha</TableCell><TableCell as="th">Tipo</TableCell><TableCell as="th">Resultado</TableCell><TableCell as="th">Próxima</TableCell></tr></TableHead><TableBody columns={4}>{sensor.calibraciones.map((item) => <tr key={item.id}><TableCell>{formatDate(item.fecha)}</TableCell><TableCell>{item.tipo}</TableCell><TableCell><StatusBadge>{item.resultado}</StatusBadge></TableCell><TableCell>{item.fecha_proxima_calibracion || "Sin datos"}</TableCell></tr>)}</TableBody></TableShell>}</section>
    <section><SectionHeader title="Lecturas" description="La medición instrumental se distingue de la forma de ingreso y de la calidad ambiental." action={<Button onClick={() => setDialog({ type: "reading", timestamp: new Date().toISOString().slice(0, 16), concepto: "", valor_numerico: "", unidad: "", metadata_tecnica: { origen_ingreso: "manual" } })}>Registrar lectura manual</Button>} />{!sensor.lecturas?.length ? <EmptyState title="Este sensor aún no tiene lecturas." description="Una ausencia de lecturas no equivale a valor cero." /> : <TableShell><TableHead><tr><TableCell as="th">Fecha</TableCell><TableCell as="th">Concepto</TableCell><TableCell as="th">Valor</TableCell><TableCell as="th">Medición</TableCell><TableCell as="th">Ingreso</TableCell><TableCell as="th">Calidad técnica</TableCell><TableCell as="th">Dato observado</TableCell></tr></TableHead><TableBody columns={7}>{sensor.lecturas.map((item) => <tr key={item.id}><TableCell>{formatDateTime(item.timestamp)}</TableCell><TableCell>{item.concepto}</TableCell><TableCell>{formatNumber(item.valor_numerico)} {item.unidad}</TableCell><TableCell>Instrumental</TableCell><TableCell>{item.metadata_tecnica?.origen_ingreso === "manual" ? "Manual" : "Ingreso no informado"}</TableCell><TableCell><StatusBadge>{item.calidad_tecnica}</StatusBadge></TableCell><TableCell>{item.observacion_id ? <TraceabilityLink onClick={() => setTrace({ provenance_type: "sensor_reading", reading: item, sensor_name: sensor.nombre })} /> : "Sin observación"}</TableCell></tr>)}</TableBody></TableShell>}</section>
    <Modal open={Boolean(dialog)} title={dialog?.type === "reading" ? "Registrar lectura manual" : dialog?.type === "calibration" ? "Registrar calibración" : "Registrar instalación"} onClose={() => setDialog(null)} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setDialog(null)}>Cancelar</Button><Button loading={busy} onClick={() => save(() => dialog.type === "reading" ? createReading(activeOrganizacionId, sensor.id, dialog) : dialog.type === "calibration" ? createCalibration(activeOrganizacionId, sensor.id, dialog) : createInstallation(activeOrganizacionId, sensor.id, dialog))}>Guardar</Button></div>}><div className="space-y-4">{dialog?.type === "reading" && <><Input type="datetime-local" label="Timestamp" value={dialog.timestamp} onChange={(e) => setDialog({ ...dialog, timestamp: e.target.value })} /><Input label="Concepto observado" value={dialog.concepto} onChange={(e) => setDialog({ ...dialog, concepto: e.target.value })} /><Input type="number" step="any" label="Valor" value={dialog.valor_numerico} onChange={(e) => setDialog({ ...dialog, valor_numerico: e.target.value })} /><Input label="Unidad" value={dialog.unidad} onChange={(e) => setDialog({ ...dialog, unidad: e.target.value })} /></>}{dialog?.type === "calibration" && <><Input type="date" label="Fecha" value={dialog.fecha} onChange={(e) => setDialog({ ...dialog, fecha: e.target.value })} /><Input label="Tipo" value={dialog.tipo} onChange={(e) => setDialog({ ...dialog, tipo: e.target.value })} /><Input label="Resultado" value={dialog.resultado} onChange={(e) => setDialog({ ...dialog, resultado: e.target.value })} /><Input type="date" label="Próxima calibración" value={dialog.fecha_proxima_calibracion} onChange={(e) => setDialog({ ...dialog, fecha_proxima_calibracion: e.target.value })} /></>}{dialog?.type === "installation" && <><Input type="date" label="Fecha" value={dialog.fecha_instalacion} onChange={(e) => setDialog({ ...dialog, fecha_instalacion: e.target.value })} /><Input label="Ubicación" value={dialog.ubicacion} onChange={(e) => setDialog({ ...dialog, ubicacion: e.target.value })} /></>}</div></Modal><TraceabilityDrawer observation={trace} open={Boolean(trace)} onClose={() => setTrace(null)} />
  </main>; }
