import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Plus } from "lucide-react";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { getAssets } from "@/features/activos/api/assetsApi";
import { Button, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, Select, StatusBadge, TableBody, TableCell, TableHead, TableShell } from "@/shared/ui";
import { formatDateTime } from "@/shared/utils/formatters";
import { createSensor, getSensors } from "../api/sensorsApi";

const initial = { dispositivo_id: "", nombre: "", tipo_sensor: "gps", estado: "operativo", activo_operacional: "" };
export default function SensoresPage() { const { activeOrganizacionId } = useOrganizacionActiva(); const [state, setState] = useState({ loading: true, sensors: [], assets: [], error: "" }); const [form, setForm] = useState(null); const [busy, setBusy] = useState(false); const load = useCallback(() => { Promise.allSettled([getSensors(activeOrganizacionId), getAssets(activeOrganizacionId)]).then(([sensors, assets]) => setState({ loading: false, sensors: sensors.status === "fulfilled" ? sensors.value : [], assets: assets.status === "fulfilled" ? assets.value : [], error: sensors.status === "rejected" ? "No fue posible cargar los sensores." : "" })); }, [activeOrganizacionId]); useEffect(() => { load(); }, [load]);
  async function save() { setBusy(true); try { await createSensor(activeOrganizacionId, Object.fromEntries(Object.entries(form).filter(([, value]) => value !== ""))); setForm(null); load(); } finally { setBusy(false); } }
  return <main className="space-y-6"><PageHeader eyebrow="Operación · Telemetría" title="Sensores" description="Dispositivos, condición técnica y variables observadas. Ninguna lectura se presenta como CO₂e directo." actions={<Button leftIcon={Plus} onClick={() => setForm(initial)}>Crear sensor</Button>} />{state.error ? <ErrorState description={state.error} onRetry={load} /> : state.loading ? <LoadingState label="Cargando sensores" /> : !state.sensors.length ? <EmptyState title="No hay sensores registrados." description="Registra un dispositivo sólo cuando exista en la operación." /> : <TableShell><TableHead><tr><TableCell as="th">Sensor</TableCell><TableCell as="th">Tipo</TableCell><TableCell as="th">Activo</TableCell><TableCell as="th">Estado técnico</TableCell><TableCell as="th">Última comunicación</TableCell><TableCell as="th">Calibración</TableCell><TableCell as="th">Acción</TableCell></tr></TableHead><TableBody columns={7}>{state.sensors.map((sensor) => <tr key={sensor.id}><TableCell><b>{sensor.nombre}</b><span className="block text-xs text-[var(--text-muted)]">{sensor.dispositivo_id}</span></TableCell><TableCell>{sensor.tipo_sensor}</TableCell><TableCell>{sensor.activo_nombre || "Sin activo asociado"}</TableCell><TableCell><StatusBadge>{sensor.estado.replaceAll("_", " ")}</StatusBadge></TableCell><TableCell>{formatDateTime(sensor.last_seen_at)}</TableCell><TableCell>{sensor.ultima_calibracion || "Sin calibración"} → {sensor.proxima_calibracion || "Sin fecha próxima"}</TableCell><TableCell><Link className="font-bold text-[var(--brand-primary)]" to={`/operacion/sensores/${sensor.id}`}>Ver detalle</Link></TableCell></tr>)}</TableBody></TableShell>}
    <Modal open={Boolean(form)} title="Crear sensor" description="El sensor producirá lecturas y observaciones, no emisiones automáticas." onClose={() => setForm(null)} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setForm(null)}>Cancelar</Button><Button loading={busy} onClick={save}>Crear</Button></div>}><div className="space-y-4"><Input required label="Identificador del dispositivo" value={form?.dispositivo_id || ""} onChange={(e) => setForm({ ...form, dispositivo_id: e.target.value })} /><Input required label="Nombre" value={form?.nombre || ""} onChange={(e) => setForm({ ...form, nombre: e.target.value })} /><Select label="Tipo de variable" value={form?.tipo_sensor || "gps"} onChange={(e) => setForm({ ...form, tipo_sensor: e.target.value })}>{["gps", "combustible", "energia", "maquinaria", "agua", "ambiente", "mixto"].map((v) => <option key={v}>{v}</option>)}</Select><Select label="Activo asociado" value={form?.activo_operacional || ""} onChange={(e) => setForm({ ...form, activo_operacional: e.target.value })}><option value="">Sin activo</option>{state.assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.nombre}</option>)}</Select></div></Modal>
  </main>; }
