import { useCallback, useEffect, useState } from "react";
import { Database, Plus } from "lucide-react";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import { listOperationalMaterials } from "@/features/operacion/api/materialsApi";
import { createFactorAmbientalV2, getFactoresAmbientalesV2, getMetodologiasAmbientales } from "@/shared/services/api";
import { Alert, Button, Card, CardContent, EmptyState, ErrorState, Input, Modal, PageHeader, Select, StatusBadge } from "@/shared/ui";
import { humanizeApiError } from "@/shared/utils/apiErrors";

const empty = { material:"",nombre:"",valor:"",unidad_entrada:"kg",unidad_resultado:"kgCO2e",fuente_tipo:"epd",fuente:"",referencia:"",alcance_ciclo_vida:"A1-A3",region:"",vigencia_desde:"",vigencia_hasta:"" };
function FactorModal({ open, close, organizationId, materials, reload }) {
  const [form,setForm]=useState(empty); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(open){setForm(empty);setError("");}},[open]); const field=(key)=>(event)=>setForm({...form,[key]:event.target.value});
  async function submit(event){event.preventDefault();setSaving(true);try{await createFactorAmbientalV2(organizationId,{...form,material:Number(form.material)});await reload();close();}catch(requestError){setError(humanizeApiError(requestError,"No fue posible registrar el factor."));}finally{setSaving(false);}}
  return <Modal open={open} onClose={close} eyebrow="GOBERNANZA CIENTÍFICA" icon={Database} title="Registrar factor" description="El factor quedará en borrador hasta completar su revisión gobernada."><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
    <Select required label="Material" value={form.material} onChange={(event)=>{const material=materials.find((item)=>String(item.id)===event.target.value);setForm({...form,material:event.target.value,nombre:material?`Factor de ${material.nombre}`:""});}}><option value="">Selecciona un material</option>{materials.map((item)=><option key={item.id} value={item.id}>{item.nombre}</option>)}</Select>
    <Input label="Nombre del factor" value={form.nombre} onChange={field("nombre")}/><Input required type="number" step="any" label="Valor" value={form.valor} onChange={field("valor")}/>
    <Select required label="Unidad del material" value={form.unidad_entrada} onChange={field("unidad_entrada")}>{["kg","t","m3","L","unidad"].map((unit)=><option key={unit}>{unit}</option>)}</Select>
    <Select required label="Unidad del resultado" value={form.unidad_resultado} onChange={field("unidad_resultado")}><option>kgCO2e</option><option>tCO2e</option></Select>
    <Select required label="Tipo de fuente" value={form.fuente_tipo} onChange={field("fuente_tipo")}><option value="epd">EPD</option><option value="base_oficial">Base oficial</option><option value="organizacion">Factor específico de organización</option><option value="otra_fuente_tecnica">Otra fuente técnica</option></Select>
    <Input required label="Fuente" value={form.fuente} onChange={field("fuente")}/><Input required label="Referencia" value={form.referencia} onChange={field("referencia")}/>
    <Select required label="Alcance de ciclo de vida" value={form.alcance_ciclo_vida} onChange={field("alcance_ciclo_vida")}><option>A1-A3</option><option>A1-A5</option><option value="otro_declarado">Otro / declarado por fuente</option></Select>
    <Input label="Región" value={form.region} onChange={field("region")}/><Input type="date" label="Vigencia desde" value={form.vigencia_desde} onChange={field("vigencia_desde")}/><Input type="date" label="Vigencia hasta" value={form.vigencia_hasta} onChange={field("vigencia_hasta")}/>
    {error&&<div className="sm:col-span-2"><Alert tone="danger">{error}</Alert></div>}<div className="sm:col-span-2 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancelar</Button><Button type="submit" loading={saving}>Registrar factor</Button></div>
  </form></Modal>;
}
export default function FactoresPage(){const{activeOrganizacionId}=useOrganizacionActiva();const[factors,setFactors]=useState([]);const[methods,setMethods]=useState([]);const[materials,setMaterials]=useState([]);const[error,setError]=useState(false);const[open,setOpen]=useState(false);const load=useCallback(async()=>{const[f,m,mat]=await Promise.allSettled([getFactoresAmbientalesV2(activeOrganizacionId),getMetodologiasAmbientales(activeOrganizacionId),listOperationalMaterials(activeOrganizacionId)]);setFactors(f.status==="fulfilled"?f.value:[]);setMethods(m.status==="fulfilled"?m.value:[]);setMaterials(mat.status==="fulfilled"?(Array.isArray(mat.value)?mat.value:mat.value.results||[]):[]);setError(f.status==="rejected"||m.status==="rejected");},[activeOrganizacionId]);useEffect(()=>{if(activeOrganizacionId)load();},[activeOrganizacionId,load]);return <main className="space-y-8"><PageHeader eyebrow="Gobernanza científica" title="Factores y metodologías" description="Recursos globales y privados que soportan cálculos gobernados."/><section className="space-y-3"><div className="flex justify-between"><h2 className="text-xl font-black">Factores ambientales versionados</h2><Button leftIcon={Plus} onClick={()=>setOpen(true)}>Registrar factor</Button></div>{error?<ErrorState/>:!factors.length?<EmptyState title="Sin factores aplicables"/>:<div className="grid gap-3">{factors.map((factor)=><Card key={factor.id}><CardContent><b>{factor.nombre}</b><p>{factor.unidad_entrada} → {factor.unidad_resultado}</p>{factor.versiones?.map((version)=><p key={version.id}>v{version.version} <StatusBadge>{version.estado}</StatusBadge> · {version.valor} · {version.fuente}</p>)}</CardContent></Card>)}</div>}</section><section><h2 className="text-xl font-black">Metodologías y versiones</h2>{methods.map((method)=><p key={method.id}>{method.nombre}</p>)}</section><FactorModal open={open} close={()=>setOpen(false)} organizationId={activeOrganizacionId} materials={materials} reload={load}/></main>}
