import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2 } from "lucide-react";
import { getBaseSnapshot, getProblemActions, getProblemCycles, getProblemHistory, getProblemIndicators, getProblems, getProblemScope, selectProblemAction, startProblemAction } from "../api/problematicasV2Api";

const tabs = ["resumen", "alcance", "indicadores", "acciones", "seguimiento", "evidencia", "historial", "expediente"];

export default function ProblemWorkspaceV2({ organizationId }) {
  const [problems, setProblems] = useState([]); const [selectedId, setSelectedId] = useState(null); const [tab, setTab] = useState("resumen");
  const [detail, setDetail] = useState({ scope: [], indicators: [], actions: [], cycles: [], history: [], base: null }); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!organizationId) return; const items = await getProblems(organizationId); setProblems(items); setSelectedId(current => current || items[0]?.id || null); }, [organizationId]);
  useEffect(() => { load().catch(()=>setError("No se pudieron cargar las problemáticas.")); }, [load]);
  useEffect(() => { if (!organizationId || !selectedId) return; Promise.all([getProblemScope(organizationId,selectedId), getProblemIndicators(organizationId,selectedId), getProblemActions(organizationId,selectedId), getProblemCycles(organizationId,selectedId), getProblemHistory(organizationId,selectedId), getBaseSnapshot(organizationId,selectedId).catch(()=>null)]).then(([scope,indicators,actions,cycles,history,base])=>setDetail({scope,indicators,actions,cycles,history,base})).catch(()=>setError("No se pudo reconstruir el workspace.")); }, [organizationId, selectedId]);
  const problem = problems.find(item=>item.id===selectedId); if (!problems.length) return null;
  async function selectAction(actionId) { await selectProblemAction(organizationId, selectedId, actionId); setSelectedId(null); await load(); setSelectedId(problem.id); }
  async function startAction(actionId) { if (!window.confirm("¿Confirmas el inicio efectivo? El snapshot BASE quedará congelado.")) return; await startProblemAction(organizationId, selectedId, actionId); setSelectedId(null); await load(); setSelectedId(problem.id); }
  const currentCycle = detail.cycles.at(-1); const mainKpi = detail.indicators.find(item=>item.rol==="principal");
  return <section className="mt-8 rounded-[32px] border border-amber-200 bg-white p-6 shadow-[var(--shadow-card)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-700">Mejora continua verificable</p><h2 className="mt-1 text-2xl font-black">Problemáticas ambientales</h2></div><select className="rounded-xl border p-3 text-sm font-bold" value={selectedId || ""} onChange={event=>setSelectedId(Number(event.target.value))}>{problems.map(item=><option key={item.id} value={item.id}>{item.titulo}</option>)}</select></div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex flex-wrap gap-2">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-xl px-3 py-2 text-xs font-black uppercase ${tab===item?"bg-amber-700 text-white":"bg-amber-50 text-amber-900"}`}>{item}</button>)}</div>
    {tab==="resumen"&&<div className="mt-5 grid gap-3 md:grid-cols-4"><Card label="Estado" value={problem.estado}/><Card label="Severidad" value={problem.nivel_riesgo}/><Card label="KPI principal" value={mainKpi?.indicador_nombre || problem.indicador}/><Card label="Ciclo actual" value={currentCycle?.numero || "Sin ciclo"}/><Card label="Baseline" value={detail.base?.valores?.[0] ? `${detail.base.valores[0].valor} ${detail.base.valores[0].unidad}` : "Pendiente"}/><Card label="Acción actual" value={detail.actions.find(x=>["seleccionada","en_implementacion","seguimiento"].includes(x.estado))?.titulo || "Sin selección"}/><Card label="Resultado" value={currentCycle?.resultado_detalle?.estado || "Pendiente"}/></div>}
    {tab==="alcance"&&<List items={detail.scope} empty="Sin alcance relacional definido." render={item=>`Unidad ${item.unidad_operacional||"—"} · Proceso ${item.proceso_operacional||"—"} · Activo ${item.activo_operacional||"—"}`}/>} 
    {tab==="indicadores"&&<div className="mt-5"><p className="mb-3 text-sm font-bold">Esta acción será evaluada mediante los siguientes indicadores:</p><List items={detail.indicators} empty="Sin KPIs asociados." render={item=>`${item.indicador_nombre} · ${item.rol} · meta ${item.valor_objetivo ?? "sin meta"}`}/></div>}
    {tab==="acciones"&&<div className="mt-5 space-y-3">{detail.actions.map(action=><div key={action.id} className="rounded-2xl border p-4"><b>{action.titulo}</b><p className="text-sm text-slate-600">{action.descripcion}</p><p className="text-xs text-slate-500">{action.estado}</p>{action.estado==="propuesta"&&<button onClick={()=>selectAction(action.id)} className="mt-2 rounded-lg bg-amber-600 px-3 py-2 text-xs font-black text-white">Seleccionar y preparar BASE</button>}{action.estado==="seleccionada"&&<button onClick={()=>startAction(action.id)} className="mt-2 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Iniciar con confirmación</button>}</div>)}</div>}
    {tab==="seguimiento"&&<div className="mt-5 grid gap-3 md:grid-cols-3"><Card label="Antes" value={detail.base?.valores?.[0]?.valor || "Pendiente"}/><Card label="Implementación" value={detail.actions.find(x=>x.estado==="en_implementacion")?.titulo || "Pendiente"}/><Card label="Después" value={currentCycle?.resultado_detalle?.metricas_comparadas?.[0]?.resultado || "Pendiente"}/></div>}
    {tab==="historial"&&<List items={detail.history} empty="Sin eventos." render={item=>`${item.evento} · ${item.estado_nuevo || item.detalle}`}/>} 
    {tab==="evidencia"&&<Empty icon={CheckCircle2} text="La evidencia se conserva en seguimientos y snapshots."/>}{tab==="expediente"&&<Empty icon={AlertTriangle} text="El expediente legacy conserva historial y ciclos para escalamiento profesional."/>}
  </section>;
}

function Card({label,value}) { return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-1 font-black">{String(value||"—").replaceAll("_"," ")}</p></div>; }
function List({items,empty,render}) { return <div className="mt-5 space-y-2">{items.map(item=><div key={item.id} className="rounded-xl bg-slate-50 p-3 text-sm">{render(item)}</div>)}{!items.length&&<p className="text-sm text-slate-500">{empty}</p>}</div>; }
function Empty({icon:Icon,text}) { return <div className="mt-5 flex items-center gap-3 rounded-2xl border border-dashed p-5 text-sm text-slate-600"><Icon/>{text}</div>; }
