import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2 } from "lucide-react";
import { confirmCopilotCommand, createCopilotProposal, getBaseSnapshot, getCopilotProposals, getProblemActions, getProblemContextV2, getProblemCycles, getProblemHistory, getProblemIndicators, getProblems, getProblemScope, selectProblemAction, sendProposalFeedback, startProblemAction } from "../api/problematicasV2Api";

const tabs = ["resumen", "alcance", "indicadores", "acciones", "seguimiento", "evidencia", "historial", "expediente", "ia"];

export default function ProblemWorkspaceV2({ organizationId }) {
  const [problems, setProblems] = useState([]); const [selectedId, setSelectedId] = useState(null); const [tab, setTab] = useState("resumen");
  const [detail, setDetail] = useState({ scope: [], indicators: [], actions: [], cycles: [], history: [], base: null }); const [error, setError] = useState("");
  const [copilot, setCopilot] = useState({ proposals: [], context: null }); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!organizationId) return; const items = await getProblems(organizationId); setProblems(items); setSelectedId(current => current || items[0]?.id || null); }, [organizationId]);
  useEffect(() => { load().catch(()=>setError("No se pudieron cargar las problemáticas.")); }, [load]);
  useEffect(() => { if (!organizationId || !selectedId) return; Promise.all([getProblemScope(organizationId,selectedId), getProblemIndicators(organizationId,selectedId), getProblemActions(organizationId,selectedId), getProblemCycles(organizationId,selectedId), getProblemHistory(organizationId,selectedId), getBaseSnapshot(organizationId,selectedId).catch(()=>null)]).then(([scope,indicators,actions,cycles,history,base])=>setDetail({scope,indicators,actions,cycles,history,base})).catch(()=>setError("No se pudo reconstruir el workspace.")); }, [organizationId, selectedId]);
  useEffect(() => { if (!selectedId) return; Promise.all([getCopilotProposals(selectedId), getProblemContextV2(selectedId)]).then(([proposals,context])=>setCopilot({proposals,context})).catch(()=>setCopilot({proposals:[],context:null})); }, [selectedId]);
  const problem = problems.find(item=>item.id===selectedId); if (!problems.length) return null;
  async function selectAction(actionId) { await selectProblemAction(organizationId, selectedId, actionId); setSelectedId(null); await load(); setSelectedId(problem.id); }
  async function startAction(actionId) { if (!window.confirm("¿Confirmas el inicio efectivo? El snapshot BASE quedará congelado.")) return; await startProblemAction(organizationId, selectedId, actionId); setSelectedId(null); await load(); setSelectedId(problem.id); }
  async function askCopilot() { setBusy(true); setError(""); try { await createCopilotProposal(selectedId, message); const proposals=await getCopilotProposals(selectedId); setCopilot(current=>({...current,proposals})); setMessage(""); } catch { setError("El copiloto no está disponible. El workflow ambiental continúa funcionando."); } finally { setBusy(false); } }
  async function feedback(proposal, decision) { const refutation = decision==="refutar" ? window.prompt("Describe la restricción o refutación operacional:") : ""; if(decision==="refutar"&&!refutation)return; setBusy(true); try { const response=await sendProposalFeedback(selectedId,proposal.id,decision,refutation||""); if(response.comando&&window.confirm("La propuesta fue preparada. ¿Confirmas crear y seleccionar la acción formal?")) await confirmCopilotCommand(response.comando); const proposals=await getCopilotProposals(selectedId); setCopilot(current=>({...current,proposals})); } catch { setError("No se pudo procesar la decisión."); } finally { setBusy(false); } }
  const currentCycle = detail.cycles.at(-1); const mainKpi = detail.indicators.find(item=>item.rol==="principal");
  return <section className="mt-8 rounded-[32px] border border-amber-200 bg-white p-6 shadow-[var(--shadow-card)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-700">Mejora continua verificable</p><h2 className="mt-1 text-2xl font-black">Problemáticas ambientales</h2></div><select className="rounded-xl border p-3 text-sm font-bold" value={selectedId || ""} onChange={event=>setSelectedId(Number(event.target.value))}>{problems.map(item=><option key={item.id} value={item.id}>{item.titulo}</option>)}</select></div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex flex-wrap gap-2">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-xl px-3 py-2 text-xs font-black uppercase ${tab===item?"bg-amber-700 text-white":"bg-amber-50 text-amber-900"}`}>{item}</button>)}</div>
    {tab==="resumen"&&<div className="mt-5 grid gap-3 md:grid-cols-4"><Card label="Estado" value={problem.estado}/><Card label="Severidad" value={problem.nivel_riesgo}/><Card label="KPI principal" value={mainKpi?.indicador_nombre || problem.indicador}/><Card label="Ciclo actual" value={currentCycle?.numero || "Sin ciclo"}/><Card label="Baseline" value={detail.base?.valores?.[0] ? `${detail.base.valores[0].valor} ${detail.base.valores[0].unidad}` : "Pendiente"}/><Card label="Acción actual" value={detail.actions.find(x=>["seleccionada","en_implementacion","seguimiento"].includes(x.estado))?.titulo || "Sin selección"}/><Card label="Resultado" value={currentCycle?.resultado_detalle?.estado || "Pendiente"}/></div>}
    {tab==="alcance"&&<List items={detail.scope} empty="Sin alcance relacional definido." render={item=>`Unidad ${item.unidad_operacional||"—"} · Proceso ${item.proceso_operacional||"—"} · Activo ${item.activo_operacional||"—"}`}/>} 
    {tab==="indicadores"&&<div className="mt-5"><p className="mb-3 text-sm font-bold">Esta acción será evaluada mediante los siguientes indicadores:</p><List items={detail.indicators} empty="Sin KPIs asociados." render={item=>`${item.indicador_nombre} · ${item.rol} · meta ${item.valor_objetivo ?? "sin meta"}`}/></div>}
    {tab==="acciones"&&<div className="mt-5 space-y-3">{detail.actions.map(action=><div key={action.id} className="rounded-2xl border p-4"><b>{action.titulo}</b><p className="text-sm text-slate-600">{action.descripcion}</p><p className="text-xs text-slate-500">{action.estado}</p>{action.estado==="propuesta"&&<button onClick={()=>selectAction(action.id)} className="mt-2 rounded-lg bg-amber-600 px-3 py-2 text-xs font-black text-white">Seleccionar y preparar BASE</button>}{action.estado==="seleccionada"&&<button onClick={()=>startAction(action.id)} className="mt-2 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Iniciar con confirmación</button>}</div>)}</div>}
    {tab==="seguimiento"&&<div className="mt-5 grid gap-3 md:grid-cols-3"><Card label="Antes" value={detail.base?.valores?.[0]?.valor || "Pendiente"}/><Card label="Implementación" value={detail.actions.find(x=>x.estado==="en_implementacion")?.titulo || "Pendiente"}/><Card label="Después" value={currentCycle?.resultado_detalle?.metricas_comparadas?.[0]?.resultado || "Pendiente"}/></div>}
    {tab==="historial"&&<List items={detail.history} empty="Sin eventos." render={item=>`${item.evento} · ${item.estado_nuevo || item.detalle}`}/>} 
    {tab==="evidencia"&&<Empty icon={CheckCircle2} text="La evidencia se conserva en seguimientos y snapshots."/>}{tab==="expediente"&&<Empty icon={AlertTriangle} text="El expediente legacy conserva historial y ciclos para escalamiento profesional."/>}
    {tab==="ia"&&<div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]"><div><h3 className="font-black">Copiloto contextual</h3><p className="mt-1 text-sm text-slate-600">La IA interpreta contexto preparado; solo tú puedes confirmar acciones formales.</p><textarea value={message} onChange={event=>setMessage(event.target.value)} placeholder="Pide una propuesta o explica una restricción…" className="mt-3 min-h-24 w-full rounded-xl border p-3 text-sm"/><button disabled={busy||!message.trim()} onClick={askCopilot} className="mt-2 rounded-xl bg-violet-700 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Pedir propuesta</button><div className="mt-4 space-y-3">{copilot.proposals.map(proposal=><article key={proposal.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><b>{proposal.titulo}</b><span className="text-xs font-black">v{proposal.version} · {proposal.estado}</span></div><p className="mt-2 text-sm">{proposal.justificacion}</p><p className="mt-2 text-xs text-slate-500">KPIs: {proposal.kpis_afectados.join(", ")||"—"} · Referencias: {proposal.referencias_contexto.join(", ")||"problem"}</p>{["propuesta","ajustada"].includes(proposal.estado)&&<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>feedback(proposal,"aceptar")} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Aceptar</button><button onClick={()=>feedback(proposal,"refutar")} className="rounded-lg bg-amber-100 px-3 py-2 text-xs font-black">Refutar / alternativa</button><button onClick={()=>feedback(proposal,"rechazar")} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-black">Rechazar</button></div>}</article>)}</div></div><aside className="rounded-2xl bg-violet-50 p-4"><h3 className="font-black">Carbono Zero consideró</h3><ul className="mt-3 space-y-2 text-sm"><li>KPI principal: {copilot.context?.kpis?.[0]?.codigo||"—"}</li><li>Tendencia: {copilot.context?.kpis?.[0]?.comparacion?.estado||"sin base"}</li><li>Acciones anteriores: {copilot.context?.acciones_probadas?.length||0}</li><li>Restricciones vigentes: {copilot.context?.restricciones?.length||0}</li><li>Evidencias resumidas: {copilot.context?.evidencia?.totales?.evidencias||0}</li></ul><p className="mt-4 text-xs text-violet-800">Se muestran referencias y justificación auditable, nunca chain-of-thought.</p></aside></div>}
  </section>;
}

function Card({label,value}) { return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-1 font-black">{String(value||"—").replaceAll("_"," ")}</p></div>; }
function List({items,empty,render}) { return <div className="mt-5 space-y-2">{items.map(item=><div key={item.id} className="rounded-xl bg-slate-50 p-3 text-sm">{render(item)}</div>)}{!items.length&&<p className="text-sm text-slate-500">{empty}</p>}</div>; }
function Empty({icon:Icon,text}) { return <div className="mt-5 flex items-center gap-3 rounded-2xl border border-dashed p-5 text-sm text-slate-600"><Icon/>{text}</div>; }
