import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useOutletContext, useParams } from "react-router-dom";
import { ArrowLeft, Plus } from "lucide-react";
import { useOrganizacionActiva } from "@/features/organizaciones/context/OrganizacionActivaContext";
import TraceabilityDrawer from "@/features/datos/components/TraceabilityDrawer";
import { Alert, Button, Card, CardContent, DataQualityBadge, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, SectionHeader, Select, StatusBadge, TableBody, TableCell, TableHead, TableShell, Textarea, Timeline, TimelineItem, TraceabilityLink } from "@/shared/ui";
import { formatDate, formatNumber } from "@/shared/utils/formatters";
import { createMeasurement, createProblemAction, escalateProblem, evaluateProblem, getBaseSnapshot, getCycles, getHistory, getMeasurements, getProblem, getProblemActions, getProblemIndicators, getProblemScope, implementProblemAction, measureFromEngine, reevaluateProblem, selectProblemAction, startProblemAction } from "../services/improvementApi";
import { currentAction, currentCycle, label, problemTone } from "../utils/improvementFormat";

const resource = (data = null) => ({ status: "loading", data });
export default function ProblemDetailPage({ workScoped = false }) {
  const { problemId, obraId } = useParams(); const workspace = useOutletContext() || {}; const { activeOrganizacionId } = useOrganizacionActiva(); const workId = workScoped ? workspace.obra?.id || workspace.obra?.obra_id : undefined;
  const [state, setState] = useState({ problem: resource(), scope: resource([]), indicators: resource([]), actions: resource([]), measurements: resource([]), cycles: resource([]), history: resource([]), base: resource() });
  const [dialog, setDialog] = useState(null); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(""); const [trace, setTrace] = useState(null);
  const load = useCallback(async () => {
    setState({ problem: resource(), scope: resource([]), indicators: resource([]), actions: resource([]), measurements: resource([]), cycles: resource([]), history: resource([]), base: resource() });
    const calls = [getProblem(activeOrganizacionId, problemId, workId), getProblemScope(activeOrganizacionId, problemId, workId), getProblemIndicators(activeOrganizacionId, problemId, workId), getProblemActions(activeOrganizacionId, problemId, workId), getMeasurements(activeOrganizacionId, problemId, workId), getCycles(activeOrganizacionId, problemId, workId), getHistory(activeOrganizacionId, problemId, workId), getBaseSnapshot(activeOrganizacionId, problemId, workId)];
    const results = await Promise.allSettled(calls); const names = ["problem", "scope", "indicators", "actions", "measurements", "cycles", "history", "base"];
    setState(Object.fromEntries(results.map((result, index) => { const isMissingBase = names[index] === "base" && result.status === "rejected" && result.reason?.response?.status === 404 && result.reason?.response?.data?.detail === "Snapshot BASE no disponible."; return [names[index], result.status === "fulfilled" ? { status: "ready", data: result.value } : isMissingBase ? { status: "missing", data: null } : { status: "error", data: names[index] === "problem" || names[index] === "base" ? null : [] }]; })));
  }, [activeOrganizacionId, problemId, workId]);
  useEffect(() => { load(); }, [load]);
  const problem = state.problem.data; const actions = state.actions.data || []; const cycles = state.cycles.data || []; const base = state.base.data; const activeAction = currentAction(actions); const cycle = currentCycle(cycles); const principal = (state.indicators.data || []).find((item) => item.rol === "principal");
  const comparison = cycle?.resultado_detalle?.metricas_comparadas || [];
  const summary = useMemo(() => [{ label: "Estado", value: problem ? label(problem.estado) : "—" }, { label: "Indicador principal", value: principal?.indicador_nombre ?? problem?.indicador ?? "Sin datos" }, { label: "Acción actual", value: activeAction?.titulo ?? "Sin selección" }, { label: "BASE", value: base?.valores?.[0] ? `${formatNumber(base.valores[0].valor)} ${base.valores[0].unidad}` : state.base.status === "missing" ? "Pendiente" : "No disponible" }, { label: "RESULT", value: cycle?.resultado_detalle?.estado ? label(cycle.resultado_detalle.estado) : "Pendiente" }, { label: "Ciclo", value: cycle?.numero ?? "Sin ciclo" }], [activeAction, base, cycle, principal, problem, state.base.status]);
  async function mutate(call, message) { setBusy(true); setFeedback(""); try { await call(); setDialog(null); setFeedback(message); await load(); } catch (error) { setFeedback(error?.response?.data?.detail || "No se pudo completar la operación."); } finally { setBusy(false); } }
  if (state.problem.status === "loading") return <LoadingState label="Cargando problemática" />;
  if (state.problem.status === "error") return <ErrorState description="La problemática no existe o no está disponible en este contexto." />;
  const back = workScoped ? `/obras/${obraId}/problemas` : "/inteligencia/problemas";
  return <main className="space-y-7"><Link className="inline-flex items-center gap-2 text-sm font-bold" to={back}><ArrowLeft size={16} />Problemáticas</Link><PageHeader eyebrow="Ciclo de mejora verificable" title={problem.titulo} description={problem.descripcion} status={<StatusBadge tone={problemTone(problem.estado)}>{label(problem.estado)}</StatusBadge>} metadata={<span>{label(problem.categoria)} · Riesgo {label(problem.nivel_riesgo)} · Detectado {formatDate(problem.fecha_deteccion)}</span>} actions={<><Button variant="secondary" onClick={() => setDialog({ type: "escalate", motivo: "" })}>Escalar problema</Button>{activeAction?.estado === "seleccionada" && <Button onClick={() => setDialog({ type: "start", action: activeAction })}>Iniciar acción</Button>}</>} />
    {feedback && <Alert tone={feedback.startsWith("No ") ? "danger" : "info"}>{feedback}</Alert>}
    <nav aria-label="Secciones del problema" className="flex gap-1 overflow-x-auto border-b">{[["resumen", "Resumen"], ["alcance", "Alcance"], ["indicadores", "Indicadores"], ["acciones", "Acciones"], ["seguimiento", "Seguimiento"], ["historial", "Historial"]].map(([id, text]) => <a key={id} className="shrink-0 px-3 py-2 text-sm font-bold text-[var(--brand-primary)]" href={`#${id}`}>{text}</a>)}</nav>
    <section id="resumen"><SectionHeader title="Resumen" description="Una acción iniciada no equivale a una mejora demostrada." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{summary.map((item) => <Card key={item.label}><CardContent><p className="text-xs font-bold uppercase text-[var(--text-muted)]">{item.label}</p><p className="mt-1 font-bold">{item.value}</p></CardContent></Card>)}</div></section>
    <ResourceSection id="alcance" title="Alcance" state={state.scope}>{!state.scope.data?.length ? <EmptyState title="Alcance no definido." description="No existen relaciones operacionales registradas." /> : <div className="grid gap-3 md:grid-cols-2">{state.scope.data.map((item) => <Card key={item.id}><CardContent><dl className="grid grid-cols-2 gap-2 text-sm"><dt className="text-[var(--text-muted)]">Unidad</dt><dd>{item.unidad_operacional ?? "Sin definir"}</dd><dt className="text-[var(--text-muted)]">Proceso</dt><dd>{item.proceso_operacional ?? "Sin definir"}</dd><dt className="text-[var(--text-muted)]">Activo</dt><dd>{item.activo_operacional ?? "Sin definir"}</dd><dt className="text-[var(--text-muted)]">Actividad</dt><dd>{item.actividad_operacional ?? "Sin definir"}</dd></dl></CardContent></Card>)}</div>}</ResourceSection>
    <ResourceSection id="indicadores" title="Indicadores" state={state.indicators}>{!state.indicators.data?.length ? <EmptyState title="No hay indicadores asociados." description="BASE y RESULT no se fabrican sin indicadores gobernados." /> : <TableShell><TableHead><tr><TableCell as="th">Indicador</TableCell><TableCell as="th">Rol</TableCell><TableCell as="th">Meta</TableCell><TableCell as="th">Dirección</TableCell><TableCell as="th">BASE</TableCell></tr></TableHead><TableBody columns={5}>{state.indicators.data.map((item) => { const baseValue = base?.valores?.find((value) => value.indicador === item.indicador); return <tr key={item.id}><TableCell className="font-bold">{item.indicador_nombre}</TableCell><TableCell><StatusBadge tone={item.rol === "principal" ? "info" : "neutral"}>{label(item.rol)}</StatusBadge></TableCell><TableCell>{item.valor_objetivo ?? "Sin datos"}</TableCell><TableCell>{label(item.direccion_deseada)}</TableCell><TableCell>{baseValue ? `${formatNumber(baseValue.valor)} ${baseValue.unidad}` : "Pendiente"}</TableCell></tr>; })}</TableBody></TableShell>}</ResourceSection>
    <ResourceSection id="acciones" title="Acciones" state={state.actions} action={<Button leftIcon={Plus} onClick={() => setDialog({ type: "action", titulo: "", descripcion: "", justificacion: "", responsable: "" })}>Crear acción</Button>}>{!actions.length ? <EmptyState title="No hay acciones propuestas." description="Crea una acción manual cuando exista una decisión operacional." /> : <div className="grid gap-3 md:grid-cols-2">{actions.map((action) => <Card key={action.id}><CardContent><div className="flex justify-between gap-3"><h3 className="font-bold">{action.titulo}</h3><StatusBadge>{label(action.estado)}</StatusBadge></div><p className="mt-2 text-sm text-[var(--text-secondary)]">{action.descripcion}</p><p className="mt-2 text-xs text-[var(--text-muted)]">Responsable: {action.responsable || "Sin asignar"} · Objetivo: {action.fecha_objetivo || "Sin fecha"}</p><div className="mt-4 flex flex-wrap gap-2">{action.estado === "propuesta" && <Button size="sm" onClick={() => mutate(() => selectProblemAction(activeOrganizacionId, problemId, action.id, workId), "Acción seleccionada. BASE preparada por backend.")}>Seleccionar acción</Button>}{action.estado === "seleccionada" && <Button size="sm" onClick={() => setDialog({ type: "start", action })}>Iniciar acción</Button>}{action.estado === "en_implementacion" && <Button size="sm" onClick={() => mutate(() => implementProblemAction(activeOrganizacionId, problemId, action.id, workId), "Implementación registrada; el resultado sigue pendiente de medición.")}>Registrar implementación</Button>}{cycle?.fecha_cierre && <Button size="sm" variant="secondary" onClick={() => mutate(() => reevaluateProblem(activeOrganizacionId, problemId, action.id, workId), "Nuevo ciclo creado sin sobrescribir el anterior.")}>Nuevo ciclo</Button>}</div></CardContent></Card>)}</div>}</ResourceSection>
    <section id="seguimiento" className="space-y-5"><SectionHeader title="BASE → RESULTADO" description="Comparación neutral entregada por la evaluación backend; no se infiere que menor o mayor sea mejor." actions={undefined} /><div className="grid gap-4 lg:grid-cols-2"><Card><CardContent><h3 className="font-bold">Situación antes de iniciar</h3>{state.base.status === "missing" ? <p className="mt-3 text-sm">BASE pendiente.</p> : state.base.status === "error" ? <ErrorState description="No fue posible cargar BASE." /> : <Snapshot snapshot={base} />}</CardContent></Card><Card><CardContent><h3 className="font-bold">Resultado evaluado</h3>{cycle?.resultado_detalle ? <><StatusBadge tone={cycle.resultado_detalle.estado === "positiva" ? "success" : "warning"}>{label(cycle.resultado_detalle.estado)}</StatusBadge><p className="mt-3 text-sm">{cycle.resultado_detalle.conclusion_estructurada?.resumen || "Resultado registrado por backend."}</p></> : <p className="mt-3 text-sm text-[var(--text-muted)]">RESULT pendiente de reevaluación real.</p>}</CardContent></Card></div>
      {!!comparison.length && <TableShell><TableHead><tr><TableCell as="th">Indicador</TableCell><TableCell as="th">BASE</TableCell><TableCell as="th">RESULT</TableCell><TableCell as="th">Cambio</TableCell></tr></TableHead><TableBody columns={4}>{comparison.map((metric, index) => <tr key={`${metric.indicador || index}`}><TableCell>{metric.nombre || metric.indicador}</TableCell><TableCell>{metric.base ?? "Sin datos"} {metric.unidad}</TableCell><TableCell>{metric.resultado ?? "Sin datos"} {metric.unidad}</TableCell><TableCell>{metric.porcentaje ?? metric.cambio ?? "Sin datos"}{metric.porcentaje !== null && metric.porcentaje !== undefined ? "%" : ""}</TableCell></tr>)}</TableBody></TableShell>}
      <ResourceSection title="Mediciones de seguimiento" state={state.measurements} action={<div className="flex gap-2"><Button variant="secondary" onClick={() => mutate(() => measureFromEngine(activeOrganizacionId, problemId, workId), "Medición obtenida desde datos actuales.")}>Obtener desde datos actuales</Button><Button onClick={() => setDialog({ type: "measurement", fecha: new Date().toISOString().slice(0, 10), valor: "", unidad: problem.unidad_indicador, fuente: "manual", observaciones: "" })}>Agregar medición</Button></div>}>{!state.measurements.data?.length ? <EmptyState title="No hay mediciones de seguimiento." description="La implementación todavía no demuestra un resultado." /> : <TableShell><TableHead><tr><TableCell as="th">Fecha</TableCell><TableCell as="th">Valor</TableCell><TableCell as="th">Fuente</TableCell><TableCell as="th">Calidad/origen</TableCell></tr></TableHead><TableBody columns={4}>{state.measurements.data.map((item) => <tr key={item.id}><TableCell>{formatDate(item.fecha)}</TableCell><TableCell>{formatNumber(item.valor)} {item.unidad}</TableCell><TableCell>{item.fuente === "manual" ? "Manual / declarado" : label(item.fuente)}</TableCell><TableCell>{item.metadata?.calidad && <DataQualityBadge label={item.metadata.calidad} />}{item.evidencia && <TraceabilityLink onClick={() => setTrace({ concepto: problem.indicador, valor_numerico: item.valor, unidad: item.unidad, estado: item.metadata?.calidad, metodo_captura: item.fuente, evidencia_detalle: { id: item.evidencia, nombre: "Evidencia vinculada" } })} />}</TableCell></tr>)}</TableBody></TableShell>}</ResourceSection>
      <div className="flex justify-end"><Button disabled={!state.measurements.data?.length || busy} onClick={() => mutate(() => evaluateProblem(activeOrganizacionId, problemId, workId), "Evaluación registrada por backend.")}>Evaluar resultado</Button></div>
    </section>
    <ResourceSection id="historial" title="Ciclos e historial" state={state.history}>{cycles.length > 0 && <div className="mb-5 grid gap-3 md:grid-cols-2">{cycles.map((item) => <Card key={item.id}><CardContent><h3 className="font-bold">Ciclo {item.numero}</h3><p className="text-sm">Acción {item.accion} · Inicio {item.fecha_inicio}</p><p className="text-sm">RESULT: {item.resultado_detalle ? label(item.resultado_detalle.estado) : "Pendiente"}</p></CardContent></Card>)}</div>}{state.history.data?.length ? <Timeline>{state.history.data.map((item) => <TimelineItem key={item.id} timestamp={formatDate(item.created_at)} title={label(item.evento)} description={item.detalle || label(item.estado_nuevo)} />)}</Timeline> : <EmptyState title="Sin eventos registrados." description="El historial aparecerá cuando existan cambios reales." />}</ResourceSection>
    <ProblemDialog dialog={dialog} busy={busy} onClose={() => setDialog(null)} onSubmit={(payload) => { if (dialog.type === "start") return mutate(() => startProblemAction(activeOrganizacionId, problemId, dialog.action.id, workId), "Acción iniciada. BASE congelada para este ciclo."); if (dialog.type === "escalate") return mutate(() => escalateProblem(activeOrganizacionId, problemId, payload.motivo, workId), "Problema escalado."); if (dialog.type === "action") return mutate(() => createProblemAction(activeOrganizacionId, problemId, payload, workId), "Acción propuesta; todavía no representa una mejora."); return mutate(() => createMeasurement(activeOrganizacionId, problemId, payload, workId), "Medición manual registrada."); }} onChange={setDialog} />
    <TraceabilityDrawer observation={trace} open={Boolean(trace)} onClose={() => setTrace(null)} workId={obraId} />
  </main>;
}

function ResourceSection({ id, title, state, action, children }) { return <section id={id}><SectionHeader title={title} action={action} />{state.status === "loading" ? <LoadingState label={`Cargando ${title.toLowerCase()}`} /> : state.status === "error" ? <ErrorState description={`No fue posible cargar ${title.toLowerCase()}. Las demás secciones permanecen disponibles.`} /> : children}</section>; }
function Snapshot({ snapshot }) { return snapshot?.valores?.length ? <div className="mt-3 space-y-2">{snapshot.valores.map((item) => <div key={item.id} className="flex justify-between border-b py-2 text-sm"><span>{item.indicador_nombre}</span><b>{formatNumber(item.valor)} {item.unidad}</b></div>)}</div> : <p className="mt-3 text-sm text-[var(--text-muted)]">BASE disponible sin valores serializados.</p>; }
function ProblemDialog({ dialog, busy, onClose, onSubmit, onChange }) { if (!dialog) return null; const titles = { start: "Iniciar acción", escalate: "Escalar problema", action: "Crear acción", measurement: "Agregar medición manual" }; return <Modal open title={titles[dialog.type]} description={dialog.type === "start" ? "Al iniciar, el snapshot BASE quedará congelado para este ciclo." : undefined} onClose={onClose} footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={busy} onClick={() => onSubmit(dialog)}>{dialog.type === "start" ? "Confirmar inicio" : "Guardar"}</Button></div>}>{dialog.type === "start" ? <Alert tone="warning">Iniciar la acción no significa que el problema esté resuelto. El resultado deberá medirse y evaluarse.</Alert> : dialog.type === "escalate" ? <Textarea required label="Motivo" value={dialog.motivo} onChange={(event) => onChange({ ...dialog, motivo: event.target.value })} /> : dialog.type === "action" ? <div className="space-y-4"><Input required label="Título" value={dialog.titulo} onChange={(event) => onChange({ ...dialog, titulo: event.target.value })} /><Textarea required label="Descripción" value={dialog.descripcion} onChange={(event) => onChange({ ...dialog, descripcion: event.target.value })} /><Textarea label="Justificación" value={dialog.justificacion} onChange={(event) => onChange({ ...dialog, justificacion: event.target.value })} /><Input label="Responsable" value={dialog.responsable} onChange={(event) => onChange({ ...dialog, responsable: event.target.value })} /></div> : <div className="grid gap-4 sm:grid-cols-2"><Input required type="date" label="Fecha" value={dialog.fecha} onChange={(event) => onChange({ ...dialog, fecha: event.target.value })} /><Input required type="number" step="any" label="Valor" value={dialog.valor} onChange={(event) => onChange({ ...dialog, valor: event.target.value })} /><Input required label="Unidad" value={dialog.unidad} onChange={(event) => onChange({ ...dialog, unidad: event.target.value })} /><Select label="Método" value={dialog.fuente} onChange={(event) => onChange({ ...dialog, fuente: event.target.value })}><option value="manual">Manual / declarado</option></Select><Textarea label="Observaciones" value={dialog.observaciones} onChange={(event) => onChange({ ...dialog, observaciones: event.target.value })} /></div>}</Modal>; }
