import { api } from "@/shared/services/api";
const base = (id) => `/organizaciones/${encodeURIComponent(id)}`;
export const getMaterials = async (id) => (await api.get(`${base(id)}/materiales-operacionales/`)).data;
export const createMaterial = async (id, data) => (await api.post(`${base(id)}/materiales-operacionales/`, data)).data;
export const getMaterialLots = async (id, material) => (await api.get(`${base(id)}/lotes-materiales/`, { params: { material } })).data;
export const createMaterialLot = async (id, data) => (await api.post(`${base(id)}/lotes-materiales/`, data)).data;
export const getMaterialEvents = async (id, material) => (await api.get(`${base(id)}/eventos-materiales/`, { params: { material } })).data;
export const createMaterialEvent = async (id, data) => (await api.post(`${base(id)}/eventos-materiales/`, data)).data;
export const getMaterialBalance = async (id, material) => (await api.get(`${base(id)}/materiales-operacionales/${material}/balance/`)).data;
export const getMaterialLineage = async (id, material) => (await api.get(`${base(id)}/materiales-operacionales/${material}/lineage/`)).data;
